### ISSUE TITLE
bug: Claim button looks disabled, fee calculation is incorrect

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#10]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

### Two things are happening. 
1. The fee amount does not have the correct decimals/denom. In the example below it shows as 0.2351, but it should be 0.002351 according to the transaction. 
2. User was able to claim and the transaction went through, even though the button looks disabled

#### Loom and screenshot from testing
Loom: https://www.loom.com/share/f334f5aa2e7e490fbb72cae9a0a0c86d?highlightComment=11261124&t=113
<img width="300" alt="Captura_de_pantalla_2023-03-02_a_las_20 15 14" src="https://user-images.githubusercontent.com/19958639/222541885-1fcb2d7f-8654-4fa2-ae84-04cb18e33cb5.png">

#### Transaction details
- [Link to explorer](https://explorer.ppnv.space/paloma/tx/57DF82F14189EC39342DD845DC119C41CF202E18B3E0C3F2C794E7E38194CC0D)
- [Calculation of balance](https://docs.google.com/spreadsheets/d/1MqT_xC64nSWF4ZqRO0DSFGpRaQIWPiFF-TFxohtfNBQ/edit#gid=1079171203)
<img width="365" alt="Screen Shot 2023-03-02 at 3 16 29 PM" src="https://user-images.githubusercontent.com/19958639/222542221-367f1a3d-3aa5-4c60-8647-de56945e8e66.png">

**Comment by taariq** [comment]
Closing for now.
