### ISSUE TITLE
Empty state for start bot page | disable all bots (on the start bot page only)

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1000]
- [x] Implement https://www.figma.com/file/6DYR6QFkucGd1bsOILr7V0/Paloma-Bot?type=design&node-id=294%3A197799&mode=design&t=39CtrsxotC1JxTRm-1
- [x] disable all bots (on the start bot page only - we want to keep them on the mybots page in case users still have funds in there)

**Comment by jamie088** [comment]
@verabehr I'd like to confirm again, so should disable all bots for now?
