### ISSUE TITLE
EPIC: Centralized Exchange Perp Arbitrage Strategy

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1006]
@fieldtheory123 let's create an EPIC for this project and document it as we would regular flow.

**Comment by fieldtheory123** [comment]
https://www.notion.so/volumefi/EPIC-11-17-23-CEX-Arb-Trading-Strategy-e9a0e299eda3477e8977511aaff059e4

**Comment by taariq** [comment]
Closed as delivered.
