### ISSUE TITLE
bug: Curve Limit Order bot script issue

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1007]
There seems to be an issue with the Curve Limit Order Bot script. My new bot was withdrawn as soon as bot was created even the Deposit price ratio value was not reached yet.
I guess problem with this line: [https://github.com/VolumeFi/curve-limit-order-bot-script/blob/7ad829c8e9b9977cf14ff283f698f96b81f2326c/limit-orders.js#L500](https://github.com/VolumeFi/curve-limit-order-bot-script/blob/7ad829c8e9b9977cf14ff283f698f96b81f2326c/limit-orders.js#L500)
I think `deposit.tracking_price` value is not updated yet.
Not sure but seems good to change this line like this:
`let current_price_ratio = price1  / price;`
Please check it out.

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/curve-limit-order-bot-script/pull/18 @jamie088 @verabehr
