### ISSUE TITLE
Paloma Rewards Bug: Rewards not received

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1018]
paloma1m7t67rgpjqz8pu0z8x5pa5996xv5kgc0u35dmd was supposed to receive Palomaswap rewareds, but none were received.

**Comment by verabehr** [comment]
@taariq do you have the transaction hash for the swap? 

@rootedbox I don't see any activity for this in mixpanel (not even the swap on palomaswap)

**Comment by rootedbox** [comment]
It never registered with paloma-nest-interface from the front end.. I've added @jamie088 to the ticket. cc: @verabehr

**Comment by jamie088** [comment]
@taariq @verabehr My understanding is Rewards is Grain token from Paloma Nest, which users can receive when they swap tokens on palomaswap.com. Correct? So I need to check the palomaswap.com project code to fix this issue. Correct?

**Comment by taariq** [comment]
### @jamie088 correct.

**Comment by jamie088** [comment]
> It never registered with paloma-nest-interface from the front end.. I've added [@jamie088](https://github.com/jamie088) to the ticket. cc: [@verabehr](https://github.com/verabehr)

@rootedbox What is paloma-nest-interface? You mean register the Paloma wallet in the paloma-nest-interface on the frontend?

**Comment by verabehr** [comment]
@jamie088 palomaswap ui calls the register API to register a claim from the FE. As far as I can tell, the API call never happened as there is no record of an attempt. Here is the link to the register function in nest service https://github.com/palomachain/paloma-nest-service/blob/main/app/controllers/RegisterController.js#L313

**Comment by verabehr** [comment]
Seems to be a CORS issue 

https://cors-test.codehappy.dev/?url=https%3A%2F%2Flcd.palomachain.com%2Fcosmos%2Fbank%2Fv1beta1%2Fbalances%2Fpaloma1h69qyvmt4gtt528pul0thdc58c88z3hl63g59l&origin=https%3A%2F%2Fwww.palomaswap.com%2Funiswap%2F&method=get

**Comment by rootedbox** [comment]
updated nginx config and it works now

https://cors-test.codehappy.dev/?url=https%3A%2F%2Flcd.palomachain.com%2Fcosmos%2Fbank%2Fv1beta1%2Fbalances%2Fpaloma1h69qyvmt4gtt528pul0thdc58c88z3hl63g59l&origin=https%3A%2F%2Fwww.palomaswap.com%2Funiswap%2F&method=get

**Comment by taariq** [comment]
@rootedbox will you document the fix please?

**Comment by taariq** [comment]
for some reason one of the lines was commented out required for us to be cors fully compliant

**Comment by verabehr** [comment]
@rootedbox reopening the issue. The FE gets an error when trying to call the register claim endpoint. 

Last test from @jamie088  https://etherscan.io/tx/0xb0b7c2dcf0c9d8a8a89e7a9022dc117b779b93ca93e47480b46c7867aa4cd7aa 

`error: reason: Non-Claimable Amount`
