### ISSUE TITLE
Improve message attestation security

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1021]
Pigeons are currently only attesting to that the transaction hash is a valid hash on the target chain. Instead, pigeons should attest to the transaction log to verify that the transaction log matches the expected transaction

**Comment by byte-bandit** [comment]
@verabehr @taariq 

There's some ground work laid, but to fully support proper message attestation, I think we need to approach it in a similar way that we do when uploading smart contracts, namely:

- Have Pigeons verify the transaction hash exists, as well as inspect the transaction in question, ensuring that it contains an event emitted for the SLC. Pigeons can compare against the expected message ID as well as the expected Payload I hope.
- Once Paloma picks a winner from the set of attested Pigeons, it should perform the same verification, comparing the dataset from the observed event against its own records

Pulling event data from transactions is something I haven't done before, so at the moment, I'd wager:

- 1 day for the changes in Pigeon
- 1 more day for the changes in Paloma & testing
- +/- 1 day buffer for unknowns

So, 2-3 days?

**Comment by taariq** [comment]
Moving this to TO-DO as we are blocked by 3 days of new vote on Paloma.

**Comment by verabehr** [comment]
This is  a dupe of https://github.com/VolumeFi/paloma/issues/1782
