### ISSUE TITLE
EPIC: How to Automate Cowswap with Paloma

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1026]

**Comment by fieldtheory123** [comment]
https://www.notion.so/volumefi/EPIC-12-01-23-Yearn-CowSwap-intent-bots-99934319168d498b8e88d4a1c805a9b4

**Comment by taariq** [comment]
@fieldtheory123 Yearn has confirmed that this is not really valuable to them and a low priority to continue discussions.
