### ISSUE TITLE
BUG: Mixpanel Gas numbers are incorrect again.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1033]
The mixpanel numbers are incorrect again. @rootedbox did you check your last fix?

**Comment by rootedbox** [comment]
Updated network.json.. removed records from fetched_blocks and restart fees-collected service.. will probably take a few hours to catch up.. will check back up on it later tonight

**Comment by taariq** [comment]
@rootedbox please check the MIxpanel data when this is complete.
