### ISSUE TITLE
TWAP for Gnosis middleware updates

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1034]
https://www.notion.so/volumefi/EPIC-09-29-23-Stables-Offramp-to-Euros-Gnosis-Bot-b1dc5977ed6340d09d3f55855f96db58?pvs=4#ff667394b54b4402a3fc0f4ce36e2fbc

### Done when

- [ ] API for FE to submit bot is available
- [ ] twap bot is triggered by backend script
- [ ] offramp bot can be triggered by backend script
- [ ] twap and offramp bot are combined in one repo and one record for the bot-info api

**Comment by rootedbox** [comment]
@verabehr seems pretty straightforward no questions at this time.
