### ISSUE TITLE
[Resilience] Re-enable deployment retries

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#1035]
As a user, I want failed compass deployments to be retried in a sane way in case they failed, so that I'm not locked out of an upgraded system and my funds are protected.

---

## DoD

- [ ] Failed deployments are retried _(there is some code present to remove a failed deployement ([see here](https://github.com/palomachain/paloma/blob/16d789675cdb3f0e8016c81418c6e6e3cb0cdf8c/x/evm/keeper/attest.go#L130)), this never worked . I don’t see a reason to not re-enable this.)_
- [ ] There's circuit breaker logic in place that prevents retries from burning through high amounts of gas

### ⏰ Esimate
1 - 2 days

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/paloma/pull/1188
