### ISSUE TITLE
[Resilience] Ensure validators with MISSING balance validations are jailed as well

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#1037]
As a user, I want Validators with missing balance reports to be jailed, or at least omitted from the relayer candidate pool, so that I can trust that messages can successfully be relayed.

---

## DoD

- [ ] Validators with missing balance reports are omitted from the relayer candidate pool
- [ ] Additionally, validators with missing balance reports may be jailed

### ⏰ Esimate
1 - 2 days

### ❓ Questions
- Should validators with missing balances be jailed, just like validators with balances that are below the minimum? Missing balances simply means "cannot be verified by other Pigeons"

**Comment by taariq** [comment]
I think this story requires that we know why we are unable to get balances. If we jail validators without knowing why they are unable to follow the rules, then we hurt their ability to stay motivated on the network.
