### ISSUE TITLE
BUG: some token icons are not showing

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1038]
There are several tokens for which we can't get an image. 

E.g. 
https://nest-service.palomachain.com/tokens/market-data?network=1&token=0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9 is valid, but the image for the token doesn't exist. 
https://cdn.jsdelivr.net/gh/curvefi/curve-assets/images/assets/0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9.png

**Comment by rootedbox** [comment]
@verabehr @jamie088 This data is coming from coin gecko so if it's not working it's there data.. I'll open a ticket with them.

**Comment by rootedbox** [comment]
https://media.discordapp.net/attachments/1014207212954066975/1181700063915954207/Captura_de_Pantalla_2023-12-05_a_las_21.54.03.png?ex=658202f2&is=656f8df2&hm=ccdd9798aa3e1dd8fd37d6822bbc9f178ebcf62f5db6e36a8362f7db44e57473&=&format=webp&quality=lossless&width=757&height=780
