### ISSUE TITLE
[BUG] SLC calls spamming JIT valset updates

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#1042]
Every time Paloma fires off a SLC message, it will check whether or not the target chain is at the latest Valset, and in case of a mismatch will create a Valset update as well.

During bursts, it's possible that a lof SLC messages will lead to a lot of Valset update messages, as the first update message might take a few blocks to process, resulting in a lot of Valset update messages with the identical valset ID.

It's not a massive problem, but something to optimise in the future to reduce network noise.

---
### Impact
⬇️ Low

### Suggested solution
When creating a JIT update, verify that there's no message on the queue that has a Valset ID that's equal to the one we're at.

### ⏰ Estimate
1 day

**Comment by maharifu** [comment]
Closed with https://github.com/palomachain/paloma/pull/1247
