### ISSUE TITLE
bug: what is happening - duplicate tokens

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1044]
WSBC token is duplicated in UniswapV2 token list.
`Warning: Encountered two children with the same key, WSBC-0xe46091dce9c67691bcf22768bbee0bc9e20d4beb. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.`
![image](https://github.com/VolumeFi/paloma/assets/83244763/d1667da3-b9e4-4641-8585-4333c11cb4d6)

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/paloma-nest-service/pull/78
