### ISSUE TITLE
Transaction fails as duplicated transaction from pigeon module

### ISSUE THREAD

**Issue by webelf101** [VolumeFi/paloma#1049]
# What is happening?
https://etherscan.io/tx/0x3a92b3c6df3422a076eb8532dada514bf6b14bb0d7273de30feee6d2e86b3029
https://etherscan.io/tx/0x3d4a36eeb35b104c3bc934412380ca46054e177ee6f59caf51af16a1f51d7f40
These transactions are what work the same TWAP swapping. But two validators sent the transaction for the same message and that's why the following one failed as "wrong count" error.
## There can be 2 cases
1. Some validator tried to send the same message even though the message from the other validator was pending.
2. During sending a transaction to EVM chain, backend script and CW sent the same message(spamming).
Honestly, I am not sure which one is a real reason of this issue. But either of them is making the issue.
# Solutions
1. pigeon module should wait for the previous transaction (maybe >=15 seconds).
3. We can set some delay parameter in CW so that we can prevent spaming same message.

**Comment by verabehr** [comment]
I'm pretty sure this is because of message spamming and should be handled on teh CW or script level. Just for one TWAP today, we at times had 10 or 11 messages in the queue. There was supposed to be 1 logic call every 5 minutes, so no reason for so many concurrent messages with the same payload

**Comment by webelf101** [comment]
5 minutes? Can we send a transaction on EVM chain every 5 minutes only?

**Comment by taariq** [comment]
from @webelf101 Understood. However, the script keeps sending a message until the TWAP succeeds.I think we need to update CW to prevent spamming. Good to close this buyg ticket and add new feature ticket.
