### ISSUE TITLE
BUG: Curve Leverage Lending Bot - Leverage value missed from the contract

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1054]
Leverage value missed from the contract, so not available on ABI. See the picture below.  See Discussion: https://discord.com/channels/987730379182051408/1164263785956134992/1182885503532544090

![Image](https://github.com/VolumeFi/paloma/assets/701864/3dd3d53c-704b-4ef1-a2a2-a1a09183e3e5)

**Comment by wc117** [comment]
I will add leverage parameter in the contract.

**Comment by verabehr** [comment]
@wc117 if this is done, will you please add the PR to the repo? https://github.com/VolumeFi/curve-leverage-lending-bot-vyper

**Comment by wc117** [comment]
This is done. But there is a bug in the contract and I am debugging it. After that, I will share the PR here. @verabehr

**Comment by verabehr** [comment]
https://github.com/VolumeFi/curve-leverage-lending-bot-vyper/pull/3
