### ISSUE TITLE
[BUG] `not_found` errors for transactions that do exist

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#1058]
I'm getting a not_found error when trying to query a TX on optimism that does exist. 

Bash


curl --request POST \
  --url https://volume.liquify.com/api=REDACTED/optimism \
  --header 'Content-Type: application/json' \
  --data '{
	"jsonrpc": "2.0",
	"method": "eth_getTransactionByHash",
	"params": ["0x6bd1c4115d1f7321fe4218d7cee4db937bfec492100dde5f8f5bbb755605d575"],
	"id": 10
}'

returns 

{
copy



	"jsonrpc": "2.0",
	"id": 10,
	"result": null
}

The TX is here though: https://optimistic.etherscan.io/tx/0x6bd1c4115d1f7321fe4218d7cee4db937bfec492100dde5f8f5bbb755605d575

---

This led to valset updates on `op-main` not being attested correctly and therefore SLCs not being executed. Brought it up with Liquify.

**Comment by taariq** [comment]
Okay. Moving this to TO-DO as it's not part of Pigeon Feed and we are best can try a different node provider.

**Comment by byte-bandit** [comment]
Closing as done, was actually an issue with RPC.
