### ISSUE TITLE
[Refactor] Paloma message attestation router

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#1062]
As an engineer, I want to define message attestation in a more modular way so that extending attestation handlers with hooks allows me to work on advanced protocol features without bloating technical dept.

---

# DoD

- [ ] Extract existing logic into modular handlers
- [ ] Allow for dynamic assignment of handler to message type
- [ ] Introduce hooks to run before and after the handler

# Other

### ⏰ Estimate
~ 3 days

**Comment by taariq** [comment]
@byte-bandit i need a description of this ticket for this week's Weekly Wings ser. Will you please provide the full requirements and changes?

**Comment by byte-bandit** [comment]
@taariq Done. These changes will come in parallel with https://github.com/VolumeFi/paloma/issues/875 as I've started the refactoring while working on the ERC20 token transfer and realised one simple message wasn't going to cut it any longer in order to support `n` tokens per target chain.
