### ISSUE TITLE
bug: market-data endpoint of nest service api is not working now

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1064]
`market-data` endpoint of the nest service api is not working now. `504 Gateway Time-out`
https://nest-service.palomachain.com/tokens/market-data?network=1&token=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
https://nest-service.palomachain.com/tokens/market-data?network=1&token=0xf939e0a03fb07f59a73314e73794be0e57ac1b4e

**Comment by rootedbox** [comment]
had to force download of all tokens then restart service

**Comment by taariq** [comment]
@rootedbox this failure is hurting users ability to get their tokens. We would like to stop restarting this service manually. What is the needed change?

**Comment by taariq** [comment]
https://www.loom.com/share/c22682a7c93a486ea965ded5c70de045 site us unuseable for our customers.

**Comment by taariq** [comment]
See pictures below of users issues
![Image](https://github.com/VolumeFi/paloma/assets/701864/b0dd955d-879f-4def-9659-2b571aa68079)


![Image](https://github.com/VolumeFi/paloma/assets/701864/3e83891a-5b89-45b6-92ae-619a3d3471fa)

**Comment by taariq** [comment]
@verabehr @rootedbox this continues to block TWAPs. We had 15 instances of [https://nest-service.palomachain.com/tokens/market-data?network=1&token=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2] [🔴 Down] timeout of 48000ms exceeded and this blocked multiple TWAPs

![Image](https://github.com/VolumeFi/paloma/assets/701864/f8b95513-94f1-4915-ab92-bf54310186a3)

**Comment by taariq** [comment]
As of this email I am only able to see ETH on my wallet as well.
