### ISSUE TITLE
Update Curve leverage lending bot script

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1068]
New contract https://etherscan.io/address/0x58fb7813a7eb9c34e01f895831d52fc2e1f37fa7

1. Add collateral requires swap route on Curve. You need to get it in service code. It is to swap additional tokens to collateral token.
2. New event added. "AdditionalToken". It emits when a user add tokens for add_collateral later. It needs to be swapped on Curve on add_collateral

**Comment by rootedbox** [comment]
might not need this

https://discord.com/channels/987730379182051408/1164263785956134992/1184270548893712434
