### ISSUE TITLE
BUG: Total bots showing on Leverage bot is 0 and the volume of Leverage Lending is not shown

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1071]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

BUG: Total bots showing on Leverage bot is 0 and the volume of Leverage Lending is not shown.

1. Show the total bots
2. SHOW THE VOLUME of the bots please. Not sure why this is not shown given ALL other bots have volume.

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/bot-info-api/pull/50
