### ISSUE TITLE
Wrong implementation in Curve leverage bot script

### ISSUE THREAD

**Issue by wc117** [VolumeFi/paloma#1072]
I just checked the update again and it is wrong. Please fix these code.

https://github.com/VolumeFi/curve-leverage-lending-bot/blob/af95b51156d2ac2bc53367b75ac39844914988c0/curve-lending.js#L404
We don't use `wsteth`.

https://github.com/VolumeFi/curve-leverage-lending-bot/blob/af95b51156d2ac2bc53367b75ac39844914988c0/curve-lending.js#L412
depositor shouldn't be `callbacker`.

**Comment by verabehr** [comment]
@wc117 do you have the values that should be used instead of the incorrect ones here?

**Comment by wc117** [comment]
https://github.com/VolumeFi/curve-leverage-lending-bot/blob/af95b51156d2ac2bc53367b75ac39844914988c0/curve-lending.js#L404
This should be "eth".
https://github.com/VolumeFi/curve-leverage-lending-bot/blob/af95b51156d2ac2bc53367b75ac39844914988c0/curve-lending.js#L412
This should be deleverage address. We already discussed it with Curve team and you confirmed at that time. Do you remember?
