### ISSUE TITLE
bug: Curve limit order bot is rounding off price incorrectly

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#1074]
When limit ratio = 0.0004 and 0.00045, FE shows You Buy 0.0004 (Fig 1, 2); when limit ratio = 0.00046, FE shows You Buy 0.0005 (Fig 3)

<img width="709" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/254e26ad-859a-4416-a219-348c0eebe89f">

<img width="709" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/55380ab3-4bdf-4b67-a210-f54469267150">

<img width="706" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/d23bccd1-1955-4619-bcd0-22b6ee235e1c">

What's expected? 
1. limit ratio = You buy / You Sell

**Comment by verabehr** [comment]
@jamie088 was this done?

**Comment by jamie088** [comment]
Almost done. I will push it in 10 mins.

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/287
