### ISSUE TITLE
BUG: tracking_price1 is incorrect for curve stop loss and curve limit order bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1076]
tracking_price1 is not being updated for curve stop loss and curve limit order bot and is therefore incorrect

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/curve-stop-loss-bot-script/pull/13

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/curve-stop-loss-bot-script/pull/13

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/curve-limit-order-bot-script/pull/20
