### ISSUE TITLE
Leverage Lending Bot: Add Total Volume to the Leverage Lending Bot Card

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1078]
As a user, I want to see **Total Volume: $XXX,XXX.XX** on the Leverage Lending Bot card for Palomabot and Curvebot.

from @rootedbox 
> the numbers are in there.. so nothing is lost.. it's just coming up with 0 for some reason

we should be able to do the same/similar that was done for curve lending https://github.com/VolumeFi/bot-info-api/commit/8b8a2957b3962acbbbe8d3b6e726f871ca4a24f0

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/bot-info-api/pull/51

**Comment by taariq** [comment]
@rootedbox will you also update https://www.curvebot.fi/? It still is NOT showing VOLUME.
