### ISSUE TITLE
Implement customer feedback on the Leverage Lending Bot

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1083]
**Rename Health threshold**
- [x] Change `Health threshold` to `Deleverage Level` 
- [x] Change tooltip for Deleverage Level to `If the loan health is below this threshold the bot will automatically repay the percentage of the loan defined in the Deleverage Percentage.`

**Add `N` as user input**
- [x] Move `leverage` field underneath borrow token field
- [x] Create a new field called `N (number of bands) underneath `leverage` field
- [x] Allow user to input integer N for this function https://github.com/VolumeFi/curve-leverage-lending-bot-vyper/blob/master/contracts/curve_leverage_bot.vy#L11

**Add new field Deleverage Percentage**
- [x]  Add a new field called `Deleverage Percentage` underneath `Deleverage Level`
- [x] Tooltip: `Percentage of Loan that should be repaid to improve loan health when the loan is below the Deleverage Level`
- [x] User can input 1 - 100%
- [x] This should be added in teh create_loan_extended call (smart contract needs to be udpated to contain this field)

**Comment by jamie088** [comment]
@verabehr Do we have a default Deleverage Percentage value? Or empty value when page loaded?

**Comment by taariq** [comment]
> @taariq @verabehr Do we have a default Deleverage Percentage value? Or empty value when page loaded?

Empty, but required by the user to complete.

**Comment by taariq** [comment]
Closing as finished.
