### ISSUE TITLE
Leverage Lending Bot Front-End N is not editable and the Health Threshold is unclear

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1084]
See the picture attached here:

1. User wants to specify bands: **I need to specify number of bands. N=4 for max leverage** Are we able to adjust the amount by the number of bands? Also, is our max leverage more than n=4?
2. And I did not understand what health threshold is lol. It's not clear what this is and what it does.  _"The health threshold should be lower than current position health. If the loan reaches the health factor, all the collateral added will be swapped to collateral and added to the loan position."_ Is not clear what this does. If this automatically adds collateral to the loan position, then we need to make this clear. Maybe change the label from **Health Threshold** to **Collateral Support Level** or similar?
3. See pic 

![Image](https://github.com/VolumeFi/paloma/assets/701864/01e7dc37-4233-499d-952b-554e2f77846a)

**Comment by fieldtheory123** [comment]
@verabehr Looks great to me. I also don't agree with his label suggestion. It is very technical and he will be the only one who understands it. Maybe we could use it as the label and add leverage / borrowed amount in parenthesis?

**Comment by taariq** [comment]
Let's change it to what the thing does instead of a directive to the user.

_"Deleverage Level: This is the health level when the bot will automatically close the position and return crvUSD to the user."_

**Comment by verabehr** [comment]
@taariq @fieldtheory123 added all points discussed in Discord here https://github.com/VolumeFi/paloma/issues/1083 Closing this ticket
