### ISSUE TITLE
Curve leverage lending bot: Add deleverage percentage to BotStarted event

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1086]
Add a new field to the create_loan_extended function called `deleverage_percentage` and emit value as part of the BotStarted event. 
The value is an integer 1...100

**Comment by taariq** [comment]
fixed with https://github.com/VolumeFi/curve-leverage-lending-bot-vyper/commit/07d18c1a6830abaefd18d9c3f43ab596c5350a6b
