### ISSUE TITLE
Update repay_extended to include the deleverage_percentage

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1087]
As a curve leverage lending bot user, I want to be able to partially repay the loan if the loan threshold is low. 

This  https://github.com/VolumeFi/curve-leverage-lending-bot/blob/main/curve-lending.js#L430 needs to be updated to include the deleverage_percentage. The field will be added to the BotStarted event here https://github.com/VolumeFi/paloma/issues/1086

**Comment by verabehr** [comment]
https://github.com/VolumeFi/curve-leverage-lending-bot-vyper/pull/4 new field

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/curve-leverage-lending-bot/pull/12

**Comment by taariq** [comment]
fixed with https://github.com/VolumeFi/curve-leverage-lending-bot/pull/12
