### ISSUE TITLE
Update offramp Gnosis bot with new contract and 2 additional fields and integrate new contract

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1090]
Notion: 
https://www.notion.so/volumefi/EPIC-09-29-23-Stables-Offramp-to-Euros-Gnosis-Bot-b1dc5977ed6340d09d3f55855f96db58?pvs=4#ff667394b54b4402a3fc0f4ce36e2fbc

Figma: https://www.figma.com/file/6DYR6QFkucGd1bsOILr7V0/Paloma-Bot?type=design&node-id=243-236963&mode=design&t=yRD3RbtmAebDG8pF-4

Contact: https://gnosisscan.io/address/0x48afa99cd4166d89718cba46db7e1eeb99535b46

**Comment by taariq** [comment]
closing as delivered.
