### ISSUE TITLE
LEVERAGE LENDING BUG: Insufficient Borrow Token Amount when attempting to use wstETH

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1094]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

**Front-end Issues:**
- [x] ERROR Insufficient Borrow Token Amount when attempting to use wstETH and MAX crvUSD See pic.
- [x] Chooser does not order by highest values on top. Please fix for palomabot and curvebot for all bots

<img width="538" alt="Screenshot 2023-12-16 at 8 47 05 AM" src="https://github.com/VolumeFi/paloma/assets/701864/f9ae360c-4cfa-40fa-8314-f080e6a1a15d">

**Comment by taariq** [comment]
Was not able to reproduce this error insufficient information . How is this error determined.

**Comment by verabehr** [comment]
it's an error coming from our FE. https://github.com/VolumeFi/palomabot/blob/main/containers/CurveLeverageLending/StartBotButton/StartBotButton.tsx#L127-L132

**Comment by jamie088** [comment]
@taariq @verabehr As N changes, the max borrow token amount changes. As N increases, the max borrow token amount decreases. In the screenshot above, the token amount entered is higher than the maximum borrowable amount when N increases, so resulting in `Insufficient Borrow Token Amount`. This logic is the same as curve.fi.
But Yes, I think so it is not clear from the current UI.

**Comment by jamie088** [comment]
@taariq `Chooser does not order by highest values on top. Please fix for palomabot and curvebot for all bots` Sorry, what does it mean?

**Comment by taariq** [comment]
@jamie088 order select token by the total value of the token. CRVUSD will e SECOND in this test listing.
<img width="536" alt="Screenshot 2023-12-18 at 7 31 26 AM" src="https://github.com/VolumeFi/paloma/assets/701864/c34bcc90-d2ca-468e-a0ff-616afcbd7cc5">

**Comment by jamie088** [comment]
Makes sense. thank you

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/294#event-11279827443
