### ISSUE TITLE
BUG: EurE bot not showing in MyBots Page 

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1095]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

BUG: EurE bot not showing in MyBots Page 
https://etherscan.io/tx/0x15803c5f07e24845a436d644f4c2fe938ecaa2202edf42cdab2109338318ebef

**Comment by rootedbox** [comment]
https://etherscan.io/address/0xe7b17ff750f6bab85bdf3ee317917fea0a9aefc6#events

https://discord.com/channels/987730379182051408/1065140873811218532/1185664653292994661
