### ISSUE TITLE
BUG: Minutes drop down is too big to be useable. See pic

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1096]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

![image](https://github.com/VolumeFi/paloma/assets/701864/fb6fd06b-b6a0-470e-a26d-2e1c697ccb5e)

**Comment by taariq** [comment]
FYI @joycehermosilla

**Comment by jamie088** [comment]
I fixed this issue. 
https://www.curvebot.fi/curve-twap/ 
https://github.com/VolumeFi/curvefi-bot/commit/a62cd56e56c529d68bcaf563636602b46b6bb59d
I will close this ticket.
