### ISSUE TITLE
CORS Issue debugging with bloxroute Team

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1098]
Error after our upgrade of bloxroute is now confimed from Vercel

> Access to fetch at eth-protect.blxrbdn.com from origin has bee blocked by CORS policy. Response to preflight request does’t pass access control check: No ‘Access-Control-Allow-Origin’ header is present in the requested resource. if an opaque response servers your needs, set the requests mode to ‘no-cors’ to fetch the resource with CORS disabled.

1. We want to implement CORS with access control checks for security
2. We do not want an opaque response
3. We will need to inform Vercel of the proposed CORS configuration as per their documentation here: https://vercel.com/guides/how-to-enable-cors#enabling-cors-in-a-next.js-app

**Comment by rootedbox** [comment]
Enabling CORS on Vercel won’t do anything. You do that if you have an api on vercel that you want others to access. That’s the opposite of our situation.

**Comment by taariq** [comment]
@rootedbox okay. so how do you propose we fix this issue?

**Comment by taariq** [comment]
@rootedbox has confirmed this is not a problem he can fix. Moving to external support with Vercl and with bloxroute. Ticket opened here: https://vercel.com/teams/volume/support/cases/00181415

**Comment by taariq** [comment]
1. it seems like your url is not entirely correct. its supposed to be https://eth-protect.rpc.blxrbdn.com
2. regarding this problem, does it work if you switch the rpc endpoint to a different one like infura or other nodes? if so, then it probably means that the issue is not on the rpc node side.
3. this simple curl request works for me curl 'https://eth-protect.rpc.blxrbdn.com' --header 'Content-Type: application/json' --data '{"jsonrpc":"2.0", "method":"web3_clientVersion", "params": [], "id":1}'. If the problem still persists, can you share a curl request to help us re-create the problem?

**Comment by taariq** [comment]
@rootedbox let's switch out to Liquify RPC endpoints and test.  Also, are we able to test the curl from Vercel domain?

**Comment by taariq** [comment]
Closing this ticket. Was able to reproduce with alternative RCP endpoint. We need to implement CORS in vercel.
