### ISSUE TITLE
Update Curve lending script

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1099]

**Comment by verabehr** [comment]
@rootedbox will you please make the change in the correct repo: https://github.com/volumefi/curve-lending-bot

**Comment by rootedbox** [comment]
@wc117 where / how do I get swap_infos.. also I'm not seeing the contract for curve lending updated so I'm guessing this will be coming?

**Comment by verabehr** [comment]
vyper update https://github.com/VolumeFi/curve-lending-bot-vyper/pull/8

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/curve-lending-bot/pull/31 @verabehr @wc117
