### ISSUE TITLE
bug: Client side error due to metamask

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#11]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Unclear when this is happening. Joyce saw this intermittently. See screenshots. This may be related to https://github.com/palomachain/paloma/issues/737 which has clear steps to reproduce and a Loom

<img width="1347" alt="Captura_de_pantalla_2023-03-02_a_las_20 13 38" src="https://user-images.githubusercontent.com/19958639/222543403-823c6c2e-4cc2-4adc-8d47-d9b05c27dacc.png">

<img width="1154" alt="Captura_de_pantalla_2023-03-02_a_las_20 45 36" src="https://user-images.githubusercontent.com/19958639/222543259-66162004-5f56-42b5-9a22-e64af29d7bae.png">
<img width="1142" alt="Captura_de_pantalla_2023-03-02_a_las_20 45 43" src="https://user-images.githubusercontent.com/19958639/222543261-634b1a5c-0e0c-4614-a8b1-90a59fba9144.png">

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

No errors

**Comment by verabehr** [comment]
saw this happening again on Uniswap only - related sentry error https://volume-x3.sentry.io/issues/4043326179/?project=4504816371236864&query=is%3Aunresolved&referrer=issue-stream&stream_index=0

**Comment by wdev733** [comment]
@verabehr Yes. I'll make a new PR

**Comment by verabehr** [comment]
thanks!
