### ISSUE TITLE
BUG: can't connect to metamask

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1103]
This seems intermittent and happens on curvebot as well as palomabot

![Image](https://github.com/VolumeFi/paloma/assets/19958639/270b7595-4769-4e5c-b695-0e595109fef7)

**Comment by taariq** [comment]
This is due to switching out bloxroute for quicknode. Now that we are NOT using bloxroute, we need to refactor the endpoint functionality.

**Comment by taariq** [comment]
Closing as part of #1113
