### ISSUE TITLE
BUG: Curvebot and Palomabot take SEVEN seconds to show the Bot list. See Loom

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1105]
See Loom: https://www.loom.com/share/9c71b6c0f2f140038499f2e3875f9b84?sid=bf2228e2-3f00-4e58-9f99-98eb4a9e78c1

**Comment by taariq** [comment]
See Loom: https://www.loom.com/share/9c71b6c0f2f140038499f2e3875f9b84?sid=bf2228e2-3f00-4e58-9f99-98eb4a9e78c1

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/bot-info-api/pull/53
