### ISSUE TITLE
Backend upgrade leverage lending bot for TWAP feature

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#1106]
# Background

We want to upgrade the leverage lending bot to add TWAP feature.
EPIC: https://www.notion.so/volumefi/EPIC-12-18-23-Leverage-trading-bot-with-automated-TWAP-to-minimize-slippage-on-swap-to-leverage-and-58ca8d258a384b85a411fa687048c5e8

# Done when

- [x] curve-lending.js is renamed to curve-leverage.js
- [x] BE can receive swap amount from frontend
- [x] price impact and gas estimates are queried
- [x] twap parameters are determined
- [x] API for FE to get the backend parameters

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/curve-leverage-lending-bot/pull/16 cc: @verabehr

**Comment by verabehr** [comment]
additional requirements: 

You need to interact with leverage(for create_next_bot()) and deleverage(for repay_bot()). You need to run create_next_bot with the remaining count that is reduced by one after the interval if the smallest remaining count of the deposit_id is more than 

That means you need to add this logic to the backend script and backend script need to run 2 kinds of functions - create_next_bot() and repay_bot() in each cases.
- [ ] If the first(biggest) remaining count of some deposit_id is more than 1 (let's say N), the lend amount equals deposit amount / N. So you need to consider it to calculate callback_args.
- [ ] When you need to run create next bots, you should use the same deposit_id. So the primary key of the bots for repay is deposit_id + remaining_counts.
