### ISSUE TITLE
UI/UX Issue: Tokens for Curvevbot.ai selector are still not listed in descending order by amount

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1107]
Tokens are still not listed on Curvebot.fi in order of amounts.

![Image](https://github.com/VolumeFi/paloma/assets/701864/3bc97cd0-57eb-4597-90e7-69c5b7f3a29e)

**Comment by jamie088** [comment]
Fixed by this PR. https://github.com/VolumeFi/palomabot/pull/298
