### ISSUE TITLE
LEVERAGE LENDING BOT - Perpetual option

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#1108]
- [x] Add a drop-down selection on the label "Bot Duration"
- [x] When the user selects Perpetual the bot will not have an end.
- [x] The Bot Duration option will appear When the user selects Custom Bot Duration. 

Designs: https://www.figma.com/file/6DYR6QFkucGd1bsOILr7V0/Paloma-Bot?type=design&node-id=821-251376&mode=design&t=lX0Z3QfBfnTU56X1-4

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/306
