### ISSUE TITLE
Chore: check nest service api alerts

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1111]
We're getting a lot of false alerts that are resolved within a minute.

**Comment by verabehr** [comment]
This issue still persists

**Comment by taariq** [comment]
@rootedbox I just experienced it today. 9:54PM PT. not able to see my token list. even after our service https://nest-service.palomachain.com/tokens/market-data?network=1&token=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 is up! ✅

**Comment by taariq** [comment]
I am still unable to get a token list 10 minute slater.

**Comment by rootedbox** [comment]
I set the confirmation period to allow it time to recover. should be less noisy now.
