### ISSUE TITLE
RPC: Test and reimplement Bloxroute for Palomaswap, Palomabot, and Curvebot.fi

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1116]
Bloxroute has been upgraded. Please re-implement Bloxroute as custom RPC endpoint and default RPC endpoint and remove Quicknode.

**Comment by jamie088** [comment]
@taariq What is the upgraded Bloxroute link?

**Comment by taariq** [comment]
@jamie088 use the most recent addresses. Bloxroute fixed their endpoints

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/307
