### ISSUE TITLE
Price monitor for user active bots

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#112]
# Background

_Describe the problem that we are trying to solve with this feature._
_If a path to a solution is known, feel free to write it down, but have an open mind_

https://www.notion.so/volumefi/EPIC-04-14-PalomaBot-ai-Momentum-Chaser-Bot-79c25a79c6ce48afafbb4d0db1cbbfc4?pvs=4#fe15a204c6f54478a3d71b34b6ea3b4e

# Done when

- [x] We have an always running service that is checking the `lorentz` DB every so often for new rows then creating a worker to monitor the prices using the coingecko API for that position.
- [x] a check to see if the price retrieved is within the stopp loss and profit taking prices.
- [x] the stored transaction is submitted to Paloma
- [ ] the telegram bot https://github.com/VolumeFi/paloma/issues/113 is triggered

**Comment by rootedbox** [comment]
"We have a cron job that runs every minute to check the prices of all active bots that are stored in the lorentz DB against coingecko api" @verabehr note this will not be a cron job but an always running service. checking the db every so often for new rows then creating a worker to monitor that position.

**Comment by verabehr** [comment]
this is no longer needed as it will be handled by https://github.com/VolumeFi/paloma/issues/156
