### ISSUE TITLE
BUG: When select euro offramp bot in my bots (twap) i get 404 Error

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1129]
BUG: When select euro offramp bot in my bots (twap) i get 404 Error

![Image](https://github.com/VolumeFi/paloma/assets/701864/077bc6f3-0465-4b78-a8ce-ef45951e5f25)

**Comment by verabehr** [comment]
@jamie088 is this caused by this https://github.com/VolumeFi/paloma/issues/1138
