### ISSUE TITLE
Chore: Update config for testnet refunds

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1134]
We are missing the configuration for Arbitrum on testnet for the gas refund script. This is the ~/app/gas-refund directory on the bot server. We only have the variables for mainnet. 

### Done when

- [ ] All variables needed to run Arbitrum refund script for Paloma testnet are on the bot server

**Comment by taariq** [comment]
@webelf101 let's complete this as Arbitrum will be important for us.

**Comment by verabehr** [comment]
testnet cron now set up to run once a day at 10 past 00:00 utc
