### ISSUE TITLE
EPIC: Grant Proposal - Silo Finance No Liquidation Bot

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1137]
Create a Grant Proposal EPIC for Silo Finance No Liquidation Bot

**Comment by taariq** [comment]
https://docs.google.com/document/d/1jWGKICyi92lVKx3aK1EdR4ll-1T-ZagaVr9IlVoHM9I/edit?pli=1

**Comment by taariq** [comment]
@fieldtheory123 we'll need one after the chat with Silo today.

**Comment by fieldtheory123** [comment]
EPIC https://www.notion.so/volumefi/EPIC-01-05-24-Silo-Finance-Lending-Bots-No-more-Hard-Liquidations-b58fa07d9f8b45ba9ce958bbf9e4cc75

**Comment by taariq** [comment]
Close as completed.
