### ISSUE TITLE
bug: EURO off-ramp bot contract address is incorrect in mybots API

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1138]
The contract address of the EURO off-ramp bot is incorrect in mybots API.
![image](https://github.com/VolumeFi/paloma/assets/83244763/2de054bf-dffe-4883-a9b8-802ee251b675)
![image](https://github.com/VolumeFi/paloma/assets/83244763/d77d617a-df54-4ab9-9468-78b6dfa66ccc)

What this mean. `"contract":"dupe"` and `"contract":"dupe2"`

**Comment by rootedbox** [comment]
that was some bad data.. I'll remove them @jamie088 
cc: @verabehr
