### ISSUE TITLE
URGENT: EurE Bot fails to complete transaction for new users on Palomabot.ai site

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1145]
1. User went to https://www.palomabot.ai/euros/ and executed the EurE bot with $1,200 USDC deposit: https://etherscan.io/tx/0x07724aec016573363e61ba8a35275464cd0585afc438fbbf7db91b2e4a112aba

2. The funds hit the gnosis bridge and the Paloma Gnosis contract. The contract shows 
Balance: 1,200.941954061655626382 xDAI seen here: https://gnosisscan.io/address/0x48afa99cd4166d89718cba46db7e1eeb99535b46. However, we don't see a recent tx on that contract. 

3. Paloma messages show multiple failures: 
Reverted 0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000b57726f6e6720636f756e74000000000000000000000000000000000000000000

And error: execution reverted: Wrong count 

5. We took the Eure bots offline.

**Conclusion:** Paloma is attempting to send the message, but this tx is failing on the Gnosis side. Is this an issue related to https://github.com/VolumeFi/paloma/issues/1130 that was not implemented on Paloambot.ai? We refunded the user $1,200 from Volume's treasury, but we want to recover the funds and ensure that the EurE bots are functioning properly.

See image

![Image](https://github.com/VolumeFi/paloma/assets/701864/e95e321e-c42f-41d1-8ce3-bacbc827a327)

**Comment by fieldtheory123** [comment]
Deposit worked: https://etherscan.io/tx/0xa9a70c33f91187057437b06aaf4d75b388be788ceb6e8beda8219176aef53aa9

Intended to have a two-swap TWAP but neither happened.

**Comment by taariq** [comment]
Fixed again with https://github.com/VolumeFi/offramp-eure-bot-script/commit/753476650a7e45df482f747f81a21a44893eb603
