### ISSUE TITLE
Review and estimate level of effort for Silo lending bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1150]
We need an estimate for the level of effort to build a Silo lending bot according to this spec:

https://www.notion.so/volumefi/EPIC-01-05-24-Silo-Finance-Lending-Bots-No-more-Hard-Liquidations-b58fa07d9f8b45ba9ce958bbf9e4cc75?pvs=4

**Comment by taariq** [comment]
@wc117 we need this ticket done today Jan 8

**Comment by taariq** [comment]
Confirmed as 2 months.
