### ISSUE TITLE
Update Curve TWAPs Slippage for Stables and Non-Stables

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1153]
As a Curve TWAP user, I want slippage to be set for Curve AMMs as follows:

1. Non-stables pool: 0.1% 
2. Stable pools: 0.03%
3. Slippage must be set on PER POOL inside the ROUTE and NOT on the WHOLE ROUTE. 

So that the stable swaps are not impacted by front-running and the non-stables are not as impacted by too low slippage setting for Failed transactions.

**Acceptance Criteria**
1. Update Vyper Contracts
2. Update CW contracts
3. Update back-end script

**Comment by taariq** [comment]
@webelf101 updated.

**Comment by verabehr** [comment]
leaving open until we have all PRs. We're missing the PR on the vyper repo and potentially on the CW repo
