### ISSUE TITLE
Vyper contract for Uniswap v3 limit order bot for any token

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#116]
# Background

_Describe the problem that we are trying to solve with this feature._
_If a path to a solution is known, feel free to write it down, but have an open mind_

https://www.notion.so/volumefi/EPIC-03-31-Vyper-Limit-Order-Bots-for-Top-50-Coingecko-Dexes-24c365366f724479baa5b96041df171b?pvs=4#73cd8db928ae48249b80b664d2bede28

# Done when

- [ ] we have a vyper contract deployed, tested and documented that allows users to deposit their tokens

**Comment by taariq** [comment]
@webelf101 I want to test this functionality today 05/01. Are we ready for a demo?

**Comment by verabehr** [comment]
https://github.com/VolumeFi/limit-order-bot-vyper-uniswap-v3
