### ISSUE TITLE
BUG: Fix Leverage Bot Service errors identified by William

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1160]
Here are the list of tasks identified by @wc117:

1. William reset data records for leverage bot and restarted service and he's am seeing weird errors. Check curve-leverage-lending-bot.service for these error?
2. William replace ABI. Please solve current errors in service. 
3. collateral amount is not matched with amount0 in database. This is an issue
4. William removed the records in deposits and fetched_block tables for leverage bot and restarted the service. But the backend script put this wrong data again. Why is this? Willaim added a log and tried to get event data in backend script and I could get correct data. But I am not sure why wrong data was put in db.
5. Problem: Because of this issue, the transaction puts bigger amount than needed so transaction fails

![Image](https://github.com/VolumeFi/paloma/assets/701864/43d911df-4618-4523-86f6-53d09b38ec42)

and 

![Image](https://github.com/VolumeFi/paloma/assets/701864/0fb50f83-2606-4a01-9cb2-074aead048ed)

**Comment by fieldtheory123** [comment]
For this tx (https://etherscan.io/tx/0x043f44c1c09cfcd329f42b050bf361cd5f7483feef4c6f1c87b1394c3f0cf6bf), `collateral_amount` is the ETH amount while `amount0` seems to be the USDT amount (a bit off by a few decimal points):

<img width="736" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/cb9bfe85-8340-4769-a79d-6b8247b2ac2b">

<img width="784" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/77dbaf4c-5e39-45ef-9989-9b61a607ab5c">
