### ISSUE TITLE
Paloma nest wallet: change tx link to explorer

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1161]
We changed the explorer website (the old one doesn't exist any more) and the links from the activity tab are broken as the url pattern is slightly different

![Image](https://github.com/VolumeFi/paloma/assets/19958639/f83a6392-ac18-49a8-912e-4ca3b3e10843)

It currently is https://paloma.explorers.guru/txs/5E425EE766324DF9E3CFBC9FF3A2DC0E3772AF6203168F2B3DB569D1089597AC
But should be 
https://paloma.explorers.guru/transaction/5E425EE766324DF9E3CFBC9FF3A2DC0E3772AF6203168F2B3DB569D1089597AC

**Comment by jamie088** [comment]
Fixed with https://github.com/palomachain/paloma-nest/pull/17
