### ISSUE TITLE
Update Ethereum bots to use the appropriate gas fee

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1163]

**Comment by webelf101** [comment]
The gas fee should be different per bot.

**Comment by verabehr** [comment]
agreed @webelf101 - will you confirm that the gas fees for curve limit order and curve stop loss and curve twap are still good? 

0x342b663894d93631851f351ece299bc04b69b562 (limit)
0xa0f74e52f6d1c2cb5db6bc3ec7be5b09ef008391 (stop loss)
0x8af32fbb0279b6713b628fe673ae5a5d15b6b3c6 (twap)

**Comment by webelf101** [comment]
This is done.
