### ISSUE TITLE
Show PnL on Leverage bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1167]
blocked by https://github.com/VolumeFi/paloma/issues/1166

Formula: 
```(current price - price at deposit) * collateral amount - gas cost```

**Comment by jamie088** [comment]
@verabehr What is the `gas cost` in formula? Can I get this from the mybots api?

**Comment by fieldtheory123** [comment]
If there's a twap with multiple prices, the pnl in USD is

`current_price * collateral_amount - (price_swap1 * amount_swap1 + price_swap2 * amount_swap2 + ...) - gas cost`

where in the `()` we sum up `price_swap * amount_swap` for all swaps

**Comment by verabehr** [comment]
The original formula `(current price - price at deposit) * collateral amount - gas cost` is still valid. There will be a small update on the backend to take twap into account, but it is not changing the structure of the data returned on the API

**Comment by jamie088** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/345
