### ISSUE TITLE
bug: Curve lending bot can't fully stop bot

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#1169]
I tried to repay and stop my Curve lending bot and the loan was fully repaid:
https://etherscan.io/tx/0xdb3b5bbb349e5ec6170a9f3b599c87c3b0339b258e5f8f4c199f5167559f006d

But then the bot is still active on the FE:
<img width="894" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/55717c35-369f-4f5b-ada8-3031dd0dc15c">

And if I click on stop bot, there's nothing to repay:
<img width="286" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/6b31bf28-aca5-4852-9793-b49bd02b274d">

What's expected:
1. Once clicking on stop bot and repaying the loan fully, the FE will show no lending bot and users can start a new one

**Comment by verabehr** [comment]
Note teh bot was actually stopped, so this appears to be an API or display issue
