### ISSUE TITLE
Curve Leverage lending bot (DEGEN) - allow user to choose their collateral token

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1173]
As a leverage lending bot user, I want to chose my collateral token and I want to choose any of the supported collateral tokens (not just ETH)

1. Rename current input field to `Deposit token`
2. Add an additional field `Collateral token` underneath --> this can be any of the supported collateral tokens on curve leverage lending

https://www.figma.com/file/6DYR6QFkucGd1bsOILr7V0/Paloma-Bot?type=design&node-id=384-198286&mode=design&t=dQdInsuIcNAVEyDE-4

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/330
