### ISSUE TITLE
BUG: Leverage Bot and lending bot - repayment doesn't work when health is below the threshold

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1175]
Bot is below health threshold, but Bot fails to repay. @rootedbox 

See Video: https://www.loom.com/share/8770d0e1dabc4bedb0f6212905b9578c?sid=f125e3cb-a4dd-4128-a69c-93cb4f34c9f5

See User Bot Creation Tx: https://etherscan.io/tx/0xaaf5ff8b2323b30a531ce817b16dafa8e606b047861f297d9b71428ce3387f64

Expected behavior: Bot will Close and Repay after 10% health threshold crossed.

**Comment by verabehr** [comment]
@rootedbox here is another example: 
```
{"deposit_id":"761202739","token0":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","token1":"0xf939e0a03fb07f59a73314e73794be0e57ac1b4e","amount0":"190730534729458","depositor":"0xCe946BC3cC175D1aAa11f8872573452F1BCcbe4c","tracking_price":"0","expire":"1705446642","withdrawer":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","network_name":"ETH","dex_name":"curve","bot":"lending_curve","contract":"0xf15450B537b7a5374450B00c6D04014968f23Dc9","bot_type":"0","sent_to_mixpanel":"0","transaction_hash":"0xcca4f91e8f1843d3dbfd63511ed1f74ee041d11a8eb0dd6c5befb055fde46347","create_to_mixpanel":"0","created_at":"2024-01-11 23:11:03","collateral_amount":"0.00014512087883848","loan_amount":"0.42529725905049043","gas_mixpanel":"0","health_threshold":"320","deleverage_percentage":"100","coin_info":
```
<img width="1241" alt="Screen Shot 2024-01-15 at 10 08 16 AM" src="https://github.com/VolumeFi/paloma/assets/19958639/851a7fea-ac0b-4914-9281-dd3569330761">

**Comment by verabehr** [comment]
@rootedbox here is another example for curve leverage bot: 

```
{"deposit_id":"3","token0":"0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0","token1":"0xf939e0a03fb07f59a73314e73794be0e57ac1b4e","amount0":"1799236948874098","amount1":"30000000000000000000","depositor":"0x425d9cA45409fd8f39f749DCF83f0EbdbB0B7Da4","tracking_price":"27152097004094490","expire":"33241092426","withdrawer":"0x8F5eBDdcf2bae86D3A4E3C4De427E705d2eBF432","network_name":"ETH","dex_name":"curve","bot":"leverage_curve","number_trades":"1","remaining_counts":"0","interval":"30","contract":"0xE79a404E31692C3043a0B03d9207D794598C3cf6","bot_type":"10","sent_to_mixpanel":"0","transaction_hash":"0x4fc8424b114f14ce06a895f937cce42a8540c217d2f4b4b2ea2aff8cb1ef20ac","create_to_mixpanel":"0","created_at":"2024-01-12 20:47:38","gas_mixpanel":"0","leverage":"671","health_threshold":"500","deleverage_percentage":"1000","coin_info":{"
```


![Image](https://github.com/VolumeFi/paloma/assets/19958639/0ae6af95-2bfd-41b7-beaf-ab28f2d96285)

**Comment by rootedbox** [comment]
curve-leverage

currently at this line is what's causing repay to fail https://github.com/VolumeFi/curve-leverage-lending-bot/blob/b0452bb2b3873cab4866266603a85dca5a34862b/curve-leverage.js#L418

it's ok with a deleverageAmountConverted that is too high of a number.. the following are 2 examples.. with the first record it's fine and comes to a value of 96.01130489006829 the second record it comes with a value of 1286231.027575216

any insight would help


{
  "id": 702,
  "deposit_id": 0,
  "token0": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
  "token1": "0xf939e0a03fb07f59a73314e73794be0e57ac1b4e",
  "amount0": "146602040495841",
  "amount1": "1920226097801365667",
  "depositor": "0x08Df29685b1862C5566ffCa487703BF51332aF56",
  "deposit_price": null,
  "tracking_price": 185.10749397989457,
  "profit_taking": null,
  "stop_loss": null,
  "expire": 33240832436,
  "withdraw_type": null,
  "withdraw_block": null,
  "withdraw_amount": null,
  "withdrawer": "0xD0e08D653C3ead747865c3674FFa93ecDefDd045",
  "network_name": "ETH",
  "dex_name": "curve",
  "bot": "leverage",
  "number_trades": 3,
  "remaining_counts": 0,
  "interval": 30,
  "starting_time": null,
  "contract": "0xE79a404E31692C3043a0B03d9207D794598C3cf6",
  "old": null,
  "tracking_price1": null,
  "deposit_price1": null,
  "bot_address": null,
  "unlock_time": null,
  "last_vote_timestamp": null,
  "bot_type": "10",
  "fees_charged": null,
  "sent_to_mixpanel": 0,
  "gas_charged": null,
  "total_charged": null,
  "transaction_hash": "0x043f44c1c09cfcd329f42b050bf361cd5f7483feef4c6f1c87b1394c3f0cf6bf",
  "volume": null,
  "create_to_mixpanel": 0,
  "created_at": "2024-01-10 20:13:59",
  "collateral_amount": null,
  "loan_amount": null,
  "error": null,
  "callbacker": null,
  "callback_args": null,
  "gas_mixpanel": 0,
  "leverage": 690,
  "health_threshold": 320,
  "deleverage_percentage": 5000,
  "is_stable_swap": null
}

96.01130489006829

{
  "id": 703,
  "deposit_id": 1,
  "token0": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
  "token1": "0xf939e0a03fb07f59a73314e73794be0e57ac1b4e",
  "amount0": "15375783442947180639",
  "amount1": "257246205515043200000000",
  "depositor": "0x89d79CDa1A62e3eA95cA21D64681E853A0847300",
  "deposit_price": null,
  "tracking_price": 42.176708820182306,
  "profit_taking": null,
  "stop_loss": null,
  "expire": 33240924011,
  "withdraw_type": null,
  "withdraw_block": null,
  "withdraw_amount": null,
  "withdrawer": "0xF9A2Fa22CB7Df26E3a10622C696f37fC345c6239",
  "network_name": "ETH",
  "dex_name": "curve",
  "bot": "leverage",
  "number_trades": 1,
  "remaining_counts": 0,
  "interval": 30,
  "starting_time": null,
  "contract": "0xE79a404E31692C3043a0B03d9207D794598C3cf6",
  "old": null,
  "tracking_price1": null,
  "deposit_price1": null,
  "bot_address": null,
  "unlock_time": null,
  "last_vote_timestamp": null,
  "bot_type": "4",
  "fees_charged": null,
  "sent_to_mixpanel": 0,
  "gas_charged": null,
  "total_charged": null,
  "transaction_hash": "0x08baae5d997ab73b927d5bdaaeebf300fb4960a0873f6c6a01a721cf62f5c4cf",
  "volume": null,
  "create_to_mixpanel": 0,
  "created_at": "2024-01-10 22:03:27",
  "collateral_amount": null,
  "loan_amount": null,
  "error": null,
  "callbacker": null,
  "callback_args": null,
  "gas_mixpanel": 0,
  "leverage": 766,
  "health_threshold": 100,
  "deleverage_percentage": 500,
  "is_stable_swap": null
}

1286231.027575216

**Comment by verabehr** [comment]
@rootedbox @fieldtheory123 @taariq looked at this again and I've identified the following issues in the calculation
1.  Debt is not being updated outside of events. Use state function to update debt: https://github.com/VolumeFi/curve-leverage-lending-bot-vyper?tab=readme-ov-file#state
2. `health_threshold` needs to be divided by 100. It is currently in this format, so that users can enter a percentage with 2 decimals
3. `health` needs to be divided by an additional 0. This is at least what it looks like comparing with the display in the UI.  (with that change the last bot is not actually up for repayment)

**Comment by rootedbox** [comment]
```
let repayMsg = new MsgExecuteContract(
            wallet.key.accAddress,
            CW,
            {"repay_bot": {"bots": bot, "callbackers": callbacker, "callback_args": callback_args}}
        );

        // Attempts to create, sign, and broadcast the transaction, recording any errors.
        try {
            const tx = await wallet.createAndSignTx({msgs: [repayMsg]});
            console.log("tx:", tx);
            result.repay = await lcd.tx.broadcast(tx);
        } catch (e) {
            result.errors.push({action: 'repay', error: e.toString()});
        }
        ```
failing on the `const tx = await wallet.createAndSignTx({msgs: [repayMsg]});` with the following error 

Error: Request failed with status code 500
    at createError (/Users/rootedbox/Source/VolumeFi/curve-leverage-lending-bot/node_modules/@palomachain/paloma.js/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/rootedbox/Source/VolumeFi/curve-leverage-lending-bot/node_modules/@palomachain/paloma.js/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/rootedbox/Source/VolumeFi/curve-leverage-lending-bot/node_modules/@palomachain/paloma.js/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1376:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    
    
the value of repayMsg is as follows

```
{\"@type\":\"/cosmwasm.wasm.v1.MsgExecuteContract\",\"contract\":\"paloma1lwyg9cj80ffrwedgtflcs5uc2g8kjj7kg8s740l3sp8sfz82e9gs2c9rmy\",\"funds\":[],\"msg\":{\"repay_bot\":{\"bots\":[\"0x9bE82CdDB5c266E010C97e4B1B5B2DF53C16384d\",\"0x9bE82CdDB5c266E010C97e4B1B5B2DF53C16384d\",\"0x9bE82CdDB5c266E010C97e4B1B5B2DF53C16384d\"],\"callback_args\":[[0,0.000995683186735525,\"2594006159218614604\",0,0],[1,115.25222370979174,\"297606133156688232343142\",0,0],[3,0.011754810739384437,\"30634687683984977104\",0,0]],\"callbackers\":[\"0x08Df29685b1862C5566ffCa487703BF51332aF56\",\"0x89d79CDa1A62e3eA95cA21D64681E853A0847300\",\"0x425d9cA45409fd8f39f749DCF83f0EbdbB0B7Da4\"]}},\"sender\":\"paloma18efhhzcvskradeqgslmaqgsgxhpaxepz884mn3\"}"
```

```
{
  "bots": [
    "0x9bE82CdDB5c266E010C97e4B1B5B2DF53C16384d",
    "0x9bE82CdDB5c266E010C97e4B1B5B2DF53C16384d",
    "0x9bE82CdDB5c266E010C97e4B1B5B2DF53C16384d"
  ],
  "callbackers": [
    "0x08Df29685b1862C5566ffCa487703BF51332aF56",
    "0x89d79CDa1A62e3eA95cA21D64681E853A0847300",
    "0x425d9cA45409fd8f39f749DCF83f0EbdbB0B7Da4"
  ],
  "callback_args": [
    [
      0,
      0.000995683186735525,
      "2594006159218614604",
      0,
      0
    ],
    [
      1,
      115.25222370979174,
      "297606133156688232343142",
      0,
      0
    ],
    [
      3,
      0.011754810739384437,
      "30634687683984977104",
      0,
      0
    ]
  ]
}
```

cc: @verabehr @wc117

**Comment by taariq** [comment]
@rootedbox it appears the create and sign tx is failing. Is the right key signing the tx?

**Comment by rootedbox** [comment]
> @rootedbox it appears the create and sign tx is failing. Is the right key signing the tx?

same key that we are setup on the server

**Comment by taariq** [comment]
@rootedbox Is the LCD server working?

**Comment by verabehr** [comment]
just checked, LCD is running, not catching up and on the latest block

**Comment by wc117** [comment]
@rootedbox CW and Vyper don't accept float data. All data should be integer/bigint.I am not sure why the second parameters of callback args are decimals but they should be integers.

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/curve-leverage-lending-bot/commit/b33f1ad1c29b61b2115c70b3b8213226721b3ecb
