### ISSUE TITLE
Curve Leverage DEGEN: Health is different from what the user sees on the start bot screen

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1177]
1. User created a bot with Health of 13%
2. User set Health Deleverage Level of 10%
3. Bot Created with Health of 5% 

See Video: https://www.loom.com/share/8770d0e1dabc4bedb0f6212905b9578c?sid=f125e3cb-a4dd-4128-a69c-93cb4f34c9f5

See User Bot Creation Tx: https://etherscan.io/tx/0xaaf5ff8b2323b30a531ce817b16dafa8e606b047861f297d9b71428ce3387f64

Expected Behavior:
Bot should be created with the health chosen by the user

**Comment by jamie088** [comment]
Fixed. https://github.com/VolumeFi/palomabot/pull/334
