### ISSUE TITLE
BUG: Leverage Lending Bot Label "Deposit Token" is incorrectly labeled "Collateral Token

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1179]
See this picture.

![Image](https://github.com/VolumeFi/paloma/assets/701864/42603aa7-009a-49e8-a997-df785fd7607a)

**Comment by jamie088** [comment]
Fixed. https://github.com/VolumeFi/curvefi-bot/commit/ff8c12b4ae0228a18cd300ccd5be91d26a18159c
