### ISSUE TITLE
ENHANCE: Change Lending Bot Labels and Leverage Lending Bot Labels for Easier Understanding

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1180]
ENHANCE: Change Lending Bot Label for **Health Threshold** to **Health Level For Automatic Repayment**

See pic: 
![Image](https://github.com/VolumeFi/paloma/assets/701864/d2903942-7300-49d7-ac2a-33753ebbbf54)

AND

Change Label: **Deleverage Level** to **Automatic Repayment Health Level
** and change Label **Deleverage Percentage** to **Percentage of Loan to Automatically Repay**
See pic: 

![Image](https://github.com/VolumeFi/paloma/assets/701864/f6ee70bf-9e68-4d2f-ac94-e8814cd39fbf)

**Comment by jamie088** [comment]
Fixed. https://github.com/VolumeFi/palomabot/pull/333
