### ISSUE TITLE
EPIC: Arbitrum Grant Proposal: Uniswap V3 TWAP Bot for Arbitrum.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1182]
Create an EPIC for the Uniswap V3 TWAP Arbitrum Bot on Arbitrum and submt here: https://explorer.gitcoin.co/#/round/42161/0x6142eedc06d80f3b362ce43b4ac52fad679dc850

**Eligibility Requirements:**
1. Projects must bring value to the Uniswap protocol within the Arbitrum ecosystem.
2. Grant request must be between $50k and $250k.
3. Ideas must cover published RFPs, more info here: https://uagp.notion.site/Request-for-Proposals-RFPs-367778d1df754a88b7ce3f889604c209.
4. Undergo KYC/KYB if your idea is approved to receive a grant.

**Comment by taariq** [comment]
Our Grant focus: **Uniswap on Arbitrum Ecosystem tools or products**
1. This will be the Volume Uniswap V3 Bot on Arbitrum.

**Comment by fieldtheory123** [comment]
Done.
