### ISSUE TITLE
BUG: Leverage Bot Error: The ContractFunctionExecutionError: Address "[object Object]" is invalid.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1185]
The ContractFunctionExecutionError: Address "[object Object]" is invalid.

Raw Call Arguments:
  from:   0xb957DccaA1CCFB1eB78B495B499801D591d8a403
  to:     [object Object]
  value:  1.1 ETH
  data:   0x707c96ae0000000000000000000000000000000000000000000000000000000000000180000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc200000000000000000000000000000000000000000000021e19e0c9bab24000000000000000000000000000000000000000000000000000000000000000000005000000000000000000000000d3e576b5dcde3580420a5ef78f3639ba9cd1b967000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000001f000000000000000000000000000000000000000000000000000000000000001f400000000000000000000000000000000000000000000000000000000000022f400000000000000000000000000000000000000000000000000000007bd5678990000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000de0b6b3a76400000000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000036f3b5f44039438c
 
Contract Call:
  address:   [object Object]

function:  create_bot((address[11] route, uint256[5][5] swap_params, uint256 amount, uint256 expected, address[5] pools)[], address collateral, uint256 debt, uint256 N, address callbacker, uint256[] callback_args, uint256 leverage, uint256 deleverage_percentage, uint256 health_threshold, uint256 expire, uint256 number_trades, uint256 interval)
  args:                ([[["0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000"],[[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]],"1000000000000000000","1000000000000000000",["0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000"]]], 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2, 10000000000000000000000, 5, 0xd3e576b5dcde3580420a5ef78f3639ba9cd1b967, [1,"3959708558042940300"], 496, 500, 8948, 33241331865, 1, 30)
  sender:    0xb957DccaA1CCFB1eB78B495B499801D591d8a403

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/335

**Comment by taariq** [comment]
@jamie088: Re-opening this ticket. This error still persists with 1 ETH:

The ContractFunctionExecutionError: Address "[object Object]" is invalid.

Raw Call Arguments:
  from:   0xb957DccaA1CCFB1eB78B495B499801D591d8a403
  to:     [object Object]
  value:  0.2 ETH
  data:   0x707c96ae0000000000000000000000000000000000000000000000000000000000000180000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc200000000000000000000000000000000000000000000003635c9adc5dea000000000000000000000000000000000000000000000000000000000000000000005000000000000000000000000d3e576b5dcde3580420a5ef78f3639ba9cd1b967000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000001f200000000000000000000000000000000000000000000000000000000000001f4000000000000000000000000000000000000000000000000000000000000043b00000000000000000000000000000000000000000000000000000007bd56e2d70000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016345785d8a0000000000000000000000000000000000000000000000000000016345785d8a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000058350a66569e594
 
Contract Call:
  address:   [object Object]

function:  create_bot((address[11] route, uint256[5][5] swap_params, uint256 amount, uint256 expected, address[5] pools)[], address collateral, uint256 debt, uint256 N, address callbacker, uint256[] callback_args, uint256 leverage, uint256 deleverage_percentage, uint256 health_threshold, uint256 expire, uint256 number_trades, uint256 interval)
  args:                ([[["0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000"],[[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]],"100000000000000000","100000000000000000",["0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000"]]], 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2, 1000000000000000000000, 5, 0xd3e576b5dcde3580420a5ef78f3639ba9cd1b967, [3,"397249867734967700"], 498, 500, 1083, 33241359063, 1, 30)
  sender:    0xb957DccaA1CCFB1eB78B495B499801D591d8a403

**Comment by taariq** [comment]
@jamie088 I want you to test the bot before the next pr is released. This bug is hurting onboarding.

**Comment by jamie088** [comment]
I already tested it on my end but no error. I can't reproduce it on my side (both local and production).

**Comment by taariq** [comment]
User was able to create the bot. Closing.
