### ISSUE TITLE
Confirm and if needed update gas fee for curve lending bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1186]
Will you confirm that the current gas fee for curve lending bot is high enough and update if needed? It is  0.015 which is much lower than curve leverage (0.1)

**Comment by wc117** [comment]
When I deploy the bot, I set gas fee as 0.1. So it's fine.

**Comment by verabehr** [comment]
https://paloma.explorers.guru/transaction/C1595D27E568E5ABA94F97FA21CF0973EF01841DF189594C955BC58EA8CDC128
