### ISSUE TITLE
bug: update uniswap v3 twap bot name to twap_uniswapv3

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1191]
Please update the uniswapV3 twap bot name to `twap_uniswapv3`?  This is because the current bot name is the same as the uniswapV2 twap bot.
![image](https://github.com/VolumeFi/paloma/assets/83244763/c971d21e-b4d0-4685-abf3-4025306705c5)

**Comment by verabehr** [comment]
The name is not changed - reopening
