### ISSUE TITLE
FEES: As a user, I want to see the Fees for my bot calculated just before I click create bot.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1192]
As a user of any bot, I want to see my total bot fees at the bottom of the flow before the Create Bot button so that I know what is the cost of the bot and what fees I will incur when I start the bot.

**Acceptance Criteria**
1. Use a comm checkout feature to show the fees that the user will pay that includes:
  i. Paloma Validator Gas Fee
  ii. Bot Execution Fee: 
**Total Fees:** 

https://www.figma.com/file/6DYR6QFkucGd1bsOILr7V0/Paloma-Bot?type=design&node-id=1479-320080&mode=design&t=zkvIjgYmkqzbiqAr-4

**Comment by jamie088** [comment]
https://github.com/VolumeFi/palomabot/pull/342

**Comment by taariq** [comment]
@jamie088 needed for Curvebot.fi as well.

**Comment by jamie088** [comment]
Done
