### ISSUE TITLE
Arbitrum Uniswap V3 TWAP bot bug: Front-end shows TWAP bot active after all TWAP cleared 

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#1197]
I had a TWAP with two trades: https://arbiscan.io/tx/0x802a3399ee0862943b79e36e1ddd2c570b0a3687eb1141ad8e42342bd89350fc

The last one went through at Jan-17-2024 08:38:14 PM +UTC: https://arbiscan.io/tx/0xf01bcc181111bb9a2d0cae7dd2fa4b78c11cf0f777115dea3201ae71958b66f7

But at Jan-17-2024 08:47:14 PM +UTC mybot page is still showing the bot as active: 
<img width="937" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/951723fb-ed97-4e5b-86c7-1f2a1c401f09">

<img width="1437" alt="Screen Shot 2024-01-17 at 3 51 44 PM" src="https://github.com/VolumeFi/paloma/assets/19958639/343c2ed5-2938-421d-a6b5-7cf174a14854">

What's needed:
1. understand why it's happening
2. All TWAP bots should become inactive and removed from My Bots to Old Bots on the FE, shortly after all TWAP clear out

**Comment by rootedbox** [comment]
@webelf101 for some reason withdraw block wasn't set on a transaction where the remaining_count is 0.
 
 ```
select deposit_id,bot,dex_name,number_trades,remaining_counts,withdraw_block,contract from deposits;

 0|twap|uniswapv3|2|0|19028014|0x7cb5d8DD2EC6aCa4F006b44De8b734Cc1298f40D
0|twap|uniswapv3|2|2||0x37D3F3B7a5F091aBF36459430Da9BB883A710E69
1|twap|uniswapv3|2|0||0x37D3F3B7a5F091aBF36459430Da9BB883A710E69
0|twap|uniswapv3|1|1||0x14dBCf69DadA3e5A9aFC54a24fdd1467c2bbd346
1|twap|uniswapv3|2|1||0x14dBCf69DadA3e5A9aFC54a24fdd1467c2bbd346
```

**Comment by webelf101** [comment]
@rootedbox If remaining_counts is zero, we can consider it is done.
