### ISSUE TITLE
Optimism Uniswap v3 TWAP bot bug: failed to execute message

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1198]
The Uniswap v3 TWAP bot fails on Optmism 
https://volume-x3.sentry.io/issues/4884297181/?environment=production&project=4505082653573120&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0

Question - why is this error occurring so many times? We had 1.6k occurrences just during internal testing over 2 days. This is potentially also the reason for the slowness that was observed during some tests

**Comment by verabehr** [comment]
Moving back into todo until we have more volume on optimism.

**Comment by taariq** [comment]
Closing. Not needed.
