### ISSUE TITLE
EPIC: Compound Grant for Automatic Repayments on all Compound Chains

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1200]
Compound Automatic Repayment bot for all Compound Loans on all chains.

**Comment by fieldtheory123** [comment]
https://www.notion.so/volumefi/Compound-Multichain-Migration-Bot-A-Grant-Application-by-Volume-01-19-2024-96b587136bb14fc996d75ebada044af9

**Comment by taariq** [comment]
Closed as delivered. Next: Review of the Compound budget issues.
