### ISSUE TITLE
BUG: Leverage Bot Fails to set min price on repay. User Lost nearly $2K

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1204]
> You did NOT set min price properly

Sandwich spotted in [tricrypto2](https://etherscan.io/address/0xD51a44d3FaE010294C616388b506AcdA1bfAAE46/)

[Frontrun](https://etherscan.io/tx/0xae7c5e5004fd893555d5cb05f7b18a9256274782b12c4f61a39662e07f4499d7/): 168 [WETH](https://etherscan.io/token/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/) ➛ 403,614 [USDT](https://etherscan.io/token/0xdAC17F958D2ee523a2206206994597C13D831ec7/)
 [Center](https://etherscan.io/tx/0x36dde5e9f96cb533ecb25c5fb4526fd0507f8ddc38aea808a01f9499c77f8ca2/): 16.56 [WETH](https://etherscan.io/token/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/) ➛ 38,910 [USDT](https://etherscan.io/token/0xdAC17F958D2ee523a2206206994597C13D831ec7/)
 [Backrun](https://etherscan.io/tx/0x0d37f2649d95d040936d9f24c14de3f53c280f543ced86dfb6d1b9a1d1e1e03a/): 403,614 [USDT](https://etherscan.io/token/0xdAC17F958D2ee523a2206206994597C13D831ec7/) ➛ 168 [WETH](https://etherscan.io/token/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/)

Leverage Bot Affected Contract:  [0xE79a404E31692C3043a0B03d9207D794598C3cf6](https://etherscan.io/address/0xE79a404E31692C3043a0B03d9207D794598C3cf6/)

 [0xb95..03](https://etherscan.io/address/0xb957DccaA1CCFB1eB78B495B499801D591d8a403/) lost **1,658** [USDT](https://etherscan.io/token/0xdAC17F958D2ee523a2206206994597C13D831ec7/) (that's -4.09% slippage, or $1655.92)

Transaction hash: https://etherscan.io/tx/0x36dde5e9f96cb533ecb25c5fb4526fd0507f8ddc38aea808a01f9499c77f8ca2

**Comment by taariq** [comment]
@wc117 is there no slippage protection on Lending Bot repayment as well?

**Comment by verabehr** [comment]
I found this transaction is run by the user on UI. So I checked UI code. I think there will be some calculation error in UI.
https://github.com/VolumeFi/palomabot/blob/1ccfcfea06f22022c3371fbe24a5b99288572dd8/hooks/useCurveSwapUpdated.tsx#L305
I am not sure exactly but we need to use entire collateral to calculate minRecv but initial collateral used. That's why we got too small minRecv and we made sandwich possible.
Please check this code part.

**Comment by verabehr** [comment]
assigning to @rootedbox to confirm if we need a similar fix in the backend script or if the collateral token is already updated

**Comment by rootedbox** [comment]
we are always getting latest collateral.
