### ISSUE TITLE
BUG: Token list doesn't show crvUSD or 3crv on the EurE Offramp Bot. Please check all bots.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1205]
BUG: Token list doesn't show crvUSD or 3crv on the EurE Offramp Bot. Please check all bots. Able to reproduce. Token 3crv does not show up in token list for Palomabot or Curvebot. It shows up for Palomaswap.

List of Bots that fail to show crvUSD or 3CRV
https://www.curvebot.fi/curve-leverage-lending/
https://www.palomabot.ai/euros/
https://www.curvebot.fi/curve-limit-order/
https://www.curvebot.fi/curve-stop-loss/
https://www.curvebot.fi/curve-lending/
https://www.curvebot.fi/curve-momentum/bot
https://www.palomabot.ai/uniswapv3-twap/

**Comment by jamie088** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/339

**Comment by taariq** [comment]
![Uploading missing_tokens_curvebot.fi.png…]()

**Comment by taariq** [comment]
<img width="1127" alt="missing_tokens_curvebot fi" src="https://github.com/VolumeFi/paloma/assets/701864/29c8bc4e-d90b-4e7d-9b0e-108cf616e111">

**Comment by taariq** [comment]
@jamie088 ticket updated.

**Comment by jamie088** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/341
