### ISSUE TITLE
BUG: Leverage bot repayment transaction fails with error execution reverted

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1206]
Here are the details of the paloma transaction that was created https://gist.github.com/rootedbox/092efa793eab3e7b90de8deb8ac2caca

This fails with error `execution reverted` 

```
Jan 18 22:09:18 lcd-mainnet palomad[591855]: {"level":"info","module":"server","module":"x/palomaconsensus","message-id":333570,"queue-type-name":"evm/eth-main/evm-turnstone-message","chain-type":"evm","chain-reference-id":"eth-main","error-data":"0x657865637574696f6e207265766572746564","time":"2024-01-18T22:09:18Z","message":"added error data"}
```

**Comment by verabehr** [comment]
Problem is that `const llamma = crvusd.getLlamma('eth');` is used, but the collateral token is wsteth

affected lines https://github.com/VolumeFi/curve-leverage-lending-bot/blob/27be8294818e2fac8386bad0c355e71afb678634/curve-leverage.js#L460
https://github.com/VolumeFi/curve-leverage-lending-bot/blob/27be8294818e2fac8386bad0c355e71afb678634/curve-leverage.js#L505

Instead of hardcoding `eth` the value should be the collateral token

**Comment by verabehr** [comment]
Additionally: 
https://github.com/VolumeFi/curve-leverage-lending-bot/blob/27be8294818e2fac8386bad0c355e71afb678634/curve-leverage.js#L447
https://github.com/VolumeFi/curve-leverage-lending-bot/blob/27be8294818e2fac8386bad0c355e71afb678634/curve-leverage.js#L460

But in here, you used only eth but we are supporting curve markets coins like wstETH, WBTC, tBTC, etc
And in the WBTC case, decimals of WBTC are 8, not 18.

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/curve-leverage-lending-bot/pull/74
