### ISSUE TITLE
Create bot and sign swap transactions

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#121]
### Background
https://www.notion.so/volumefi/EPIC-04-14-PalomaBot-ai-Momentum-Chaser-Bot-79c25a79c6ce48afafbb4d0db1cbbfc4?pvs=4#459accda36b947cba87e70654436b755

### Done When

- [x] swap transaction swap from token into USDT is created and routed through palomaswap
- [x] limit order bot `deposit` function is executed using https://github.com/VolumeFi/limit-order-bot-vyper-uniswap-v2

**Comment by jamie088** [comment]
> ### Background
> https://www.notion.so/volumefi/EPIC-04-14-PalomaBot-ai-Momentum-Chaser-Bot-79c25a79c6ce48afafbb4d0db1cbbfc4?pvs=4#459accda36b947cba87e70654436b755
> 
> ### Done When
> * [ ]  swap transaction (buy token and enter bot) is created and routed through palomaswap
> * [ ]  bot information is stored in postgresDB - [columns](https://www.notion.so/volumefi/EPIC-04-14-PalomaBot-ai-Momentum-Chaser-Bot-79c25a79c6ce48afafbb4d0db1cbbfc4?pvs=4#c01396c14d6c4fcea153029264d83d4a), Endpoint: https://backend.robots.palomachain.com/register
> * [ ]  swap transaction (sell token and close bot) is created and sent to the DB for later execution

**Comment by verabehr** [comment]
@jamie088 are all the tasks already done in this ticket? If yes, what are you working on now? If not, please reopen and also feel free to edit the ticket to better reflect your tasks

**Comment by verabehr** [comment]
nvm, I see you updated the status already, but hte ticket still shows as closed. That's a github weirdness. I'll reopen

**Comment by jamie088** [comment]
Thank you @verabehr

**Comment by jamie088** [comment]
@verabehr One question. About second field: `bot information is stored in postgresDB` in this task.
I think current logic is deposit tokens to pool (for create a bot) using limit order bot contract and then in backend, scan the deposited function event and register for a new bot in backend. Is this right? I am not sure what should I do in frontend about this.

**Comment by verabehr** [comment]
@jamie088 this ticket wasn't updated after the change was made, so this is no longer correct. That being said, my understanding is that the FE still needs to send the paloma transaction to the backend, but I don't know if this is still right or changed. This document is supposed to have the latest requirements, but I don't think it does https://www.notion.so/volumefi/EPIC-04-14-PalomaBot-ai-Momentum-Chaser-Bot-79c25a79c6ce48afafbb4d0db1cbbfc4?pvs=4#9470f088b6f04e7abe2d05de316a3bcd. 

@taariq will you weigh in here?

**Comment by verabehr** [comment]
done with https://github.com/VolumeFi/palomabot/pull/9
