### ISSUE TITLE
[PF XX] Add feature set to weight proposal CLI command

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#1210]
The `FeatureSet` weight (i.e. does the relayer have MEV support?) was defined after the original set of weights and hasn't been implemented on the full vertical slice yet.

### Done when

- [ ] Users can define the weight associated to a relayer's feature set when submitting a weight proposal change.

### ⏰ Estimate

- `0.5 days`

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/paloma/pull/1168
