### ISSUE TITLE
BUG: Curvebot.fi Bot Repayment gives Gas estimation Error: cannot estimate gas; transaction may fail 

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1225]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>
)
    at f.throwError (_app-3252e2ad12fbc790.js:1:189427)
    at b (_app-3252e2ad12fbc790.js:1:263738)
    at l.<anonymous> (_app-3252e2ad12fbc790.js:1:273617)
    at Generator.throw (<anonymous>)
    at s (_app-3252e2ad12fbc790.js:1:262855)
2670-cede8ef3d9f0da2d.js:1 repayTokens Array(1)
7562-9d0786875e186ef4.js:1 swapRoutes Array(1)
2670-cede8ef3d9f0da2d.js:1 args Array(3)
2670-cede8ef3d9f0da2d.js:1 Preparing transaction hash...
2670-cede8ef3d9f0da2d.js:1 Estimating gas...
VM31:1 MetaMask - RPC Error: execution reverted Object
(anonymous) @ VM31:1
mybots-b38070ffe41c0b77.js:1 e Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x1e121993b4A8bC79D18A4C409dB84c100FFf25F5","to":"0x938981627835ca1c821aF36777D8E942aCc3F555","data":"0xaded898a0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f939e0a03fb07f59a73314e73794be0e57ac1b4e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a969dc335fd74c1d000000000000000000000000000000000000000000000000a969dc335fd74c1d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32000,"message":"execution reverted"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at f.makeError (_app-3252e2ad12f

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Repay Loan on Curvebot.fi lending. This problem is NOT on Palomabot.ai

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Loan Repayment works.

**Comment by jamie088** [comment]
Blocked by https://github.com/VolumeFi/paloma/issues/1226
