### ISSUE TITLE
BUG: Curve Limit Order Bot shows incorrect TVL amount and P&L

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1231]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Curve LImit Order: https://gist.github.com/rootedbox/942293b27082dcfda331bc6c11fc6d20 is not showing properly on the User'S Mybot page. See image below. 

![image](https://github.com/VolumeFi/paloma/assets/701864/8b4b6211-01dc-4678-9047-09ecc5e103b3)

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Show the Correct TVL and P&L on the Curve LImit Order Bot.

**Comment by jamie088** [comment]
@rootedbox 
![image](https://github.com/VolumeFi/paloma/assets/83244763/654a27be-6f1e-4d88-bfbb-9b1145de4a8c)
What value is tracking_price1? this value(tracking_price1 and deposit_price1) exists on only curve limit order and stop loss bots on the api. Do we need both? tracking_price vs tracking_price1 and deposit_price vs deposit_price1
If no, please remove one. Or I can update FE ui to match these values if you let me know.

**Comment by rootedbox** [comment]
tracking_price is coin0 tracking_price1 is coin1
deposit_price is coin0 deposit_price1 is coin1

**Comment by jamie088** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/349
