### ISSUE TITLE
BUG: Curve Leverage Bot Created, but no Mybots showing and no bot creation alerts

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1232]
User created the bot: https://etherscan.io/tx/0x8615b0786260539b93618560cb2e8d418363d26e5ab84194aaea45b29fc58cba

However, no bots show up on Mybots page and no bot alerts.

User is unable to adjust the bot.

**Comment by webelf101** [comment]
I checked db and there have been no leverage bots since Jan 19. Please check backend script. @taariq @rootedbox
