### ISSUE TITLE
Paloma EVM Landing Page

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#1241]
- [ ] Airdrop Code Page: 
Designs: https://www.figma.com/file/WeCoqHrTScxZNt6iiSR7E4/Paloma-EVM?type=design&node-id=11-283&mode=design&t=VKiuoWOlFxQdteam-4

As a user, when I land on the PalomaEVM landing page, I want to be able to enter my code to access the site and get information about Paloma EVM
 **Acceptance Criteria**
Users will need a 5 digit code to enter the website.
The code will affiliate code that will allow Volume to track rewards for promoters

- [ ] About Page
Designs: https://www.figma.com/file/WeCoqHrTScxZNt6iiSR7E4/Paloma-EVM?type=design&node-id=11-305&mode=design&t=VKiuoWOlFxQdteam-4

As a user, when I land on the Paloma EVM landing page, I want to see an About Tab that will give me information about how PalomaEVM is different and offers me native yield.

***** I'm still working on the logo.

**Comment by verabehr** [comment]
This project was killed, closing
