### ISSUE TITLE
mybots api update for completed bot

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1243]
Please match `withdraw_type` across all bots in mybots API.
```
Canceled: 1
Profit Taking: 2
Stop Loss: 3
Expired: 4
```

In the current api result, there are 1,2,4,8, etc of the withdraw_type and these values are different than each bot. So FE is very confusing.

**Comment by rootedbox** [comment]
I did not design these.. I just put them in the database. discuss with @verabehr @wc117  if you need them changed

**Comment by verabehr** [comment]
Not all bots use these, it's not clear why some bots have withdraw type 8, like this one https://etherscan.io/tx/0xb905893aaedcb24b9d77debfd36a235fa9431bb176adff0b3c60a186ba996979. Closing as won't fix
