### ISSUE TITLE
Enter Code Page - JUICE

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#1246]
As a user, when I land on the PalomaEVM landing page, I want to be able to enter my code to access the site and get information about Paloma EVM
Acceptance Criteria
- Users will need a 5-digit code to enter the website.
- The code will affiliate code that will allow Volume to track rewards for promoters

Design: https://www.figma.com/file/WeCoqHrTScxZNt6iiSR7E4/Paloma-EVM?type=design&node-id=11-283&mode=design&t=VwqdTvxgmyDKD4nS-4

**Comment by jamie088** [comment]
https://www.juicebot.ai/

**Comment by taariq** [comment]
Closing as delivered.
