### ISSUE TITLE
BUG: Curvebot Limit Orders Fail - Gas Estimation

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1251]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

https://www.curvebot.fi/curve-limit-order/

**Token Pair: CRV/YCR**

  Failed to load resource: net::ERR_FAILED
5392-62fb692d3744a9ec.js:1 CURVE-JS IS CONNECTED TO NETWORK: Object
7562-35264ab1fc96f3c5.js:1 e Error: could not coalesce error (error={ "code": -32012, "message": "credits limited to 550/sec" }, payload={ "id": 44, "jsonrpc": "2.0", "method": "eth_chainId", "params": [  ] }, code=UNKNOWN_ERROR, version=6.7.0)
    at o (5392-62fb692d3744a9ec.js:1:2178274)
    at aF.getRpcError (5392-62fb692d3744a9ec.js:1:340919)
    at 5392-62fb692d3744a9ec.js:1:334302
9373-7a2da6ca7f2c1e03.js:1 e Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0xxxxxxxxxxxxxxxxxxxxxxxxx","to":"0xD533a949740bb3306d119CC777fa900bA034cd52","data":"0x095ea7b3000000000000000000000000342b663894d93631851f351ece299bc04b69b562ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff","accessList":null}, error={"code":-32603,"message":"execution reverted","data":{"originalError":{"message":"execution reverted","code":3}}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at f.makeError (_app-0d8891ab66d15b5f.js:1:189313)
    at f.throwError (_app-0d8891ab66d15b5f.js:1:189427)
    at b (_app-0d8891ab66d15b5f.js:1:263738)
    at l.<anonymous> (_app-0d8891ab66d15b5f.js:1:273617)
    at Generator.throw (<anonymous>)
    at s (_app-0d8891ab66d15b5f.js:1:262855)

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Test Limit Order.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

No gas estimation issue on https://www.curvebot.fi/curve-limit-order/

**Comment by jamie088** [comment]
> @jamie088 Checking out your bot but when I'm making approval for 10000 amount of tokens, the approval is for 115792089237316195423570985008687907853269984665640564039457.584007913129639935 token. I don't have the toknen as yet.

That's correct logic. Because we do approval with MAX amount (2^256). No problem even if you don't have enough amount.

**Comment by taariq** [comment]
@jamie088 how much token did he have then?

**Comment by jamie088** [comment]
@taariq I don't know. I can't get user info from the above screenshot.

**Comment by taariq** [comment]
@jamie088 ticket updated with full log and token pair.
