### ISSUE TITLE
UI/UX: Curve Limit Order Bot Chain Select for Ethereum and Arbitrum

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1253]
As a user, I want to choose Arbitrum chain for my Curve Limit Order Bot.

**Comment by jamie088** [comment]
Pushed the code to new branch: https://github.com/VolumeFi/palomabot/tree/feat/curve-limit-order
We don't have the bot deployed on Arbitrum yet so I didn't send a PR yet.
