### ISSUE TITLE
LEDGER: Still unable to use Ledger

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1254]
Even after upgrade of Ledger, it appears that we're stull uanble to use ledger. The issue identified in this bug: https://github.com/Agoric/agoric-sdk/issues/8783 is still ongoing.

Do we need to upgrade any other dependencies?

**Comment by byte-bandit** [comment]
Looking at the full conversation on the original bug report, looks like there was an additional change in the accepted fix: https://github.com/Agoric/agoric-sdk/commit/bc4a284e7346369f64757be20543045df52e8c3b

They're also indirectly upgrading a Cosmos dependency, which appears to contain the actual fix. We can include this in `1.12.1` I think.
