### ISSUE TITLE
BUG: Unable to broadcast ledger transaction on local v1.12.1 build signature verification failed

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1258]
Local build commands 
Step 1: `$git tag v1.12.1`
Step 2: `LEDGER_ENABLED=true make build`
Step 3: `mv palomad /usr/local`
Step 4: `palomad version` returns 1.12.1
Step 5:  command used: 
`palomad tx bank send paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx paloma1dlwec08s93gykwflpsssuqj0ds03yfmahcjs4x 1000000ugrain --chain-id messenger --gas 3500000 --node https://paloma-rpc.acloud.pp.ua:443 --sign-mode "amino-json" --fees 1000ugrain -b sync`

The ledger responds to sign the tx and review the details. 
1. Chain ID: messenger
2. Account: 5
3. Sequence: 88
4. Type: Send
5. Amount: 1000000ugrain
6. From: paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
7. To: paloma1dlwec08s93gykwflpsssuqj0ds03yfmahcjs4x
8. Fee: 1000ugrain
9. Gas: 3500000
10. APPROVE?

However, when I click approve on the ledger, I get the console output below. It appears that the account sequence being sent is incorrect. It's always 88 and the account number is always 5. I've tested with different rpc endpoints so I think this is related to the upgrade of go-ledger. So now, I am able to sign, but the signature verification fails. 

Output of the error. 
```
auth_info:
  fee:
    amount:
    - amount: "1000"
      denom: ugrain
    gas_limit: "3500000"
    granter: ""
    payer: ""
  signer_infos: []
  tip: null
body:
  extension_options: []
  memo: ""
  messages:
  - '@type': /cosmos.bank.v1beta1.MsgSend
    amount:
    - amount: "1000000"
      denom: ugrain
    from_address: paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
    to_address: paloma1dlwec08s93gykwflpsssuqj0ds03yfmahcjs4x
  non_critical_extension_options: []
  timeout_height: "0"
signatures: []
confirm transaction before signing and broadcasting [y/N]: y
code: 4
codespace: sdk
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: 'signature verification failed; please verify account number (5), sequence
  (88) and chain-id (messenger): unauthorized'
timestamp: ""
tx: null
txhash: 85659102E63E8675B76E692D3E33FB6187832C9BCBB48EE6C6D316279C8EE46B
```

Conclusion: The chain-id is correct so account number and sequence must be incorrect. These appear to be generated by the ledger. 

`palomad tx bank send [from_key_or_address] [to_address] [amount] [flags]` takes the following flags for account and sequence.
`-a, --account-number uint      The account number of the signing account (offline mode only)`
` -s, --sequence uint            The sequence number of the signing account (offline mode only)` 
but these are offline mode only.

 I was able to reproduce this error on both mac and linux laptops so it appears that MacOS is not the issue.

Found more details on the error: 
_The node uses the public key of the sender account to verify the signature. When verification failed, the node responds to this error. So you can decode the signature to verify that signerInfos (X Y Z) and signedDoc in the signature must match with the info when you sign._

So now I suspect that the account number or the account sequence is not matching the public key information in the keys. I will try to reload the keys.

**Comment by byte-bandit** [comment]
Closing as user error.
