### ISSUE TITLE
Backend for Juice website

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1260]
We need a new backend for the new juicebot website. https://www.juicebot.ai/

### Done when

- [x] DB is created with the following fields
    - [x] wallet (EVM wallet)
    - [x] passcode (5 digit numerical)
    - [x] passcode_expiration (timestamp)
    - [x] registered (bool)
- [x] FE can call an API to retrieve the stored information in the DB for a wallet or passcode
- [x] FE can call an API to set `registered` to TRUE (when user submits passcode)

**Comment by rootedbox** [comment]
GET /wallet/:id: This API endpoint fetches the details of a wallet given its ID. If the wallet is found, it returns the wallet data. If any error occurs during this process, it returns an error message with a status code of 500.

GET /passcode/:passcode: This API endpoint fetches the details of a wallet given its passcode. If the wallet is found, it returns the wallet data. If any error occurs during this process, it returns an error message with a status code of 500.

PUT /register/:id: This API endpoint updates the status of a wallet to registered given its ID. If the wallet is updated successfully, it returns a success message. If any error occurs during this process, it returns an error message with a status code of 500.
