### ISSUE TITLE
BUG: Unable to use the Curve Leveage Bot - Fetching Prices never ends and console error Cannot read properties of undefined (reading 'contract')

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1262]
TypeError: Cannot read properties of undefined (reading 'contract')
    at 5392-62fb692d3744a9ec.js:1:1975331
    at 5392-62fb692d3744a9ec.js:1:1961396
    at Object.next (5392-62fb692d3744a9ec.js:1:1961501)
    at u (5392-62fb692d3744a9ec.js:1:1960225)

When trying to use Curve Leverage Bot.  See screenshot

![Image](https://github.com/VolumeFi/paloma/assets/701864/99c685d9-1a90-4512-8b36-ae8ccd20079a)

**Comment by jamie088** [comment]
Fixed it by https://github.com/VolumeFi/palomabot/pull/359
