### ISSUE TITLE
BUG: TypeError: Cannot read properties of null (reading 'timestamp') Curve TWAP

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1268]
Curve TWAP error: TypeError: Cannot read properties of null (reading 'timestamp') when trying to load page.

**Comment by jamie088** [comment]
I think fixed it with https://github.com/VolumeFi/palomabot/pull/365. Please test it again.

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/365
