### ISSUE TITLE
BUG: Curve TWAP Bot gives Insufficient Amount when TWAP from USDC to ETH 1 trade

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1269]
BUG: Curve TWAP Bot gives Insufficient Amount when TWAP from USDC to ETH 1 trade. See picture

![Image](https://github.com/VolumeFi/paloma/assets/701864/3f1ae602-1044-41a1-8411-361228665b43)

**Comment by verabehr** [comment]
Jamie, Fieldtheory and I couldn't reproduce closing as won't fix
