### ISSUE TITLE
BUG: Curve Limit Order Bot: Error: call revert exception(method="estimategas",

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1270]
![Image](https://github.com/VolumeFi/paloma/assets/701864/b4c3a7b7-be31-4035-adf5-971a94286848)

**When attempting to complete a Limit Order from CRV to yCRV**

CALL_EXCEPTION
This error occurs when a call or transaction is used to interact with the blockchain reverts (via revert, require, et cetera).

Due to the overall flexibility of Ethereum and Turing Completeness, there is a large variety of reasons this can occur and troubleshooting requires attention.

Common Causes
The code does not exist on-chain. This may happen if you failed to wait until the contract was deployed, the address is incorrect or if you are connected to a different network than the contract has been deployed. Check the code exists using provider.getCode(address).
The wrong code is being accessed, for example if an artifact file was not correctly updated so an older instance of the contract is being called
The contract is failing during a require statement. For example, if a contract method requires an admin account to be used, but the contract is connected to another [Signer](https://docs.ethers.org/v5/api/signer/#Signer).
The wrong ABI is being used to interact with a contract.
Debugging
Always double check the address and network you are connected to and use provider.getCode(address) to verify the deployed code matches your most recent version.
Try accessing other, simpler contract methods to verify the account is correct.

**Comment by jamie088** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/361
