### ISSUE TITLE
BLOXROUTE: Replace Quicknode with Bloxroute endpoints

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1271]
Migrate all Quicknode endpoint references here: https://github.com/search?q=org%3AVolumeFi%20serene-divine-crater.quiknode.pro&type=code

back to Bloxroute: 

1. See ticket: https://github.com/VolumeFi/palomabot/pull/309 that was done in December, but we are back on Quicknode.
2. RE-enable custom RPC endpoint.

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/360

**Comment by jamie088** [comment]
Done by https://github.com/VolumeFi/palomabot/pull/360
