### ISSUE TITLE
BUG: Curve TWAP BOT: Error: cannot estimate gas; transaction may fail or may require manual gas limit (reason="execution reverted: ERC20: transfer amount exceeds allowance", method="estimateGas"

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1272]
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: ERC20: transfer amount exceeds allowance", method="estimateGas", transaction={"from":"0x83334ef0C6f6396413C508A7762741e9FD8B20E9","to":"0x8aF32Fbb0279B6713B628Fe673AE5a5d15B6B3c6","value":{"type":"BigNumber","hex":"0x58d15e17628000"},"data":"0x2930a9a200000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000003c0000000000000000000000000000000000000000000000000000000065cab9c70000000000000000000000000000000000000000000000000000000000000001000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000005426178799ee0a0181a89b4f57efddfab49941ec000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001a781f8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002845524332303a207472616e7366657220616d6f756e74206578636565647320616c6c6f77616e6365000000000000000000000000000000000000000000000000","message":"execution reverted: ERC20: transfer amount exceeds allowance","cause":null}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at f.makeError (_app-0d8891ab66d15b5f.js:1:189313)
    at f.throwError (_app-0d8891ab66d15b5f.js:1:189427)
    at b (_app-0d8891ab66d15b5f.js:1:263738)
    at l.<anonymous> (_app-0d8891ab66d15b5f.js:1:273617)
    at Generator.throw (<anonymous>)
    at s (_app-0d8891ab66d15b5f.js:1:262855)

See picture: 

![Image](https://github.com/VolumeFi/paloma/assets/701864/061d2be5-82af-4321-bccd-24df8b2a03e6)

**Comment by jamie088** [comment]
@taariq I think this is not an error. seems you didn't approve with the correct inputted token amount.
`execution reverted: ERC20: transfer amount exceeds allowance`
In above screenshot, when the approval MetaMask pop-up appeared, how much did you approve?
Did you correctly approve 444.08 USDC or higher?

**Comment by taariq** [comment]
the approval interaction is messed up for USDC. did you test with USDC?

**Comment by jamie088** [comment]
Yes, I tested with USDC several times. But no problem for me.

**Comment by jamie088** [comment]
Anyway, this error happened because you did not approve an amount more than the amount you entered.

**Comment by taariq** [comment]
okay. closing as won't fix.
