### ISSUE TITLE
BLOXROUTE: Replace Bloxroute endpoints with Liquify and remove custom endpoint

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1277]
Looks like we still have this problem:

curve-limit-order/:1 Access to fetch at 'https://eth-protect.rpc.blxrbdn.com/' from origin 'https://www.curvebot.fi' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

 So let's replace bloxroute with Liquify.

**Comment by jamie088** [comment]
@taariq Do we still need this ticket?

**Comment by taariq** [comment]
Closing as won't need.

**Comment by taariq** [comment]
@jamie088 let's revert the change.

**Comment by taariq** [comment]
closed as fixed.
