### ISSUE TITLE
BUG: Leverage Bot Returning Too Many Requests Error. Solution: Move decimals to mybots API

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1279]
POST https://eth-protect.rpc.blxrbdn.com/ 429 (Too Many Requests).

@rootedbox 
Will we please stop hammering on the endpoints from the front-end?

### Done when 

- [x] add decimals of the token0 and token1 are added to mybots api in the coin info (@rootedbox ) Coingecko returns this in the GET coins/{id} endpoint
```
"coin_info":{"id":"crvusd","symbol":"crvusd","name":"crvUSD","platforms":{"ethereum":"0xf939e0a03fb07f59a73314e73794be0e57ac1b4e","polygon-pos":"0xc4ce1d6f5d98d65ee25cf85e9f2e9dcfee6cb5d6","xdai":"0xabef652195f98a91e490f047a5006b71c85f058d","base":"0x417ac0e078398c154edfadd9ef675d30be60af93","optimistic-ethereum":"0xc52d7f23a2e460248db6ee192cb23dd12bddcbf6","arbitrum-one":"0x498bf2b1e120fed3ad3d42ea2165e9b73f99c1e5"},"image":{"large":"https://assets.coingecko.com/coins/images/30118/large/crvusd.jpeg?1683171990","small":"https://assets.coingecko.com/coins/images/30118/small/crvusd.jpeg?1683171990","thumb":"https://assets.coingecko.com/coins/images/30118/thumb/crvusd.jpeg?1683171990"}}
```
- [x] the withdraw timestamp is added (converted from withdraw block) in mybots api (@rootedbox )
- [x] the FE API calls are reduced after API update (@jamie088 )

**Comment by verabehr** [comment]
@jamie088 I believe this is an FE issue. Will you check on this one?

**Comment by taariq** [comment]
@jamie088 I have looked at noticed the following:

1. It appeas that Paloma makes 150 requests on the Mybot page for MY Account
2. CORS errors begin after about 200 requests are made. Why do we need to request 150 times on page load?
3. It appears that we are being offloaded to a secondary server that does not have CORS setup for Bloxroute. I'll inform the bloxroute team.  However, we need to fix why we are making so many requests from the endpoint provider, See picture
4. 

![Image](https://github.com/VolumeFi/paloma/assets/701864/5364999e-6b27-4940-893f-eb964f9d0214)
