### ISSUE TITLE
BUG: Users on Palomaswap are complaining they are not receiving GRAINs

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#128]
User claims that the following BNB transactions did not receive GRAINs.
1. https://bscscan.com/tx/0xb7f94b8a246e234b936ab1de622f278ac693ea074b27e5f292ae037a9af2662e
2. https://bscscan.com/tx/0xbed5768e809c91d1bec2bb5be02f7c9c1dfccad70c9649cda6e932522a075b56
3. https://bscscan.com/tx/0x9d8a0849bb38aee9ace3c26a0596121e1e80917ba69830d866404def32a1a0bf
4. https://bscscan.com/tx/0xc48c83b4774f6fe648bf27c3320bb3a530ee8f1a68c1667ced8e64e49295dea3
5. https://bscscan.com/tx/0x9e6bcb3a68764b5211d1853af20fab95a38cef82160e19ca38a1e45541e1aeec

We have the following tasks:
1. We need to confirm that these tx qualify for GRAINs.
2. We want to award the missing GRAINS
3. We want to confirm this issue will not recur
4. We want to add ALL registration of GRAINS failure in Sentry AND Alert Bots on Discord
5. We want to find ANY other txes that weren't registered and need GRAINs awards.

**Comment by taariq** [comment]
@rootedbox I tested this with my own wallet today and was able to reproduce.

**Comment by rootedbox** [comment]
![image](https://user-images.githubusercontent.com/3997890/234055255-c21af934-0791-4854-ac73-9333c9192a4d.png)
it worked from postman so might be an issue with the front end I'm going to add the sentry notifications now and I'll make sure all those transactions get their grains.

**Comment by taariq** [comment]
> it worked from postman so might be an issue with the front end I'm going to add the sentry notifications now and I'll make sure all those transactions get their grains.

How are we going to make sure ALL users who didn't report unclaimed GRAINs also get their missing GRAIS?
