### ISSUE TITLE
BUG: Leverage BOT JSON RPC error VM102:1 MetaMask - RPC Error: JsonRpcEngine: Response has no error or result for request:

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1280]
When choosing metamask, JSONRPC engineer has no response. 

**Metamask wallet is already on MEV ETH Protect endpoint.**

VM35257:1 MetaMask - RPC Error: JsonRpcEngine: Response has no error or result for request:
{
  "method": "net_version",
  "jsonrpc": "2.0",
  "id": 1820024992,
  "origin": "https://www.curvebot.fi",
  "networkClientId": "de1f9b7a-3dc6-4a19-a7b4-7a81bd70feab",
  "tabId": 900248278
} {code: -32603, message: 'JsonRpcEngine: Response has no error or result for…6-4a19-a7b4-7a81bd70feab",\n  "tabId": 900248278\n}', data: {…}}code: -32603data: {request: {…}, cause: null}message: "JsonRpcEngine: Response has no error or result for request:\n{\n  \"method\": \"net_version\",\n  \"jsonrpc\": \"2.0\",\n  \"id\": 1820024992,\n  \"origin\": \"https://www.curvebot.fi\",\n  \"networkClientId\": \"de1f9b7a-3dc6-4a19-a7b4-7a81bd70feab\",\n  \"tabId\": 900248278\n}"[[Prototype]]: Object
onChooseMetamask @ _app-7fab06ca97c77edc.js:1068
m @ _app-7fab06ca97c77edc.js:1068
onClick @ _app-7fab06ca97c77edc.js:1068
onClick @ _app-7fab06ca97c77edc.js:1068
eU @ framework-a2363dd3c3dbe572.js:9
eH @ framework-a2363dd3c3dbe572.js:9
(anonymous) @ framework-a2363dd3c3dbe572.js:9
re @ framework-a2363dd3c3dbe572.js:9
rn @ framework-a2363dd3c3dbe572.js:9
(anonymous) @ framework-a2363dd3c3dbe572.js:9
oP @ framework-a2363dd3c3dbe572.js:9
eF @ framework-a2363dd3c3dbe572.js:9
ro @ framework-a2363dd3c3dbe572.js:9
nU @ framework-a2363dd3c3dbe572.js:9
nD @ framework-a2363dd3c3dbe572.js:9
_app-7fab06ca97c77edc.js:1068 Uncaught (in promise) {code: -32603, message: 'JsonRpcEngine: Response has no error or result for…6-4a19-a7b4-7a81bd70feab",\n  "tabId": 900248278\n}', data: {…}}
ee @ _app-7fab06ca97c77edc.js:1068

**Comment by jamie088** [comment]
@taariq Are you getting this error right now? When creating a bot or loading the UI?
Because no issue for me.

**Comment by taariq** [comment]
Closing as rollback to Liquify
