### ISSUE TITLE
BUG: Paloma DEGEN bot shows Total Volume: $17,203,478 which is impossible.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1286]
BUG: Paloma DEGEN bot shows Total Volume: $17,203,478 which is impossible since https://etherscan.io/address/0xe79a404e31692c3043a0b03d9207d794598c3cf6 has not totaled $17MM in transactions. The numbers are incorrect.

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/bot-info-api/pull/65
