### ISSUE TITLE
Reduce Palomaswap Grain Rewards from 10% of Volume to 1% of Volume

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1289]
CHORE: Let's reduce the Palomaswap Grain rewards fro 10% of the transaction size to 1% of the transaction size. We will ratchet this down again in another month.

**Comment by jamie088** [comment]
@taariq @verabehr Is Grain reward % determined by FE? I don't think so and FE only displays the expected grain amount before executing the swap tx.

**Comment by verabehr** [comment]
@jamie088 I'm not 100% sure, but the FE passes the `claim amount` here, right? https://github.com/palomachain/paloma-nest-service/blob/main/app/controllers/RegisterController.js#L313

**Comment by jamie088** [comment]
@verabehr No, claimAmount is calculating from tx_hash in backend. https://github.com/palomachain/paloma-nest-service/blob/9cac65a0a71ed3cecd7db59a803a2de55903451d/app/controllers/RegisterController.js#L471
