### ISSUE TITLE
LEVERAGE BOT: Launch the N00B Leverage Bot Back-End

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1291]
As a user, I want to have the back-end system for the n00b bot completed so that I am able to get the collateral token instead of crvUSD and I have less choices to make when starting a bot.

**Acceptance Criteria**
- [x]  Make sure backend is working.
- [x] See the https://www.notion.so/volumefi/Palomabot-repo-and-contract-address-inventory-73691914623c4e91a0972ef6f13aad98 for the Curve Leverage Lending (NOOB)
- [x] Rename `curve-leverage.js` to `curve-noob-leverage.js`
- [x] Add the swap route for crvUSD (token1) into the collateral token when calling the repay function, so that users get the collateral token back. CW contract: https://github.com/VolumeFi/Curve-degen-leverage-bot-CW/blob/master/src/contract.rs#L214-L274

**Comment by verabehr** [comment]
https://github.com/VolumeFi/curve-noob-leverage-lending-bot/commit/5017d7735e18d71fe5fc2b8a9243026798360487
