### ISSUE TITLE
BUG: Old Bots Display showing both OLD and CURRENT bots. See pics

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1297]
BUG: Old Bots Display showing both OLD and CURRENT bots. See pics. @jamie088 this is a regression from today's update.

https://github.com/VolumeFi/paloma/issues/1295

![Image](https://github.com/VolumeFi/paloma/assets/701864/ef7c61a0-4206-4c9a-9a01-1e230e77efce)

![Image](https://github.com/VolumeFi/paloma/assets/701864/b1c97f43-968f-4f1a-87b8-bfb4f8233029)

**Comment by jamie088** [comment]
@rootedbox Why are the current mybot and closed bots API results the same?
Please check this api result. (Curve leverage bot)
https://service.palomabot.ai/robots?depositor=0x83334ef0C6f6396413C508A7762741e9FD8B20E9
https://service.palomabot.ai/robots?completed=true&depositor=0x83334ef0C6f6396413C508A7762741e9FD8B20E9

**Comment by taariq** [comment]
fixed with https://github.com/VolumeFi/bot-info-api/pull/67#event-11884693390

**Comment by taariq** [comment]
@rootedbox this is not fixed. Still showing dead bots in Mybots page. 
<img width="1617" alt="Screenshot 2024-02-21 at 9 26 21 PM" src="https://github.com/VolumeFi/paloma/assets/701864/69128409-233e-4670-9fbb-a100c4b9ac25">

**Comment by rootedbox** [comment]
@jamie088 
https://service.palomabot.ai/robots?completed=true&depositor=0x83334ef0c6f6396413c508a7762741e9fd8b20e9

https://service.palomabot.ai/robots?depositor=0x83334ef0c6f6396413c508a7762741e9fd8b20e9

are now different.. and the api is showing 4 records open but not seeing any bots in the front end

cc: @taariq 

https://cdn.discordapp.com/attachments/1014207212954066975/1210305987379208223/Screenshot_2024-02-22_at_11.23.24_AM.png?ex=65ea1449&is=65d79f49&hm=7d2d2fe6ff1213039e6680b471c2cee51f06315ddb12fbd0979413b588e29e5f&

**Comment by rootedbox** [comment]
![Image](https://github.com/VolumeFi/paloma/assets/3997890/36655a89-cb92-42f2-b284-e2371e42fa54)

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/bot-info-api/pull/69
