### ISSUE TITLE
BUG: User created a tBTC Leverage Bot, but the Mybot pages showas a WETH Token

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1303]
BUG: User created a tBTC Leverage Bot, but the Mybot pages showas a WETH Token. 

Transaction: https://etherscan.io/tx/0xa66bd50ca82160e696002e4b9ca216b1e8e26725f2502ec48675513880f65d6a

Mybots Page:

![Image](https://github.com/VolumeFi/paloma/assets/701864/c5f1f05c-9d6a-419a-a5ce-0a8f9a008b94)

**Comment by rootedbox** [comment]
![Image](https://github.com/VolumeFi/paloma/assets/3997890/8b0ccd23-d2c8-4431-9f73-802d60bc91c3)

tBTC was not one of the coins sent to the backend as an event. only owner, bot and collateral.

**Comment by taariq** [comment]
@wc117 this ticket now assigned to you. 
User took his tBTC, but it appear that it was swapped instead of used as collateral?
https://etherscan.io/tx/0xa66bd50ca82160e696002e4b9ca216b1e8e26725f2502ec48675513880f65d6a#eventlog

According to @rootedbox 
> so the backend is sending the weth that the contract sent it. so the front end shows weth
> so it's an issue with the contract

**Bug: Thus, the leverage loan ended up in WETH when it received a deposit of tBTC.**

**Comment by wc117** [comment]
The transaction actually swapped the tBTC into WETH and used it as a collateral. So the transaction and frontend data are correct. It looks like the user selected WETH as a collateral instead of selecting tBTC.

**Comment by wc117** [comment]
@taariq

**Comment by taariq** [comment]
user error to be fixed with https://github.com/VolumeFi/paloma/issues/1305
