### ISSUE TITLE
Set up backend for Lido staking TryLSD bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1306]
https://github.com/VolumeFi/lido-trylsd-staking-bot

### Done when
- [ ] complete missing features of the staking bot back-end.
- [ ] service is set up
- [ ] service is started on server
- [ ] service is debugged 

Vyper contract: https://github.com/VolumeFi/lido-trylsd-staking-bot-vyper
Cosmwasm contract: https://github.com/VolumeFi/lido-trylsd-staking-bot-cw

**Comment by rootedbox** [comment]
just a heads up @webelf101 https://github.com/VolumeFi/lido-trylsd-staking-bot is missing it's index.js

**Comment by taariq** [comment]
@rootedbox please restart on this ticket today. Let's complete this so that the back end is functional by the end of the week.

**Comment by taariq** [comment]
@fieldtheory123 will provide support and tracking on this feature.

**Comment by rootedbox** [comment]
@webelf101 still missing index.js

**Comment by taariq** [comment]
@rootedbox do you need @webelf101 to complete or can you just get this done?

**Comment by rootedbox** [comment]
If we are using the entry point that I use in my bots `processDeposits` we should be ok.. @webelf101 let me know if you wanted to use a different entry point

**Comment by webelf101** [comment]
`processDeposits` is a correct entrypoint. And I modified the script a bit.

**Comment by taariq** [comment]
Closing as complete as we focus on the Liquid Restaking Tokens Bots
