### ISSUE TITLE
Improve: momentum api update

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1308]
In Curve leverage bot newbie version (Juice bot), I want to get these token's market and volume data: `ETH, WBTC, tBTC, sfrxETH V2, wstETH`. (as so that we can get data with just the token name or symbol.)
Currently, we are not able to get the selected token's volume and market information from the Momentum API
https://momentum.palomabot.ai/
(we can get the data when passing token name, dex, lag_return, vol_30, and market_cap values as parameters. But in this case, there is case of empty result.)

**Comment by verabehr** [comment]
https://www.palomabot.ai/momentum/bot/?dex=curve_ethereum&lag_return=6&daily_volume=0&vol_30=100000&market_cap=1000000&token=keep3rv1

This is an example of a link that returns the data that we want

**Comment by taariq** [comment]
Closing as unable to fix. @jamie088 we will do without the chart data for now.
