### ISSUE TITLE
Create Python Cache Refresh that will catch Cron update failures

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#131]
# Background

We currently have a maximum of 500K queries on our Coingecko API. We want to be able to check the cache of the Coingeko queried data each minute and make sure that updates are completed every 3 hours so that users do not have data is that more than 3 hours old.

# Done when
- [ ] Python side cache completes every minute and the cron is run every 3 hours
- [ ] We do not use more than 500K of our monthly limit in requests.

**Comment by taariq** [comment]
@measure-fi is this finished in the latest PR merge?

**Comment by measure-fi** [comment]
@taariq Should be after I finish work on https://github.com/VolumeFi/trading-bots/pull/16, which should not have been merged.

**Comment by taariq** [comment]
> @taariq Should be after I finish work on [VolumeFi/trading-bots#16](https://github.com/VolumeFi/trading-bots/pull/16), which should not have been merged.

Understood. In future, let's put a *DO NOT MERGE* tag on PRs that aren't to be merged.

**Comment by verabehr** [comment]
https://github.com/VolumeFi/trading-bots/pull/17
