### ISSUE TITLE
LLAMALEND: As a user, I want to leverage EzETH against crvUSD with Llamalend

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1313]
As a user, I want to be able to use EzETH for leverage collateral with LLlamalend so that I am able to take leverage positions on Renzo's EzETH as a Curve Leverage Bot and Palomabot.

**Acceptance Criteria**
1. Use new Llamalend contracts to create leverage position on EZETH
2. Use the borrow_more_extended functionality to allow user to increase leverage on the position, if profits exists
3. Use all the curve leverage bot features

Notion: https://www.notion.so/volumefi/EPIC-3-1-24-LLAMALEND-ezETH-leverage-bot-92d10b971f344ceb89642c5b5fa62d09?pvs=4

**Comment by verabehr** [comment]
redeployment logs: https://github.com/curvefi/curve-stablecoin/commit/1c817319f53631f97a9a88a5578d13ca90aed780

**Comment by taariq** [comment]
As per @wc117: Time to completion:
> 1 day. At most 2 days? I hope it will be ready by tomorrow, 03/26/24
