### ISSUE TITLE
EPIC: LLamalend for EzETH Leverage

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1317]
As a developer for Volume, I want to read the Llamalend leverage bot epic for EzETh so that we know how to use Llamalend for Leveraged LRTs.

**Comment by fieldtheory123** [comment]
https://www.notion.so/volumefi/EPIC-3-1-24-LLAMALEND-ezETH-leverage-bot-92d10b971f344ceb89642c5b5fa62d09

**Comment by taariq** [comment]
Closing as completed.
