### ISSUE TITLE
BUG: Error: cannot estimate gas; transaction may fail or may require manual gas limit

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1321]
Link: https://www.curvebot.fi/curve-juice/ETH/

contentScript.bundle.js:1 Content script works!
contentScript.bundle.js:1 ===> FROM THE PRINT MODULE: Using the 'printLine' function from the Print Module
6916-ec1e2a261749e8f6.js:1 CURVE-JS IS CONNECTED TO NETWORK: Object
ETH/:1 Third-party cookie will be blocked. Learn more in the Issues tab.
curve-twap-45e45d5ca5198576.js:1 swapRoutes Array(2)
[id]-1cd58abd764e7da9.js:1 args Array(10)
VM100:1 MetaMask - RPC Error: execution reverted Object
(anonymous) @ VM100:1
3514-6fa56f3a9c7848d5.js:1 e Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x83334ef0C6f6396413C508A7762741e9FD8B20E9","to":"0x34BC9970228b14A76ebF0A7f5a601001bBCA20C8","value":{"type":"BigNumber","hex":"0x016345785d8a0000"},"data":"0x707c96ae0000000000000000000000000000000000000000000000000000000000000180000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000000000000000000000000002a9bedf49efdd4914000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000d3e576b5dcde3580420a5ef78f3639ba9cd1b967000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000002e4000000000000000000000000000000000000000000000000000000000000138800000000000000000000000000000000000000000000000000000000000000c800000000000000000000000000000000000000000000000000000007bd8e40df0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000bebc44782c7db0a1a60cb6fe97d0b483032ff1c7000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7000000000000000000000000d51a44d3fae010294c616388b506acda1bfaae46000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007735940000000000000000000000000000000000000000000000000008b58215849f84cf000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000036cd530765d97448","accessList":null}, error={"code":-32000,"message":"execution reverted"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at f.makeError (_app-a8980f84eb85d281.js:1:189313)
    at f.throwError (_app-a8980f84eb85d281.js:1:189427)
    at b (_app-a8980f84eb85d281.js:1:263738)
    at l.<anonymous> (_app-a8980f84eb85d281.js:1:273617)
    at Generator.throw (<anonymous>)
    at s (_app-a8980f84eb85d281.js:1:262855)

![Image](https://github.com/VolumeFi/paloma/assets/701864/d4e74ede-a239-4a33-927c-89b344838649)

**Comment by jamie088** [comment]
I tested it several times but couldn't reproduce it. @fieldtheory123 Could you please test it?

**Comment by taariq** [comment]
@jamie088 does this smell like bloxroute issue?

**Comment by jamie088** [comment]
No, it is not bloxroute issue. This issue happens when estimating gas before running the tx and this means the parameters or contracts have an unknown error. But I tested it several times and also checked your tx and did not find an error. Could you please test it again?

**Comment by taariq** [comment]
@jamie088 how does the service estimage gas? It makes an RPC call via bloxroute. I am not the only person having this issue. If there's another way that the call to get gas estimate is made, let me know, but I suspect this is RPC endpoint issue. Correct  me if there's another way to get gas estimate. This issue is impacting front-end experience.

**Comment by taariq** [comment]
Closing until it hurts.
