### ISSUE TITLE
BUG: The list of bot shows UniswapV2 TWAP Bot (0) and UniswapV3 TWAP Bot (0) with leverage_curve

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1322]
![Image](https://github.com/VolumeFi/paloma/assets/701864/fe8268cb-607a-4ca7-b439-6354079fdd34)

**Comment by taariq** [comment]
PR for this fix?

**Comment by jamie088** [comment]
There are no PRs for any curvebot updates. We are pushing the code directly to the main-curvefi-bot branch after syncing with palomabot.

**Comment by taariq** [comment]
okay. closing
