### ISSUE TITLE
BUG: The juice bot TVL formula should same as the Leverage bot. TVL is wrong.

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1325]
Volume of the Juice bot and Leverage bot is not correct.
Please check it. this is our bot's TVL calculating formula: https://www.notion.so/volumefi/PNL-and-TVL-calculation-for-bots-734b59446f084078b5f22733b1042d76
The juice bot TVL formula should same as the Leverage bot.
 (https://service.palomabot.ai/stats)

**Comment by taariq** [comment]
Fixed.
