### ISSUE TITLE
BUG: Profit/Loss Total on Mybots page is $0.00 when health is 11%

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1326]
Bot created here:
https://etherscan.io/tx/0xed9d18bd7a2494b5aacfdd98de209dd5f41c605bfc0931f03ef1f6484bc950f3

Mybots Page is here:

![Image](https://github.com/VolumeFi/paloma/assets/701864/98f8310c-a774-4d67-8078-779feb41caaf)

**Comment by rootedbox** [comment]
> @rootedbox `tracking_price` field is missing for Juice bot in mybots API.

  {
    "deposit_id": "1",
    "token0": "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599",
    "token1": "0xf939e0a03fb07f59a73314e73794be0e57ac1b4e",
    "amount0": "2737747",
    "amount1": "8933664357680402000000",
    "depositor": "0xc0c7DA58E5455621D918FD155870EAddEf51E227",
    "deposit_price": "1493.13983633",
    "expire": "33244989131",
    "withdrawer": "0x83334ef0C6f6396413C508A7762741e9FD8B20E9",
    "network_name": "ETH",
    "dex_name": "curve",
    "bot": "juice_wbtc_curve",
    "number_trades": "1",
    "remaining_counts": "0",
    "interval": "30",
    "contract": "0x34BC9970228b14A76ebF0A7f5a601001bBCA20C8",
    "bot_type": "4",
    "fees_charged": "0.09544838837316044",
    "sent_to_mixpanel": "0",
    "transaction_hash": "0xed9d18bd7a2494b5aacfdd98de209dd5f41c605bfc0931f03ef1f6484bc950f3",
    "create_to_mixpanel": "0",
    "created_at": "2024-02-26 23:12:43",
    "gas_mixpanel": "0",
    "leverage": "706",

@jamie088

**Comment by rootedbox** [comment]
![image](https://github.com/VolumeFi/paloma/assets/3997890/b908fbd0-7acc-4e97-a454-80474045941f)


A quote was missing from a query breaking the bot.
