### ISSUE TITLE
DEVOPS Error: ENOENT: no such file or directory, open './networks.json'

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1327]
Error: ENOENT: no such file or directory, open './networks.json'
  File "/Users/rootedbox/Source/VolumeFi/curve-noob-leverage-lending-bot/curve-noob-leverage.js", line 73, in setupConnections
    const data = await fs.readFile('./networks.json', 'utf8');

https://volume-x3.sentry.io/issues/5017802354/?referrer=alert_email&alert_type=email&alert_timestamp=1709065673636&alert_rule_id=14737330&notification_uuid=3df1afc6-d1ab-44b0-a454-a089a6e9fff2&environment=production

**Comment by rootedbox** [comment]
this was a local issue on my computer
