### ISSUE TITLE
BUG: Difference in Mybot Pages Profit vs. Actual Settlement deposit. How do we explain?

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1328]
User believes that profit presentation on Mybots page is inaccurate when cmpared with received funds.

Create Bot: 
https://etherscan.io/tx/0x1b68bf266d71ee52833b68fb7445ca77106f7220da31b85ed99af7cb41ecbed3

Disscord Create Bot Alert:
* New Bot! - Bot Name: leverage, Token Input: eth, Amount Input: 6277.41, Token Output: crvusd, Amount Output: 42014.31, Chain Name: ETH

Repay Bot:
https://etherscan.io/tx/0xc16aae54d8b31158f056fb72969e75b342ab525be129042e89603453386e515f

Profit on the Mybots page: $3,073.00
Profit Collected in crvusd $2,680.00

User deposited $6,263.95 CRVUSD
User received $8,928.80 CRVUSD

Onchain Values: $2,664.85 CRVUSD in the create and repay bot flows.

Difference in user expectation: $393. 

Conclusion: I am not sure how to explain these and worry that the crvUSD prices are fluctuating continuously so that even when we look at the Etherscan txes now, they are really out of date on price. I tried to reproduce this myself with my own txes:

Create Bot Taariq: https://etherscan.io/tx/0x88b14a2c19626d5b416ad61cae8dfca6b802e5655647003337ddbc263e737dd3

Repay Bot Taariq: https://etherscan.io/tx/0xc4071c0ebdc0a73549232dbe583c1d60eb90394e291c7128820ac5a3349110ff

Taariq deposited $1,491.81 CRVUSD
Taariq recieved $2,943.47 CRVUSD

Onchain Profit: $1,451.66 CRVUSD in the create and repay bot flows.

Profit on the Mybots page: $1,438.74

So the Profit on the Mybots page was LESS than the actual CRVUSD received.

**Comment by fieldtheory123** [comment]
Seems to be slippage + crvUSD price volatility

<img width="799" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/5f203735-c541-4f12-9e31-7572425d82d9">

51,162.95 - 50,833.64 = 329.31, accounting for most of user expectation difference.

**Comment by taariq** [comment]
Thank you. Closing as answered!
