### ISSUE TITLE
BUG: Volume.finance website showing $569,123,242 which is impossible

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1329]
BUG: Volume.finance website showing $569,123,242 which is impossible

Also, this impacts https://www.palomabot.ai/

<img width="522" alt="Screenshot 2024-02-27 at 4 29 25 PM" src="https://github.com/VolumeFi/paloma/assets/701864/0b01593a-088f-410b-82b4-00dd6e35673a">

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/bot-info-api/pull/74/files

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/bot-info-api/pull/74
