### ISSUE TITLE
As a user, I want the DCA Bot run as a Test Bot on the Private Testnet for end-to-end testing

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#133]
# Background

We want to move the private testnet to be able to automatically run tests of one bot on network start so that we will be able to test the deployment of bot Cosmwasm and Vyper contracts and run the actually test of a transaction.  We propose to select the DCA bot as the bot for automated testing. 

# Done when
- [x] Follow the DCA bot test instructions sequence as documented here: [How to run DCA bot using pancakeswap](https://www.notion.so/volumefi/EPIC-01-20-Build-a-DCA-trading-bot-b25aa8da2a0f489d880aac178ac65384?pvs=4#dd952fb10e0e4304b98ae0ef59da6c02)
- [x] Deploy the DCA Bot cosmwasm contract to Paloma's private testnet with this repo: https://github.com/VolumeFi/dca-bot-pancakeswap-cosmwasm
- [ ] Run the DCA bot Python script  from within Ansible: https://github.com/VolumeFi/dca_bot_python_script
- [x] Check for the transaction hash of a successful transaction

**Comment by verabehr** [comment]
This is not run as part of the Ansible playbook, but I don't think it's needed for this task @taariq @ToasterTheBrave or do we want to run this every time we spin up the testnet? I think we can close this out.

**Comment by verabehr** [comment]
as discussed on standup, we do want the DCA bot to be run every time we spin  up the testnet, so we have an end to end test integration test of one bot

**Comment by verabehr** [comment]
moving last task into separate ticket
