### ISSUE TITLE
EPIC: Add Back-end Workflow requirements for "Curve Healthy DEGEN JuiceBOT"

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1331]
Add Back-end Workflow requirements for "Curve Healthy DEGEN JuiceBOT"

Notion: https://www.notion.so/volumefi/EPIC-03-01-24-Curve-leverage-lending-bot-with-automatic-re-leveraging-aka-Curve-Healthy-DEGEN-Juic-0d634914ea9040ed933b8758d553b261

**Comment by fieldtheory123** [comment]
https://www.notion.so/volumefi/EPIC-03-01-24-Curve-leverage-lending-bot-with-automatic-re-leveraging-aka-Curve-Healthy-DEGEN-Juic-0d634914ea9040ed933b8758d553b261

**Comment by taariq** [comment]
@fieldtheory123 Anything else left here

**Comment by fieldtheory123** [comment]
> @fieldtheory123 Anything else left here

Should be all set
