### ISSUE TITLE
BLAST: Implement Validator Refunds on Blast

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1340]
@webelf101 Blast is an OP Fork. We need Validator refunds on Blast activated before the Compass-EVM is deployed in 2 days.
https://paloma.explorers.guru/proposal/46

**Comment by verabehr** [comment]
Blast Compass evm: 0x89Eb9f00498FFd5df9430426f2802dBa82D414b6

**Comment by verabehr** [comment]
@webelf101 there is a sentry error related to Blast here https://volume-x3.sentry.io/issues/5059648587/?alert_rule_id=14490847&alert_timestamp=1710274255270&alert_type=email&environment=production&notification_uuid=8d923ed6-296f-4203-8a5d-00bba4b88c4f&project=4504030535155712&referrer=alert_email

**Comment by verabehr** [comment]
@webelf101 new issue https://volume-x3.sentry.io/issues/5062266194/?alert_rule_id=12564416&alert_timestamp=1710339161227&alert_type=email&environment=production&notification_uuid=b03c9af7-a2c6-4979-b4f4-1cd112a57d97&project=4504030535155712&referrer=alert_email

**Comment by verabehr** [comment]
@webelf101 https://volume-x3.sentry.io/issues/5062458148/?referrer=alert_email&alert_type=email&alert_timestamp=1710342646642&alert_rule_id=14490847&notification_uuid=746f0a47-9ac6-4ee6-9381-a810c4b53f1a&environment=production
