### ISSUE TITLE
Curve Healthy Juice Bot: add additional fields to BotStarted event

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1342]
### Background
https://www.notion.so/volumefi/EPIC-03-01-24-Curve-leverage-lending-bot-with-automatic-re-leveraging-aka-Curve-Healthy-DEGEN-Juic-0d634914ea9040ed933b8758d553b261?pvs=4#bfcd47db39b84cdf8334ba01badd371c

For the new Curve Healthy Juice Bot, users will be able to enter a lower AND an upper health threshold. 

### Done when

- [ ] The https://github.com/VolumeFi/Curve-degen-leverage-bot-vyper (is forked) and the `health_threshold_upper` field is added 
- [ ] field `settlement` is added which holds the settlement token that the user chooses to get swapped into when automatic deleveraging happens
- [ ] the contract is deployed on ethereum

**Comment by wc117** [comment]
Can you add more details about settlement? What is it and what does it work? @verabehr

**Comment by verabehr** [comment]
@wc117 it's the token that is paid back to the user when the backend script deleverages the loan. So we have the deposit token, the collateral token, crvUSD and the settlement token

**Comment by verabehr** [comment]
https://github.com/VolumeFi/Curve-healthy-juice-degen-vyper
