### ISSUE TITLE
Curve Healthy Juice Bot UI

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1344]
https://www.notion.so/volumefi/EPIC-03-01-24-Curve-leverage-lending-bot-with-automatic-re-leveraging-aka-Curve-Healthy-DEGEN-Juic-0d634914ea9040ed933b8758d553b261?pvs=4#bfcd47db39b84cdf8334ba01badd371c

This is very similar to the Curve leverage lending Degen bot, but with 2 additions
- ~~users can choose 2 health thresholds, a lower limit and an upper limit~~
- users can choose a "profit taking" amount. When the bot's profit reaches this amount, the bot will automatically deleverage according to the user's parameters. 
- When the user chooses the profit taking amount, we will also display the APY that this amount corresponds to
- users can choose their settlement token

Contract: 
https://etherscan.io/address/0x7188df1c4b1c40ae86ef86fe8e3498690da8a917#code

Figma:
https://www.figma.com/file/6DYR6QFkucGd1bsOILr7V0/Paloma-Bot?type=design&node-id=2131-464378&mode=design&t=0LXxC7en71UPXLua-4

**Comment by verabehr** [comment]
@taariq so the settlement token is not the collateral token or the deposit token, but a third token?

**Comment by taariq** [comment]
> @taariq so the settlement token is not the collateral token or the deposit token, but a third token?

Yes. Not collateral. Not deposit. Not crvUSD, but any token for which there is a curve pool. We could limit it to any stable crvUSD, USDC, or USDT to keep it simple. Most people want to hold gains in stable.

**Comment by verabehr** [comment]
got it, @fieldtheory123 FYI. will add this to the smart contract update ticket where this choice will be stored

**Comment by verabehr** [comment]
@joycehermosilla @jamie088 updated the ticket description to reflect the new requirements

**Comment by jamie088** [comment]
@verabehr `users can choose their settlement token`
Is the settlement token one of the Curve Market tokens (5 tokens: eth, wbtc, wstETH, sfrxeth, tbtc)? Or is it some other token?

**Comment by jamie088** [comment]
@fieldtheory123 Could you please update the APY calculation formula for this?
