### ISSUE TITLE
Private Testnet: Running run.sh on linode servers does not upgrade software.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#135]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Attempted to run the linode servers, but it appears that master was not building for either paloma or pigeon. File checks on the linode servers show dates in April for a deployment request for May.

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

Master

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

I think this may just be a documentation issue for making sure we know how to deploy/test on the linode servers.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

when running `./run.sh`, linode servers will deploy the correct tag and code for testing.

**Comment by verabehr** [comment]
https://github.com/palomachain/private-testnet/pull/18
