### ISSUE TITLE
Add target return to the Profit & Loss Calculation in the my bots page

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1353]

**Comment by fieldtheory123** [comment]
Current annualized interest rate (APY):
1. run `rate(token_address)` query on this contract https://etherscan.io/address/0x8c5A7F011f733fBb0A6c969c058716d5CE9bc933#readContract
2. use the formula `borrowApy = e** (rate/1e18*365*86400) - 1` to get the APY

Interest rate accrued:
1. run `debt(user)` query on this contract https://etherscan.io/address/0x4e59541306910ad6dc1dac0ac9dfb29bd9f15c67#readContract
2. `debt - initial debt at deposit` is interest accrued

**Comment by fieldtheory123** [comment]
Renamed the title to "target return"

Instead of APY, we will call it target return. The formula is `profit taking percentage * leverage`. Note this is net of fees and gas

**Comment by taariq** [comment]
@fieldtheory123 and we confirm that profit taking still includes gas cost and annual interest rate on the collateral?

**Comment by taariq** [comment]
@jamie088 this ticket is for Mybots page, but this calculation is also for healthy Bot page.

**Comment by fieldtheory123** [comment]
@taariq @jamie088 Gas costs and accrued interest should be included in pnl calculation, profit taking is a user input number. And when pnl > profit taking, the bot closes out

**Comment by fieldtheory123** [comment]
@jamie088 profit-taking is the number above which a user would like to deleverage. When total pnl > profit taking, the bot deleverages
