### ISSUE TITLE
Access to Fetch has been Blocked

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1355]
Access to fetch at 'https://nest-service.palomachain.com/tokens/market-data?network=1&token=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2' from origin 'https://www.curvebot.fi/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled

URL: https://www.curvebot.fi/curve-juice/ETH/

Expected behavior: There should be no such errors. Our Coingecko account is paid and upgraded.

**Comment by verabehr** [comment]
From @rootedbox 
rootedbox — Yesterday at 12:39 PM
working fine for me.. you might need to refresh cache..also  https://cors-test.codehappy.dev/?url=https%3A%2F%2Fnest-service.palomachain.com%2Ftokens%2Fmarket-data%3Fnetwork%3D1%26token%3D0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2&origin=https%3A%2F%2Fcors-test.codehappy.dev%2F&method=get
