### ISSUE TITLE
BUG: Dogecoin decimals should be 8, not 18 in api

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1358]
- [x] This tx is missing from the DB https://bscscan.com/tx/0xf0a6b962911109ba7caacb39584f979254e8161776cf42d7b0b8591c792eba8f
- [x] `Dogecoin` decimals should be 8, not 18 in api
- [x] Please confirm if `Maga Trump` decimals is 9.
Other memecoins decimals are 18.

**Comment by rootedbox** [comment]
had to reset fetched block for momentum blocks then I also had to update the robot-api because different networks called doge coin slightly different names
