### ISSUE TITLE
EPIC: Paloma Leverage Bot Sweepstakes

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1359]
Update https://www.notion.so/volumefi/EPIC-3-8-24-Curve-Leverage-Bot-Sweepstakes-d014fa9bccca4715a9fb051bb9873371 based on price prediction sweepstakes.

**Comment by fieldtheory123** [comment]
https://www.notion.so/volumefi/EPIC-03-08-24-Juice-Bot-Price-Prediction-Competition-Sweepstakes-d014fa9bccca4715a9fb051bb9873371

**Comment by taariq** [comment]
Done.
