### ISSUE TITLE
Curve Healthy Bot price predictor vyper contract

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1366]
https://www.notion.so/volumefi/EPIC-03-08-24-Juice-Bot-Price-Prediction-Competition-Sweepstakes-d014fa9bccca4715a9fb051bb9873371?pvs=4#f25c1064e67140768f2b5d6d53926fc5

**Comment by fullstack412** [comment]
EthPricePrediction Arb - https://arbiscan.io/address/0x2945E8A9d13Ff004F6d5bCe1DAcA80b918074fcd
EthPricePrediction Eth - https://etherscan.io/address/0xaf4078a536FA9B7C3b2Cb23c48325b12e4CaB3B3

@rootedbox
