### ISSUE TITLE
Bot scripts: Receipt not available for From block

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1371]
There are a few sentry errors with the same error message `Receipt not available for From block`. Will you please investigate what's causing this and if this is an issue? 
Note, currently this is not impacting any active bots. 

[Sentry 1](https://volume-x3.sentry.io/issues/5058546290/?alert_rule_id=14209893&alert_timestamp=1710254667958&alert_type=email&environment=production&notification_uuid=47844a20-fb58-428f-87f9-d0febc4da5a0&project=4505082653573120&referrer=alert_email)

[Sentry 2](https://volume-x3.sentry.io/issues/5058577758/?alert_rule_id=14209893&alert_timestamp=1710255203966&alert_type=email&environment=production&notification_uuid=9e0ca411-3ab4-4552-af88-3378c67e1f01&project=4505082653573120&referrer=alert_email)

[Sentry 3](https://volume-x3.sentry.io/issues/5058625019/?alert_rule_id=14209893&alert_timestamp=1710255951750&alert_type=email&environment=production&notification_uuid=92e607b6-a5f2-4283-9058-d071cb0c92c8&project=4505082653573120&referrer=alert_email)

[Sentry 4](https://volume-x3.sentry.io/issues/5058592846/?alert_rule_id=14209893&alert_timestamp=1710255546705&alert_type=email&environment=production&notification_uuid=41daea99-1d7b-4f5f-8849-d51db973fed1&project=4505082653573120&referrer=alert_email)

[Sentry 5](https://volume-x3.sentry.io/issues/5058647012/?alert_rule_id=14209893&alert_timestamp=1710256328493&alert_type=email&environment=production&notification_uuid=b8b5d853-9b96-4e79-a15d-e3dddeb3cf9b&project=4505082653573120&referrer=alert_email)

**Comment by rootedbox** [comment]
Other folks online report the same issue with getLogs but because we just move on to more blocks it doesn't hold us up and we don't lose anything.
