### ISSUE TITLE
Healthy Bot Updates

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1379]
1. As a user, I want the Curve healthy bot to set minimum health to 3% for repayment so that repayment will occur when bot health hits 3.5% OR LESS.

3. As a user, I want the repayment amount to be based on a both health of 5% so that the bot will repay the loan when loan health is 3% but enough to bring loan health back to 10%. 

Question: @fieldtheory123 We are able to calculate the repayment amount for a target health rate. Yes?

**Comment by fieldtheory123** [comment]
Yes I think we are able to do so. Alternatively, we could use a recursive algorithm to query Curve multiple times to see what it takes to bring health factor back to 10%.
