### ISSUE TITLE
Healthy Bot: Convert Bands to Leverage from Low Leverage to Maximum Leverage

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1380]
Convert Healthy Bot Leverage Bands to Lowest Leverage to Highest Leverage Slider with Lowest Leverage on the left.

**Comment by jamie088** [comment]
@taariq Should I display the bands number in the UI?

![Image](https://github.com/VolumeFi/paloma/assets/83244763/b84dcc87-efbc-466f-bd1a-5e7fbad1dcdd)

**Comment by taariq** [comment]
@jamie088 no bands. Just low leverage to high leverage

**Comment by taariq** [comment]
@jamie088 please use **Low Leverage** and **Maximum Leverage**

**Comment by jamie088** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/398
