### ISSUE TITLE
BUG: Profit and Loss over $400 on creation of a bot and TVL is appears incorrect.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1381]
New Bot! - Bot Name: leverage, Token Input: tbtc, Amount Input: 5978.72, Token Output: crvusd, Amount Output: 31970.59, Chain Name: ETH.

Transaction: 
https://etherscan.io/tx/0x7007aef02f33282e3638a2f544acbebfd3f01a81954ecc7704106eaac718b382

My bots page:
![Image](https://github.com/VolumeFi/paloma/assets/701864/1cfecc61-11ed-4f33-97a4-67c12ddb3b90)

1. Bot shows profit of $400 immediately on creation
2. TVL amount is **$38,383.40**, but Amount Output is **$31970.59**

**Comment by fieldtheory123** [comment]
@rootedbox @jamie088 One thing I'd check is the pricing of tBTC and make sure it's correct. There's a slight difference in price between wbtc and tbtc.

**Comment by jamie088** [comment]
@fieldtheory123 Checked the tBTC price and no issue.

**Comment by jamie088** [comment]
@taariq checked user transaction and FE but couldn't find the problem. We used this formula to calculate TVL and PnL.: https://www.notion.so/volumefi/PNL-and-TVL-calculation-for-bots-734b59446f084078b5f22733b1042d76
@fieldtheory123 Could you please check the TVL and PnL formula of the Curve leverage lending bot again?

**Comment by fieldtheory123** [comment]
Both formulas look fine to me

**Comment by taariq** [comment]
Closing as won't fix. the profit is real.
