### ISSUE TITLE
BUG: rpc2.palomachain.com doesn't work

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1390]
rpc2 was pointing to a linode that no longer exists. This was changed in google domains to point to the same mainnet validator server that lcd2 points to, but additional changes are needed to make this work. 

Server: mainnet-validator 45.56.95.14
Error: ```palomad status
Error: post failed: Post "https://rpc2.palomachain.com:443": x509: “lcd.palomachain.com” certificate name does not match input```

**Comment by rootedbox** [comment]
https://rpc2.palomachain.com now running
