### ISSUE TITLE
set minimum health to 3.5% for repayment and for loan creation

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1391]

**Comment by jamie088** [comment]
> Can you set Maximum CRVUSD for health greater than 3.5%?

This will be some difficult because we are getting the Health value from Curve api with Deposit token amount and output crvUSD amount.
The opposite case(crvUSD amount from Health) does not exist in curve API.

**Comment by taariq** [comment]
okay. Closing this ticket since we already have automatic repayment at 3% for Curve Healthy bot.
