### ISSUE TITLE
BUG: Gnosis Relays are still getting stuck on Gnosis after upgrade on Paloma

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1394]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

User Submits TWAP to Gnosis:
https://etherscan.io/tx/0x06c79bdffae2b1d32810d985d76cf39d1174ecf3aea8740b28b240678b2303fb

Funds Arrive on Gnosis:
https://gnosisscan.io/address/0x48afa99cd4166d89718cba46db7e1eeb99535b46#internaltx

No submit Logic call for 21 hours.:
https://gnosisscan.io/address/0x0c6571537d0275dbc6c93e00f4ca19500fa9c835

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

We Tested Gnosis offramp yesterday and it work. Somehow the relays don't work today.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

https://gnosisscan.io/address/0x48afa99cd4166d89718cba46db7e1eeb99535b46#internaltx needs to relay.

**Comment by verabehr** [comment]
palomad on LCD server was down since palomad hadn't been updated to paloma v1.12.2. (This was due to the fact that it still needed to catch up yesterday and couldn't be upgraded during the chain halt time.)
Upgraded palomad now, restarted service, LCD is still catching up. Set a reminder to 1 hour from now to check in again

**Comment by verabehr** [comment]
Failed over to LCD2, tx now going through

**Comment by taariq** [comment]
Closing as fixed.
