### ISSUE TITLE
Alert and monitor when LCD is stuck

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1395]
We need a monitor and discord/telegram alert when the LCD is stuck (not progressing in blocks and not catching up either). We only have one when palomad on the LCD server is down.

**Comment by rootedbox** [comment]
https://lcdcheck.palomachain.com

**Comment by verabehr** [comment]
reopening as we didn't get an alert from the snapshot server which is stuck on the same block. Same for the validator, but the validator is no longer in the stuck state. The snapshot server wasn't touched.

**Comment by verabehr** [comment]
This was tested - closing
