### ISSUE TITLE
non-performance: can't see Curve limit order bot for Arbitrum in mybots api result

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1396]
I saw my Curve limit order bot for Arbitrum until 1 hour ago but I can't see my bot on mybots api result for now on both active and closed bots. 
There is no withdrawn event and I haven't received the buy token yet.
https://arbiscan.io/address/0x48afa99cd4166d89718cba46db7e1eeb99535b46#code (contract address)
https://arbiscan.io/tx/0xb94fa5b9027e0392a8c3103e35b66f2d97455c26647f89d9cebf45ee658d1d88 (created bot tx)

**Comment by rootedbox** [comment]
the bots had expired however... on closed bots we don't show expired.. so I had to add them.
