### ISSUE TITLE
Add backrun wallet balance monitor in Mixpanel 

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#14]
# Background

We need to keep track of  backrun wallet balances in Mixpanel. The python script for querying the balance data is ready. We need to set up a cronjob that runs on a daily basis and record balance data in Mixpanel. 

Here is the script for monitoring the balance of all backrun wallets
https://github.com/VolumeFi/paloma-wallchain/blob/main/balance_monitor.py

python balance_monitor.py will return lists of balances.

# Done when

- [ ] The balances are being recorded regularly in Mixpanel.

**Comment by rootedbox** [comment]
Added code to [kits](https://github.com/palomachain/kits)
