### ISSUE TITLE
Fix decimal conversion bug in all bots

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1401]
The bug that was found here: https://github.com/VolumeFi/paloma/issues/1393 needs to be fixed in all other contracts as well. 

https://github.com/VolumeFi/curve-leverage-lending-bot/blob/main/curve-leverage.js#L545
https://github.com/VolumeFi/llamalend-leverage-lending-bot-/blob/main/llama-leverage.js#L545
https://github.com/VolumeFi/curve-healthy-juicebot/blob/main/curve-leverage.js#L585

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/curve-healthy-juicebot/pull/1
https://github.com/VolumeFi/llamalend-leverage-lending-bot-/pull/1
https://github.com/VolumeFi/curve-leverage-lending-bot/pull/85

all code updated.. server updated.. services restarted.

**Comment by verabehr** [comment]
This regressed https://volume-x3.sentry.io/issues/4705816501/?notification_uuid=29f86afe-fd8c-4734-ad7a-77a8c58f09be&project=4506192492232704&referrer=regression_activity-email
