### ISSUE TITLE
Additional bot monitor alerts

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1402]
We're missing monitors and alerts for the following two bot services, please create. 

curve-healthy-juicebot
curve-leverage-lending-bot
llamalend-leverage-lending-bot-

**Comment by rootedbox** [comment]
https://check.bots.palomachain.com/limit-order/
https://check.bots.palomachain.com/curve_healthy/
https://check.bots.palomachain.com/curve_leverage/

setup and connected to uptime servers
