### ISSUE TITLE
Request: smart contracts for trading 

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#1405]
Tickets:

- [x] Ticket 1: https://www.notion.so/volumefi/EPIC-03-22-24-Simple-Trading-Bot-Smart-Contracts-032a84bd635f403589d320c33bace8f5?pvs=4#a541c1e9a5724f00ae6b9cd55f9e569a
- [x] Ticket 2: https://www.notion.so/volumefi/EPIC-03-22-24-Simple-Trading-Bot-Smart-Contracts-032a84bd635f403589d320c33bace8f5?pvs=4#cd3dc4cf1f9a4653b3aed1c8db6149b6
- [x] Ticket 3: https://www.notion.so/volumefi/EPIC-03-22-24-Simple-Trading-Bot-Smart-Contracts-032a84bd635f403589d320c33bace8f5?pvs=4#7c06501629d84136b4962222f090f7fb
- [x] Ticket 4: https://www.notion.so/volumefi/EPIC-03-22-24-Simple-Trading-Bot-Smart-Contracts-032a84bd635f403589d320c33bace8f5?pvs=4#66313253c0314b89aa9d93471c890849

All details and requirements:
https://www.notion.so/volumefi/EPIC-03-22-24-Simple-Trading-Bot-Smart-Contracts-032a84bd635f403589d320c33bace8f5

**Comment by fieldtheory123** [comment]
EPIC updated

**Comment by taariq** [comment]
Nothing to be done here. Closing.
