### ISSUE TITLE
User Request: Please show link to the Leverage Bot address in the Mybots page.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1407]
As a user, I want to see an explorer link to my Leverage Bot contract address so that I am able to monitor the leverage bot and see it on Etherscan

**Acceptance Criteria**
1. Create link to Leverage Bot address on Etherescan
2. Place the link under **Status** as (Address) with the last 4digits of the address:
3. Use the Tokentx link for the URL to open into a new tab. 
4. Example: https://etherscan.io/address/0x2a9b16e78375c3b303ab56fbe736be6ec3b3e016#tokentxns 

https://www.figma.com/file/6DYR6QFkucGd1bsOILr7V0/Paloma-Bot?type=design&node-id=2282-548787&mode=design&t=1uQbNhcCzzAXJmjh-4

**Comment by verabehr** [comment]
I don't see the link to my bot contract here

![Image](https://github.com/VolumeFi/paloma/assets/19958639/846ec79b-46a4-4e9e-91ed-6d4cd1d07e39)
