### ISSUE TITLE
BUG: Curve Healthy Leverage Bot on Home page shows total Volume $711 with 1 bot

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1408]
https://www.curvebot.fi/ shows **Total Volume: $711 and Total Bots: 1** which is wrong. since there are multiple bots created.

New Bot! - Bot Name: healthy, Token Input: wbtc, Amount Input: 4234.35, Token Output: crvusd, Amount Output: 24917.42, Chain Name: ETH

![Image](https://github.com/VolumeFi/paloma/assets/701864/31dce6cd-3a74-45ef-8421-35d15dcb39b4)

**Comment by rootedbox** [comment]
fixed when fixing other healthy bot issues
