### ISSUE TITLE
birdlady is getting jailed repeatedly due to not attesting message

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1409]
Birdlady was jailed twice on March 20 due to not attesting a message. The first one was an arbitrum message, the second wasn't checked. Jail reason looks like the one below

```{"reason":"No evidence supplied for contentious message 231111"}```

**Comment by byte-bandit** [comment]
Palomad logs: https://gist.github.com/byte-bandit/2715ed0de0ae9231f1757c946ea9fde7

Pigeon logs: https://gist.github.com/byte-bandit/b3616e36d025e341312136a19938bae4

**Comment by byte-bandit** [comment]
Looks like we're getting jailed for a message that never went into attestation phase. 

With the growing complexity of the consensus queue & gravity stuff on top, I really want to add something like a FSM that clearly define a message state. I might look into adding this in the future.

**Comment by verabehr** [comment]
Thanks @byte-bandit that makes sense. Closing this ticket as completed then for now.
