### ISSUE TITLE
Update API for palomabot.ai

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#141]
Update API to get this data from `momentum_cache`, so teh FE cna read it

SELECT value FROM daily_high_returns
WHERE dex=%s
  AND lag_return=%s
  AND daily_volume=%S

**Comment by rootedbox** [comment]
I need to know where this server is

**Comment by rootedbox** [comment]
code is here https://github.com/VolumeFi/momentum_trades_api and it's running on Lorentz box listed in the epic. that being said there is no daily_high_returns table that I can find on that DB

**Comment by verabehr** [comment]
@rootedbox my bad, the table is here rootedbox@nest-service.palomachain.com:~/app/trading-bots/momentum_cache.db

**Comment by verabehr** [comment]
missing item `decimals` value
