### ISSUE TITLE
DEVOPS: Add Mixpanel to palomabot.ai and curvebot.fi

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1410]
Add Mixpanel back to https://github.com/volumefi/palomabot and https://github.com/VolumeFi/curvefi-bot. 

The update to curvefi-bot should be done via updating the fork and merging. Details here or ask Jamie for help https://www.notion.so/volumefi/Making-updates-to-Palomabot-and-Curvebot-00705e89669641ecac11d7b9888ec8e0?pvs=4

**Comment by rootedbox** [comment]
Added Mixpanel object.. example code and Mixpanel key to Vercel
