### ISSUE TITLE
BUG: Unable to view mybots page: Quicknode: 429 (Too Many Requests)

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1411]
Unable to view mybots page: Quicknode: 429 (Too Many Requests)

Finally able to get to page after hard refresh. 

How do we not overload Quicknode with requests for the mybots page?

**Comment by jamie088** [comment]
@taariq May I know about wallet address happened this issue?

**Comment by taariq** [comment]
> @taariq May I know about wallet address happened this issue?

`0xb8c9f1fba80327dab67f26f0d8cd2c829af2404f`

**Comment by verabehr** [comment]
blocked by https://github.com/VolumeFi/paloma/issues/1411)

**Comment by verabehr** [comment]
@jamie088 This should be unblocked now, please test again when you have a moment https://github.com/VolumeFi/paloma/issues/1415

**Comment by jamie088** [comment]
@rootedbox `health` value was not found in the current API results. Will this be reflected from the next bots?

**Comment by verabehr** [comment]
@jamie088 it is there now, will you please check again?

**Comment by jamie088** [comment]
@rootedbox I can only see `health` value in `Juice` bots, not in `Healthy, Lending, and Leverage` bots.

**Comment by verabehr** [comment]
@jamie088 I believe this is good now
