### ISSUE TITLE
tooltip for TVL

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1420]
Add a tooltip for the TVL number on the mybots account. 

```TVL is the current value of the deposited amount and if applicable the total leverage amount borrowed is added.```

Figma: https://www.figma.com/file/6DYR6QFkucGd1bsOILr7V0/Paloma-Bot?type=design&node-id=2359-709740&mode=design&t=0oEeE1HIeMu3JXIM-4

**Comment by jamie088** [comment]
@verabehr I am not sure where to add the tooltip.

**Comment by verabehr** [comment]
@joycehermosilla will you please add this to Figma?

**Comment by joycehermosilla** [comment]
@verabehr https://www.figma.com/file/6DYR6QFkucGd1bsOILr7V0/Paloma-Bot?type=design&node-id=2359-709740&mode=design&t=0oEeE1HIeMu3JXIM-4

**Comment by jamie088** [comment]
@verabehr I mean this tooltip text is for only Leverage bot types. But our `Total TVL` is the total of all the bots, not only Leverage bots. Anyway, add a tooltip next to the Total TVL value?

**Comment by verabehr** [comment]
Yes, good point, I adjusted the text a bit to make it more generic. But yes, it has bo be next to the Total TVL, it doesn't make sense otherwise @jamie088
