### ISSUE TITLE
BUG: Silo Token not showing up in the Arbitrum Uniswap v3 bot

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1431]
Tenzent, [3/28/24 11:33 AM]
Cannot find the SILO token in there

Tenzent, [3/28/24 11:33 AM]
https://www.coingecko.com/en/coins/silo-finance

![Image](https://github.com/VolumeFi/paloma/assets/701864/c36311aa-ff1b-406a-9b3d-bceb31a8a738)

**Comment by jamie088** [comment]
@rootedbox I can't find the Silo finance token in the palomanest api result.
https://nest-service.palomachain.com/tokens/uniswap-listed

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/paloma-nest-service/pull/86
