### ISSUE TITLE
BUG: No jobs are being relayed / same message ID was put into message queue twice/multiple times (arbitrum)

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1432]
Problem: 
1. Successful SLC happened after I tested Silo
2. Validator set all jailed after William attempts to SLC a few minutes later.

From @byte-bandit 
> So, looks like the SLCs were not relayed becaues of valset mismatch. That's expected, we need a valset update to go through before we send the SLCs. So those messages simply timed out, and because the fix is not yet deployed, everyone is getting jailed.

> Trying to find the valset update message that should be linked to 490649
I found the valset upate: 490648

> It failed with execution reverted: Invalid Valset ID

> That means that the valset was actually deployed (likely by an earlier message), but Pigeons again failed to attest to that. We've seen this in the past a few times already, which is why we added this attestation enforcement. 

From @verabehr 
> ok, this is weird, this is this message (the update valset). But it is actually visible on Compass https://arbiscan.io/tx/0xe6fa94ac5931fe427fc602f55cfd43b71f0f08443f29e4c0c69d3fcee7a85b8a#eventlog

From @byte-bandit 
> I also cannot find another message that would have relayed this valset ID
Sadly we do not send our internal message ID to compass when updating the valset, so there's no hard link for me to follow.
Okay, we had the message reassgined. Here's what I think happened:

> We had a valset update
A relayer picked it up and sent it (successfully), but did not report back to Paloma
Message got reassigned
New relayer attempts to send and receives the error forwards it to Paloma
Everyone attests the error

> I do not see the original relayer ever calling back to Paloma.
But we also know that some pigeons are VERY slow to call in.

From @byte-bandit 
> There is something else that's weird though.
The Valset Update message is put onto the queue twice. Same message ID (that shouldn't even be possible), and the assignee is different for both. So maybe we even had two messages with the same ID that two relayers tried to forward at the same time.
Three seconds apart

<img width="1512" alt="image" src="https://github.com/VolumeFi/paloma/assets/19958639/cdf90609-5007-4712-bb20-bef2e03f5a45">

> Mega weird. This log is only emitted after a new ID has been generated. I do not see how this could be in the logs twice. 

> Unless, the first message was in a block that got rejected, and the whole thing happend a second time later for a block that was included.

**Comment by verabehr** [comment]
Looks like here this was actually put into the queue several times. This is an update valset message
https://gist.github.com/verabehr/4434e16a19fb8b92d68faea66f303df7

**Comment by verabehr** [comment]
Logs from another attempt - note that the queue was observed for the whole time and there is no additional error data from the queue. 

https://gist.github.com/verabehr/62a1101ee56959f3d96a61eb703227d9
https://gist.github.com/verabehr/68e76b8b671ec9fff1bdd89f2663bc25

**Comment by verabehr** [comment]
Note that this also happens on eth-main. Other chains weren't tested

**Comment by verabehr** [comment]
We had 2 relayed messages on gnosis ([valset](https://gnosisscan.io/tx/0x9c95cd3c9ee556c269a0d3c908d5a806ae15bfc51c05a0be7cc32508de1a46ff) and [SLC](https://gnosisscan.io/tx/0x38a75805c3d0e9d6ec792e6caf9499ca7943e318ddc205c58db2c9323f035bea)) 

This appears went through after over 200? attempts from a bot backend script. The attempts are captured as `Execute Contract` transactions from this wallet https://paloma.explorers.guru/account/paloma1v6eq9al4ftd3ph4fvc8wt3mw0dsxt3scvjzswm

**Comment by verabehr** [comment]
@byte-bandit Here are the results from another test on Gnosis. 

1. Started offramp eure-bot ( [offramp-eure-bot-script](https://github.com/VolumeFi/offramp-eure-bot-script) [offramp-eure-bot-cw](https://github.com/VolumeFi/offramp-eure-bot-cw) 
[vyper](https://github.com/VolumeFi/offramp-eure-bot) 
2. I observed 4 messages in the queue
     i. 509118: valset update   - https://gist.github.com/verabehr/12d4d01d8d3618dc435c0b1a703bf495
    ii. 509119 SLC - https://gist.github.com/verabehr/08321605530d6f091f6e36e3bcbab454
    iii. 509120 valset - https://gist.github.com/verabehr/acde62a23d73c5a3f12bb6563c432483
    iv. 509121 SLC - https://gist.github.com/verabehr/00766afeebfcf2d418507f4948a60b6a
3. Some actually were relayed but the messages were still put into the queue several times. 
4. Logs are from the LCD server and are in UTC
5. I see 2 contract execution tx on the wallet https://paloma.explorers.guru/account/paloma1v6eq9al4ftd3ph4fvc8wt3mw0dsxt3scvjzswm - screenshot times are in ET
![Image](https://github.com/VolumeFi/paloma/assets/19958639/6c41d9b3-2961-4013-9f73-139cdb855c6e)

**Logs from message queue**
Error/access data https://gist.github.com/verabehr/40d8152aae0e44dbfafe418ab92901d8
Full log: https://gist.github.com/verabehr/bf43f8740b5390d1475c3c3c739d345e

**Comment by taariq** [comment]
Closing as related to `messenger` issues post 0.47.1
