### ISSUE TITLE
LCD/FCD is stuck on one transaction

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1435]
https://volume-x3.sentry.io/issues/5127617191/?alert_rule_id=14786669&alert_timestamp=1711979683202&alert_type=email&environment=messenger&notification_uuid=eb015fc9-86ce-4ae7-8967-20c5eb12c59f&project=4506192492232704&referrer=alert_email

This does not appear to be a real error. Bot LCD and LCD2 can fetch other transactions. They can also fetch other "KeepAlive" transactions. This specific transaction actually failed because of a parsing issue see: https://paloma.explorers.guru/transaction/F5769A05E26F68759BFAB31AC56621C6376EA49D088F8C2061E8E4F3F5EE7340

### Done when
This error is either resolved, or the tx is skipped as right now, we're just racking up Sentry errors and are potentially blocking other FCD functionality

**Comment by rootedbox** [comment]
FCD got stuck.. moved block number and now it's processing more transactions. LCD server seems to be fine
