### ISSUE TITLE
BUG: LCD response Status 500 - errUnknownField "*types.MsgCreateJob" after Cosmos SDK 0.50.5 Upgrade

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1436]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

paloma_sdk.exceptions.LCDResponseError: Status 500 - errUnknownField "*types.MsgCreateJob": {TagNum: 1, WireType:"bytes"}: tx parse error [cosmos/cosmos-sdk@v0.50.5/x/auth/tx/decoder.go:44] with gas used: '6972'

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

Paloma v1.13.
Pigeion v1.11.0

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Paloma Message Relay with Cosmwasm Job

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Message relay still functions under Cosmwasm 1.5.2 as it did with 1.3.0

**Comment by taariq** [comment]
@webelf101 @wc117 it appears we may have to migrate our contracts will you confirm with details here: https://github.com/CosmWasm/cosmwasm/blob/v1.5.2/MIGRATING.md

**Comment by taariq** [comment]
@byte-bandit from @wc117 
> No, it is earlier step than CW. The failed transaction was to create a job. So I think Paloma protocol changed and we have to change some part to create a job. I don't know the details so @ByteBandit only can let me know how to change it.

**Comment by byte-bandit** [comment]
This looks like it's caused by a change in message definition.

Paloma `v1.13.0` removed some fields that had been deprecated for about half a year now: https://github.com/palomachain/paloma/compare/v1.12.2...v1.13.0#diff-e70526f754289da7f9ba89f1c44add9c03d5bb6e3fedcfa7e6b0ec74cfdc7d1b

I assume the contract sending this transaction is still using this dropped `creator` field.

**Comment by taariq** [comment]
@wc117 reassigned to you.

**Comment by verabehr** [comment]
@byte-bandit - from @wc117 

What should I change to work with this update?

![Image](https://github.com/VolumeFi/paloma/assets/19958639/f170134a-3d75-4bb5-b4d4-6a5ba10d469c)


I think we need to change paloma.py library and CW too.
