### ISSUE TITLE
Update stuck alert for the snapshot server

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1449]
Update the alert implemented here https://github.com/VolumeFi/paloma/issues/1395 for the snapshot server, so we don't get an alert every time it is scheduled to go down. 

Done when: 

- [ ] snapshot server has the stuck alert 
- [ ] we don't get an alert when the server is scheduled to stop to build the snapshot

**Comment by rootedbox** [comment]
updated code and put on server.. waiting on snapshot server to catch up on blocks before turning everything on
