### ISSUE TITLE
EPIC: Curve Exponential Leverage Bot

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1453]
Curve Exponential Leverage Bot: 

We will create a new Curve leverage bot that will just continously add new leverage as price goes up. Like a limit order, but if price falls it won't add to leverage. 

NOTE: The bot will still allow for automatic repayments and stop losses on health and on dollar amount.

**Comment by fieldtheory123** [comment]
https://www.notion.so/volumefi/EPIC-04-12-24-Curve-Exponential-Leverage-Bot-b301931963344de286beeddc4addc898

**Comment by taariq** [comment]
Closed as finished.
