### ISSUE TITLE
DEVOPS: instructions for vitwit to do the migration testing

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1461]
@byte-bandit Let's assign @vishal-kanna instructions on the following:
1. Download Paloma Snapshots from Volume and Polkachu here: https://polkachu.com/tendermint_snapshots/paloma
> Grab snapshot from height before upgrade, sync to upgrade height with 1.13.0 stop at upgrade height, modify db to be a single validator via https://docs.cosmos.network/main/build/building-apps/app-testnet, see if the network continues

3. Setup Application Testing Network with 1 validator
4. Attempt upgrade proposal from 1.13.0 to 1.13.1
5. If chain stops at same point, lets look into using iavl tool to inspect the db to find the state thats different

**Comment by byte-bandit** [comment]
see https://github.com/palomachain/paloma/issues/1124
