### ISSUE TITLE
As a user I want to always be able to withdraw my funds from my bot even if palomachain is down

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1472]
@wc117 will you please provide the feature proposal that you have to address this issue? We have no documentation on what/how.

**Comment by wc117** [comment]
If a user have TWAP option, the funds are remaining in the factory contract but until TWAP processed, he can't access the funds. The requirement should be
1. Users must be able to withdraw their pending TWAP funds without Paloma feature.
2. The withdrawal must emit events to manage it for backend.
3. TWAP after withdrawal should be failed.
4. This must not affect the other users and funds.
@verabehr @taariq
