### ISSUE TITLE
Allow admins to withdraw from price prediction vyper contract

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1474]
As Paloma admin, I want to be able to withdraw all unused/available funds from the price prediction contract without using compass.

**Comment by verabehr** [comment]
by the admin - cc @taariq

**Comment by fullstack412** [comment]
@verabehr @taariq and please let me know the admin address please for deploying

**Comment by fullstack412** [comment]
done. please check @verabehr 
https://github.com/VolumeFi/juice-bot-eth-predictor-vyper/commit/23e3e2b560e24c4e758223a7a60373439f1a474b
https://github.com/VolumeFi/interest-rate-prediction-bot-vyper/commit/ed548c8a318b7a5fc02273000d3760d23a6f3647
