### ISSUE TITLE
[CI] Add CodeQL to CI

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#1476]
https://github.com/cosmos/cosmos-sdk/blob/main/.github/workflows/codeql-analysis.yml

**Comment by taariq** [comment]
@byte-bandit how much effort required here?

**Comment by byte-bandit** [comment]
@taariq Not a lot from my initial judgement. Maybe 1-2 hours if that. Just keeping it in TODO For this week if I get around to it.

**Comment by taariq** [comment]
@byte-bandit let's give to @maharifu to get him started?

**Comment by byte-bandit** [comment]
@taariq Absolutely.
