### ISSUE TITLE
AAVE Interest Rate Predictor Vyper Contract

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#1478]
https://www.notion.so/volumefi/EPIC-04-19-24-AAVE-Interest-Rate-Prediction-Competition-bda6a0d2eec14c428ebb398ebc264aad?pvs=4#0ab75b05da404405a6d965931ee3b70d

**Comment by fullstack412** [comment]
@verabehr done
https://arbiscan.io/address/0x1FAB1A81EA05e981c16Ab938B761Fb7Fe22CEfeb
https://etherscan.io/address/0x1FAB1A81EA05e981c16Ab938B761Fb7Fe22CEfeb
