### ISSUE TITLE
AAVE Interest Rate Predictor CW Contract

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#1479]
https://www.notion.so/volumefi/EPIC-04-19-24-AAVE-Interest-Rate-Prediction-Competition-bda6a0d2eec14c428ebb398ebc264aad?pvs=4#465a856e0d47408e8386a443a3bafd5a

**Comment by fullstack412** [comment]
@verabehr done. I deployed the CW contract last friday.
