### ISSUE TITLE
bug: TWAP doesn't work on Curvebot Ethereum 

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#1497]
Deposit https://etherscan.io/tx/0xd59c5bec4e2632700575e04343c1387ed475e3dafef469be0812f594cf9d3c88

TWAP didn't happen following the deposit.

**Comment by verabehr** [comment]
I think your tx are here https://etherscan.io/tx/0xf71d97e4478819df5ca674f39a21abac8f3dae1ff08df87cfcada3b112089725#eventlog
https://etherscan.io/tx/0xd59c5bec4e2632700575e04343c1387ed475e3dafef469be0812f594cf9d3c88#eventlog

@fieldtheory123 

The tx are expected to be delayed until all pigeons updated to the new versions

**Comment by taariq** [comment]
Okay @verabehr @fieldtheory123 closing so we will wait tomorrow and test again.
