### ISSUE TITLE
Updates to valset updates (pigeon)

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#15]
# Background

_Describe the problem that we are trying to solve with this feature._
_If a path to a solution is known, feel free to write it down, but have an open mind_

As a validator, I want the pigeon relayer to read the last valset message id from the deployed chain CompassEVM conract instead of fetching event log. 

See the EPIC https://www.notion.so/volumefi/EPIC-03-10-Upgrade-Pigeon-3ebe803a472545a398330b0d28a092bc for full description 

# Done when

- [ ] Pigeon gets the last valset-message ID from a view function of a compass-EVM instead of filtering event log.
- [ ] Upgrade https://github.com/palomachain/pigeon/blob/32c32ffe3008b74a37b8e562c5a9aedd420ba847/chain/evm/compass.go#L320 to use the event emitted.

**Comment by taariq** [comment]
@webelf101 is this the ticket for @mszuyev? It's not clear after seeing #27
