### ISSUE TITLE
[BUG] Messages are still put into the queue twice

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1500]
EVM relay messages are still put into the consensus queue twice. I've seen this in the logs several times, here is an example from querying the queue. 

Steps to reproduce: 
Trigger a logic call

![Image](https://github.com/VolumeFi/paloma/assets/19958639/ed462c18-6373-4054-a323-8a0b798ac27d)

related to https://github.com/VolumeFi/paloma/issues/1432

**Comment by maharifu** [comment]
From the mainnet logs, it seems to only get triggered when scheduling jobs, possibly by a bot. The messages are slightly different, with different deadline field, so the job execution is being called multiple times with the same payload.

I couldn't reproduce it locally by triggering job executions, though. The only way to achieve a similar result was to change the codebase to call `ExecuteJob` concurrently, using the same context. The context gets rewritten between calls, so we get the same ID applied more than once.

Could a smart contract be doing be doing multiple calls within the same context? How can I apply one locally to test this?

**Comment by byte-bandit** [comment]
@maharifu I'm convinced it's a smart contract who's issuing these calls, yes. It's possible that the event handler is getting fired more than once. Depending on how that is handled (I imagine it's like just a `for event in all_events: handle(ctx)`), it could mean executing the function twice with the same context, yes.

@verabehr We had a different ticket the last time I looked into this, where we also linked the contracts responsible for sending those messages. Can you find it?

**Comment by verabehr** [comment]
@byte-bandit (@maharifu) I think you're referring to this one here https://github.com/VolumeFi/paloma/issues/1432.

**Comment by taariq** [comment]
Closing as a bug. This will require a feature to handle over-eager CW submits.
