### ISSUE TITLE
Degen Leverage Bot initialization Fails to hit Compass-EVM on ETH

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1504]
I tried to run a transaction for Degen Leverage bot initialization but it didn't come to Ethereum.
Tx hash on Paloma is [3F2D94D03B868372A0405B14A60986915F9F0497D29A27EEFB4351FC0092A311](https://paloma.explorers.guru/transaction/3F2D94D03B868372A0405B14A60986915F9F0497D29A27EEFB4351FC0092A311)

Compass-EVM on ETH: https://etherscan.io/address/0x652bf77d9f1bda15b86894a185e8c22d9c722eb4

**Comment by byte-bandit** [comment]
This is a consequence of https://github.com/VolumeFi/paloma/issues/1501

Closing in favour of #1501
