### ISSUE TITLE
[TWAP Bot] Deploy Uniswap v3 TWAP bot for ETH, ARB, OP, BASE

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1510]
We want to bring back the Uniswap V3 TWAP bot for the following chains:

- [x] 1. ETH
- [x] 2. ARB
- [x] 3. OP
- [x] 4. BASE

**Comment by verabehr** [comment]
@jamie088 Base tokens are here https://nest-service.palomachain.com/tokens/base
