### ISSUE TITLE
Backend script for short funding bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1511]
Requirements: 
https://www.notion.so/volumefi/EPIC-03-15-24-Short-Funding-Rate-Bot-987993502ca04cd698e7b09a8a36cd4a?pvs=4#092400e3514643ebae12608e989d4ebf

Vyper contract: https://github.com/VolumeFi/short-funding-bot-vyper
CW contract: https://github.com/VolumeFi/short-funding-bot-cw

**Comment by verabehr** [comment]
got responses from GMX. This requires some additional smart contract work

**Comment by fieldtheory123** [comment]
Per new feedback from GMX, a contract is not needed. Added requirements for querying https://www.notion.so/volumefi/Steps-b23c3583e6e349e681cdb65293ab84c7

**Comment by taariq** [comment]
From @rootedbox 
i'm currently having to take apart https://github.com/gmx-io/gmx-interface/tree/master to get everything i need.. their docs on their site don't cover everything and they don't have a node.js library and their python library is minimal

**Comment by verabehr** [comment]
WIP here https://github.com/VolumeFi/short-funding-rate-bot

**Comment by taariq** [comment]
Closing as won't ship
