### ISSUE TITLE
[BUG] OP-Main: snapshot not found in store

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1515]
Attempting to relay a message on op main gives this error. Note this error is not found on eth-main. 

Potentially related. When op-main compass was deployed there was no additional valset update call. I'm not sure if that's relevant though since every SLC also has a valset ID associated with it. https://optimistic.etherscan.io/address/0x56Bff1a8D2af62584D7Ebf123452b765392e20E3

paloma v1.13.4, pigeon v1.11.1

```
{"level":"error","module":"server",
"module":"x/paloma",
"msg.args.chain-reference-id":"op-main",
"msg.args.queue-type":"evm/op-main/evm-turnstone-message","msg.args.message-type":"*types.Message_SubmitLogicCall",
"msg.args.message-id":"11490",
"msg.args.message-nonce":"0x0000000000002ce2",
"msg.args.message-error-data":"0x",
"msg.args.message-public-access-data":"0x",
"component":"pigeon-status-update",
"status":"original error: rpc error: code = InvalidArgument desc = item (*types.Snapshot) not found in store: snapshot-id: invalid request\nenriched fields:\nmessage id[uint64] = 0x2ce2\nmessage type[*types.Message_SubmitLogicCall] = &types.Message_SubmitLogicCall{SubmitLogicCall:(*types.SubmitLogicCall)(0xc000563580)}\n",
"sender":"palomavaloper1kludne80z0tcq9t7j9fqa630fechsjhxc324tt",
"time":"2024-04-29T14:00:51Z",
"message":"original error: rpc error: code = InvalidArgument desc = item (*types.Snapshot) not found in store: snapshot-id: invalid request\nenriched fields:\nmessage id[uint64] = 0x2ce2\nmessage type[*types.Message_SubmitLogicCall] = &types.Message_SubmitLogicCall{SubmitLogicCall:(*types.SubmitLogicCall)(0xc000563580)}\n"}
```

**Comment by verabehr** [comment]
per byte-bandit: 
snapshot not found in store is a bug we've had for a long time. Basically, when a new chain is added, Paloma doesn't keep track of that deployed valset. Until a new valset is triggered and deployed, relays to that chain won't work.
But it needs to be an actual new valset version with a higher ID, otherwise it won't be relayed.

**Comment by byte-bandit** [comment]
This has been fixed a while ago.
