### ISSUE TITLE
Setup `concord` service ingress

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#1516]
## Current status

There is a binary service running on the following machine: https://cloud.linode.com/linodes/57952894/configurations, accepting HTTP traffic on port :8080

## Acceptance criteria

- [x] Create a new domain record `concord.palomachain.com` that's setup against this machine
- [x] Setup SSL on the machine and automatically upgrade all `80` traffic to `443`. Self signed cert should be enough.
- [x] Setup a reserve proxy on the machine (NGINX should be enough) that redirects `443` to `8080`
- [x] Make sure that content type `application/json` is accepted for ingress & egress (default config should be fine usually)
- [x] Ensure you can do a `curl https://concord.palomachain.com/messages` and get a 200 response

**Comment by rootedbox** [comment]
up and running will dm @byte-bandit new root password.
