### ISSUE TITLE
Normalise valset and consensus before submitting to compass

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1519]
Compass is checking the number of shares among signers of a message against 2/3 of `2^32`, because it expects all requests to have been normalised against this number.

Pigeon needs to normalise the shares in signatures against that number while transforming a valset for Compass in order to guarantee both sides implement the approach. 

## Acceptance criteria

- [ ] During valset data transformation for compass, Pigeon performs a normalisation operation, so that the total number of shares across an entire valset would represent `2^32` instead of the true value
- [ ] The total number of shares among signatures of a messages (a subset of the valset) is also normalised in this way
- [ ] Majority vote can therefore be derived as `total shares of signatures on message > 0.66 * 2^32`

## Estimate
`1d`

---

## Original bug report

We still don't have a valset update on 
bnb: https://bscscan.com/address/0x1876e5fA704039dfF7da0C66d516AFAcBe23c59B
matic: https://polygonscan.com/address/0x10812c485BF5cE3c5296a9f603b53344a15cC0cD
op: https://optimistic.etherscan.io/address/0x56Bff1a8D2af62584D7Ebf123452b765392e20E3
base: https://basescan.org/address/0xB54E2c37645fd42F09C93B50B29648a9Cc4F6065
blast: https://blastscan.io/address/0xa039cDb2eF436D754d507759A3f1afFcb9b28e36
On OP, this is blocking to instantiate the Uniswap v3 bot as SLCs require at least one valset update published on Compass. 

I've observed this error on bnb, matic and op `657865637574696f6e2072657665727465643a20496e73756666696369656e7420506f776572`: 
```
execution reverted: Insufficient Power
```

I'm not sure if we have the same error on blast and base, since the last errors that I get are still the error fixed by pigeon v1.11.2 and I can't easily trigger new valsets and ensure that an upgraded pigeon is selected. 

Where is this error coming from? Is this a bug or a feature? What is needed to get past this?

**Comment by taariq** [comment]
@byte-bandit @webelf101 this is blocking our next Curve TWAPs bots on Base, Matic, and BNB. We need functionality here

**Comment by byte-bandit** [comment]
The error is coming from compass and basically indicates that the combined shares of all signatures on the message are not enough to reach the "power threshold", which is a constant defined as follows:

`POWER_THRESHOLD: constant(uint256) = 2_863_311_530 # 2/3 of 2^32, Validator powers will be normalized to sum to 2 ^ 32 in every valset update.`

I'm unsure why this constant value is being used as an absolute value to check for 2/3's majority, as obviously that depends on the total amount of shares among validators and is variable. 

I do remember that Paloma also used to use this variable though, a long time ago. Tyler found and changed it. So it's possible that there's now a mismatch here, with compass checking against this constant value and Paloma using the real amount of total shares to verify that 2/3s majority is met.

I don't know the story behind this constant, I imagine it was done this way so that compass wouldn't have to be updated with the total number of shares as well? Maybe @webelf101 can share some more light on this.

**Comment by byte-bandit** [comment]
Here is the commit where Tyler removed the constant used in Pigeon: https://github.com/palomachain/pigeon/commit/4e9dc09d406e6aaed05c88d666fbb4f4148bcbcb

But at that time, it already wasn't used. I have no idea if it ever was used at some point. I went back the history a little longer, but couldn't find anything. So I'm not sure this was every really done by Pigeon.

My current theory is that on `messenger`, the total amount of shares across validators just happened to exceed this magic number, where the number of shares on `tumbler` does not. Maybe we lost some validators with higher stake, or some people decided to unstake, idk.

**Comment by webelf101** [comment]
This came from the original Gravity bridge model. However, we need a model to check if the sum of the signer's power is greater than 2 / 3 of the total sum of the validator's power. We assumed that the total sum of the validator's power is 2 ^ 32 and maybe the original code should have such value. I think you are already aware of it though. I'd like to avoid adding more data in consensus just like a total sum of power or something else. How do we calculate the powers of validators right now? @byte-bandit @taariq

**Comment by byte-bandit** [comment]
> This came from the original Gravity bridge model. However, we need a model to check if the sum of the signer's power is greater than 2 / 3 of the total sum of the validator's power. We assumed that the total sum of the validator's power is 2 ^ 32 and maybe the original code should have such value. I think you are already aware of it though. I'd like to avoid adding more data in consensus just like a total sum of power or something else. How do we calculate the powers of validators right now? @byte-bandit @taariq

Pigeon takes the valset with the ID that's currently on compass and just calculates the total stake of all active validators. Then it adds up the stake of everyone who signed the message, and checks if that is above the total stake of all validators. So, it seems to be dynamic, there's no normalisation happening.

This has been this way for a really long time (like more than a year at this point), and I think on the old network we just had more stake on validators, which meant the total just was above this magic number.

The way I see it, we have two ways forward:

a) add more stake to validators so the total is above that number
b) create a new version of Pigeon that performs this normalisation before sending the data

I don't believe I will have capacity to engineer, test & deploy option b. We should probably create a ticket for that regardless so we can come back to it and clean it up. But for now, increasing the stake seems to be best option to get quick results?

**Comment by taariq** [comment]
Thank you @byte-bandit @webelf101 

1. Let's create the ticket for backlog to upgrade this. Good ticket for Luis to work on?
2. Let's increase the stake. How much is required and which validators need this stake?

**Comment by webelf101** [comment]
I have a question. Why do we have this issue on OP only? @byte-bandit

**Comment by byte-bandit** [comment]
We have it on

bnb: https://bscscan.com/address/0x1876e5fA704039dfF7da0C66d516AFAcBe23c59B
matic: https://polygonscan.com/address/0x10812c485BF5cE3c5296a9f603b53344a15cC0cD
op: https://optimistic.etherscan.io/address/0x56Bff1a8D2af62584D7Ebf123452b765392e20E3
base: https://optimistic.etherscan.io/address/0x56Bff1a8D2af62584D7Ebf123452b765392e20E3
blast: https://optimistic.etherscan.io/address/0x56Bff1a8D2af62584D7Ebf123452b765392e20E3

**Comment by taariq** [comment]
@byte-bandit but why don't we have it on the other 3 chains?

**Comment by byte-bandit** [comment]
> @byte-bandit but why don't we have it on the other 3 chains?

I don't know whether we actually have consensus on all other 3, but we do know for sure we have it on eth.

So the most obvious answer would be: timing. Valset (and therefore total shares) can change over time, which means at some point we're above the magic number, and at times with less validators in the set, we might be below. It's just an elaborate guess for now though.

**Comment by verabehr** [comment]
@byte-bandit @webelf101 timing seems to be a factor here. I just checked all 5 chains and we have a valset on all of them now, so maybe this is no longer an issue

**Comment by byte-bandit** [comment]
It's still not the intended design, as compass still doesn't actually check for true majority vote. Just that total number of shares exceed a magic number.

Let's keep this open to address at a later stage, Pigeon should normalise the numbers before sending to compass.

**Comment by verabehr** [comment]
The valset that went through was the first valset on that chain after contract deployment and not associated with a logic call. So theoretically all valsets that were generated before would have failed. Note that arbitrum-main, eth-main, gnosis-main, did not have that issue. 

The original bug report was generated when **valset 125** was trying to get deployed. 

Deployed valsets: 
[bnb-main: 127 ](https://bscscan.com/tx/0xb8ba08cb951bb6cfca25c1fa50417cbb0e9d6bebba4635cc376f46d4a469ac5e#eventlog)
[op-main: 127](https://optimistic.etherscan.io/tx/0x21eb0a3860bfb4e0f0dd648fd784133932057090bf3c67b8eaa134463483de28#eventlog)
[base-main: 127](https://basescan.org/tx/0xeb599d3b842943274cfaf2bc7d5187dac9bce9c00f5c70b63620b57d95acbbe1#eventlog)
[blast-main: 127](https://blastscan.io/tx/0x53476a289861a46d7accb38898c444627af178a54afffa71fd9df08b7b407b5f#eventlog)

**[matic-main: 131](https://polygonscan.com/tx/0x84edc7c9d3adc61df09a8d452132960730f9b12258342c3c9e8b3f93f66c0f3f#eventlog)**, note that this valset update looks different on the blockscanner than the others. Unclear if that is an explorer issue or something different in the valset update

**Comment by byte-bandit** [comment]
We can close this, as Paloma actually performs the normalisation.
