### ISSUE TITLE
Security: Review the Paloma Messaging Security Model

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#152]
As a user, I want to know that I am able to use a whitelist registry on Paloma that will only permit messages from Smart Contracts I approve to send messages to my contracts that Paloma is the owner on EVM or on Solana.

Requirements:
1. Registry is in Cosmos
2. Registry is available in Cosmwasm
3. Registry is also verified on Compass.

See current epic: https://www.notion.so/volumefi/EPIC-04-28-23-Message-Security-Whitelists-for-Compass-EVM-execution-601616603769401495a5ce5cd728a6be

**Comment by taariq** [comment]
@measure-fi you have the ticket and the Notion. We'll review today.

**Comment by measure-fi** [comment]
Reviewed once, still need to review updates.

**Comment by taariq** [comment]
> Reviewed once, still need to review updates.

We will need a NEW review once I use the Allowance design pattern. I'll update.

**Comment by taariq** [comment]
Finished with Chase's feedback here: https://www.notion.so/volumefi/EPIC-04-28-23-Message-Security-Paloma-Whitelist-for-Message-Relay-601616603769401495a5ce5cd728a6be?pvs=4#011cb8c20978418999d299c60dff7424
