### ISSUE TITLE
Rename Juice bots to Squeeze bots

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1521]
Rename 
`Curve Wrapped Bitcoin (WBTC) Juice Bot` to `Curve Wrapped Bitcoin (WBTC) Squeeze Bot`
`Curve Ethereum (ETH) Juice Bot` to `Curve Ethereum (ETH) Squeeze Bot`

**Comment by verabehr** [comment]
@jamie088 will you close on this today please?

**Comment by jamie088** [comment]
@verabehr Yes, no problem. And just reminder: I think we'll also need to update the backend and smart contract repo names for Juice Bot to avoid confusion.

**Comment by jamie088** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/435. But it is blocked by API update of this ticket: https://github.com/VolumeFi/paloma/issues/1565

**Comment by verabehr** [comment]
@jamie088 the API was updated, is this one unblocked now?

**Comment by jamie088** [comment]
@verabehr API has not been updated as discussed. I will add this to the #1565 ticket.
