### ISSUE TITLE
[Security] Enhance Paloma and Compass relay security to add signature checks on relays

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1524]
As a Paloma developer, I want Paloma to increase my relay security by instead of sending <address+payload> in the relay, send <address+signature+payload> so that all receiving contracts on target chains can make sure that the address matches what was expected and that the signature also matches the address and the payload.  

**Acceptance Criteria** 
1. Update Paloma to send <address+signature+payload> instead of the current <address+payload> 
2. Update Compass to receive and evaluate <address+signature+payload> instead of the current <address+payload> 
3. Test to ensure this works as designed.

**Comment by webelf101** [comment]
We have signatures in SLC parameters in Consensus so I don't think this ticket is needed.
