### ISSUE TITLE
bug: Curve leverage lending bot can't start bot

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#1526]
Can't start the bot with a gas estimation error

<img width="646" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/0f2efeab-5eb7-46a5-b63a-ca6acc86049a">

**Comment by fieldtheory123** [comment]
`e Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: Blacklistable: account is blacklisted", method="estimateGas", transaction={"from":"0xD0e08D653C3ead747865c3674FFa93ecDefDd045","to":"0xDE3e88BA5B92236eD2682D34AE960168D3B96084","value":{"type":"BigNumber","hex":"0xd529ae9e860000"},"data":"0x707c96ae0000000000000000000000000000000000000000000000000000000000000180000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000000000000000000000000000a230e7d6683e4898000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000d3e576b5dcde3580420a5ef78f3639ba9cd1b967000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000002b70000000000000000000000000000000000000000000000000000000000001388000000000000000000000000000000000000000000000000000000000000015400000000000000000000000000000000000000000000000000000007bdea11b80000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000005426178799ee0a0181a89b4f57efddfab49941ec000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001e8480000000000000000000000000000000000000000000000000000244c685cb864f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000d4ab3adc53472","accessList":null}, error={"code":-32603,"message":"execution reverted: Blacklistable: account is blacklisted","data":{"originalError":{"code":3,"data":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000025426c61636b6c69737461626c653a206163636f756e7420697320626c61636b6c6973746564000000000000000000000000000000000000000000000000000000","message":"execution reverted: Blacklistable: account is blacklisted"}}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at Logger.makeError (_app-e7317575d23d4db1.js:1:203690)
    at Logger.throwError (_app-e7317575d23d4db1.js:1:203809)
    at checkError (_app-e7317575d23d4db1.js:1:283184)
    at Web3Provider.<anonymous> (_app-e7317575d23d4db1.js:1:293481)
    at Generator.throw (<anonymous>)
    at rejected (_app-e7317575d23d4db1.js:1:282225)`
    
   @jamie088

**Comment by fieldtheory123** [comment]
The the same error seen on Palomabot.ai too.

**Comment by fieldtheory123** [comment]
<img width="662" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/6d2dd232-a2d6-4c3d-8a72-4613e825de7e">

**Comment by fieldtheory123** [comment]
@rootedbox Bot started but not seen on mybot page
deposit: https://etherscan.io/tx/0x9a4e5c7ae79d96d23b06d6e8005bcd400c5fd31cf2509346d681afbe854f7dba

**Comment by jamie088** [comment]
@rootedbox I think you didn't update the Curve Degen leverage bot contract address in backend.
This is a new address: 0x532D78498BEA19051B6b55F53A9AB407a02F41C7
