### ISSUE TITLE
[Devops] Failed to load resource: the server responded with a status of 502 (Bad Gateway)

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1527]
https://www.curvebot.fi/curve-juice/WBTC/ does not load.

Error in event handler: Error: write after end
  at <URL>
  at y.write (<URL>)
  at i.d (<URL>)
  at a.emit (<URL>)
  at U (<URL>)
  at F (<URL>)
  at B.push (<URL>)
  at i._onMessage (<URL>)
  at <URL>
Error in event handler: Error: write after end
  at <URL>
  at y.write (<URL>)
  at i.d (<URL>)
  at a.emit (<URL>)
  at U (<URL>)
  at F (<URL>)
  at B.push (<URL>)
  at i._onMessage (<URL>)
  at <URL>
www.curvebot.fi/:1 Unchecked runtime.lastError: The message port closed before a response was received.
6916-b889c2b489a691b3.js:1 CURVE-JS IS CONNECTED TO NETWORK: Object
6916-b889c2b489a691b3.js:1 CURVE-JS IS CONNECTED TO NETWORK: Object
6916-b889c2b489a691b3.js:1 CURVE-JS IS CONNECTED TO NETWORK: Object
6916-b889c2b489a691b3.js:1 CURVE-JS IS CONNECTED TO NETWORK: Object
6916-b889c2b489a691b3.js:1 CURVE-JS IS CONNECTED TO NETWORK: Object
6916-b889c2b489a691b3.js:1 CURVE-JS IS CONNECTED TO NETWORK: Object
momentum.palomabot.ai/?dex=curve_ethereum&lag_return=6&daily_volume=0&vol_30=100000&market_cap=1000000&token=wbtc:1 
        
        
       Failed to load resource: the server responded with a status of 502 (Bad Gateway)
270-1a898e9a5098688d.js:1 error AxiosError
6916-b889c2b489a691b3.js:1 CURVE-JS IS CONNECTED TO NETWORK: Object

**Comment by rootedbox** [comment]
setup systemctl to restart service when it goes down for system issues.. i.e. reboot or system kill. it was already setup to auto restart if it failed.
