### ISSUE TITLE
Backend script for Aave price predictor bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1536]
This is very similar to the eth-price prediction bot, but users can bet on any token available Aave instead of just one token. 
@fullstack412 will you please add any additional requirements for the script?

**Deployed Contracts:**
Arbitrum:
0x1FAB1A81EA05e981c16Ab938B761Fb7Fe22CEfeb

Ethereum
0x1FAB1A81EA05e981c16Ab938B761Fb7Fe22CEfeb

**Repos**
[interest-rate-prediction-bot-vyper](https://github.com/VolumeFi/interest-rate-prediction-bot-vyper)
[interest-rate-prediction-bot-cw](https://github.com/VolumeFi/interest-rate-prediction-bot-cw)

### Done when 

- [ ] Backend script is done for aave price predictor bot 
- [ ] networks.json and .env files are set up on server
- [ ] contracts are initialized

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/price-prediction can be configured to do this.
