### ISSUE TITLE
Bitcoin price prediction bot - backend script

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1538]
This is the same as the eth-price prediction bot backend, but instead of ETH, we'll need to query the price for BTC

repo: https://github.com/VolumeFi/btc-price-prediction

BtcPricePrediction Eth https://etherscan.io/address/0x36B5236EfB6F266611D9D81F4CE52492D3Eae53f
BtcPricePrediction Arb https://arbiscan.io/address/0x36B5236EfB6F266611D9D81F4CE52492D3Eae53f

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/price-prediction can be configured to do this.
