### ISSUE TITLE
Update Curve Degen Leverage bot address

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1539]
Please update the Curve Degen leverage bot factory contract address in the backend.
This is a new address: 0x532D78498BEA19051B6b55F53A9AB407a02F41C7

We can't see the Zhibai's bot now. https://etherscan.io/tx/0x9a4e5c7ae79d96d23b06d6e8005bcd400c5fd31cf2509346d681afbe854f7dba

**Comment by rootedbox** [comment]
done and transaction in DB
