### ISSUE TITLE
bug: Curve leverage bot health factor not showing on mybot page

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#1540]
Deposit https://etherscan.io/tx/0x9a4e5c7ae79d96d23b06d6e8005bcd400c5fd31cf2509346d681afbe854f7dba

Mybot page 
<img width="920" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/88eb9207-1ef5-4f4f-b986-d719a8c2413f">

**Comment by verabehr** [comment]
The UI still shows the same. No health value
