### ISSUE TITLE
[Recovery]  Error: call revert exception; VM Exception while processing transaction: reverted with reason string "Multicall3: call failed"

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1543]
When user of bot https://etherscan.io/tx/0x4eef2c5f77844b4151507ca4ff20cc8fd919ed8d29d5f8c99112fd0e2cfcf757 attempts to stop bot, they get the error below:

Error: call revert exception; VM Exception while processing transaction: reverted with reason string "Multicall3: call failed"

> content: background > inpage: {"id":"21","jsonrpc":"2.0","result":null}
provider-bridge.js:1135  content: inpage > background: {"id":"22","target":"tally-provider-bridge","request":{"method":"eth_requestAccounts","params":["Palomabot","https://www.palomabot.ai/assets/Favicon.png"]}}
provider-bridge.js:1140  content: background > inpage: {"id":"22","jsonrpc":"2.0","result":["0x79c9a765d865f949c18335321436faafa865b2e6"]}
6382-13c0c9c1c87f533e.js:1 Error: call revert exception; VM Exception while processing transaction: reverted with reason string "Multicall3: call failed" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="aggregate((address,bytes)[])", data="0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000174d756c746963616c6c333a2063616c6c206661696c6564000000000000000000", errorArgs=["Multicall3: call failed"], errorName="Error", errorSignature="Error(string)", reason="Multicall3: call failed", code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.makeError (_app-7ded98dbc1d7779a.js:1:203690)
    at Logger.throwError (_app-7ded98dbc1d7779a.js:1:203809)
    at Interface.decodeFunctionResult (_app-7ded98dbc1d7779a.js:1:57357)
    at Contract.<anonymous> (_app-7ded98dbc1d7779a.js:1:97343)
    at Generator.next (<anonymous>)
    at fulfilled (_app-7ded98dbc1d7779a.js:1:92600)
6063-b17b2090feee2e24.js:1 TypeError: Cannot read properties of undefined (reading 'routes')
    at stopBot (6063-b17b2090feee2e24.js:1:12271)
    at async handleStopBot (mybots-423f22b67071614d.js:1:54444)

**Comment by wc117** [comment]
Where did this error come from? I don't think we use aggregate() function anywhere but I see the error comes from running aggregate() function. @rootedbox @taariq

**Comment by taariq** [comment]
@wc117 https://www.palomabot.ai/mybots/ using Rabby with the watch address `0x79c9a765d865f949c18335321436faafa865b2e6` Could @rootedbox  setup the wrong bot instead of Degen Leverage? I don't see `aggregate() ` in any of our code either. @jameslee6178 why are we using multicall?

**Comment by taariq** [comment]
@jamie088 use Rabby with the watch address 0x79c9a765d865f949c18335321436faafa865b2e6

**Comment by verabehr** [comment]
this is not a vyper issue, but an API/Backend issue. Record has the wrong bot type
