### ISSUE TITLE
[DEVOPS] Approaching Sentry Quota - Please fix

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1544]
We seem to be capturing lots of errors. Where are they coming from?

<html><head></head><body><p style="font-weight:400;font-size:16px;line-height:24px;margin:0 0 20px!important">Your organization <strong style="font-weight:bold">Volume</strong>
 has consumed 80% of its errors capacity for the current usage period. 
It’s important to keep in mind that, should you hit your quota, and 
consume your on-demand spend, any excess errors will be dropped until 
you roll over into the next period after May 20, 2024.</p>

   <h4 style="font-weight:700;font-size:18px;margin:20px 0">Your Current Usage</h4>
  
Error Capacity Used                    40,001           /           50,000 | On-Demand Spend Used                                       $0.00 / $50.00
-- | --
</body></html>

**Comment by rootedbox** [comment]
most of our errors were coming from the fcd.. which wasn't erroring it was just logging.. disabled as we really don't need sentry watching fcd code
