### ISSUE TITLE
Add Base chain tokens to the Uniswap token listed on paloma nest service api

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1546]
Please add the `Base` chain tokens to the uniswap token listed on the paloma nest service
Api url: https://nest-service.palomachain.com/tokens/uniswap-listed

Base chainId is 8453

**Comment by rootedbox** [comment]
@jamie088 @verabehr there will be a new endpoint called [https://nest-service.palomachain.com/tokens/base](https://nest-service.palomachain.com/tokens/base) when this is completed.

**Comment by rootedbox** [comment]
https://github.com/palomachain/paloma-nest-service/pull/88
