### ISSUE TITLE
API: Update @curvefi/api version to latest(2.58.5)

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1552]
We need to update `@curvefi/api` to the latest to completely resolve the multicall issue. (https://github.com/VolumeFi/paloma/issues/1543)

But we can't do it now due to `ethcall` npm package issue. (https://github.com/Destiner/ethcall/issues/254)
Vercel deployment failed.

**Comment by taariq** [comment]
@jamie088 this is updated and can be updated on our end: https://github.com/curvefi/curve-js/blob/master/package.json

**Comment by jamie088** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/438.
