### ISSUE TITLE
aave interest prediction bot UI

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1553]
interest rate predition on AAve (https://www.notion.so/volumefi/EPIC-04-19-24-AAVE-Interest-Rate-Prediction-Competition-bda6a0d2eec14c428ebb398ebc264aad?pvs=4#488fe889561f496d821d961a0139c4b2)

Similar to BTC and ETH price prediction, but 
* users also have to select the token instead of entering a price
* a price chart doesn't make sense. I think we best pull in the current interest rates from Aave.

**Comment by taariq** [comment]
@joycehermosilla is this done?
