### ISSUE TITLE
Backend service for Curve healthy Juice bot does not seem to work correctly.

### ISSUE THREAD

**Issue by wc117** [VolumeFi/paloma#1564]
https://etherscan.io/tx/0x694ef89a123a11b3ccf882a05184c177116676ca933f9a14095411dc3cb1ae8a
https://etherscan.io/tx/0xec5b9ecd84fb8e4ec69c4e805f3f32ef8562b92d03fc415df3a0cc7042a023da
I tried to test Curve healthy juice bot and created 2 bots.
I set the profit taking as 1% with 6x leverage so when the BTC price raises 0.2%, the repay should be triggered but it didn't yet.
And on my bot page, the health shows 0%. I don't think it is correct.
Furthermore, it shows the health shows 0% and health threshold is 3% so it should trigger repay but it does not.
Please fix these issues. Otherwise we can not use this Curve Healthy Juice bot.

**Comment by jamie088** [comment]
@rootedbox The backend api doesn't return the `health` value for the Curve Healthy bot. So users show 0% of bot health. Please add the `health` value to the API results for the Curve Healthy bot, just like Levearge and Juice(Squeeze) bots.

**Comment by rootedbox** [comment]
Multiple bots with same bug...
https://github.com/VolumeFi/curve-healthy-juicebot/pull/16
https://github.com/VolumeFi/llamalend-leverage-lending-bot-/pull/5
https://github.com/VolumeFi/curve-noob-leverage-lending-bot/pull/8

this seems to have resolved the issues.

**Comment by rootedbox** [comment]
May 14 21:09:08 bots-server start.sh[384164]: executeWithdraw(withdraws) []
May 14 21:09:10 bots-server start.sh[384164]: processWithdrawEvents(withdrawn_events)
May 14 21:09:10 bots-server start.sh[384164]: cycleDeposits [{"id":828,"deposit_id":0,"token0":"0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599","token1":"0xf939e0a03fb07f59a7>
May 14 21:09:10 bots-server start.sh[384164]: Health updated successfully.
May 14 21:09:10 bots-server start.sh[384164]: id health health_threshold:  828 553.6796366478517 300
May 14 21:09:10 bots-server start.sh[384164]: id health profit_taking:  828 553.6796366478517 null
May 14 21:09:10 bots-server start.sh[384164]: Health updated successfully.
May 14 21:09:11 bots-server start.sh[384164]: id health health_threshold:  829 771.8115617408416 300
May 14 21:09:11 bots-server start.sh[384164]: id health profit_taking:  829 771.8115617408416 null
May 14 21:09:11 bots-server start.sh[384164]: executeWithdraw(withdraws) []
