### ISSUE TITLE
CHORE: update bot, repo & service names

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1565]
Update repo, service and bot names in API to be consistent. Full bot repo inventory can be found here https://www.notion.so/volumefi/Palomabot-repo-and-contract-address-inventory-73691914623c4e91a0972ef6f13aad98?pvs=4 cc @jamie088 

@wc117 

- [ ] https://github.com/VolumeFi/Curve-noob-leverage-bot-CW --> `curve-squeeze-leverage-bot-cw`
- [ ] https://github.com/VolumeFi/Curve-noob-leverage-bot-vyper --> `curve-squeeze-leverage-bot-vyper`

@rootedbox 

- [x] https://github.com/VolumeFi/curve-noob-leverage-lending-bot --> `curve-squeeze-leverage-bot`
- [x] Service: curve-noob-leverage-lending-bot --> `curve-squeeze-leverage-bot`
- [x] API: `juice_curve` --->  `squeeze_curve`
- [x] stats API: `squeeze_curve` --> `squeeze_wbtc_curve` and `squeeze_eth_curve`
- [x] https://github.com/VolumeFi/curve-healthy-juicebot --> `curve-healthy-bot`
- [x] Service: curve-healthy-juicebot --> `curve-healthy-bot`

![image](https://github.com/VolumeFi/paloma/assets/83244763/41b1337f-e6a2-4a34-b993-d2d5520efb4c)

**Comment by rootedbox** [comment]
all my pieces have been done and restarted.

**Comment by rootedbox** [comment]
https://www.curvebot.fi is working again @verabehr
