### ISSUE TITLE
Bug: env file doesn't exist in server price-prediction

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1571]
@rootedbox 
I couldn't find any env file in price-prediction folder. which directory is correct one?
didn't you set .env file in price-prediction? 
please fix this issue in your early morning so Jimmy can test in active epoch time. we only have around 19 hours from now for this active epoch.

**Comment by fullstack412** [comment]
after fixing that, please run the processEpoch function one time manually so we can call the setEpoch function in the script
