### ISSUE TITLE
Bug: DB error while processing epoch in ETH price prediction bot backend script

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1572]
when I run the `npm run processEpoch` cli command, I got this error below.

"Processing epoch.
Error retrieving highest epoch ID: error: column "eth" does not exist
    at /home/rootedbox/app/pp-bots/eth/node_modules/pg/lib/client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getCurrentEpoch (/home/rootedbox/app/pp-bots/eth/index.js:206:17)
    at async processEpoch (/home/rootedbox/app/pp-bots/eth/index.js:224:27) {
  length: 103,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '97',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3553',
  routine: 'errorMissingColumn'
}
Error processing epoch: error: column "eth" does not exist
    at /home/rootedbox/app/pp-bots/eth/node_modules/pg/lib/client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getCurrentEpoch (/home/rootedbox/app/pp-bots/eth/index.js:206:17)
    at async processEpoch (/home/rootedbox/app/pp-bots/eth/index.js:224:27) {
  length: 103,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '97',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3553',
  routine: 'errorMissingColumn'
}
"

**Comment by fullstack412** [comment]
It looks query error.
select max(epoch_id) will not return value at first. so it returns error in WHERE clause.
`SELECT * FROM epoch_info WHERE epoch_id = (SELECT MAX(epoch_id) FROM epoch_info WHERE contest = ${CONTEST})`

**Comment by fullstack412** [comment]
@rootedbox 
in code line 244, you need to check if current epoch_id is existed in bid_info table, not in epoch_info table,
recordBids and setWinners functions shouldn't be call if the current epoch id is already existed in bid_info table.
i think you need to add one more function for it (like bidsExist()).

and in setWinners function,
you should call set_winner_list cosmwasm function with empty array if there is no bid infos

I think it's the last step. we are almost done.
cc: @taariq @verabehr

**Comment by rootedbox** [comment]
> [@rootedbox](https://github.com/rootedbox) in code line 244, you need to check if current epoch_id exists in bid_info table, not in epoch_info table, recordBids and setWinners functions shouldn't be call if the current epoch id already exists in bid_info table. i think you need to add one more function for it (like bidsExist()).
> 

This won't work if we have no bids in a day.. we need to check the epoch table


> and in setWinners function, you should call set_winner_list cosmwasm function with empty array if there is no bid infos
> 

we already do that...

```
    const winnerInfos = [];
    if (winners.length > 0) {
      winnerInfos = winners.map((winner) => ({
        epoch_id: epoch.epoch_id,
        winner: winner.sender,
        claimable_amount: claimableAmount,
      }));
    }
```

> and in code line 253, you need to add condition. setEpoch function and insert into query should be run only if the epoch.competition_start != '0' and epoch.competition_end != '0' and epoch.prize_amount != '0' (because if we read non exist epoch info from contract, it returns [0,0,0])
> 

done.

> I think it's the last step. we are almost done. cc: [@taariq](https://github.com/taariq) [@verabehr](https://github.com/verabehr)

**Comment by fullstack412** [comment]
need to test setWinner function yet, I updated the index.js file again, let's do the final test @rootedbox 
cc: @verabehr @taariq

**Comment by fullstack412** [comment]
@rootedbox Let's do the final test for testing the setWinners functionality with mockup data.
We have 2 bids now
so, Let's make these two bidders winners.
after that, test is done and let's reset the code and run the real backend script code without test code
