### ISSUE TITLE
Tailored Landing page

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1573]
Figma link

https://www.figma.com/design/fO2IMDgKqgwO9kqlfmDN1s/Tailored?node-id=497-3003&t=MaF184j4eTx5EVC0-4

Link for whitepaper: https://docs.google.com/document/d/1XnYja2RGLzJtQJ5yXDIGIxe3rMaIN9QEIY1zFwEz5Qo/edit?usp=sharing 

"Join the Community" link: https://t.me/tailoredai

**Comment by verabehr** [comment]
@Cieloc @joycehermosilla I don't see a link to for the whitepaper on the new design. @joycehermosilla will you please add?

**Comment by jamie088** [comment]
@verabehr @joycehermosilla I will add a whitepaper to the new design, just like the previous design.
![Image](https://github.com/VolumeFi/paloma/assets/83244763/55fd71d5-ad2b-4c70-b618-e941d9de17bd)

**Comment by verabehr** [comment]
- [ ] organizes should be capitalized.

![Image](https://github.com/VolumeFi/paloma/assets/19958639/e768c613-4045-4a62-8202-9d682e6e5e48)

- [ ] add favicon https://discord.com/channels/987730379182051408/1118035594686234665/1250891788609257502
- [ ] How it works menu should redirect to "Your Personal AI organizes your time" section.

**Comment by Cieloc** [comment]
Taariq needs to ship out to investors. To the extent that there are any links that go nowhere let's remove for now.
