### ISSUE TITLE
Balance alert for wallet was not triggered

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1574]
Fixes for wallet balance alert check 

- [ ] Balance alert is not triggered when wallet balance is below 5 Grain. See e.g. paloma156nvzxcp59wa9j5zj3fuj56lw2r5kldesas0l9. [Has less than 1 grain ](https://paloma.explorers.guru/account/paloma156nvzxcp59wa9j5zj3fuj56lw2r5kldesas0l9), but wcheck address [returns true](https://wcheck.palomachain.com/paloma156nvzxcp59wa9j5zj3fuj56lw2r5kldesas0l9)
- [ ] any random paloma address actually returns `true` for the wcheck address, even if it is not added in the address.txt file - e.g. https://wcheck.palomachain.com/paloma1wm4y8yhppxud6j5wvwr7fyynhh09tmv5x5sfzm

**Comment by taariq** [comment]
Closing as won't ship.
