### ISSUE TITLE
[EPIC] Create Two New Epics based on Gnosis Chain Finality

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1575]
**Epic 1:**
 Allow Pigeons to speficy multiple RPC providers with auto-fail-over if RPC errors.  Will you create an epic that will allow pigeons to add multiple RPC providers for any of their chains. Also, that if RPC endpoints return an error, the pigeon will be able to fail over to their next endpoint? 

NOTE: This may impact how long a pigeon will get a message and message assignments. We will need an epic to document the question of whether this is an issue.

**EPIC 2:** 
Add Finality Duration for each chain when adding chain proposal. Maybe a setting in config.yaml. 

So it appears that Gnosis does not reach blockchain finality (when a tx is considered as in a block) for about it's 2 epochs ~160 seconds = 2.6 MINUTES!!.  This means that if Paloma is faster than Gnosis, Validators will NOT be able to attest to a tx. It's not yet on chain for nearly 3 minutes.

We will need to allow all pigeons to specify the finality needed for each chain. This may be a setting we can set in pigeon as validator-controlled, but again, I think it will impact assignments if pigeons are too slow and Paloma expects fast attestation.  If it's easiest to just set it as a feature in pigeon, then the question is: How will such a setting affect assignments. Gnosis is a slow-finality chain

From @verabehr 
> I‘m not sure if this would be an issue at assignment. We fail over to another pigeon if the first doesn’t deliver. The mass hailing’s that we’ve seen is because pigeons don’t attest to a message

**Comment by verabehr** [comment]
This is still WIP, some thoughts
1. I think it would make sense to combine this into one epic as the overall purpose is to prevent mass jailings and move messages through the queue quickly
2. There is something else going on. Validators are running out of gas on Paloma. It's not clear yet if there is also a gnosis specific issue actually happening. WIP notes here https://www.notion.so/volumefi/EPIC-05-17-Prevent-mass-jailings-due-to-lack-of-evidence-76e97b58dcc346068e906e32e3b84363?pvs=4

**Comment by verabehr** [comment]
@taariq have we seen any evidence that finality on gnosis is an actual issue for us? I'm still wrapping my head around it, but I would think that is an issue, we should see problems far more often given the number of tx we're running on Gnosis?

**Comment by verabehr** [comment]
https://www.notion.so/volumefi/EPIC-06-14-Pigeon-RPC-failover-920c4e7344a94da68ea3efdacc648967?pvs=4
https://www.notion.so/volumefi/EPIC-06-14-Custom-chain-finality-settings-25503197406946fa8924b44e9ca9e171?pvs=4
