### ISSUE TITLE
TRACKING BUG: Error: recovered: Block (unix) time must never be empty or negative

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1587]
For details see https://github.com/palomachain/paloma/issues/1115. This is blocking (some) new validators to join the chain

as well as https://github.com/VolumeFi/paloma/issues/1532

**Comment by verabehr** [comment]
Observed again on the mainnet validator - steps that led to discovery

1. validator down alert in alert channel 
2. confirmed that validator was not actually jailed (via cli and explorer) and confirmed that we were not signing any block (explorer)
3. checked paloma logs - couldn't do `-f` due not enough descriptors available. I didn't copy the logs of the first few lines of`-n 100` , but validator seemed to be stuck in the P2P module (I didn't check all 100 lines though)
4. restarted palomad service
5. Observed the error and as far as I can tell that is still ongoing```{"level":"error","module":"server","err":"recovered: Block (unix) time must never be empty or negative \nstack:\ngoroutine 37248 [running]:\nruntime/debug.Stack()\n\t/opt/hostedtoolcache/go/1.22.2/x64/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.func5({0x302d500, 0x46c8ed0})\n\t/home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.6/baseapp/recovery.go:74 +0x25\ngithub.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.newRecoveryMiddleware.func7({0x302d500?, 0x46c8ed0?})\n\t/home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.6/baseapp/recovery.go:42 +0x2d\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x302d500, 0x46c8ed0}, 0x0?)\n\t/home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.6/baseapp/recovery.go:31 +0x2f\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x302d500, 0x46c8ed0}, 0x0?)\n\t/home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.6/baseapp/recover...```

**Comment by byte-bandit** [comment]
We investigated this to the point where there's not much gain in contrast to time spent, given that the validator is able to recover from a snapshot and we haven't had a lot of reports come in yet. So I will close this for now and come back to should it be needed.
