### ISSUE TITLE
Uniswap v3 limit order service

### ISSUE THREAD

**Issue by webelf101** [VolumeFi/paloma#1588]
# Background

We need a backend service for Uniswap v3 limit order bot.

# Done when

- [x] create a service from https://github.com/VolumeFi/limit-order-bot-uni-v3-script.git
- [x] copy .env file and networks.json file from limit-order-bot-uniswap-v2 service
- [x] create a paloma account and replace the mnemonic words in .env file
- [x] fund the paloma account

**Comment by verabehr** [comment]
@webelf101 this is complete
