### ISSUE TITLE
[Pigeon Feed] As a user, I want to be able to deploy any smart contract to any supported chain via the CLI and Python SDK using Pigeon Feed

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#159]
# Background
Pigeon Upgrade: As a user, I want to be able to deploy any smart contract to any supported Paloma chain via the CLI and Python SDK using the Pigeon Feed functionality for paying for message relays.

# Done when
- [ ] Ensure that this performs the same as the `palomad tx gov submit-proposal evm propose-new-smart-contract '[JSON ABI BLOB]' [HEX BLOB]` code 
- [ ] Accept ABI and BYTECODE as file inputs
- [ ] Return the success of the contract creation with the contract address or failure with target chain return error.
- [ ] Implement the ability to prepay for this transaction in the target chain DENOM and with the estimated amount.
- [ ] Store the contract hash address and make it queryable and settlement.
- [ ] Use Pigeon Feed functionality for message relay payments

# Gotchas
- At the moment, we'll try to re-send the last scheduled contract. In theory, those could be overridden when multiple users try to attempt sending. We should keep a buffered list instead of a single item.

**Comment by verabehr** [comment]
no longer needed, replaced by https://github.com/VolumeFi/paloma/issues/164

**Comment by taariq** [comment]
This is still needed. This is for the Golang side of the CLI.

**Comment by byte-bandit** [comment]
@taariq 

> Put the signatures and powers from the constructor from the powers of the validators

Can you expand on what exactly you mean by this?

**Comment by taariq** [comment]
@byte-bandit removed. I was drunk when I wrote that. Please check with @wc117 to verify anything else that will be needed to deploy any contract via the Pigeons.

**Comment by byte-bandit** [comment]
@taariq 

`Implement a DDOS attack mitigation: This can only be run 6 times per day to limit abuse as all fees are refunded to validators and these will be possibly the most expensive.`

Are we talking 6 times per day per validator? Or 6 times per day in total, shared across all nodes?

**Comment by byte-bandit** [comment]
@taariq 

Another question: Does it matter which Pigeon deploys the smart contract? Up to now, I was under the consideration that it won't really matter which validator ends up deploying the smart contract to the target chain, as the new gas management will ensure a weighed distribution among validators. 

But now I have started to think of this contract deployment as something that validators don't have to agree on. It's not "owned by all" so to speak, although the information still gets stored on the chain, there is no voting, etc...

So I would like to confirm with you.

**Comment by taariq** [comment]
> @taariq
> 
> `Implement a DDOS attack mitigation: This can only be run 6 times per day to limit abuse as all fees are refunded to validators and these will be possibly the most expensive.`
> 
> Are we talking 6 times per day per validator? Or 6 times per day in total, shared across all nodes?

Six times per day in total across all nodes.

**Comment by taariq** [comment]
> @taariq
> 
> Another question: Does it matter which Pigeon deploys the smart contract? Up to now, I was under the consideration that it won't really matter which validator ends up deploying the smart contract to the target chain, as the new gas management will ensure a weighed distribution among validators.
> 
> But now I have started to think of this contract deployment as something that validators don't have to agree on. It's not "owned by all" so to speak, although the information still gets stored on the chain, there is no voting, etc...
> 
> So I would like to confirm with you.

It doesn't matter which. Just like deploying Compass-EVM.

**Comment by taariq** [comment]
I made this upate: 
`- [ ] Implement the ability to prepay for this transaction in the target chain DENOM and with the estimated amount.`

**Comment by maharifu** [comment]
@taariq what does this mean "Ensure that Compass-EVM is owner of the contract"? Does this still make sense?

**Comment by taariq** [comment]
@maharifu updated and removed. Let's continue!
