### ISSUE TITLE
api: /swap api endpoint for 1inch

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1593]
Please add `/swap` api endpoint for 1inch api call.
(similar to passthrough api endpint)

I will send these params

- fromTokenAddress
- toTokenAddress
- amount
- fromAddress
- slippage
- disableEstimate
- chain (chainId 1 or 56 or)

ex url: `https://api.1inch.dev/swap/v6.0/1/swap?fromTokenAddress=0xdAC17F958D2ee523a2206206994597C13D831ec7&toTokenAddress=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2&amount=20000000&fromAddress=0x8F5eBDdcf2bae86D3A4E3C4De427E705d2eBF432&slippage=1&disableEstimate=true`

**Comment by verabehr** [comment]
this was completed
