### ISSUE TITLE
Feature: Update backend service for emergency cancelling of bots.

### ISSUE THREAD

**Issue by wc117** [VolumeFi/paloma#1596]
# Background

If the server gets CancelPendingBot event, it says the user's pending bots were cancelled. So we need to update db as all the pending bot cancelled. Maybe you can set remaining count as 0.

event format is as follows.

```
event CancelPendingBot:
    user: address
    collateral: address
    collateral_amount: uint256
```

# Done when

- [x] Update llamalend bot server
- [x] Update noob leverage bot server
- [x] Update degen leverage bot server
- [x] Update healthy juice bot server

**Comment by rootedbox** [comment]
@wc117 I'm guessing user is the bot address?? or else none of these params are unique. is that correct?

**Comment by taariq** [comment]
from @rootedbox to @wc117 
> https://github.com/VolumeFi/paloma/issues/1596 is complete.. but it does make the assumption that user is the bot address. if its not then the contract event needs to be redone to use the bot address as its the unique id for us to find the transaction

We will re-open and assign to @wc117 to confirm.

**Comment by wc117** [comment]
What's number trades and what's remaining counts?
https://github.com/VolumeFi/curve-squeeze-leverage-bot/blob/b6011f2ddfdc9589df2cbd7aa9d49c5640323119/curve-noob-leverage.js#L325
You are getting the pending bots by remaining counts but you set number trades as zero.
https://github.com/VolumeFi/curve-squeeze-leverage-bot/blob/b6011f2ddfdc9589df2cbd7aa9d49c5640323119/curve-noob-leverage.js#L388
I don't think it can work.
@rootedbox

**Comment by taariq** [comment]
@rootedbox the ticket suggest `Maybe you can set remaining count as 0.` not trades count as zero

**Comment by rootedbox** [comment]
> What's number trades and what's remaining counts? https://github.com/VolumeFi/curve-squeeze-leverage-bot/blob/b6011f2ddfdc9589df2cbd7aa9d49c5640323119/curve-noob-leverage.js#L325 You are getting the pending bots by remaining counts but you set number trades as zero. https://github.com/VolumeFi/curve-squeeze-leverage-bot/blob/b6011f2ddfdc9589df2cbd7aa9d49c5640323119/curve-noob-leverage.js#L388 I don't think it can work. [@rootedbox](https://github.com/rootedbox)

it works because I set the withdraw_block.. and that stops any transaction. that being said I will set remaining count over instead of number of trades.. 


that being said.. the question that really needs to be answered is the one I asked above..

>I'm guessing user is the bot address?? or else none of these params are unique. is that correct?

@wc117 cc: @taariq

**Comment by verabehr** [comment]
@rootedbox as per our discussion, will you please do the following: 

**check**
1. the factory contract address that emits the event
2. the user's wallet address that is sent in the event (and is the withdrawer) in the DB
3. if any of the user's bot have a remaining_count > 0
**then**
set the remaining_count to 0 for all of them AND/OR set the withdraw block for these

**Comment by rootedbox** [comment]
@verabehr that will cancel all bots related to a user.

**Comment by rootedbox** [comment]
updated all code.. and servers.. and restarted servers
