### ISSUE TITLE
Mixpanel: Gas fee cost in USD

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#16]
# Background

_Describe the problem that we are trying to solve with this feature._
_If a path to a solution is known, feel free to write it down, but have an open mind_

The gas refund events are correct, but not useful at the moment as they are not shown in USD. To evaluate the network cost across chains for the business, we want to know the cost in USD

# Done when

- [ ]  The gas_refund events are show in USD instead of MATIC and BNB

**Comment by rootedbox** [comment]
I forgot this is python code.. I can do it.. it's probably just going to take half a day to do. @verabehr

**Comment by taariq** [comment]
closed as won't fix.
