### ISSUE TITLE
[RECOVERY] Build UI to allow user to recover ETH from failed TWAP

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1600]
Create one-time UI to run this function. https://etherscan.io/address/0xcc9a2a4c2a7a48ceca71f998e09dbe907c77930e#writeContract#F5

**Comment by jamie088** [comment]
@taariq Need to add a one-time UI to palomabot's mybots page?

**Comment by taariq** [comment]
Just give me a dedicated URL. This doesn't need to be on the Mybots page.

**Comment by jamie088** [comment]
I will add a simple table to show the bot name and status including the Stop Bot button. Is it okay?
And url will be like this? `https://www.palomabot.ai/bot/recover-twap`

**Comment by taariq** [comment]
That's perfect. Let's do it.

**Comment by jamie088** [comment]
Done. https://palomabot-miap4oqy9-volume.vercel.app/bot/cancel-pending-bot/

**Comment by taariq** [comment]
Done and used by the user.
