### ISSUE TITLE
[Bug]  ERROR :"UNSUPPORTED_OPERATION","operation":"getAddress"

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1601]
EVM Bug on the back-end blocks repayments and TWAPs.

May 21 14:31:08 bots-server start.sh[189172]: executeWithdraw(withdraws) []
May 21 14:31:10 bots-server start.sh[189172]: processWithdrawEvents(withdrawn_events)
May 21 14:31:11 bots-server start.sh[189172]: getNextBotArgs {"reason":"unknown account #0","code":"UNSUPPORTED_OPERATION","operation":"getAddress"}
May 21 14:31:11 bots-server start.sh[189172]: {"reason":"unknown account #0","code":"UNSUPPORTED_OPERATION","operation":"getAddress"}
May 21 14:31:11 bots-server start.sh[189172]: cycleDeposits [{"id":830,"deposit_id":0,"token0":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","token1":"0xf939e0a03fb07f59a7331>
May 21 14:31:11 bots-server start.sh[189172]: Health updated successfully.
May 21 14:31:11 bots-server start.sh[189172]: id health health_threshold:  830 4549.993063435179 200

**Comment by jamie088** [comment]
@taariq @rootedbox If you share the backend code where this issue is appearing, I will confirm it.

**Comment by taariq** [comment]
@jamie088 the issue is also referenced here with links to the code: https://github.com/VolumeFi/paloma/issues/1393#issuecomment-2121374350

**Comment by jamie088** [comment]
@taariq @rootedbox I checked why this issue occurs on the server and it is from when init the crvusd (from curvefi npm) in the backend code.

In this line:
```await crvusd.init(
      "JsonRpc",
      { url: NODE },
      { gasPrice: 0, maxFeePerGas: 0, maxPriorityFeePerGas: 0, chainId: 1 }
    );```

It has nothing to do with FE, I am curretnly thinking 3 solutions.

- [ ] First, we need to upgrade the curvefi npm package version in all backend repos. This also resolves the `multicall` issue that was previously happening.

@curvefi/api: `2.53.6` -> `2.58.10`
@curvefi/stablecoin-api: `1.5.2` -> `1.5.3`
I already confirmed these versions on FE and no issue so far.

- [ ] Second, if the above solution is not correct, we should check with the curve team that the curvefi API works on node backend server. In curve doc example, say only in FE(react)

- [ ] Third, check the rpc endpoint
backend is using `liquify` rpc url on eth
frontend is using `quiknode` rpc url but no issue.

**Comment by taariq** [comment]
@jamie088 Thanks for this write-up. 
To Reflect: 
This is a back-end library and RPC endpoint issue.
1. Upgrade libraries
2. Curve team on node
3. RPC endpoint (why is this an issue?)

NOTE: front is not supposed to be using Quicknode. All production need to be on Liquify. Quicknode is emergency backup only.

**Comment by rootedbox** [comment]
@jamie088 @taariq @verabehr I've upgraded the libraries on all twaps.. updated the server and restarted all services. I'm not seeing any getAddress at this time.. so should probably put this on a wait and see for now.

**Comment by rootedbox** [comment]
moving to blocked until we see this again or it's been a week.

**Comment by verabehr** [comment]
This is still happening. Last observed on the `curve-healthy-bot` on May 28

**Comment by taariq** [comment]
Errors today:
{"reason":"unknown account #0","code":"UNSUPPORTED_OPERATION","operation":"getAddress"}
May 29 18:41:29 bots-server start.sh[1369661]: {"reason":"unknown account #0","code":"UNSUPPORTED_OPERATION","operation":"getAddress"}
May 29 18:41:31 bots-server start.sh[1369661]: processWithdrawEvents(withdrawn_events)
May 29 18:41:31 bots-server start.sh[1369661]: getNextBotArgs {"reason":"unknown account #0","code":"UNSUPPORTED_OPERATION","operation":"getAddress"}
May 29 18:41:31 bots-server start.sh[1369661]: {"reason":"unknown account #0","code":"UNSUPPORTED_OPERATION","operation":"getAddress"}
May 29 18:41:32 bots-server start.sh[1369661]: processWithdrawEvents(withdrawn_events)
May 29 18:41:32 bots-server start.sh[1369661]: cycleDeposits []
May 29 18:41:32 bots-server start.sh[1369661]: executeWithdraw(withdraws) []
May 29 18:41:33 bots-server start.sh[1369661]: processWithdrawEvents(withdrawn_events)
May 29 18:41:34 bots-server start.sh[1369661]: getNextBotArgs {"reason":"unknown account #0","code":"UNSUPPORTED_OPERATION","operation":"getAddress"}
May 29 18:41:34 bots-server start.sh[1369661]: {"reason":"unknown account #0","code":"UNSUPPORTED_OPERATION","operation":"getAddress"}
May 29 18:41:34 bots-server start.sh[1369661]: processWithdrawEvents(withdrawn_events)
May 29 18:41:34 bots-server start.sh[1369661]: cycleDeposits []
May 29 18:41:34 bots-server start.sh[1369661]: executeWithdraw(withdraws) []
May 29 18:41:36 bots-server start.sh[1369661]: processWithdrawEvents(withdrawn_events)
May 29 18:41:36 bots-server start.sh[1369661]: {"data":null}
May 29 18:41:37 bots-server start.sh[1369661]: getNextBotArgs {"reason":"unknown account #0","code":"UNSUPPORTED_OPERATION","operation":"getAddress"}
May 29 18:41:37 bots-server start.sh[1369661]: {"reason":"unknown account #0","code":"UNSUPPORTED_OPERATION","operation":"getAddress"}

**Comment by verabehr** [comment]
The endpoint was the culprit. Need to confirm and check all bot services that need to be upgraded. 

- [ ] llmalend
- [ ] limit-order-bot-v3
- [ ] curve-dca-bot-service (curve TWAP)
- [ ] curve-leverage-lending-bot
- [ ] curve-squeeze-leverage-bot
- [ ] curve-healthy-bot

**Comment by rootedbox** [comment]
all service endpoints updated and servers restarted
