### ISSUE TITLE
[BUG] Llamalend squeeze bot: I can't see my bot in mybots api

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1602]
just tested the Llamalend squeeze bot and the bot was created successfully. But I can't see my bot in mybots api result.

https://etherscan.io/tx/0x471ae8ed1c6e50db5e68e8e2ac6c210e52659c229d4b6e81885e0e922509a394

**Comment by rootedbox** [comment]
![Image](https://github.com/VolumeFi/paloma/assets/3997890/042d4df8-a5db-481c-9d29-2f438352d93b)

[https://service.palomabot.ai/robots](https://service.palomabot.ai/robots?depositor=0x8F5eBDdcf2bae86D3A4E3C4De427E705d2eBF432) shows it active
