### ISSUE TITLE
bug: withdrawn bot is still in api result.

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1604]
This user (0x79C9A765d865f949c18335321436fAAfa865B2e6) already withdrew all twaps of the old Curve ETH squeeze bot 10 days ago.
But his bot is still in the mybots API results.
```"deposit_id":"10","token0":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","token1":"0xf939e0a03fb07f59a73314e73794be0e57ac1b4e","amount0":"2994000000000000000","amount1":"2.06354538500345e+23","depositor":"0x33EB6cC730f0C8c47cC4503B54D41E03C7C32fe8","deposit_price":"9146.99934","expire":"33247318997","withdrawer":"0x79C9A765d865f949c18335321436fAAfa865B2e6","network_name":"ETH","dex_name":"curve","bot":"squeeze_eth_curve","number_trades":"5","remaining_counts":"0","interval":"30","contract":"0x34BC9970228b14A76ebF0A7f5a601001bBCA20C8","bot_type":"12","fees_charged":"0.05223062279655718","sent_to_mixpanel":"0","transaction_hash":"0x4eef2c5f77844b4151507ca4ff20cc8fd919ed8d29d5f8c99112fd0e2cfcf757","create_to_mixpanel":"0","created_at":"2024-05-07 20:15:12","gas_mixpane"...```

**Comment by rootedbox** [comment]
I don't know the exact reason.. but I've set the withdraw block for the transaction so it will no longer be in the users mybots
