### ISSUE TITLE
Upgrade Paloma Leveraget Bot TWAP Algorithm on Front-end

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1606]
As a user, I want Paloma to upgrade the TWAP algorithm to the new proposed TWAP formula outlined in the Python code here: 
https://www.notion.so/volumefi/EPIC-05-22-24-TWAP-count-for-Leverage-bots-bd45c5f5bb774b97bddb011233ce1b90?pvs=4#700215adc4e34ccaa5dc5d99e7b9dd9d

**Acceptance Crteria**
1. Upgrade TWAP calculation on front-end for all Leverage Bots
2. Verify that TWAPs work with this issue resolved: https://github.com/VolumeFi/paloma/issues/1601

**Comment by taariq** [comment]
@jamie088 this is not yet done?

**Comment by jamie088** [comment]
@taariq Fixed with https://github.com/VolumeFi/palomabot/pull/439
