### ISSUE TITLE
[BUG] Curve TWAP Bot fails with Front-End Alert "Error - Please stop Bot" 

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1613]
Transaction: https://etherscan.io/tx/0x637290663ce90d2316e0922d585270d8136abf18f0ab60170c2c75078303e5d4

User then sees the MyBots page error to Stop bot. 

![Image](https://github.com/VolumeFi/paloma/assets/701864/9f60ebb4-08f9-430d-a61d-3221acba83ca)

**Comment by verabehr** [comment]
We implemented an error field that results in this FE message. 

Here is the code line https://github.com/VolumeFi/curve-twap-bot-script/blob/master/bot_execute.py#L308 where `error` is set to  1 if the bot can't be processed by the backend. If Error is 1, then the FE displays this message so the user can withdraw https://github.com/VolumeFi/palomabot/pull/231. 

Here is the ticket that requested the backend change: https://github.com/VolumeFi/paloma/issues/935
