### ISSUE TITLE
[Gravity] Last Observed Event Nonce & Block Height are not chain agnostic

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#1617]
Paloma's gravity module keeps track of the last observed event nonces and block heights on the remote chain, but there is no separation of concern for different target chains, which means, if the bridge were to be used on more than one target chain at the same time, it would fail.

This is likely a leftover from the original project that wasn't intended to be used with more chains at the same time. We need to extend the keeper logic to support that.

**Comment by taariq** [comment]
Closed with https://github.com/palomachain/paloma/pull/1174
