### ISSUE TITLE
[BUG] Unable to trade wTAO with ETH on uniswap v2 LImit Order bot ERROR: Insufficient Amount

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1618]
![Image](https://github.com/VolumeFi/paloma/assets/701864/6dc95303-e00d-4ca3-a71e-004308851e30)

**Comment by jamie088** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/440

**Comment by taariq** [comment]
@jamie088 getting 404 
<img width="1123" alt="Screenshot 2024-05-27 at 10 22 18 AM" src="https://github.com/VolumeFi/paloma/assets/701864/fe8baa59-9e90-4a6b-9b45-80dcfd1031aa">
