### ISSUE TITLE
bug: some values are missing in the API results for the Uniswap v2 limit order bot.

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1619]
I tested the Uniswap V2 twap bot and `amount1`(buy token), `deposit_price`, `tracking_price` are missing in the API results for the Uniswap v2 limit order bot.
`{"deposit_id":"0","token0":"0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE","token1":"0x77E06c9eCCf2E797fd462A92B6D7642EF85b0A44","amount0":"5000000000000000","depositor":"0x8F5eBDdcf2bae86D3A4E3C4De427E705d2eBF432","profit_taking":"50","stop_loss":"0","expire":"1716839333","network_name":"ETH","dex_name":"uniswapv2","bot":"limitorder_uniswapv2","contract":"0x74c6d395428A5343b81A333A2ea93Dbf107663c6","old":"0","tracking_price1":"437.05","deposit_price1":"437.05","sent_to_mixpanel":"0","create_to_mixpanel":"0","created_at":"2024-05-27 18:49:56","gas_mixpanel":"0","deleverage_percentage":"100",`

tx hash: https://etherscan.io/tx/0xbf618adc48a08d7df986587d13924e856757ef80a42ae2b9f29d1ac6628115c1

![image](https://github.com/VolumeFi/paloma/assets/83244763/98508881-90bf-47a1-ac3d-2e54513e8813)

**Comment by rootedbox** [comment]
I'm getting confused on how the prices are calculated weth and COINGECKO_CHAIN_ID.. @wc117 can you please check this out.. I think the cache mechanism is off.

cc: @verabehr

**Comment by verabehr** [comment]
according to @rootedbox: 

There are no values for the missing prices in the cache. This is the line where we get the values https://github.com/VolumeFi/limit-order-bot-script/blob/master/limit-orders.js#L521 

This code was last touched by @wc117 - assigning to @wc117 and @webelf101

**Comment by verabehr** [comment]
This is solved by removing

https://github.com/VolumeFi/limit-order-bot-script/blob/master/limit-orders.js#L320-L322
and
https://github.com/VolumeFi/limit-order-bot-script/blob/master/limit-orders.js#L330-L332
