### ISSUE TITLE
bug: EurE bot can't start with CRV input

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#1633]
EurE bot can't start with CRV input

<img width="628" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/a06510f9-d58d-47e8-be74-8647db3947d1">

`e Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: Exchange is suspended. Operation prohibited", method="estimateGas", transaction={"from":"0xD0e08D653C3ead747865c3674FFa93ecDefDd045","to":"0x09346b6264eafCA5d857DF74fC44c84cfAA3D872","data":"0x217770310000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000d533a949740bb3306d119cc777fa900ba034cd520000000000000000000000004ebdf703948ddcea3b11f675b4d1fba9d2414a14000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000c5424b857f758e906013f3555dad202e4bdb45670000000000000000000000005e74c9036fb86bd7ecdcb084a0673efc32ea31cb000000000000000000000000c011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f00000000000000000000000057ab1ec28d129707052df4df418d58a2d46d5f51000000000000000000000000a5407eae9ba41422680e2e00537571bcc53efbfd0000000000000000000000006b175474e89094c44da98b954eedeac495271d0f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001aa535d3d0c000000000000000000000000000000000000000000000000000000d44790033a778f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"execution reverted: Exchange is suspended. Operation prohibited","data":{"originalError":{"code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002b45786368616e67652069732073757370656e6465642e204f7065726174696f6e2070726f68696269746564000000000000000000000000000000000000000000","message":"execution reverted: Exchange is suspended. Operation prohibited"}}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at Logger.makeError (_app-7b32296c9306a0b2.js:1:203690)
    at Logger.throwError (_app-7b32296c9306a0b2.js:1:203809)
    at checkError (_app-7b32296c9306a0b2.js:1:283184)
    at Web3Provider.<anonymous> (_app-7b32296c9306a0b2.js:1:293481)
    at Generator.throw (<anonymous>)
    at rejected (_app-7b32296c9306a0b2.js:1:282225)`

**Comment by jamie088** [comment]
Confirmed. It works fine with palomabot.ai, but not with curvebot.fi.

**Comment by jamie088** [comment]
Fixed it on curvebot.fi
