### ISSUE TITLE
[Resilience] Periodically update the reference block height in chains-infos

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1637]
As a pigeon, I want all valid chains to be validated on pigeon startup /chain info change even if my rpc endpoint is pruned
https://github.com/VolumeFi/paloma/issues/1634

### Done when

- [ ] Reference block height of the available evm chains (chains-infos) is updated every 10'000 blocks 
- [ ] All pigeons agree to the new block height and hash when updated

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/paloma/pull/1175
