### ISSUE TITLE
API: Create a new API that returns the ETH price at the end of epoch

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1638]
FE needs the ETH price at the end of each epoch. But we can't get this value from Vyper contract.
I know we store the ETH price at the end of each epoch in the Backend DB so please create a new api that returns the ETH price at the end of epoch. I will send you an epoch id as a param.
![image](https://github.com/VolumeFi/paloma/assets/83244763/86f41fc1-f692-4860-b02a-a78c062de6b7)

**Comment by rootedbox** [comment]
We were not storing the closing price.. but I updated the priceprdiction so it will from now on also we now have an api https://github.com/VolumeFi/price-prediction-api that being said our dns host is not accepting new domains right now so I won't be able to set up an endpoint until tomorrow. that being said it'll be https://pp.palomachain.com/epoch_info and https://pp.palomachain.com/bid_info when that's finished.. if you use the blank endpoints it'll bring all the records back if you use ?epoch_id you will be able to Bring a specific epochs back

**Comment by verabehr** [comment]
This is blocked by squarespace. Somehow we're unable to edit or save new dns records here https://account.squarespace.com/domains/managed/palomachain.com/dns/dns-settings 
<img width="356" alt="Screen Shot 2024-05-31 at 12 10 28 PM" src="https://github.com/VolumeFi/paloma/assets/19958639/6fe0c555-7742-43c1-ab64-c025e67af6a1">

@rootedbox created a ticket for this

**Comment by verabehr** [comment]
@rootedbox this seems to be still down. Let's put this on palomabot.ai which is on namecheap and move on

**Comment by rootedbox** [comment]
https://pp.palomabot.ai/epoch_info
https://pp.palomabot.ai/bid_info

?epoch_id  for a specific epoch

@jamie088
