### ISSUE TITLE
APX short funding bot vyper contract

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1642]
### Background
We want the same short funding bot that we have on GMX https://github.com/VolumeFi/short-funding-bot-vyper for APX. 

Epic: https://www.notion.so/volumefi/EPIC-05-03-24-APX-Short-Funding-Rate-Bot-fd7717c21aba40759825014d08b635fb

### Done when

- [ ] we have the vyper contract for APX short funding bot

**Comment by verabehr** [comment]
@jamie088 moving this back into your list as the auction epic was closed

**Comment by taariq** [comment]
Won't ship.
