### ISSUE TITLE
[BUG] Curve healthy bot - repay bot doesn't trigger an event

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1652]
Steps
1. curve-healthy-bot backend script triggered repay bot 
2. paloma tx was successful (see tx hashes below)
3. logic call was triggered (see tx hashes below)

Expected: I should see an event and a tx on the factory bot contract

Actual: I don't see anything on the factory bot contract

note: service was stopped

-------
**Paloma tx**
https://paloma.explorers.guru/transaction/E89BEF61D64F7C6FA92A6FF2DC9165D83CFF84AE3D34D8B8DEDD949BF40132E1?height=18243720
https://paloma.explorers.guru/transaction/7BBC3FFD7266BB30934D5F1FC1C0FF2793D472156FD0EEB67D8DE145524748E2?height=18243759
https://paloma.explorers.guru/transaction/1ED9694D7191629D3EC3BF48626EEC6956BD68CA6B0D507D409E43634F310AA7?height=18243801
https://paloma.explorers.guru/transaction/312C1EF1DAD82CD4B9BC2DC6971FD23E911D890A8B5ECC1DC0EB517A5DAF0459?height=18243841
https://paloma.explorers.guru/transaction/B3461FCBBE09353769F80D03C21EC9894788792E7CB3FE7B6E56535DA45BF2C0?height=18243883
https://paloma.explorers.guru/transaction/BF6411EF47D08941478BAB8BAE3B57706D4C251E8B64CD48C0722602F93BEDE6?height=18243922
https://paloma.explorers.guru/transaction/79EA188F512F51F65B69300768ED25F313689D221B0D3F393201D4704E2B5804?height=18243959
https://paloma.explorers.guru/transaction/3B072ECB1DEAB3B5FF53AE54A545855CBFC27CE238D183F50B8733F06AF89565?height=18243995
https://paloma.explorers.guru/transaction/5E8F9C8113B610357BBF67C630412142DAE9108DBE4B7A1DF953205255D870F9?height=18244034
https://paloma.explorers.guru/transaction/AF5397FE3F3C239B2450871609AA5A8C172435E0FDF91AC457C447683ED6AF6F?height=18244073
https://paloma.explorers.guru/transaction/5C8598EB30B4BDB66732F997A77D69A3AF84DEB9A1046FBB90C53147339844E4?height=18244111
https://paloma.explorers.guru/transaction/9D510966FF899663EB7F0D6904413D7ED2EA0C3A4340C9CB8B5B92DE7914DE37?height=18244153

**Logic calls:**
https://etherscan.io/tx/0xd10f04676f2e552794305bbcae5f7a4daa2ec772851d826c885d9c0530c32de4
https://etherscan.io/tx/0x0c0aee91a066bb9e0f42df6a0f56263270676036c78687609ce0dd237b39ce6f
https://etherscan.io/tx/0x66b71bf6fe1cae6f698f6ec73d6a8aabe2954dec186cef6d59ceb30baaae78e7
https://etherscan.io/tx/0x0a466cf9429abc91e21eb17bc147d73ecb917c38d2ec8d8e088d9c3e451f9839
https://etherscan.io/tx/0x5ce0b53ac0a9e66d5c8c56785fe433b12f8c123588fd143f86f179b3699fa84c
https://etherscan.io/tx/0x1b881332b13e34de11c7f86282ff1dd714def04c62889b25e148928c8122ffe1
https://etherscan.io/tx/0x28b13bbfb32f7acb61e50063487b572b2f6d207fe424a0941ce04527d6f8dc23
https://etherscan.io/tx/0xa0e15ddc79f7d7342160f1cca23928c0dc2b5ece10e364d83f16e4508559e802
https://etherscan.io/tx/0x7cd3420a506f602da373a6503230e64f9b148a736674d2774e552f0f23ee4b93
https://etherscan.io/tx/0xa273d90ce702582aff0f3228e25d6cacbfbfe0ede74c33fb6cf7c63517617c45
https://etherscan.io/tx/0x2c703bec44a507f7053b9a4cc11e8bce6fa7fded1fc995e501e4ee43d91020d5
https://etherscan.io/tx/0x4e026347c14c7caed9b4a35f34917fb99f013022074c7461e877cef27b6b0704

**Comment by verabehr** [comment]
according to william, we need a new CW contract

**Comment by verabehr** [comment]
https://github.com/VolumeFi/curve-healthy-cw

**Comment by wc117** [comment]
I fixed the but in CW and redeployed. We can test with new address. @verabehr

**Comment by verabehr** [comment]
@wc117 yes, we have kicked off a test and are waiting for repayment. This ticket was already closed
