### ISSUE TITLE
bug: EurE bot won't start with 0.03 CRV

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#1655]
EurE bot won't start with 0.03 or less CRV
<img width="236" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/57ee47a6-698c-4089-8732-ca7eefb5492e">

But it's okay with 0.05 or more
<img width="446" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/a9fab7e2-eade-447e-b818-a51a2d081069">

**Comment by taariq** [comment]
Closing as wont' fix.
