### ISSUE TITLE
bug: Curve limit order bot market ratio higher than limit ratio 

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#1656]
Started a Curve limit order bot https://etherscan.io/tx/0x146492ea73dd582b71d3855205915b21f50d9438f42a31cc27ce325c5514810b
The bot is to swap 0.001 ETH for USDC at limit ratio 3782, at deposit market ratio is around 3781.9

After started, the bot shows market ratio at 3793 > 3782, which should have triggered the swap but mybot page shows otherwise
<img width="901" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/41ab1ed3-a524-425a-8fc8-52ab78f7ba26">

Need to check logic, make sure if market ratio > limit ratio a swap is triggered

**Comment by verabehr** [comment]
there is an error in the backend

```Jun 05 15:42:06 bots-server start.sh[3590232]: Error: Returned error: No response or no available upstream for eth_getLogs
Jun 05 15:42:06 bots-server start.sh[3590232]:     at Object.ErrorResponse (/home/rootedbox/app/curve-limit-order-bot-script/node_modules/web3-core-helpers/lib/errors.js:28:19)
Jun 05 15:42:06 bots-server start.sh[3590232]:     at /home/rootedbox/app/curve-limit-order-bot-script/node_modules/web3-core-requestmanager/lib/index.js:300:36
Jun 05 15:42:06 bots-server start.sh[3590232]:     at /home/rootedbox/app/curve-limit-order-bot-script/node_modules/web3-providers-http/lib/index.js:131:13
Jun 05 15:42:06 bots-server start.sh[3590232]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
Jun 05 15:42:06 bots-server start.sh[3590232]:   data: null```

**Comment by rootedbox** [comment]
We were not getting prices correctly to check the ratio.
