### ISSUE TITLE
bug: Uniswap V3 limit order bot

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1657]
https://etherscan.io/address/0x257facb5d1ffd0f7bb0ee2091bb44ab6018c8a8b (Current Uniswap V3 limit order bot contract)

Currently, this Uniswap V3 limit order bot contract only allows users to create a limit order bot between tokens in existing pools. For example, users can create a limit order bot between ETH and USDT, but not between CRV and USDT.
If the swap path includes multiple pools, we will not be able to create a bot, so please update the Vyper contract to use the swap path got from the Uniswap router.

**Comment by verabehr** [comment]
reopening, until confirmed that we're all set with v3
