### ISSUE TITLE
Status 500 - failed to execute message; message index: 0: dispatch: submessages: invalid character 'Ù' looking for beginning of value

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#166]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Error:
Status 500 - failed to execute message; message index: 0: dispatch: submessages: invalid character 'Ù' looking for beginning of value [!cosm!wasm/wasmd@v0.40.0-rc.0/x/wasm/keeper/keeper.go:1206] With gas wanted: '18446744073709551615' and gas used: '107290'. Unclosed client session

The full trace is here: 
https://gist.github.com/taariq/ac1869ecd9ac273630b1eaad0e064a35

Our Wasm Message Handler in app.go is here. 
https://github.com/palomachain/paloma/blob/master/app/app.go#L627

We suspect that there were changes in v0.40.0-rc.0 that may require changes in the WasmMessage Handler app.go, but we are not sure. 

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

[Paloma v1.0.0-beta1](https://github.com/palomachain/paloma/releases/tag/v1.0.0-beta1)
[PIgeon v1.0.0-beta1](https://github.com/palomachain/pigeon/releases/tag/v1.0.0-beta1)

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

palomad tx wasm execute paloma1yyca08xqdgvjz0psg56z67ejh9xms6l436u8y58m82npdqqhmmtq0mr8tt '{"swap":{"swap_id":"0","amount_out_min":"199984287258530117","number_trades":"0"}}' --from paloma1jn0ntegqn998hg5v6kakcn55dc2u6gu68rgah9 --fees 100000ugrain

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

WASM executes the message transaction.

**Comment by taariq** [comment]
Via Alex from Confio: The contract emits a custom message type, which is handled by https://github.com/palomachain/paloma/blob/v1.0.0-beta1/app/app.go#L647 and mapped into "ExecuteJobWasmEvent" type.

**Comment by ToasterTheBrave** [comment]
Here are the steps to reproduce the error on the private testnet.  This assumes you are running on our `m1` host, as we've made some changes to the host settings and already uploaded and instantiated the contract in this testnet.  Full steps are documented elsewhere if we need to start fresh

#### Running with python script
```
python3 dca_bot_execute.py
```

#### Running with palomad cli
```
FROM_ADDRESS=$(palomad keys list | grep address | sed -E 's/.*address: (.+)$/\1/g')
LAST_WASM_CONTRACT=$(palomad q wasm list-contract-by-code 1 | grep "-" | tail -n 1 | sed 's/- //g')
palomad tx wasm execute $LAST_WASM_CONTRACT '{"swap":{"swap_id":"0","amount_out_min":"199984287258530117","number_trades":"0"}}' --from $FROM_ADDRESS --fees 100000ugrain --yes
```

**Comment by taariq** [comment]
Closing as this is now a known message decoding bug on the Paloma golang side to be fixed with https://github.com/VolumeFi/paloma/issues/169
