### ISSUE TITLE
bug: Curve healthy bot can't start with balance issue

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#1663]
Can't start Curve healthy bot for the insufficient balance issue, even though my balance is enough for the tx.
On metamast it says 0.12ETh is needed 
 
<img width="239" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/7f0a2303-9edf-45e9-9f07-deac83846b5a">

and the balance of the wallet:
<img width="239" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/0427fc65-79e7-4eb5-a847-d4e38214c7be">

and yet I can start a Curve leverage bot with even higher fees
<img width="248" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/5b339dad-9665-4608-9e15-f9ca75fcf660">

**Comment by jamie088** [comment]
@fieldtheory123 It is not an issue. In your screenshot,
 total ETH amount = payable amount + gas fee amount
so 0.06 + 0.126 = 0.186 ETH
But you have 0.17 ETH so got an insufficient balance issue.

**Comment by fieldtheory123** [comment]
healthy bot created successfully 
https://etherscan.io/tx/0x2b24162a5bdfa4347c7f5afd565c6d5287cd45bf5ff0ed0dcad0c0a3ffa38f63
