### ISSUE TITLE
[CHORE] update health_threshold for testing and check logs

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1664]
Update the health threshold for the following two bots and check the logs for errors

- [x] Curve leverage: 0xEC3c1940d88B8875b39b41e6D023026da500D4bB - update to 30%
- [x] Curve squeeze: 0x420BA68F74FAf559e702138093e044fDE77C172C - update to 15%

**Comment by verabehr** [comment]
<img width="719" alt="health_threshold" src="https://github.com/VolumeFi/paloma/assets/19958639/f792cfb7-52e6-460e-a2d1-6fb1651d5119">


Health threshold was not actually updated

**Comment by rootedbox** [comment]
Sorry.. I updated based off of contract not depositor.. should be fixed now.

```
sqlite> update deposits set health_threshold=1500 where depositor="0x420BA68F74FAf559e702138093e044fDE77C172C";
sqlite> update deposits set health_threshold=3000 where depositor="0xEC3c1940d88B8875b39b41e6D023026da500D4bB";
```
