### ISSUE TITLE
Curve limit order bot mybot page price issues

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#1665]
1. Current price is always the same as Entry price, seems like not updated
2. Deposit ratio was rounded up from 0.002677 to 0.003, which is too much. Need to keep more digits 

<img width="740" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/934fbfb1-09c6-457f-a1e0-8313d77dcdce">

**Comment by taariq** [comment]
Closing as won't ship.
