### ISSUE TITLE
CHORE: Create Test GRAIN ERC-20 Token Vyper Contract on Ethereum to act as Blueprint contract.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#167]
As a user, I want a GRAIN ERC20 blueprint contract to be created and deployed on Ethereum to test the bridge functionality for Paloma to track the GRAIN ERC20 token matched to the Paloma Comos token:

Rrequirements:
1. Create GRAIN ERC20 in Vyper
2. Create arguments for GRAIN token that matches Paloma Denom
3. Test Blueprint of Compass-EVM with GRAIN blueprint

**Comment by verabehr** [comment]
Testing is blocked as we're unable to get the transaction event data from the python sdk - [see discord conversation](https://discord.com/channels/987730379182051408/1098323494636372129/1107773242451693720)

**Comment by verabehr** [comment]
https://github.com/VolumeFi/Pancakeswap-pool-create-script
