### ISSUE TITLE
[BUG] Curve leverage lending - evm tx fails `execution reverted: repay fail`

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1673]
Curve leverage lending repay tx fails with `execution reverted: repay fail` error

This is the payload in HEX (I couldn't decode it using https://bia.is/tools/abi-decoder/ because of this error `Can't process the ABI / Input: BigNumber Error: new BigNumber() not a number:`) 
```
0xc60e14e2000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000ec3c1940d88b8875b39b41e6d023026da500d4bb00000000000000000000000000000000000000000000000000000000000000010000000000000000000000009be82cddb5c266e010c97e4b1b5b2df53c16384d00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007a1a86e45cbae0000000000000000000000000000000000000000000000006e0caa6320d9433e8e8cd35a5fa471732a01798cc99b29274d8dd832b0fac07e5e3342453c1cd816
```

**Comment by wc117** [comment]
You can use https://lab.miguelmota.com/ethereum-input-data-decoder/example for abi decode instead.
But I found backend used half amount of collateral so it is partial repayment. We should full repayment so we need to check backend script so that we do full repay instead. @verabehr

**Comment by verabehr** [comment]
Thanks @wc117
I checked the bot again (0xD694e9c66C353a72df4B6C03C24B997027cE2d26) and the backend only uses half because `deleverage_percentage` is 50%. So the backend should only partially repay the loan. If I understand you correctly this currently not possible? cc @fieldtheory123

**Comment by verabehr** [comment]
Closing in favor of https://github.com/VolumeFi/paloma/issues/1684
