### ISSUE TITLE
[BUG] curve-squeeze-leverage-bot: not working

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1682]
after https://github.com/VolumeFi/curve-squeeze-leverage-bot/pull/16 we now observe this error message:

```
Jun 11 14:30:52 bots-server start.sh[3034142]:     data: {
Jun 11 14:30:52 bots-server start.sh[3034142]:       code: 2,
Jun 11 14:30:52 bots-server start.sh[3034142]:       message: "failed to execute message; message index: 0: Error parsing into type curve_healthy_juice_bot_cw::msg::ExecuteMsg: invalid Uint256 '4582.5' - Generic error: Parsing u256: (bnum) attempt to parse integer from string containing invalid digit: execute wasm contract failed [!cosm!wasm/wasmd@v0.50.0/x/wasm/keeper/keeper.go:404] with gas used: '97156'"
```

**Comment by ranshaojiqing** [comment]
@wc117 can you confirm this is not a smart contract issue? looks like the number needs to get casted/`round`ed/`floor`ed

**Comment by wc117** [comment]
`Uint256` in rust CW requires string integer number just like "100000". So you need to floor it and convert into string type. @ranshaojiqing

**Comment by ranshaojiqing** [comment]
@wc117 i think i'm missing something. wouldn't we want to floor the data _before_ it's passed into `curve-squeeze-leverage`? i imagine there's smart contract code somewhere that's calling this?

**Comment by wc117** [comment]
Where did you get '4582.5'? If it is token amount, you need to multiply 10 ** decimals of token instead of floor. @ranshaojiqing

**Comment by verabehr** [comment]
Blocked as per @webelf101 there are some bugs in the smart contract that will be fixed first
