### ISSUE TITLE
[CHORE] Releases and versioning of compass

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1686]
As a paloma protocol engineer, I want to have tagged releases and versioning of compass, so that I can ensure that paloma is always talking to the correct (same) version of compass and can control what changes are included.

**Comment by verabehr** [comment]
@webelf101 Will you please run a build on the v1.1.0 tag and then attach bytecode and ABI to the release?

**Comment by webelf101** [comment]
https://github.com/palomachain/compass-evm/pull/33
