### ISSUE TITLE
[CHORE] Update Figma so that team is able to access correct and current designs.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1687]
@joycehermosilla we failed to launch Tailored today due to access to old designs. We want to resolve this issue with this ticket:

- [x] Update Figma so that all old designs are clearly marked as deprecated or unused
- [x] Create Figma tickets in github for @jamie088 for Tailored with links to the correct design and update links as needed
- [x] Ensure that all current design Figma links are clearly marked for all team members to access.

We lost an entire week due to this issue

**Comment by Cieloc** [comment]
@jamie088 I think I was able to invite you. https://www.figma.com/design/fO2IMDgKqgwO9kqlfmDN1s/Tailored?node-id=0-1&t=u1NIOCw1VG4rz8h5-1

This is what we were looking for:

![Landing Page (1)](https://github.com/VolumeFi/paloma/assets/19340497/8ee5a0c5-97ca-4353-ab42-710c0fc1542d)

**Comment by taariq** [comment]
Closing as shipped.
