### ISSUE TITLE
[BUG] WBTC Squeeze Bot Fails to show created bot on Mybots Page

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1691]
Bot created https://etherscan.io/tx/0xc3825d26add73aa948013a6c70e5d367076332235f34942cdf65bf951a21b1e0 does not show up on MyBots Page after contract upgrades. Most likely bot is missing from API.

**Comment by verabehr** [comment]
![Image](https://github.com/VolumeFi/paloma/assets/19958639/7ab22f9e-9ea0-45b5-8310-9d4db0228c1f)

This has been resolved
