### ISSUE TITLE
[DEVOPS] Upgrade the snapshot server to v1.15.1

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1692]

**Comment by verabehr** [comment]
This is the current statuts: 
Error in palomad: ```panic: can't get node [0 0 0 0 0 254 205 145 0 0 0 22]: open /home/rootedbox/.paloma/data/application.db/2863977.ldb: too many open files```
https://github.com/cosmos/iavl/blob/master/nodedb.go#L147


palomad version: v1.13.4
Height: 16708672

Tested updating `DefaultLimitNOFILE` in `/etc/systemd/system.conf` to from nothing to 65536 and 1024:524288. Neither resulted in a change

**Comment by verabehr** [comment]
next step: sync from snapshot to get this back up and running

**Comment by taariq** [comment]
Fixed.
