### ISSUE TITLE
Tailored Backend: Email Loading & Processing

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#1696]
As a user, I want to see a loading spinner until the backend processes my emails with the LLM so that I know the system is working on my request.

https://www.notion.so/volumefi/EPIC-06-13-24-Tailored-Email-Calendar-MVP-Backend-658ff555bd0e4250bc345b0c1b769852?pvs=4#de2979566f044dec89d66325706701bb

**Comment by ranshaojiqing** [comment]
this is not a backend ticket, this is a frontend ticket

**Comment by Cieloc** [comment]
@ranshaojiqing I'm intending this ticket to capture the backend service that processes emails via LLM and tells the frontend to show a spinner. I've retitled to "Email Loading & Processing"
