### ISSUE TITLE
Tailored Backend: Display Processed Email Outputs & Process User Actions

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#1698]
As a user, I want to see the processed email outputs so that I can review the summaries and suggested responses.

https://www.notion.so/volumefi/EPIC-06-13-24-Tailored-Email-Calendar-MVP-Backend-658ff555bd0e4250bc345b0c1b769852?pvs=4#2ae1dc6eda854d04a1011826fd5bc613

**Comment by ranshaojiqing** [comment]
@Cieloc would you like me to use an LLM to determine if email action should be taken, or something else?
