### ISSUE TITLE
Tailored UI:  Sign In/ Log in.

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#1700]
- [ ] The user will arrive at the Landing Page and press the CTA "Get Started"

![Image](https://github.com/VolumeFi/paloma/assets/22323189/6fceb6e3-63b0-4ea3-a307-ca4ed04b9e93)

- [ ] The user will be redirected to the Log in flow.
https://www.figma.com/design/fO2IMDgKqgwO9kqlfmDN1s/Tailored?node-id=1128-1902&t=OeF3HUl7zxUoc4J5-4

- [ ] From the Log in Flow the user can go to Sign in flow.
https://www.figma.com/design/fO2IMDgKqgwO9kqlfmDN1s/Tailored?node-id=1226-5064&t=OeF3HUl7zxUoc4J5-4

- [ ]  In both cases (Log in or Sign In) the user will confirm their Email with Magic Link.

**Comment by joycehermosilla** [comment]
@taariq Thank you, fixed.

**Comment by taariq** [comment]
Completed.
