### ISSUE TITLE
Debug contract deployment of compass v1.1.0 on paloma 1.15.0

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1706]

**Comment by maharifu** [comment]
@taariq Just needed to double check target addresses. I'll close this ticket now.

I started the local testnet clean and added chain support manually. I was able to deploy compass 1.1.0 into gnosis, arbitrum and base and confirm it's alright, so I don't think there's an issue deploying compass.

I believe the issue we were seeing last Friday was unrelated to compass, we were just unable to reach consensus on the testnet, which is something I'll look into further down the line.
