### ISSUE TITLE
Volumefi page Feedback

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#171]
Missing links

- [x] `Community` (top right) https://discord.gg/Ebh6YjMShu
- [x] `Paloma Swap` (footer) https://www.palomaswap.com/
- [x] `Paloma Bot` (footer) https://www.palomabot.ai/
- [x] `Carrers` (footer) https://volume.finance/careers/

Add page

- [x] add the old careers page https://volume.finance/careers/  back. Use the exact same design as before the switch to the new site

Social Media tab Footer has incorrect items. It should only have these:

- [x] Discord https://discord.gg/Ebh6YjMShu
- [x] Twitter https://twitter.com/volumefi
- [x] LinkedIn https://www.linkedin.com/company/volumefi/

Remove from footer

- [x] brand assets

**Comment by wdev733** [comment]
@verabehr `Discord` (top right) means Community ?

**Comment by verabehr** [comment]
Yes, It does, updating 😄
