### ISSUE TITLE
[Pigeon Feed] As a user, I want Pigeon to set a daily Bridge Limit for token transfers across the bridge to the target EVM chain

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1711]
As a user, I want Pigeon to set a daily Bridge Limit for token transfers across the bridge to the target EVM chai.

**Acceptance Criteria**
1. https://www.notion.so/volumefi/EPIC-06-21-2024-Paloma-Bridge-Token-Transfer-Limits-in-Governance-abfdc78d40a84b6387f5d3e8a6e027c6 as the EPIC. May require additional stories.

**Comment by maharifu** [comment]
Should we update the transfer counters as the transfer is accepted into the queue, or only after it's confirmed as successful?

If we update them only after successful confirmation we may get a burst of transfers that all get queued and might go over the defined limit. However, if we update them when accepting the transfer, we will be counting unsuccessful and canceled transfers.

For now, I'm assuming we want to update the counters when accepting the transfer as it's safer.
