### ISSUE TITLE
Tailored Points on Discord: Joining

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#1720]
**User Story**:
As a user, I want to earn points by joining Discord.

**Acceptance Criteria**:

1. User navigates to the web application and sees an option to “Join the Community” their Discord account.
2. User joins Discord and is directed to the Tailored channel.
3. Upon joining the channel for the first time, a bot welcomes the user and lets them know how many points they have earned from joining (1000 points).

**Comment by taariq** [comment]
@Cieloc convert this into discrete stories.
