### ISSUE TITLE
bug: can't create a llamalend bot on arbitrum

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#1721]
Couldn't start bot, Fetching Prices takes forever. Deposit price doesn't show

<img width="719" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/056d7b42-3ae3-4cca-9a60-f094b5de57bd">

**Comment by verabehr** [comment]
This is an API error https://one.palomachain.com/swap?fromTokenAddress=0xf939e0a03fb07f59a73314e73794be0e57ac1b4e&toTokenAddress=0x9D39A5DE30e57443BfF2A8307A4256c8797A3497&amount=200260119350986940638&fromAddress=&slippage=1&disableEstimate=true&chain=42161 

@jamie088 will you confirm if that is the only issue with arbitrum?

**Comment by taariq** [comment]
Fixed.
