### ISSUE TITLE
[llamalend] Reduce the Struggle to know which chain I am on for llmalaend leverage

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1724]
As a user, I want to see the chain that I am on even for ETH-only markets as I may be on ARB chain and attempting to use an ETH only market. Please see the vidoeo recording here: https://www.loom.com/share/3cf81d6fa1ef4e6eb8e67b34f2e13124?sid=fe6b38a5-c2fe-4ccc-9d87-45b2158f27d1

![Image](https://github.com/VolumeFi/paloma/assets/701864/dad4f3fd-e617-473d-bef1-33a3598f337c)

**Comment by jamie088** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/454
