### ISSUE TITLE
[BUG]: stats api is not showing sUSDe bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1730]
sUSDE llamalend bot was created, but it doesn't show in the stats API

https://service.palomabot.ai/stats

<img width="1389" alt="Screen Shot 2024-06-18 at 8 41 27 PM" src="https://github.com/VolumeFi/paloma/assets/19958639/713d732a-ae95-4f7c-8079-77c56a501147">

Repo: https://github.com/VolumeFi/bot-info-api

**Comment by taariq** [comment]
Closing as no longer needed.
