### ISSUE TITLE
Update LLAMALEND bot for new deposits

### ISSUE THREAD

**Issue by wc117** [VolumeFi/paloma#1734]
# Background

Currently when a user who already has a bot create a new bot, it emits new deposit_id so it looks like a new bot even though his bot is single and not deployed again.
And during the TWAP, the user can deposit again with the same collateral and it causes new bot but it actually goes to old bot.

# Done when

- [ ] Prevent new bot during TWAP.
- [ ] Merge existing bots and new bots if they have the same address.
- [ ] Add calculation for merging bots.

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/paloma/issues/1734

from @webelf101 
> We updated the backend script so that we don't need to update Vyper or CW.
