### ISSUE TITLE
Launch CVX lending and leverage pool on LLAMALEND Ethereum

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#1739]
Launch CVX lending and leverage pool on LLAMALEND Ethereum

Run LLAMALEND contracts to add the following:
- [ ] CVX collateral ; crvUSD borrow; no leverage 
- [ ] crvUSD collateral ; CVX borrow; no leverage
- [ ]  CVX collateral ; crvUSD borrow; max leverage 10

Please document any questions / open items / blockers below.

**Comment by taariq** [comment]
Closing as needs liquidity. Wont' fix.
