### ISSUE TITLE
[llamalend]: add pufETH llamalend squeeze bot info to the backend script

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1742]
address: { '1': '0xd9a442856c234a39a81a089c06451ebaa4306a72' },
controller: { '1': '0x4f87158350c296955966059c50263f711ce0817c' },
controllerId: {  '1': 10 },

**Comment by webelf101** [comment]
https://github.com/VolumeFi/llamalend-leverage-lending-bot/pull/31
