### ISSUE TITLE
CRV price prediction for llamalend bot (arbitrum) backend script

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1746]
https://github.com/VolumeFi/price-prediction | current server location `~/app/pp-bots/crv`

TODO
- [ ] update ABI with the latest correct ABI
- [ ] add new smart contract functions that are currently missing in the script
- [ ] update remaining smart contract interfaces
- [ ] test end to end when smart contract and FE is available

**Comment by verabehr** [comment]
@fullstack412 Will you confirm that my understanding of what needs to be done is correct: 

- [ ] update ABI with the latest correct ABI
- [ ] update remaining smart contract interfaces
- [ ] test end to end when smart contract and FE is available

**Comment by fullstack412** [comment]
1. yes
2. yes
3. before step 3, i need to update some functions in backend script because the smart contract has new functions but the current backend script doesn't have that logic.
4. after step 3, yes

**Comment by fullstack412** [comment]
@verabehr

**Comment by verabehr** [comment]
Thanks, updated the description accordingly

**Comment by verabehr** [comment]
https://github.com/VolumeFi/llamalend-crv-prediction-bot
