### ISSUE TITLE
Tailored MLM invites: Multi-Level Invite Points

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#1748]
2. **Multi-Level Invite Points**
    - **User Story:** As a user, I want to earn points for  invites made by my direct invitees.
    - **Acceptance Criteria:**
        - Direct invitees invite additional members.
        - Points are awarded based on the level of the invite:
            - Second-level: 10 points
        - Bot tracks and announces points for each level.
        - Points award amount should be configurable as we may do "limited time" boost promotions.
https://www.notion.so/volumefi/EPIC-06-20-24-Tailored-Multi-Level-Marketing-MLM-Plan-885e7b089d824f5db5456df1ddfd6695?pvs=4#21a7db9279fd4e0abb2d80f418e1a502

**Comment by taariq** [comment]
Closing as wont' ship
