### ISSUE TITLE
[BUG] Users bot Shows up in Active Bot list but appears to be repaid. What happened?

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1753]
User sends attached position in active bots, but had a repay transaction. Is the API incorrect?

![Image](https://github.com/VolumeFi/paloma/assets/701864/0405fc84-335d-4d58-988f-faa8014bd9f8)

Did user bot repay?  
Repay Transaction: https://etherscan.io/tx/0xa8e2733e4f55f6084610152e579caec6e970a4a3d5bd22c29bbfffc6aed13e5e

**Comment by taariq** [comment]
I was able to repro:

Repay bot: https://arbiscan.io/tx/0xabfd0482aa93651f01ef80217ae7493b9366ea3c53f4b162473565e6f025fda1

Bot still in Bot list: 


![Image](https://github.com/VolumeFi/paloma/assets/701864/45ee7cf1-70ef-4e77-9ac4-a77e65b7ee2b)

**Comment by verabehr** [comment]
this is the same issue as https://github.com/VolumeFi/paloma/issues/1780



![Image](https://github.com/VolumeFi/paloma/assets/19958639/577c451f-ebec-4fc6-b479-eeb2074bcbb3)
