### ISSUE TITLE
[BUG] Attempting to stop Llamalend Bot Fails: 400 Bad Request

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1754]
Attempting to stop bot fails: 
BOT: https://arbiscan.io/tx/0xd1fb6753baf78a9715bc07240f8b99986cfe0c60dda649f0f63a22e344459a47        
       
Error 400 Bad Request: GET https://one.palomachain.com/swap?fromTokenAddress=0x82aF49447D8a07e3bd95BD0d56f35241523fBab1&toTokenAddress=0xf939e0a03fb07f59a73314e73794be0e57ac1b4e&amount=895456213687157874&fromAddress=0x14D9B77DA2857aFAfFC44dEAe0652Ec02562eAdd&slippage=1&disableEstimate=true&chain=42161 400 (Bad Request)

**Comment by jamie088** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/459
