### ISSUE TITLE
[BUG] Llamalend CRV Squeeze Bot shows Total Ethereum Gas of $0.00

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1755]
Gas of $0.00?? on ETH?

![Image](https://github.com/VolumeFi/paloma/assets/701864/093d7e65-74e7-4977-a9c9-0e0e2a96e626)

**Comment by jamie088** [comment]
@taariq Could you please check again? I can't reproduce this problem.

**Comment by verabehr** [comment]
I cannot reproduce either - closing
