### ISSUE TITLE
Audit the Cosmwasm DCA and Limit Order Bots for Production Release

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#176]
As a user, I want to see that the Cosmwasm Limit Order Bots from Volume have been audited by Rust expert to ensure that they will be ready for production deployment and use of user funds.

- https://github.com/VolumeFi/dca-bot-pancakeswap-cosmwasm/pull/1
- https://github.com/VolumeFi/limit-order-bot-uni-v2-cosmwasm/pull/1
- https://github.com/VolumeFi/limit-order-bot-uni-v3-cosmwasm/pull/1

**Comment by measure-fi** [comment]
Audits complete, linked above. In @wc117's court now.

As a meta-audit, I would like to know how much code @wc117 thinks these bots can share. They look _awfully_ similar at present.

**Comment by taariq** [comment]
Thanks! @wc117 will you confirm on the question. Closing this as completed.
