### ISSUE TITLE
VoteDistribution Coswmasm Bot for Curve.fi

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#177]
As a Paloma user, I want to be able to use a Vote Distribution Bot cosmwasm contract that will allocate my votes from an offchain calculation to maximize my APR on Curve.fi gauges.

**Requirements**
1. As a user, I want cw contracts that can query, calculate and execute a simple voting strategy
  - ~CW contracts that can query StakeDAO’s gauge contracts and see how much votes and reward APR each gauge has~
  - ~a function to determine which gauge has the highest APR~
  - Discussed, paloma does not have the ability to query ethereum.
        
2. As a user, I want cw contracts to remote control the functions described in the above EVM story
- [ ] CW contracts that can execute the EVM contract functions described in https://github.com/VolumeFi/paloma/issues/210

**Comment by fieldtheory123** [comment]
@measure-fi I updated the user stories. Let me know if you have questions. The second task is dependent on another ticket.
