### ISSUE TITLE
[BUG] Old Bots Showing Bots that are fully repaid and no longer active

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1773]
[BUG] Old Bots Showing Bots that are fully repaid and no longer active. Fully Repaid Bots need to be in **Close Bots**

![Image](https://github.com/VolumeFi/paloma/assets/701864/75f3ee28-aefd-4e5a-8e29-3bde4c46842d)

**Comment by jamie088** [comment]
@taariq @verabehr It is also an API issue.

**Comment by verabehr** [comment]
no longer reproducible. This may be related to stopping/starting the service and the backend updates

**Comment by verabehr** [comment]
this is still reproducible

**Comment by verabehr** [comment]
this is a missing feature - ticket: https://github.com/VolumeFi/paloma/issues/1780
