### ISSUE TITLE
Add 2 parameters in LLAMALEND bot creation

### ISSUE THREAD

**Issue by wc117** [VolumeFi/paloma#1778]
## Description

I added a delegate parameter for price prediction bot. Also I added a controller index so that we can use different controller of the same collateral. We need to update frontend for the update.

Changed Vyper function is as follows.

https://github.com/VolumeFi/curve-llamalend-leverage-bot-vyper/blob/6829c853909295f1b5bfd6b443b4a72baabe5bae/contracts/factory.vy#L192

**Comment by jamie088** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/464
