### ISSUE TITLE
Message vault

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#1783]
At the moment, investigating messages is incredibly tedious due to the high volatility in storage. We will need a better way to investigate messages after they've been removed from the consensus queue.

Theoretically, we can simply move them from the queue on to a different store that contains the last `n` messages, can simply be queried by message ID, and automatically rolls over.

However, there's no reason to bloat persistence with stale messages. Instead, I suggest a full log of the entire message structure (including signatures, evidence, etc...) at the time of its removal from the queue. That way we gain the insight needed from log files. The biggest challenge here will be generating readable log formatting that avoids raw byte or pointer representation. But should still be less work than the store approach.

**Comment by verabehr** [comment]
estimate ~ 1hour
