### ISSUE TITLE
Tailored Twitter: User Signup

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#1786]
**As a new user, I want to sign up with my email and password, so I can access the Tailored Twitter Tweeter features.**

- **Acceptance Criteria:**
    - User can enter an email and password.
    - User confirms ownership of the email with a magic link.
    - User has the option to join the community Discord.
 
https://www.notion.so/volumefi/EPIC-06-22-24-Tailored-Twitter-Tweeter-6ebf00473b8047e19710b729ec24c33c?pvs=4#ec373b11bf3c45b6888ab3182b5b6f9a

**Comment by maharifu** [comment]
We dropped the password requirement. Users signup only with email and login with a magic link.

From the backend perspective, we need to:
- [ ] Create database structure
  - [ ] Include users and magic links tables
- [ ] Create the register/signin API endpoint
  - Accepts an email, creates a new user if necessary, sends the magic link
- [ ] Create the login endpoint
  - Verifies the magic link, returns a session token (jwt)
- [ ] Create an endpoint to change user settings, to keep track if user has joined community Discord
