### ISSUE TITLE
Tailored Twitter: Select Target Public Profiles

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#1788]
### Select Target Public Profiles

**As a user, I want to select a target public profile to mimic their tweet style, so my generated tweets can reflect the tone and engagement of top influencers.**

- **Acceptance Criteria:**
    - User can search and select target public profiles.
    - System can access the last 50 tweets from the selected profiles for style analysis.

https://www.notion.so/volumefi/EPIC-06-22-24-Tailored-Twitter-Tweeter-6ebf00473b8047e19710b729ec24c33c?pvs=4#32d8d8dec3a54b4e9e2e148b319f908f

**Comment by maharifu** [comment]
As backend requirements, this will address:
- [ ] querying the twitter API for up to 50 tweets of target subject matter
- [ ] querying the twitter API for up to 50 tweets of styling and tone profile
- [ ] update the user settings with the last selected profiles

We won't save the tweets as we don't need them in the database. We will query them at the time of generating new tweets. We may decide to cache them for awhile in the future so we can generate tweets at multiple points in time from the same context.
