### ISSUE TITLE
Tailored Tweet Generation

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#1790]
### Automated Tweet Generation

**As a user, I want the system to generate tweets for me, so I can maintain an active and engaging Twitter presence with minimal effort.**

- **Acceptance Criteria:**
    - System generates up to 5 tweets per day for free (more with payment).
    - Tweets are generated based on selected topics, target profiles, and filters.
    - Tweets can mimic the style of the chosen public profiles using DeepInfra LLama3.
    - User can approve, edit, or reject tweets before posting.
    - System constructs a link for users to post tweets directly on Twitter.

https://www.notion.so/volumefi/EPIC-06-22-24-Tailored-Twitter-Tweeter-6ebf00473b8047e19710b729ec24c33c?pvs=4#496b3614164a422dbd1b580be44501b9

**Comment by taariq** [comment]
@maharifu @Cieloc is this done?

**Comment by taariq** [comment]
Thank you @maharifu
