### ISSUE TITLE
[BUG] Bigint calculation error prevents offramp twaps to go through

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1798]
We can add very small xDAI to the bot contract.
We can move into JavaScript.
Third option is using some library to manage bigint correctly.
Python division doesn't work exactly in very small digits. The reason of error is that.

More details on the discussion here https://discord.com/channels/987730379182051408/1065140873811218532/1256271650530529331

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/offramp-eure-bot-script/pull/30
