### ISSUE TITLE
Remove FCD newrelic alerts

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#18]
# Background

_Describe the problem that we are trying to solve with this feature._
_If a path to a solution is known, feel free to write it down, but have an open mind_

We don't need these

# Done when

- [x] We're no longer getting any alerts from the FCD server in newrelic https://onenr.io/0vwBL3qa8jp

**Comment by rootedbox** [comment]
disabled logging in config file
```
ubuntu@localhost:~/app/fcd$ cat .envrc
export SERVER_PORT=3060
export CHAIN_ID=paloma-testnet-15
export LCD_URI=https://lcd.testnet.palomaswap.com
export FCD_URI=https://fcd.testnet.palomaswap.com
export RPC_URI=https://testnet.palomaswap.com
export SENTRY_DSN=
export USE_LOG_FILE=false
```
