### ISSUE TITLE
Rename gravity2 and change single chain references to multichain

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1801]
As a Paloma user, I want the "gravity2" module to have a name that better represents it's functionality (it was heavily modified from the original gravity source) and I want the (cli) documentation to make clear that it is multichain instead of just for ETH. 

Done when
- [ ] rename gravity2 module to XXX

cli commands that reference ETH only  are updated:
- [ ] `palomad q gravity2 last-observed-eth-block`
- [ ]  `palomad q gravity2 last-observed-eth-nonce`
- [ ] `palomad q gravity2 pending-send-to-eth`
- [ ] `palomad tx gravity2 cancel-send-to-eth`
- [ ] `palomad tx gravity2 send-to-eth`

**Comment by byte-bandit** [comment]
Any good idea for the new name? The most really good ideas are obviously already connected to big projects (gravity/wormhole/nexus/etc...). One I thought of that's not quite broadly used yet is `flux`. Or take inspiration from real world and call it `skyway`.

  We can also be blunt and just call it `bridge`, but it's kinda boring.

**Comment by byte-bandit** [comment]
Old commands:

```sh
palomad q gravity2 last-observed-eth-block [chain-id]
palomad q gravity2 last-observed-eth-nonce [chain-id]
palomad q gravity2 pending-send-to-eth
palomad tx gravity2 cancel-send-to-eth
palomad tx gravity2 send-to-eth
```

New commands:

```sh
palomad q skyway last-observed-block [chain-id]
palomad q skyway last-observed-nonce [chain-id]
palomad q skyway pending-outgoing-txs [chain-id]
palomad tx skyway cancel-outgoing-tx [chain-id]
palomad tx skyway send-tx [chain-id]
```
