### ISSUE TITLE
Backend API for signup pages

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#181]
### Background
The new volume website has a whitelist, so we need to store the information of anyone who signs up. 

```
POST /API_ENDPOINT

body {
   firstName: '',
   lastName: '',
   companyName: '',
   email: '',
   jobTitle: '',
   businessSector: '',
   hearAbout: '',
}
```
### Deployment
- [ ] Can we change the API base url to `service.volume.finance` or `api.volume.finance` ?
- [ ] Update `.env`
```
NODE_ENV=production
BASE_URL=https://user.volume.finance
```

### Done when

- [x] Backend API code is pushed here https://github.com/VolumeFi/volume-api
- [x] FE uses the API
- [x] API is deployed on a volume server

**Comment by verabehr** [comment]
https://github.com/VolumeFi/volumefi-website/pull/31

**Comment by rootedbox** [comment]
https://user.volume.finance @wdev733 @verabehr

**Comment by wdev733** [comment]
@rootedbox @verabehr 
Added origin urls for production in this [PR](https://github.com/VolumeFi/volume-api/pull/2)
We need to update the `.env` and deploy the api again.

```
NODE_ENV=production
BASE_URL=https://user.volume.finance
```

**Comment by rootedbox** [comment]
updated  env and restarted
