### ISSUE TITLE
[CHORE] Deploy ERC20 blueprint contract on Arbitrum and Blast

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1813]
We're currently missing the ERC-20 blueprint contract on Arbitrum and Blast

Done when
Blueprint contract is deployed on

- [x] arbitrum main
- [x] blast main

**Comment by taariq** [comment]
@verabehr is this required for all tokens? This is very manual.

**Comment by verabehr** [comment]
This ticket is for the blueprint contract @taariq. It is a one time deploy. Tokens cannot be created on these two chains until the blueprint contract was deployed on those chains.
