### ISSUE TITLE
[GAMING] As a user, I want to pay a $5.00 gas fee for all gaming bots on ARB

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1814]
As a user, I want to pay a $5.00 gas fee for the price prediction bot on Arbitrum.
Use the following address for the collection of the gas fee: `0x26075E00a66415398bdD773DF080DAdd6f26C18F`

**Acceptance Criteria**
1. Charge $5.00 gas fee to start the bot
2. Charge $5.00 gas fee to the winner to start the llamalend bot.

**Comment by taariq** [comment]
We will charge the gas fee like we do for all our other trading bots. However, this gas fee will toward the address updated in the ticket.

**Comment by taariq** [comment]
@fullstack412 Yes. You will need to redeploy the bots.

**Comment by taariq** [comment]
@fullstack412 we will charge the fee as gas when users start the bot

**Comment by fullstack412** [comment]
@taariq I just checked prediction bot contract again. we can use current contract for the gas fee logic. that gas fee will be charged in llamalend bot contract directly and on my side, i only forward the parameter to the llamalend bot contract.
I will redeploy the prediction bot contract once James finish the testing.
