### ISSUE TITLE
My bots API for price prediction bots

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1817]
Repo for other bots for both stats on landing page and bot details on mybots page https://github.com/VolumeFi/bot-info-api

- [ ] Mybots api
 There are 2 bots like Current active bot info and previous days bot
      {
          bot: 'CRV_price_prediction' , 'ETH_price_prediction', 'BTC_price_prediction'
          dex_name: 'curve',
          epoch_id,
          competition_start,
          competition_end,
          coin_info,
          coin_info1,
          coin_info2,
          prediction_price,
          current_price,
          network_name: 'ARBITRUM',
          chainId: '42161',
          old: '0',
          contract: prediction bot contract Address,
          token: token contract address,
          denominator: eth-> 100, btc-> 1, crv->10**6,
          fixed: eth, btc->0, crv->3,
      }
- [ ] stats api
    - [ ] number of bots
    - [ ] total winnings

**Comment by taariq** [comment]
We will pause on this for now.
