### ISSUE TITLE
[BUG] Prediction Mybots page is unclear

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1818]
As a user I do not understand what happened to my Prediction bot result.
1. How much did I win?
2. Why am I seeing the current price and not the final price?
3. Where is my price prediction gone?
4. Why is **Total Rewards** not a number, but a sentence **Previous Game finished at $0.272** Did I win or not?
5. What is **Status** for? This column is unhelpful.

Just tell me if I won or if I didn't win and what was my bet and the actual closing price. Also, give me a link to play again so I can try again!

![image](https://github.com/VolumeFi/paloma/assets/701864/f4b570b2-6fd8-44a2-8575-c462aede991f)

**Comment by taariq** [comment]
@jamie088 it appears we have bugs that don't match the UI designs in https://github.com/VolumeFi/paloma/issues/1423. removing @joycehermosilla from the ticket.

**Comment by jamie088** [comment]
@taariq Sorry, I forgot to tell you about the new PR. https://github.com/VolumeFi/palomabot/pull/469

**Comment by taariq** [comment]
Closing as fixed. New bug.
