### ISSUE TITLE
Account Signup and Community Join

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#1819]
**As a** new user,

**I want** to sign up using my email and confirm it through a magic link,

**So that** I can access the Tailored Twitter Tweeter feature and optionally join the community on Discord.

*Acceptance Criteria:*

- User can sign up with an email.
- User receives a magic link to confirm email.
- User can confirm email and proceed to join Discord optionally.

https://www.notion.so/volumefi/EPIC-06-22-24-Tailored-Twitter-Tweeter-V002-4784202cc6da4485aaa038f4dfa0091e?pvs=4#622ac247297b48ea95c31e6d237a9253

https://www.figma.com/design/fO2IMDgKqgwO9kqlfmDN1s/Tailored?node-id=1128-1902&m=dev

**Comment by jamie088** [comment]
@joycehermosilla Please share the design link.

**Comment by taariq** [comment]
Closed!
