### ISSUE TITLE
Select Target Twitter Profiles for Tweet Generation

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#1820]
**As a** user,

**I want** to select a target public Twitter profile for subject matter,

**So that** Tailored can source tweets to use as primary points of reference for generating new tweets.

**I want** to select a target public Twitter profile for style and tone,

**So that** Tailored can mimic the writing style of the selected profile when generating tweets.

*Acceptance Criteria:*

- User can search for and select a target Twitter profiles.
- System retrieves tweets (excludes retweets) from the selected profiles.
- System stores selected profile for tweet generation reference.

https://www.notion.so/volumefi/EPIC-06-22-24-Tailored-Twitter-Tweeter-V002-4784202cc6da4485aaa038f4dfa0091e?pvs=4#7b06f19b40bc428aafe430d14807b854

**Comment by taariq** [comment]
Finished with https://github.com/VolumeFi/tailored-ui/pull/15
