### ISSUE TITLE
Automated Tweet Generation

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#1821]
**As a** user,

**I want** Tailored to generate tweets based on selected target profiles and my preferences,

**So that** I can review, edit, or discard them before posting.

*Acceptance Criteria:*

- System generates tweets using the subject matter and style of selected profiles.
- User receives generated tweets for review.
- User can edit, approve, or reject generated tweets.
- Approved tweets are composed into a link for direct posting on Twitter.
- Only 3 (sets of 4) generations are permitted per user per day.
- VIP users can be allowed extra generations.

https://www.notion.so/volumefi/EPIC-06-22-24-Tailored-Twitter-Tweeter-V002-4784202cc6da4485aaa038f4dfa0091e?pvs=4#545451988fe746f8afaecc8fb22628b6

**Comment by taariq** [comment]
Finished with Finished with https://github.com/VolumeFi/tailored-ui/pull/15
