### ISSUE TITLE
Earning Points

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#1822]
**As a** user,

**I want** to earn points by posting tweets,

**So that** I can gain rewards and recognition within the platform.

*Acceptance Criteria:*

- User earns points for the first post of the day
- User earns a multiplier on special boost days.
- System tracks and updates user points based on activities.
https://www.notion.so/volumefi/EPIC-06-22-24-Tailored-Twitter-Tweeter-V002-4784202cc6da4485aaa038f4dfa0091e?pvs=4#dc6410ebb58f4745a59357bbc2def659

**Comment by maharifu** [comment]
Implemented in https://github.com/VolumeFi/tailored-twitter-tweeter-backend/pull/4
