### ISSUE TITLE
[BUG] Failure Stopping ETH lamalend Leverage bot "Invalid callbacker address"

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1825]
Unable to close leverage bot. Receive the error: Invalid callbacker address

Error: call revert exception; VM Exception while processing transaction: reverted with reason string "Multicall3: call failed" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="aggregate((address,bytes)[])", data="0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000174d756c746963616c6c333a2063616c6c206661696c6564000000000000000000", errorArgs=["Multicall3: call failed"], errorName="Error", errorSignature="Error(string)", reason="Multicall3: call failed", code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.makeError (_app-712aca752b4de1db.js:1:204760)
    at Logger.throwError (_app-712aca752b4de1db.js:1:204879)
    at Interface.decodeFunctionResult (_app-712aca752b4de1db.js:1:57357)
    at Contract.<anonymous> (_app-712aca752b4de1db.js:1:98407)
    at Generator.next (<anonymous>)
    at fulfilled (_app-712aca752b4de1db.js:1:93664)

**Comment by jamie088** [comment]
@taariq Where is the ETH llamalend bot? We don't have an ETH llamalend leverage bot. Please recheck it.

**Comment by verabehr** [comment]
We're missing self liquidation feature - tracked here https://github.com/VolumeFi/paloma/issues/1854
