### ISSUE TITLE
[PREDICTION] Prediction bot way to play and rules are not clear no anywhere on the UI

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1828]
Problems with the UI[

- [x] 1. Change the title to: "Predict CRV PRICE TO Within $0.001. Unlimited Free Plays" 
- [x] 2. Add Arbitrum logo next to the token <img width="556" alt="Captura de pantalla 2024-07-04 a las 15 24 26" src="https://github.com/VolumeFi/paloma/assets/22323189/2d07680c-1748-4c06-bb88-157298512800">
- [x] 3. Add Today's Game Pot tokens
- [x] 5. Add a one-time anti-spam fee 
<img width="532" alt="Captura de pantalla 2024-07-04 a las 15 25 19" src="https://github.com/VolumeFi/paloma/assets/22323189/96cf83b6-3d13-48d1-b4d9-58dd17b6e087">

- [x] 6. Add Play conditions

- [x] Designs here: (https://www.figma.com/design/6DYR6QFkucGd1bsOILr7V0/Paloma-Bot?node-id=3271-647081&t=HVfQ9TEwahCHh7OQ-4)

**Comment by joycehermosilla** [comment]
- [ ] @jamie088 @taariq Let's change the text from 18px to 24px. 
<img width="394" alt="Captura de pantalla 2024-07-04 a las 10 34 58" src="https://github.com/VolumeFi/paloma/assets/22323189/e261aabc-73d9-42d7-bd94-31f28cebed0c">

- [ ] Text change to: "to predict the Curve DAO (CRV) price to within $0.001. Start playing for free now!"

Figma here: https://www.figma.com/design/6DYR6QFkucGd1bsOILr7V0/Paloma-Bot?node-id=3271-647081&t=XRqCATSZridwfHKj-4

**Comment by taariq** [comment]
Closing as fixed.
