### ISSUE TITLE
[GAMING] As a user, I want to pay the anti-spam fee to play the Prediction Bot Game and a bot with specific start and end times

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1829]
As a user of the Prediction Bot, I want to be able to pay an anti-spam fee so that I know that others can't cheat by taking advantage of very low gas to enter hundreds of time into the prediction bot game.

**Acceptance Criteria**
1. create an anti-spam fee for each prediction game bot
2. allow the anti-spam fee to be changeable and set it to 0.002 ETH.
3. the anti-spam is required once per address per game
4. add UI below the start button to show **Anti-SPAM fee of 0.002 ETH required for fair play** The fee must be clear and readable
5. add one more function to the smart contract for adding new epoch with specific start and end time as needed.

**Comment by fullstack412** [comment]
@taariq spam fee collect address => 0x26075E00a66415398bdD773DF080DAdd6f26C18F
is this address correct?

**Comment by taariq** [comment]
@fullstack412 that is correct.

**Comment by taariq** [comment]
Closing as fixed.
