### ISSUE TITLE
CHORE: manually insert nest register transaction

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#183]
### Background
The user must have closed their browser window before the nest register api was called to register their tokenback.

### Done when
 
- [x] this transaction is registered through the API: [BSCAN - 0x3830e025fe44d4111101c98568a12599aa801d160811c9db996514c83e95e797](https://bscscan.com/tx/0x3830e025fe44d4111101c98568a12599aa801d160811c9db996514c83e95e797), [MIXPANEL](https://mixpanel.com/project/2744781/view/3280621/app/events#fXrjGMR5s6KN)

**Comment by rootedbox** [comment]
done
