### ISSUE TITLE
Price Prediction Bots: Add Bidders number + change font size

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1833]
- [ ]  Designs: https://www.figma.com/design/6DYR6QFkucGd1bsOILr7V0/Paloma-Bot?node-id=3271-647081&t=0438gyyRs3HQKM0t-4 
- [ ] Add arrow up or down in Buttons Higher and Lower.
![Image](https://github.com/VolumeFi/paloma/assets/22323189/9a9eb38f-5a6a-4c20-9e93-6bb31ef4cebe)

- [ ] Change the price input area to editable. 
![Image](https://github.com/VolumeFi/paloma/assets/22323189/bab51893-24b4-41ee-9f7a-d5dacf7fbb82)

**Comment by taariq** [comment]
This is complete.
