### ISSUE TITLE
[PF] 🚧 Ensure SLC message senders are not abused for system calls

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#1834]
There multiple points in the Paloma source code where the sender of an SLC is set. Sometimes, when the message is triggered by consensus, Paloma sets the sender to some arbitrary value or to a random relayer.

With Pigeon feed, the message sender will have to cover the funds for sending the message. 

a) Either create a "volume" wallet that we can send these messages from
b) Examine these cases in question and extract the messages into their own type, so they don't fall into SLC fee structures and will instead be an infrastructure message like `update_valset`. Better, but **will require compass update**

**Comment by maharifu** [comment]
@byte-bandit 
I think option b would be cleaner, but, on top of the compass changes, we would need more extensive changes, for instance on just in time valset updates, which would now have to be triggered for two message types. There may be other edge cases around this as well.

On option (a), instead of having a wallet to cover the funds, can we use, e.g., a module account address, and have compass check for it and handle it differently?

**Comment by byte-bandit** [comment]
@maharifu 

I agree option (b) would be cleaner, but also I don't think the benefits outweigh the changes needed to make this happen on top of the massive PF changes already coming in.

Your suggestion for (a) could work, but it would make the compass SLC implementation yet more complex. The calls in question would not generate community/security fees, and compass would not actually pay the relayer fee, but only reimburse gas cost.

@webelf101 What are your thoughts on this?

**Comment by webelf101** [comment]
I don't understand what is the issue. Is the relayer supposed to get refund? Is the fact that msg.sender can be different than relayer an issue? @byte-bandit @maharifu

**Comment by byte-bandit** [comment]
@webelf101 The question is whether it's possible/good idea to extend `submit_logic_call` on compass in a way that it will check the `msg.sender` and compare against a hard coded address. And if the call does come from that address, do not perform the regular fee operations, but just reimburse from security fund.

**Comment by webelf101** [comment]
@byte-bandit I may not understand. When relayer is the same as `msg.sender`, why don't we need perform the regular fee operations? I think even whether relayer equals to `msg.sender` or not, regular fee operations(regular fee, security fee, community fee) is required.

**Comment by byte-bandit** [comment]
@webelf101 This is an architecture issue. At the moment, Paloma is allowing users to send arbitrary function calls to target chains via compass, using `submit_logic_call`. Now, we're adding the concept of fees to this, so that users will have to pay for every call they issue, and relayers can claim their raked up rewards.

The problem is that Paloma also uses `submit_logic_call` for internal operations that are triggered by us, and not by a user. For example to call `deploy_erc20`, or to call `new_compass()` on the tokens themselves. So, we have some infrastructure messages that sort of piggy back on the SLC pipeline.

The problem now is obvious. Since those are SLC calls, who will pay for them?

We have a few options:

- Setup an address on Paloma for this specific purpose, make deposits on compass for it, make sure it's always funded, have this address be in Paloma governance, then use this address for every message send
  - the downside is that this is again a lot of work to implement 
  - we have no control over how much it will bleed us
- Change the `submit_logic_call` implementation on compass to check the message sender is actually the paloma address
  - doing the full fee run will increase the costs for these messages
  - instead, we can just treat them like other infrastructure messages (`update_valset` and `submit_batch` for example. They're also infrastructure messages sent by the protocol, but they are simply reimbursed from the security funds)

We think the first option is probably better, but also more time consuming to implement and more error prone. The second one would get us to the goal faster, but will need a compass update.

**Comment by webelf101** [comment]
https://github.com/VolumeFi/paloma-compass-evm/commit/ee37fff6a3ab78f47263d8e14b7518135a4856ed
Can this solve this issue? @byte-bandit

**Comment by webelf101** [comment]
So when the relayer is different than msg.sender in SLC, do you want to process fees like update_valset? @byte-bandit

**Comment by byte-bandit** [comment]
> So when the relayer is different than msg.sender in SLC, do you want to process fees like update_valset? @byte-bandit

No. Not just if it's different. The `msg.sender` address would have to equal a specific ETH address. Let me think about this a little more. With https://github.com/VolumeFi/paloma-compass-evm/commit/ee37fff6a3ab78f47263d8e14b7518135a4856ed we only abuse SLC to deploy a new token, which is rare. Maybe we can just pay for this by making a deposit. I'll get back to you.

**Comment by byte-bandit** [comment]
Confirmed this is no longer needed with the move to the atomic upgrade path on compass.
