### ISSUE TITLE
[GAMING] As a user, I want to be charged anti-spam once per game

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1836]
As a user, I want to pay the game ANT-SPAM fee once per address and per game, but every 30 epochs, so that I can come back for the next epoch and play again until my 30 attempt when I must pay the fee..

**Acceptance Criteria**
1. Update to charge the anti-spam fee once for every 30 epochs for each address

**Comment by fullstack412** [comment]
@taariq pay fee once for every 3 epochs per game?

**Comment by taariq** [comment]
Closed. Won't fix.
