### ISSUE TITLE
WBTC SQUEEZE bot creation failed due to slippage

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1851]
bot creation failed for slippage https://etherscan.io/tx/0x68f2598d6fa17ab2c029b61b8a6420c56b549c806f74609c5f3429d7ef1650f1

**Comment by verabehr** [comment]
@wc117 @jamie088 - cc @fieldtheory123 my understanding is that the FE should update slippage to 0.05%? Is that correct?

**Comment by wc117** [comment]
Currently, slippage for leverage is 0.1% and it may be too big for non-stable coin swap. I think we need to change it and I suggest 0.5%. Not 0.05%

**Comment by verabehr** [comment]
thanks @wc117

**Comment by jamie088** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/476
