### ISSUE TITLE
[BUG] EurE Bot failed to complete swap XDAI to EurE

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1856]
Bot: July 9
New Bot! - Bot Name: eure, Token Input: crvusd, Amount Input: 10020.11, Token Output: dai, Amount Output: 10044.14, Chain Name: eth

https://gnosisscan.io/address/0x5d5dab5c8f2b182ca96b3201d50e3b610c3250f1#tokentxns shows no SLCs for the balance on the account

**Comment by verabehr** [comment]
This is a protocol issue that is tracked here https://github.com/VolumeFi/paloma/issues/1857
