### ISSUE TITLE
Address dependabot upgraded dependencies for Paloma

### ISSUE THREAD

**Issue by ToasterTheBrave** [VolumeFi/paloma#186]
Dependabot has suggested several dependency upgrades for palomad and pigeon.  These need tested before we add them in

For this ticket, let's test:
* cometbft
* gogoproto
* grpc
* ginko
* docker/distribution

**Comment by ToasterTheBrave** [comment]
Tested and merged the ones that were easy.  There are two remaining from the list
* cometbft: This can't be merged until a breaking change is fixed: https://github.com/cosmos/cosmos-sdk/issues/16027
* gogoproto: It appears we probably need to regenerate the proto files along with this PR

**Comment by verabehr** [comment]
moving this ticket back into the todo as the cosmos team closed our the blocking ticket as "cannot reproduce"
