### ISSUE TITLE
Paloma LigntNode Automation with Authz

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1866]
As a Paloma LightNode Client, I want the light client to automatically claim and delegate my staking rewards with Authz so that I don't have to enter my password each time.

**Acceptance Criteria**
  * Automatic delegation to active validators to maximize low-stake validators
  * Automatic redelegate from inactive validators to active validators.
  * GRAINs will be claimed and redelegated every 24-hours

**Comment by maharifu** [comment]
@taariq I'm not sure authz allows us to do what we want, here.

Authz allows us to setup one account to be authorized to perform actions for another account. However, we're only dealing with a single account here, the vesting account. Who should we be granting staking permission to?

The LightNode client will be doing the delegations, so it has to be able to operate an account. Am I missing something on this?

**Comment by taariq** [comment]
@maharifu we want to grant permission to an account that will execute the claim, delegate and redelegate commands. Are we able to limit just those commands to a new Paloma account that we control on the back end?

**Comment by maharifu** [comment]
@taariq We can set a [StakeAuthorization](https://docs.cosmos.network/v0.50/build/modules/authz#stakeauthorization) for the delegate and redelegate, and we should be able to set the [GenericAuthorization](https://docs.cosmos.network/v0.50/build/modules/authz#genericauthorization) for the claims. But will we have a backend to do these operations?

We can look into other solutions for the passwords. For instance, we should be able to setup the [pass backend](https://docs.cosmos.network/v0.46/run-node/keyring.html#the-pass-backend) to require the password only once on every restart.
