### ISSUE TITLE
[BUG] Success rate seems capped at `0.5`

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#1869]
`palomad q metrix validators` shows no validator with a success rate beyond `0.5`, which should span between `1.0` and `0.0`, with a gradual pull towards `0.5`. It seems to work for punishing, but not for rewarding?

**Comment by taariq** [comment]
This is in To-Do. Does this need an epic @byte-bandit?

**Comment by byte-bandit** [comment]
@taariq I don't think so.

**Comment by taariq** [comment]
This is fixed with https://github.com/palomachain/paloma/pull/1301
