### ISSUE TITLE
fix button size of connect wallet button

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#187]
<img width="379" alt="Screen Shot 2023-03-28 at 2 51 48 PM" src="https://user-images.githubusercontent.com/19958639/228339019-e21a67a6-59a8-45f1-9ad6-3ef45db97f4b.png">

connect wallet button is too big

**Comment by verabehr** [comment]
@wdev733 will you please take this today as well? Should be a quick fix

**Comment by wdev733** [comment]
sure!

**Comment by wdev733** [comment]
https://github.com/palomachain/paloma-swap-ui/pull/98
