### ISSUE TITLE
Search twitter users API on tailored backend

### ISSUE THREAD

**Issue by maharifu** [VolumeFi/paloma#1877]
We need to be able to search for twitter users on the tailored twitter tweeter backend.

The endpoint should accept a list of strings and return a list of twitter users.

**Comment by maharifu** [comment]
@taariq @Cieloc The user search API endpoint is not available on our current subscription. We need to be at least at the pro level, which costs 5000$ per month.

**Comment by taariq** [comment]
Then we'll close this as won't ship. We won't pay $5K for search. This feature will be excluded.
