### ISSUE TITLE
Paloma LIghtNode Sale Vyper Contracts go Multichain

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1879]
As a user, I want to be able to use my liquidity on any of the Paloma target chains to purchase nodes for the node sale so that I do not have to change chains to use my liquidity to purchase a Paloma Light Node.

**Acceptance Criteria**
1. Track balance of slots available and GRAINs available on Paloma CW contract
2. Mint the Node NFT and the settlement when Paloma CW confirms the balance
3. Store all the users’ purchase information on Paloma CW Contract
4. Collect all funds from all chains into one address controlled by Paloma
5. All funds must be stored on the same address on the target chain
6. Taariq will provide the address for funds collection on the target chain
7. Target Chains:
  * ETH
  * BNB
  * ARB
  * OP
  * BASE
  * BLAST
  * MATIC
8. Test
  []  unit test
  []  integration test

**Comment by fullstack412** [comment]
step 1: user fetch the estimated price for node sale 
step 2: user run the tx with that estimated value.
step 3: on paloma side, we fetch the event and check if the current amount is correct. if it’s correct,move to step 4. not, move to step 5.
step 4: mint nft function.
step 5: mint refund function. (in refund function, we need to refund USDC, not original input token)
step 6: fetch the mint nft token event (or refund event) and if that transaction failed, we need to call that function again.

@taariq
