### ISSUE TITLE
[DEVOPS] Restart Bot services for limit-order and curve-lending return status 502

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1880]
1. https://check.bots.palomachain.com/limit-order/
2. https://check.bots.palomachain.com/curve_lending_bot/

All return status 502. Let's restart these services.

**Comment by verabehr** [comment]
- Curve lending is not in use atm
- restarted limit order bot service
- pointed momentum and gecko.momentum to lorentz server where they are hosted and updated notion

NOT WORKING
- one.palomachain.com. This is hosted on the bots server
- fcd.palomachain.com This seems intermittent. Changed from cname to A record in case that helps
- status or uptime. This is the interface for the telegram and discord alerts. Having trouble sshing into the server for some reason, so going through linode directly to confirm setup.
