### ISSUE TITLE
Paloma LightNode Sale User Activation from LightNode Client

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1881]
As a user who has purchased a Paloma LightNode Client, I want to activate my Paloma address that I created with my LightClient software so that Paloma will link my EVM purchase address with my Paloma address on the Paloma CW contract.

**Acceptance Criteria**
1. Create a activation endpoint for the lightnode https://palomachain.com/lightnode/activate
2. Request user to connect their EVM wallet and sign a transaction verfiying that they own the private key to the purchasing wallet
3. Provide a form for the user to enter their Paloma address while showing their EVM address
4. Sign a Paloma transaction to store the EVM and Paloma address in the Nodesale CW contract
5. Emit the CW event with the EVM address and the Paloma Light Client address.
6. @joycehermosilla provide a UI form for the user to register their Paloma LightNode client.

**Comment by fullstack412** [comment]
What's this ticket for? @taariq

**Comment by taariq** [comment]
@fullstack412 this is updated. Please check and send questions/comments as needed.

**Comment by fullstack412** [comment]
@taariq @maharifu i added the paloma address params in the contract.
