### ISSUE TITLE
Light node sale UI

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1888]
Figma: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=1-2491&t=mGTy8y0v0kN2jtS9-4
EPIC: https://www.notion.so/volumefi/EPIC-07-12-24-Paloma-Light-Node-Public-Sale-8ea43ca42b2442d3977f8dc6237624f3?pvs=4#37cf7650e6734793a38d672286da780a

**Comment by taariq** [comment]
Closing as delivered.
