### ISSUE TITLE
[COSMOS] Add Paloma to the Cosmos Chain Registry

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1897]
@maharifu we've been asked to add Paloma to the Cosmos chain registry:
https://github.com/cosmos/chain-registry?tab=readme-ov-file#chainjson
1. chain.json
2. Assetlists
3. IBC Data

Let's add them and make the PR. I'll alert the team.

**Comment by maharifu** [comment]
Opened PR upstream - https://github.com/cosmos/chain-registry/pull/5027
