### ISSUE TITLE
[LIGHTNODE SALE] BUG: The countdown says 8 minutes instead of the 14 days.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1907]
The Countdown shows the incorrect time as 8 minutes instead of the 14 days.

![Image](https://github.com/user-attachments/assets/e5603d86-6555-420f-9a00-f88ac6e55799)

**Comment by jamie088** [comment]
@taariq I need to know the exact Node Sale start date. 8 minutes or 14 days are for example countdown purposes only and are not valid date.

**Comment by taariq** [comment]
@jamie088 we'll start the node sale at 11:00 AM, Jul 25 Coordinated Universal Time (UTC)

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/website/pull/70
