### ISSUE TITLE
Skyway: Send to ETH tx that was sent during missing relay weights was only partially completed

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1912]
Steps to reproduce
1. need a network with paloma v1.15.4, but without all evm relay weights set
2. need a token contract deployed on evm chain and the erc-to-denom set for that token contract
3. Send a tx to the evm 
4. observe the tx succeeds on Paloma (on mainnet this happened here: [E563AC789B8BAC5607C14012A2CE98EC2F39EBD6484F0C58A35553A9156381DB](https://paloma.explorers.guru/transaction/E563AC789B8BAC5607C14012A2CE98EC2F39EBD6484F0C58A35553A9156381DB?height=20815295))
5. observe that the next steps fail in the paloma logs because of hte missing relay weights

Expected: 
I should be able to get my funds back on Paloma or the EVM chain

Actual:
Funds seem lost 
My paloma account was reduced by 7grain (the value of the send tx), but I don't seem to be able to retrieve them and they weren't send to the evm when the [vote passed](https://paloma.explorers.guru/proposal/75)

**Comment by byte-bandit** [comment]
Yes, I think we can close this is a migration issue. It won't happen again.
