### ISSUE TITLE
[LIGHTNODE SALE] Node Sale Calculator

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#1924]
As a user, i want to see the node calculator  on the paloma sales page so that I am able to choose my node amounts to purchase and determine my ROI on the nodes available for sale.

**Acceptance Criteria**
1. Add a calculator to the Node Sale landing page.
https://docs.google.com/spreadsheets/d/1xs3RXaxIbPomG-szU1aSXL5dhYXMmCHKhNKEhrAPU3I/edit?usp=sharing
2. Ok to use static numbers.

**Comment by taariq** [comment]
Shipped!
