### ISSUE TITLE
[LIGHTNODE SALE] As a user, I want to know the swap slippage and Transaction processing Fees

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1925]
As a user, I want to know and to pay the swap slipapge fee of 1% and the Purchase Transaction Fee of 5.00 per purchase so that I know any additional fees that add to the total amount.

- [x] Add a Purchase Processing Fee of $5.00 to each node purchase listed after the number of nodes purchased
- [x] Confirm that the Purchase Processing Fee is per purchase.
- [x] When a user connects their wallet, I want to see a note above the buy now button: "All purchases include a 1% slippage fee for swaps".
- [x] All Processing Fees and Slippage Fees go to the following wallet `0xADC5ee42cbF40CD4ae29bDa773F468A659983B74`
- [x]  Add UI/UX to show the sub total with the Processing Fee and indication of slippage.
- [ ]  Allow user to set slippage in the token selection screen. This will require UI update from @joycehermosilla

**Comment by fullstack412** [comment]
@taariq fee address please.

**Comment by fullstack412** [comment]
@taariq should we refund those processing fee and slippage fee to the users when we refund the purchased money to the users due the node price impaction?

**Comment by taariq** [comment]
@fullstack412 no. that fee is non refundable

**Comment by joycehermosilla** [comment]
@taariq "Confirm that the Purchase Processing Fee is per purchase" Do we need a disclaimer?

**Comment by joycehermosilla** [comment]
@jamie088 @taariq The UI is updated. 

![Image](https://github.com/user-attachments/assets/d2ca4976-398d-4a62-8217-20e0c6fbeb9c)

![Image](https://github.com/user-attachments/assets/19c65cf6-fd31-411c-bdef-8469cfed2990)

**Comment by taariq** [comment]
Thank you @joycehermosilla. This is exactly what we needed. FYI @jamie088 @fullstack412

**Comment by fullstack412** [comment]
@taariq @joycehermosilla Isn't tatal value $55 and 100.0015ETH?

**Comment by joycehermosilla** [comment]
Yes. @fullstack412 I will fix it

**Comment by jamie088** [comment]
@taariq @fullstack412 **Allow user to set slippage in the token selection screen.**

I remember we discussed that we don't need a slippage selection part again, isn't it?

**Comment by verabehr** [comment]
yes, that is what we said @jamie088 @taariq
