### ISSUE TITLE
[LIGHTNODE SALE] Support Subscription Add-on on Sale page

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#1932]
For our node sale, we will be adding an optional Enhanced support subscription. This support model will be structured similarly to the one found on [Elastic's pricing page](https://www.elastic.co/pricing). There will be two tiers of support: a free Standard level and a paid Enhanced level.

https://www.notion.so/volumefi/EPIC-07-30-24-Lightnode-Support-Model-e562006093fd4bb1b538e8714c87bd7d?pvs=4

**Comment by taariq** [comment]
Delivered.
