### ISSUE TITLE
[BUG LIGHTNODE SALE] some content is duplicated

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1936]
this section has the same text as the section above
![Image](https://github.com/user-attachments/assets/2e90af7c-9b4e-4112-98d2-bf7ed34755c7)

but it should be a different text, see figma https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=1-4784&t=4KQYy4DHNCt6zIfF-1

**Comment by taariq** [comment]
All good. Figma is behind on this one. @joycehermosilla will you update Figma to reflect the site?
