### ISSUE TITLE
[PALOMA LIGHT NODE] Send event to compass on sale

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1937]
Create an event when a lightnode sale is complete - see https://www.notion.so/volumefi/EPIC-07-25-24-Light-Node-Sale-Events-77d356af248b4eb58426e311a836e364?pvs=4

**Comment by fullstack412** [comment]
done (called emit_nodesale_event function from compass.)
@verabehr

**Comment by verabehr** [comment]
https://github.com/VolumeFi/paloma_nodesale_vyper/commit/7f9ede34e044852bb13bc2d8b6ac8b2a5144563b
