### ISSUE TITLE
Security: x/jobgrant module for cross-chain message permissions

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#194]
As a user, I want to be able to use the x/whitelist module feature to whitelist paloma addresses that will be authorized to send messages to my target account or public key on the specific target chain supported by Paloma.

**Requirements**
1. Implement x/jobgrant module based on the EPIC: https://www.notion.so/volumefi/EPIC-04-28-23-Message-Security-Paloma-Whitelist-for-Message-Relay-601616603769401495a5ce5cd728a6be

**Comment by byte-bandit** [comment]
@taariq Is this still needed?

**Comment by taariq** [comment]
No. Closing as won't ship.
