### ISSUE TITLE
[PALOMA LIGHT NODE] Allow compass address to be configurable by admins

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1945]
This is a temporary feature to speed up private sales. 

Done when
Compass address in Light node contracts can be updated by admins

**Comment by fullstack412** [comment]
done. https://github.com/VolumeFi/paloma_nodesale_vyper/tree/task/new_compass

**Comment by verabehr** [comment]
https://github.com/VolumeFi/paloma_nodesale_vyper/commit/7f9ede34e044852bb13bc2d8b6ac8b2a5144563b
