### ISSUE TITLE
[PALOMA LIGHT NODE] As a user, I want my payment to be processed before I activate my Paloma LightNode

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1952]
[PALOMA LIGHT NODE] As a user, I want my payment to be processed before I activate my Paloma LightNode so that my payments, less any rewards or referral fees are paid to the Paloma Foundation

**Acceptance Criteria**
1. user pay first
2. Funds are swapped into the appropriate revenue addresses on swap
3. Referral Fees are kept on the contract as agreed.
4. No minting logic required to process payments

**Comment by fullstack412** [comment]
@taariq referral fee also go to the referral address when user make the payment. is that ok?

**Comment by taariq** [comment]
> @taariq referral fee also go to the referral address when user make the payment. is that ok?

@fullstack412 and if we have to refund the user we are screwed? No. We'll need to collect and then let referrals claim.

**Comment by fullstack412** [comment]
@taariq updated. now, referrals can claim only by using claim function.
