### ISSUE TITLE
Stable Coin Limit order bot UI

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1955]
As a Palomabot user, I want to open a limit order on stablecoins to protect me against depges. 

Done when:
We have a new bot on Palomabot
```
Name: Stablecoin Limit Order Bot
Description: Open limit orders for Stablecoin Depegs
```

Contract: [0x19b7766ae51b1b45ddfed3cfd48a7a71639a3e7a](https://arbiscan.io/address/0x19b7766ae51b1b45ddfed3cfd48a7a71639a3e7a) 

This is very similar to the original limit order bot, but users can specify the number of orders and some smart contract functions changed - see https://www.notion.so/volumefi/EPIC-07-19-24-Systematic-Limit-Order-Bot-for-AlphaGrowth-245fa95da2f547d1b2085f114c68cef8?pvs=4#eb02c607e0014d50b84ba8556472268e

**Comment by taariq** [comment]
Close as won't ship
