### ISSUE TITLE
[LIGHTNODE SALE] Add Privacy, Terms and Conditions and Terms of Use

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1958]
CHORE: Add the following pages that will link to new windows.
1. Terms and Conditions: https://docs.google.com/document/d/1puUO41mEjnj6qQqFpSyjzXIJanfG16KoXEZ8xBoB-VI/edit
2. Terms of use: https://docs.google.com/document/d/1xt-CNyditQZXZLcfwM_wsPMpiBL5TUiFQu7Alnw5VeY/edit
3. Privacy Policy: https://docs.google.com/document/d/1wohVWiIEvsrswkV3KbOoxmOmc0fwnE6Wsk_JIqQrKrE/edit?usp=sharing

**Comment by joycehermosilla** [comment]
@jamie088 @taariq The Designs: Figma: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=1045-1079&t=LTktCxS9yrHTIc4m-4
<img width="652" alt="Captura de pantalla 2024-08-07 a las 21 27 33" src="https://github.com/user-attachments/assets/0c71fb80-d67a-415f-bc43-42893670a5ac">

**Comment by taariq** [comment]
Thank you @joycehermosilla. Moving to assign now just to @jamie088

**Comment by jamie088** [comment]
@taariq @joycehermosilla Where is the `Privacy Policy` used? I couldn't find it in design.

**Comment by taariq** [comment]
@joycehermosilla the Privacy Document is here: https://docs.google.com/document/d/1wohVWiIEvsrswkV3KbOoxmOmc0fwnE6Wsk_JIqQrKrE/edit?usp=sharing

**Comment by joycehermosilla** [comment]
@jamie088 @verabehr https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=1-2491&t=l7AjgYWToQEdAUvN-4 Added here.

**Comment by taariq** [comment]
shipped with https://github.com/palomachain/website/pull/104
