### ISSUE TITLE
[Hardening] Ensure that NOBODY can simply put a message in queue to relink ownerships

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#1959]
Ensure it's impossible for a malicious entity to broadcast the messages used for changing ERC20 token or fee manager ownerships.

**Comment by taariq** [comment]
@byte-bandit is this landing in v.1.16.0?

**Comment by byte-bandit** [comment]
> @byte-bandit is this landing in v.1.16.0?

There's no time to delve into this as well. It'll have to come later.

**Comment by verabehr** [comment]
> > [@byte-bandit](https://github.com/byte-bandit) is this landing in v.1.16.0?
> 
> There's no time to delve into this as well. It'll have to come later.

updated to 1.16.1
