### ISSUE TITLE
[Hardening] Have one atomic function call on compass for all handovers

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#1960]
Instead of making `n` calls to change ownership of ERC20 tokens and fee manager and potentially ending in a situation where some calls went through and other don't, it would be faster and more efficient to have only one function on compass to call, that forwards handover calls to all tokens and the fee manage. 

Since those will all be in the same TX, it will either go through or fail.

**Comment by byte-bandit** [comment]
@webelf101 Here's the suggested implementation:

1. Make  `update_compass_address_in_fee_manager`  an internal function.
2. Add  a new public function `compass_handover()` 

That new function should:

- Verify the call was made from Paloma and assert consensus
- Accept a batch of submit logic call arguments
- For each item in the batch, execute  the submit logic call (ignoring fees)
- Lastly, run `update_compass_address_in_fee_manager`

That way, when we upgrade compass, we can call the old compass **once**. The submit logic call batch would contain the calls to `new_compass()` for each deployed ERC20 token. That way, we can make sure that ALL dependencies will be updated in one atomic transaction. 

This would be a great improvement on the current situation, where we have to make `n` calls instead of one, and deployments can get stuck if one or more tokens fail to be updated.

**Comment by webelf101** [comment]
https://github.com/VolumeFi/paloma-compass-evm/commit/ee37fff6a3ab78f47263d8e14b7518135a4856ed
Can this solve this issue? @byte-bandit
