### ISSUE TITLE
[LIMIT ORDER BOT] Upgrade StableCoin LimitOrder Bot to Factory design for new bot

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1970]
As a user, I want Paloma to use factory contract templates to allow the system to launch new LimitOrder bots when my current bots expire so that my volume is onchain as well as automation of limitorder creation.

**Acceptance Criteria**
1. @webelf101  will move current code to factory - blueprint model
2. @webelf101  will add the new deployment feature to current bot

**Comment by verabehr** [comment]
https://github.com/VolumeFi/limit-order-repeat-bot-uniswap-v3-vyper/pull/4
https://github.com/VolumeFi/limit-order-repeat-bot-uniswap-v3-cw/pull/1
https://github.com/VolumeFi/limit-order-repeat-bot-uniswap-v3-script/pull/3
