### ISSUE TITLE
[LIGHTNODE SALE] Update Paloma LightNode Sale pricing on website and contracts

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1976]
As a user, I want the Paloam website to show the update LIghtNode Sale  pricing so that we are using the market-ready pricing.

**Acceptance Criteria**
1. Node sale pricing update sheet: https://docs.google.com/spreadsheets/d/1Cm6IXnuOeR-_plD16mgX3EH26_X91X2v4-UCeYstaWs/edit?usp=sharing with the tab: 
2. Tab to use **Paloma Node Sale 2024 V3 LATEST**
3. Update website 
4. Update contract cosmwasm

**Comment by fullstack412** [comment]
set the pricing tiers information to the contract
@taariq

**Comment by taariq** [comment]
Thank you. Closing.
