### ISSUE TITLE
[LIGHTNODE SALE] As a Paloma LightNode user, I want to always have my lightnode version automatically updated

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1978]
As a user of the first version of the Paloma LightNote, I want my Paloma Light-Node Client always updated on Docker with the latest tag for that version so that I don't have to manually pull the latest version

**Acceptance Criteria**
- [ ] Create tag v1 for the Paloma LightNode Sale version. 
- [ ] Always update v1 tag with each push 
- [ ] Ensure that docker always builds on the updated tag

**Comment by maharifu** [comment]
Closed with https://github.com/VolumeFi/lightnode-client/commit/94d8225ab3c62f64007b7dcd819f2866a4e4baaf
