### ISSUE TITLE
BUG: trade bots api doesn't yield the correct results

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#198]
### Done when

- [x] momenutm bot api gives the expected results (James to provide more details) @rootedbox 
- [x] frontend uses the API instead of mock data @jamie088

**Comment by jamie088** [comment]
I am using these 2 apis : 
`https://service.robots.palomachain.com/robots?depositor=<wallet address>` to get my active bots list
`http://lorentz.palomachain.com:3000/?dex=uniswap_v2&lag_return=12&daily_volume=200000` to get momentum tokens list.
But these 2 APIs have issues and currently do not work.

**Comment by verabehr** [comment]
issue with lorentz.palomachain captpured here: https://github.com/VolumeFi/paloma/issues/199

**Comment by verabehr** [comment]
Remaining Api issues are captured in https://github.com/VolumeFi/paloma/issues/199 and https://github.com/VolumeFi/paloma/issues/173 closing this as duplicate
