### ISSUE TITLE
[LIGHTNODE SALE] Lightnode Dowload and Instructions Page

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#1988]
https://www.notion.so/volumefi/EPIC-08-09-24-Paloma-LightNode-Sale-Download-and-Installation-Instructions-22feac6d62334a6ca9a5098e0da8531e

**Comment by joycehermosilla** [comment]
This is ready @taariq 

Mac: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=1-4378&t=CV8Q4fphaluwXC85-4

Windows: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=1860-325&t=CV8Q4fphaluwXC85-4

**Comment by taariq** [comment]
This is done.
