### ISSUE TITLE
BUG: Momentum token list doesn't return any results

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#199]
```
curl -X POST -H "Content-Type: application/json" http://localhost:8080/get_high_returns   -d '{"dex": "uniswap_v2", "lag_return": 12, "daily_volume": 200000}'

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;http://localhost:8080/get_high_returns&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
        </body>
    </html>
```

**Comment by verabehr** [comment]
Closing. This is a case where the query actually doesn't return any results. The API and script work https://discord.com/channels/987730379182051408/1065140873811218532/1108430605630308362

**Comment by measure-fi** [comment]
This seems to be a temporary circumstance: when no high-volume coin is doing well an empty result is returned.

**Comment by verabehr** [comment]
Reopening this for now. Team cannot confirm that the API actually works. @measure-fi if you have the parameters with which a result would be returned please share here. 
@fieldtheory123 are we too restrictive? We tried a few variations with no luck

**Comment by verabehr** [comment]
Last query used (before search parameters were commented out) https://momentumbots.palomachain.com/?dex=uniswap_v2&lag_return=24&vol_30=84855678.16089071&market_cap=0

**Comment by verabehr** [comment]
We are now getting results 🎉 https://momentumbots.palomachain.com/?dex=uniswap_v2&daily_volume=200000&lag_return=6&vol_30=0&market_cap=0

Last open question is if we want to add `daily_volume` to the UI and allow the user to search on it or if we want to instead remove it from the API (and wherever else it is referenced in the python, js code). Right now it is required for the API to return any results, so the FE will pass in a static value. 

cc @fieldtheory123 @taariq

**Comment by taariq** [comment]
What would `daily_volume` look like on the UI?

**Comment by verabehr** [comment]
It would be another input parameter here https://www.palomabot.ai/ - in addition to `Market Capitalization` and `30 Day Volume`

**Comment by taariq** [comment]
Less is more. Let's leave it out. We might a/b test it in the future.

**Comment by verabehr** [comment]
I believe we need @fieldtheory123's help with that - @measure-fi correct me if I'm wrong

**Comment by verabehr** [comment]
- dropping daily volume was done by always sending a value of 0 for daily_volume. 

- dropping 24h return filter here https://github.com/VolumeFi/palomabot/pull/15
