### ISSUE TITLE
[LIGHTNODE SALE] Activation confirmation when no node was purchased

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1992]
When I click on `Activate Node` with a wallet connected, I get a confirmation that my node was activated even though I didn't buy a node yet. I expected to see the message that no light node is linked to my wallet https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=741-479&t=tjy8ebyW62T5MtvF-1

Loom: https://www.loom.com/share/30db3cd77d09452ebab41b940334e67b?sid=32ddd176-1421-41d5-b921-7303e67a3385

**Comment by taariq** [comment]
Closing as fixed?
