### ISSUE TITLE
[LIGHTNODE SALE] Download & Installation Pages

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#1993]
![Image](https://github.com/user-attachments/assets/87120f02-d044-488d-83c1-551036cf9266)
After the email confirmation view of the purchase flow, the user will be redirected to the Download and Installation page.

Designs: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=1860-324&t=ZZtiHSFthd1FvN8R-4

Mac: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=1944-323&t=ZZtiHSFthd1FvN8R-4

Download Setup: https://github.com/VolumeFi/lightnode-client/blob/main/run.sh
Download Apple Silicon: https://desktop.docker.com/mac/main/arm64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-mac-arm64

Download Intel Chip: 
https://desktop.docker.com/mac/main/amd64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-mac-amd64

Windows: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=1860-325&t=ZZtiHSFthd1FvN8R-4

Download Intel Chip: [https://desktop.docker.com/win/main/amd64/Docker Desktop Installer.exe?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-win-amd64](https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-win-amd64)

Download ARM: [https://desktop.docker.com/win/main/arm64/Docker Desktop Installer.exe?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-win-arm64](https://desktop.docker.com/win/main/arm64/Docker%20Desktop%20Installer.exe?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-win-arm64)

**Comment by taariq** [comment]
Closing as shipped. We will debug and bug tickets in prod.
