### ISSUE TITLE
[LIGHTNODE SALE] Activation Flow: Instructions after Activation.

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#1994]
After successful activation. 
we want to add instructions on how to return to your Lightnode

- [ ] Remove text "Return to the Paloma LightNode Client and start minting"
- [ ] Replace this text with a Continue button
- [ ] Add a next screen with the Instructions.  Designs: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=1947-544&t=ZZtiHSFthd1FvN8R-4

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/website/pull/110
