### ISSUE TITLE
[LIGHTNODE SALE] BUG - when user goes to passcode page, the purchase page shows for a split second

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#2003]
Steps to reproduce
1. go to palomachain.com before the sale start date
2. click on CTA to `purchase your lightnode`

Expected:
I immediately see the passcode page 

Actual:
I see the purchase page for a split second and am then redirected to the passcode page

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/website/pull/119
