### ISSUE TITLE
[Lightnode sale] API for node registration 

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#2008]
We need to user register for LightNode using the magic link.
[work flow]
- FE will send the `Full Name` and `Email` to the backend.
- The backend api uses Magic link to return a confirmation email to the user's email including palomachain redirect url.
- When the user clicks on this confirmation email, the user goes back to the Palomachain website and the backend stores this user information in the DB
![image](https://github.com/user-attachments/assets/029640a0-aa65-4a5d-8b44-da7d5fe1e5e2)
![image](https://github.com/user-attachments/assets/e4576761-2281-4224-9eee-a78f6d83839d)

**Comment by fullstack412** [comment]
https://github.com/VolumeFi/paloma_nodesale/pull/3
