### ISSUE TITLE
add deploy_contract() to compass

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#2009]
This needs to get into the `v2.0.0` release of compass that is going to be released on Monday. 

- [ ] It only needs one additional public function called `deploy_contract()` that will essentially just take the passed argument bytecode and deploy it on the chain. 
- [ ] It performs a consensus check just like with SLC
- [ ] It moves fees just like the SLC 

Suggestion on function definition (missing the argument for **constructor input** as I wasn't sure how to define this in vyper):

`def deploy_contract(consensus: Consensus, code: bytes, constructor_input: bytes, fee_args: FeeArgs, message_id: uint256, deadline: uint256, relayer: address):`

**Comment by taariq** [comment]
@webelf101 this is required to tag Compass-EVM v2.0
