### ISSUE TITLE
[CHORE] Deploy node sale contract for PTN testing

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#2010]
Deploy the node sale contract for testing in private testnet

Compass address on Arbitrum: 0x9D352C4a98d9C1bBede3441740aD88018aF347F3

**Comment by fullstack412** [comment]
https://arbiscan.io/address/0xF125C18161C833a386A02214256c521f9e64F967
@verabehr

**Comment by fullstack412** [comment]
@verabehr should i deploy the cosmwasm contract too?

**Comment by verabehr** [comment]
thanks @fullstack412 - updated contract in vercel
