### ISSUE TITLE
[LIGHTNODE SALE] Upgrade the Call-to-Action instructions at the "node is ready for activation" step

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2018]
Change  "Congratulations, your node is ready for activation.
Please go to https://palomachain.com/activate and enter your paloma address.

![Image](https://github.com/user-attachments/assets/2674c924-6ee2-4d08-afe9-2a4f37eb0f62)

to the following:

 "Congratulations, your node is ready for activation follow the next three (3) steps:

Step 1: Copy your Paloma address above [full paloma address] and keep it safe with your 24-word passphrase

Step 2: Go to https://palomachain.com/purchase/activate to connect your wallet and add your Paloma address

Step 3: Come back to the command line and type "start minting"

So that the user has three clear steps to copy their information, enter it into the validation form and then start their minting.

**Comment by maharifu** [comment]
@taariq is `"start minting"` supposed to be a command for the lightnode? Can we make it one word? For instance:
Step 3: Come back to the command line and type "sh $HOME/run.sh start"

This command is supposed to activate the node and automate claiming and delegating, right?
I don't think we can reliably tell if the user has activated the node without wasting gas. Can we split this into two commands, so the users activate the node first, and automate claiming and delegating after?

**Comment by taariq** [comment]
@maharifu let's just use the `automate` command for this function. Yes. It was supposed to automate. Do we really need any new commands since we already have that?

**Comment by maharifu** [comment]
Thank you. I'll look into it.

> **Question:** In step 1, are we able to print their Paloma address in the text?

I'm not sure we can do it without asking for the password again, but I'll try to get it.

**Comment by maharifu** [comment]
This is done with https://github.com/VolumeFi/lightnode-client/commit/e488e91582fe79ccfe3e4685ea47c9277a31f66e
