### ISSUE TITLE
[LIGHTNODE SALE] Upload Terms & Conditions in HTML on separate pages

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2026]
Terms and conditions are in WORD DOCUMENT ON GOOGLE. This is a bug. 

All terms need to be in HTML on Paloma webpages
1. I agree with the Paloma LightNode Sale Terms and Conditions: https://palomachain.com/lightnode_sales_terms_and_conditions
2. I agree with the Paloma LightNode Terms of Use: https://palomachain.com/lightnode_sales_terms_of_use
3. I agree with the Paloma LightNode Privacy Policy: https://palomachain.com/privacy

**Comment by jamie088** [comment]
@taariq So do I need to create these HTML webpages?

**Comment by taariq** [comment]
Yes. These can't be in Google docs.

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/website/pull/119
