### ISSUE TITLE
Upgrade paloma to using github.com/CosmWasm/wasmd 0.40.1

### ISSUE THREAD

**Issue by ToasterTheBrave** [VolumeFi/paloma#203]
Upgrade to Cosmwasm 0.40.0

https://github.com/CosmWasm/wasmd/releases/tag/v0.40.0

We would like this in our next release after v1.1.0 on the public testnet

**Comment by verabehr** [comment]
Note the next minor version is out already, so maybe we should upgrade to 0.40.1 instead https://github.com/CosmWasm/wasmd/releases

**Comment by taariq** [comment]
Moving this to In Progress, then.
