### ISSUE TITLE
[LIGHTNODE SALE] REFERRAL CODE FOR ALPHA GROWTH

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2030]
We have our first referral Partner: AlphaGrowth.

They will need the code ALPHAGROWTH
10% Referral
5% Discount

**Comment by fullstack412** [comment]
ALPHAGROWTH
0x000000000000000000000000000000000000000000414c50484147524f575448
0x6e57181D6b4b7c138a6F956AD16DAF4f27FC5E04

I will create the script for adding, removing code

**Comment by taariq** [comment]
Completed.
