### ISSUE TITLE
[LIGHTNODE SALE] Landing Page Missing Sections

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#2032]
The current Landing Page is missing 2 sections.

- [x] The Paloma Ecosytem add Nectar. https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=439-1108&t=mZCIOwF5CNt0dUpv-4

Nectar Logo:

![Image](https://github.com/user-attachments/assets/48a83c73-4562-442f-a583-8f77099b4680)

- [x] Where can I buy a Paloma LightNode? https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=316-140&t=mZCIOwF5CNt0dUpv-4

- [x] Hero section should use the same Color logos. 

![Image](https://github.com/user-attachments/assets/180081fb-ffbe-4a24-ad8e-021d74844679)

Token icons: 

![Image](https://github.com/user-attachments/assets/f78dd358-ee30-4a07-8ea0-38d980411550)
![Image](https://github.com/user-attachments/assets/8be678f0-304e-4078-8563-7e73237d8164)
![Image](https://github.com/user-attachments/assets/746c7a50-5b41-414c-99d3-20a6e20b0813)
![Image](https://github.com/user-attachments/assets/c32a79e3-053f-4c7d-a1b1-8816810a561a)
![Image](https://github.com/user-attachments/assets/dfffb6d0-f310-4924-a4c8-87685f03a6fa)
![Image](https://github.com/user-attachments/assets/e3741c1c-e73d-4bb6-97fd-c65f1b3160f7)
![Image](https://github.com/user-attachments/assets/e38faeb6-1b41-48ab-a882-186ae3b69b8f)

**Comment by taariq** [comment]
Closed as shipped.
