### ISSUE TITLE
PUBLIC TESTNET: initialize compass on fee manager after compass 2.0.0 vote

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#2033]
Once the vote to deploy compass passes, you will need to call the fee manager MANUALLY and call the initialize_compass() function on it. I can show you once we get to that stage.

fee manager addresses: 
https://docs.palomachain.com/guide/resources/networks.html#testnet

Compass proposal - vote 30

**Comment by maharifu** [comment]
@taariq The initialize_compass function call must come from the address that deployed the contract. It was deployed from [this address](https://arbiscan.io/address/0xa3b473b9b14a1bf3fa9fb26a9b9e749196d0f34e). Is this a Volume wallet? How can I use it?

**Comment by taariq** [comment]
@maharifu I asked Vera for a response on this question.

**Comment by taariq** [comment]
> [@taariq](https://github.com/taariq) The initialize_compass function call must come from the address that deployed the contract. It was deployed from [this address](https://arbiscan.io/address/0xa3b473b9b14a1bf3fa9fb26a9b9e749196d0f34e). Is this a Volume wallet? How can I use it?

@webelf101 from Vera; 
> this is Steven's account. He deployed the fee manager contract

Will you run the call please?

**Comment by webelf101** [comment]
What are the compass addresses on Eth and Arb for public testnet? @taariq @maharifu

**Comment by maharifu** [comment]
> What are the compass addresses on Eth and Arb for public testnet? @taariq @maharifu

@webelf101 They are here: https://docs.palomachain.com/guide/resources/networks.html#testnet

**Comment by maharifu** [comment]
Compass is now redeployed on the testnet. The new addresses are:
ETH: 0x061A44249c2050adcdEB8Ab09213b3E6510Cd43F
ARB: 0xC859BCf62DC2571e693422277cdb3453f84c14bf

And FeeManager addresses:
ETH: 0xf62d5ab8bb6378238c3e67e468809081ad8b77dd
ARB: 0xdc503ab31f8295cf87b09e151bf1f8fb6824d118

**Comment by webelf101** [comment]
I initialized the fee manager contracts. @maharifu
