### ISSUE TITLE
[LIGHTNODE SALE] Landing Page: Paloma Ecosystem Layout.

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#2034]
The Paloma Ecosystem section on the Landing Page needs some layout and design adjustments.

- [x] Add Space between sections. (at least 40px)
- [x] Remove Background icons. 
![Image](https://github.com/user-attachments/assets/a08ac10f-8f5c-47fd-83a5-1685015fd9d0)

**Comment by taariq** [comment]
Closing as shipped.
