### ISSUE TITLE
[LIGHTNODE SALE] Landing Page UI

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#2035]
- [x] Change Fonts. Body text should go in Inter and Titles with RockStar Black.

Fonts: 

[RockStar.zip](https://github.com/user-attachments/files/16694219/RockStar.zip)
[Inter 2.zip](https://github.com/user-attachments/files/16694214/Inter.2.zip)

- [x] Replace Testimonial photos with: 
![Image](https://github.com/user-attachments/assets/9c6db321-69be-42e9-9191-96ba1e8e29d9)
![Image](https://github.com/user-attachments/assets/80275ee1-0582-46ae-b653-490c9202b6b3)
![Image](https://github.com/user-attachments/assets/041ae506-ca34-457b-be1a-295787caf9c6)
![Image](https://github.com/user-attachments/assets/9ba91d73-12fc-4f4f-aaff-6087cbad0770)
![Image](https://github.com/user-attachments/assets/f5f11df7-8dff-4684-b231-2d1f8334144c)
![Image](https://github.com/user-attachments/assets/0ada7497-bb04-4915-9c74-f190bf19be76)

- [x] Replace Images with:

![Image](https://github.com/user-attachments/assets/f8a005a3-9867-49a4-98ad-3621f3194784)
![Image](https://github.com/user-attachments/assets/74a2f608-d544-421f-9324-68499d0d721b)
![Image](https://github.com/user-attachments/assets/48883d87-a11a-43af-961d-ce0e3318cc17)
![Image](https://github.com/user-attachments/assets/aed6360a-9b43-46bd-b9b4-63cc5797fd06)
![Image](https://github.com/user-attachments/assets/22e5a8fb-4862-4278-bad9-dadc391d5941)
![Image](https://github.com/user-attachments/assets/99210475-d24a-4067-bb72-cd3b44043830)
![Image](https://github.com/user-attachments/assets/fd1ecb1d-0856-4e68-9ee8-e375473b3404)
![Image](https://github.com/user-attachments/assets/b2b7eeca-cbde-476b-b6d5-9df162b9d598)

- [ ] Change Background to #2c2c2c. So we don't see this background difference (white) between the last section and the footer.

![Image](https://github.com/user-attachments/assets/a6bf37e9-3520-4859-924a-3c7727c8e56c)

**Comment by taariq** [comment]
@jamie088 is this shipped?

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/website/pull/119
