### ISSUE TITLE
[CHORE] update refund scripts with compass 1.1.1 and compass 2.0

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#2039]
Please update all chains in mainnet with compass 1.1.1

- [x] bnb-main | 0x9d703a2bE7ac576454fa310Aca1c667D1D5e8081
- [x] eth-main | 0x4E74982adB77496308f9c16e45966264D1A4e596
- [ ] matic-main | 0xEf4E24B1a9aAb82e7a0a2e238E7815Cd9A566c48
- [x] op-main  | 0x0b15cd4f536c0c198bccfa69fd6eb5e8192d5fd9
- [ ] base-main | 0xde43bac3ddc0dfd71117ade93a92a2aa079377bb
- [x] gnosis-main | 0xcb48c27e69acfc2466941f71ff9e8530d53b5581
- [ ] arbitrum-main | 0xd865124b3d9c67acdfb830bea4f3070a4123ed34
- [x] blast-main | 0x621fa57c7229d207d1d9b6deeb6c25b936d86db8

After the refund script goes through update the following chains for the failed compass 2.0, so the validators who deployed it get reimbursed

- [ ] arb-main | 0x1D0e77dFBDF7B8503087fDb7d631fc48CF226815
- [ ] base-main | 0xF8bacd79456e20e661Dd47FF0137Bbc1929F60c8
- [ ] blast-main | 0xf498FD5FC4942E18e536d99334c4F1411B5a2985

**Comment by verabehr** [comment]
arbitrum-main	0x82Ed642F4067D55cE884e2823951baDfEdC89e73	5
base-main	0xD41Cc53d6F483c8C77bb806A2d17c569B216Dfb9	5
blast-main	0x994653E3916c93008F25cA0eeec71252C7566686	5
bnb-main	0x042Ab4cd2897BA02a420146af8d95f161A4230F1	5
eth-main	0xDcBd07EEC1D48aE0A14E61dD09BB5AA9c7ed391d	5
matic-main	0x26f5Da70095d69103ba8b2Ee264A20cD4B590EAb	5
op-main	0x5a7A8fAf7f73063b4F175E4eF354B6426aF3bd52	5


Note: still waiting for gnosis

**Comment by webelf101** [comment]
I finished updating it including updated gnosis chain.
@taariq @verabehr

**Comment by verabehr** [comment]
Thank you, closing
