### ISSUE TITLE
[LIGHTNODE SALE] As a user, I want to be able to activate new nodes with the Paloma LightNode Client.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2042]
As a buyer of a Paloma LightNode who has activated one purchase, I want to be able to activate a new Paloma wallet for my additional LightNode purchases so that I am able to purchase more lightnodes after my prior purchase.

**Acceptance Criteria**
1. Change `setup` option to `setup-node`
2. Change `create-key` to `add-node`
3. Remove the `create-key` option as this is not needed. We expect users to either setup or add nodes or import keys.
4. Make the `add-node` option the setup for a new Paloma account to receive node rewards that is not a first setup.
6. Let's test again!

**QUESTION:** What happens if a user accidentally hits `setup` after they've already setup a node? Do we check and warn them not to start the setup again from scratch @maharifu?

**Comment by maharifu** [comment]
@taariq 

> QUESTION: What happens if a user accidentally hits setup after they've already setup a node? Do we check and warn them not to start the setup again from scratch @maharifu?

If the password store directory exists when the user runs setup, we only show the message `"Your node is already set up."` and quit.

**Comment by taariq** [comment]
> @taariq There's nothing special we have to do on the initial setup, so we can also remove that check and always create and import a key. That way the setup-node and add-node commands would be the same. Would this simplify?

Let's discuss in a quick call

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/lightnode-client/pull/3
