### ISSUE TITLE
[LIGHTNODE SALE] BUG: POST https://nodesale.palomachain.com/api/v1/register 500 (Internal Server Error)

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2044]
When attempting to register, user gets the error.

POST https://nodesale.palomachain.com/api/v1/register 500 (Internal Server Error)
defaultFetchFn @ _app-39cf079f7d0e277c.js:426
(anonymous) @ _app-39cf079f7d0e277c.js:426
await in (anonymous)
executeEndpoint @ _app-39cf079f7d0e277c.js:426
(anonymous) @ _app-39cf079f7d0e277c.js:467
(anonymous) @ _app-39cf079f7d0e277c.js:467
(anonymous) @ _app-39cf079f7d0e277c.js:467
dispatch @ _app-39cf079f7d0e277c.js:6084
(anonymous) @ _app-39cf079f7d0e277c.js:426
(anonymous) @ _app-39cf079f7d0e277c.js:467
(anonymous) @ _app-39cf079f7d0e277c.js:426
handleRegister @ register-0e7ef2063ab35c5e.js:1
Nb @ framework-fee8a7e75612eda8.js:9
Tb @ framework-fee8a7e75612eda8.js:9
(anonymous) @ framework-fee8a7e75612eda8.js:9
nf @ framework-fee8a7e75612eda8.js:9
se @ framework-fee8a7e75612eda8.js:9
(anonymous) @ framework-fee8a7e75612eda8.js:9
Qk @ framework-fee8a7e75612eda8.js:9
Jb @ framework-fee8a7e75612eda8.js:9
hd @ framework-fee8a7e75612eda8.js:9
fd @ framework-fee8a7e75612eda8.js:9
ed @ framework-fee8a7e75612eda8.js:9

**Comment by fullstack412** [comment]
Fixed. please test again. @taariq
