### ISSUE TITLE
[LIGHTNODE SALE] Create the script for adding/removing promo code #5

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2047]

**Comment by taariq** [comment]
@fullstack412 I will need this tomorrow, Monday 09/01 for our first sales.

**Comment by fullstack412** [comment]
@taariq https://github.com/VolumeFi/w3tools/pull/4

**Comment by fullstack412** [comment]
@taariq FYI, you need to sync with me when you add new promo code because i have to add promo code in CW contract too.

**Comment by taariq** [comment]
Shipped.
