### ISSUE TITLE
[LIGHTNODE SALE] Upgrade the Python Deposit Script to ask for Paloma Contract Address, Amount,

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2050]
As a user, I want to use the Python script to prepay for my Paloma contract execution so that I can choose the chain, the amount, and the Paloma address that can run executions on the target chain.

**Acceptance Criteria**
1. Fork Current Python to run and return list of chains where prepayment is needed. I want to enter a number.
2. Python Script asks for Paloma address that will execute txes
3. Python Script asks for EVM address that needs funding
4. Python script asks for Funding amount
5. Python script asks to connect wallet and complete the funding transaction

NOTE: Current Python script is here: https://github.com/VolumeFi/w3tools/blob/master/depositor/deposit_funds.py

**Comment by webelf101** [comment]
Vyper or python? @taariq
