### ISSUE TITLE
[DEVOPS] downsize/remove unused linode capacity & add storage to LCD server

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#2052]
Details here 

https://www.notion.so/volumefi/EPIC-08-30-24-review-and-downsize-linodes-a71eef6e51784a129eb67891c9012230?pvs=4

### Todo
Complete the following items from the notion

- [x] item 1
- [x] item 2
- [x] item 6
- [x] item 7

**Comment by maharifu** [comment]
Moved snapshots into the data volume on mainnet-snapshots, and revised the snapshots script to delete old snapshots. I'll leave it over the weekend to see if it works alright and remove the volume early next week.

**Comment by taariq** [comment]
@maharifu what's next for item 6 and item 7?

**Comment by maharifu** [comment]
> @maharifu what's next for item 6 and item 7?

Item 6 is waiting to see if the snapshot script works correctly when left unattended. If it is OK, I'll remove the volume early next week. The snapshots server is also catching up and needs a few paloma upgrades, so it will take awhile.

Item 7 is pending on having the wallet to call `initialize_compass` on the fee manager.

**Comment by maharifu** [comment]
Removed the extra storage from mainnet-snapshots, everything is now in `/mnt/data`.

Added 500GB storage to the lcd-mainnet VM. Paloma data is now in `/mnt/lcd-mainnet/paloma`.
