### ISSUE TITLE
[LIMIT ORDER BOT] Add a Try again CTA in the magic link modal view.

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#2053]
As a user who inputs a bad email on the Registration page, I want to be able to return and enter another email. 

Design: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=1-4159&t=HluKLLMr2jfSvvxx-4

![Image](https://github.com/user-attachments/assets/bc0793ec-372f-4480-8f5c-7970b2a8b150)

**Comment by jamie088** [comment]
Fixed with https://github.com/palomachain/website/pull/121
