### ISSUE TITLE
[LIGHTNODE] As a Windows user, I want to download a script to create my Lightnode on my Windows machine

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2056]
As a user, I want to download a script to create my Lightnode on my Windows machine so that I am able to create LightNodes on my Windows machine.

**Acceptance Criteria**
1. Create setup for windows machine
2. Test with @fullstack412 and @Cieloc who have windows machines.

**Comment by maharifu** [comment]
@taariq the windows script was included in  https://github.com/VolumeFi/lightnode-client/pull/6
It is available for download [here](https://download.palomachain.com/lightnode/setup.ps1)

It was executed with `powershell -noexit -ExecutionPolicy Bypass -File setup.ps1`

**Comment by taariq** [comment]
@maharifu. After tests today, @Cieloc  we decided that we will not use the script. We will give three comman line commands to Windows users and have them run it. It works faster than downloading and running powershell scripts.
