### ISSUE TITLE
[LIGHTNODE SALE] BUG Node purchased, but Paloma has no evidence of purchase

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2058]
Purchase transaction: https://etherscan.io/tx/0xcba568824f704fb779026751e706eef6393ff358541ec68d9cf2a5f8a930c32a

Problems:
1. No evidence showing that the license to be activated.
`light_node_client_licenses: []`
2. No events on Compass: https://etherscan.io/address/0xDcBd07EEC1D48aE0A14E61dD09BB5AA9c7ed391d#events
3. Question: Were the right contracts deployed and is the back-end working?

**Comment by fullstack412** [comment]
1. I also got this error. https://discord.com/channels/987730379182051408/1258872748269109299/1277494792951173224
2. I can see the nodesold event: https://discord.com/channels/987730379182051408/1258872748269109299/1277487986271064116
3. Yes. right contract is deployed and backend script is working
FYI, @taariq

**Comment by taariq** [comment]
Closing as issue with Paloma.
