### ISSUE TITLE
[LIGHTNODE] Update confirmation email content

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2059]
Need to update the email
We need to add more context to the email content

**EMAIL SUBJECT:** 
[Action Required] Paloma invites you to verify your email and activate your LightNode purchase.

**EMAIL BODY:**
Coongratulations Paloma LightNode Buyer,

You are receiving this email because you provided this as registration for your Paloma LightNode purchase.

Pease click the link below to verify your email and continue to activate your node.

https://palomachain.com/purchase/confirmation

Welcome to Paloma,
The Paloma Foundation
https://palomachain.com

@taariq can you give me full content for email please?

**Comment by fullstack412** [comment]
@taariq can you give me full content for email please?

**Comment by taariq** [comment]
@fullstack412 see below.

Email for login:

**SUBJECT:** Sign in to Paloma LightNodes

**BODY**
If you didn't request this e-mail, there's nothing to worry about — you can safely ignore it.

Sign in to Paloma LightNodes now

https://palomalightnodes/email Link

We will sign you in magically.

Any question? Please feel free to reach us at support@palomachain.com

Paloma
https://palomachain.com

**Comment by taariq** [comment]
Closed with https://github.com/VolumeFi/paloma_nodesale/pull/12
