### ISSUE TITLE
Update vyper and cosmwasm contract for allowing activate_wallet in all networks, not only in arb

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2060]
As a user, I want to be able to activate my node on the network that I purchased the node so that I am able to update the node in the network that I made the purchase.

**Acceptance Criteria**
1. Activate works in all networks, not just arbitrum
2. Activate works in the network of the purchasing wallet.

**Comment by fullstack412** [comment]
https://github.com/VolumeFi/paloma_nodesale_vyper/pull/8
https://github.com/VolumeFi/paloma_nodesale_cw/pull/6

**Comment by taariq** [comment]
Fixed with 
https://github.com/VolumeFi/paloma_nodesale_vyper/pull/8
https://github.com/VolumeFi/paloma_nodesale_cw/pull/6

**Comment by fullstack412** [comment]
PR for backend script - https://github.com/VolumeFi/paloma_nodesale/pull/7
