### ISSUE TITLE
Deepinfra API Wrapper Epic

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#2071]
We want to use Light Nodes to provide trustless, anonymized LLM inference.

**Comment by Cieloc** [comment]
Initial research on costs, potential frameworks to copy:

https://www.notion.so/volumefi/EPIC-08-24-24-AI-Inference-API-Wrapper-f7077bb891db43b69876c1560260aea2

**Comment by taariq** [comment]
Close as shipped.
