### ISSUE TITLE
GPU License Node Sale

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#2072]
With a node licensing scheme we can fractionalize the GPU  and hosting costs to make it accessible to average users while benefiting from efficiencies of scale.

**Comment by Cieloc** [comment]
Initial Research. Costs. GPU Acquisition. 

https://www.notion.so/volumefi/EPIC-08-28-24-GPU-Node-License-Sale-74b142a7e2134bde9730ddfe948e2523

**Comment by taariq** [comment]
Closing.
