### ISSUE TITLE
[BUG] Fix reverts with primary key duplication error.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2074]
As erp @webelf101 

> We have an issue on bot-info api.
> It returns so many errors right now.
> The reason is that it uses 2 tables to store token data. And token address was set as primary key.
> But we use multiple chains and they can have the same address.
> That's why it reverts with primary key duplication error.
> Because of the so many errors with db, the API speed response is so slow.

**Comment by webelf101** [comment]
This is done. @taariq
