### ISSUE TITLE
[LIGHTNODE SALE] BUYMORE BOARD: Log In

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#2075]
As a user who bought a LightNode, I want to see my Lightnodes and Buy More from a Dashboard.

To Log In to the Dashboard we will add 2 items to the Paloma Navigation Menu. "LightNode" and "Log In". 
For now "LightNode" will redirect to the Landing Page and "Log In" to the Dashboard Log in Flow.

Log in Flow: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=2320-485&t=zJp7ngbiWKXbxi7o-4

- [x] User can connect with the E-mail used in the Registration Flow.
- [x] User needs to receive a Magic link email. 
- [x] User can also connect with EVM Wallet used to Purchase LightNodes
- [x] If the user presses "Create an Account" will be redirected to the Purchase Flow.

**Comment by taariq** [comment]
I don't see any link to this feature: **"User can also connect with EVM Wallet used to Purchase LightNodes"**

**Comment by taariq** [comment]
Completed.
