### ISSUE TITLE
[LIGHT NODE SALE] API: login and user activates history

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#2077]
LightNode sale FE needs 3 GET apis
- [x] user login api
- [x] user register api
- [x] user activates history

here is the design: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=2341-5588&m=dev

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/paloma_nodesale/pull/8
