### ISSUE TITLE
[CHORE] restart all bots that used updated gecko.json

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2082]
Restart all the bots using new gecko.json

- [x] https://github.com/VolumeFi/curve-twap-bot-script
- [x] https://github.com/VolumeFi/uniswap_v3_twap_bot_script
- [x] https://github.com/VolumeFi/curve-limit-order-bot-script
- [x] https://github.com/VolumeFi/limit-order-bot-uni-v3-script
- [x] https://github.com/VolumeFi/curve-stop-loss-bot-script
- [x] https://github.com/VolumeFi/twap_bot_python_script

**Comment by webelf101** [comment]
Done.
