### ISSUE TITLE
[CHORE] Remove Wrapped Flow from Curve token list. It's Uniswap and Sushiswap

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2086]
{"id":"wrapped-flow","symbol":"wflow","name":"Wrapped Flow","platforms":{"ethereum":"0x5c147e74d63b1d31aa3fd78eb229b65161983b2b"}}

Remove from the Curve token lists.

**Comment by webelf101** [comment]
Done.

**Comment by taariq** [comment]
@webelf101 do we need a PR?
