### ISSUE TITLE
bug: account sequence mismatch error on continuous transactions.

### ISSUE THREAD

**Issue by webelf101** [VolumeFi/paloma#209]
# What is happening?
As a user, when I tried to send 2 transactions to Paloma continuously using python sdk, the first transaction was successful but the second transaction failed as an account sequence mismatch error.
In my understanding, the first transaction was broadcasted but it wasn't put into the block. So the lcd server returns the sequence number before the first transaction. So to make the second transaction successful, I must wait a moment(~ block time) and send the second transaction after the first transaction.
In EVM chains, the nonce number is a similar concept and the server returns the nonce number including the pending transactions.
I'd like to get the sequence number of an account including the pending transactions that are waiting for the next block but not included in the blocks.

**Comment by taariq** [comment]
@webelf101 will you share the transaction hashes of the successful transaction?

**Comment by webelf101** [comment]
SyncTxBroadcastResult(txhash='95421878369BB9696508F38DEF03DF32E22C7F5D8FF01E9A2D1AF7F10EC27CF3', raw_log='[]', code=0, codespace='')
https://lcd.testnet.palomaswap.com/cosmos/auth/v1beta1/accounts/paloma1flgt0un95wlj2j6ws4xfsw5vfefmvzm98rx60l
SyncTxBroadcastResult(txhash='23BCE01911A41A402C65E5E06DEDDBEE970736F220AB2B6159835CF167B7477F', raw_log='[]', code=0, codespace='')
These are the successful transactions that I put 6 seconds delay.

**Comment by verabehr** [comment]
I think this might actually be expected, since it sounds like 2 transactions are being sent in the same block from the same key. The workaround was to wait 6 seconds before sending the second transaction which is pretty much the workaround @ToasterTheBrave implemented in pigeon

**Comment by ToasterTheBrave** [comment]
Yes, @verabehr is exactly right.  We hit this same issue with Pigeon and that was the solution.

**Comment by verabehr** [comment]
kk, closing then

**Comment by webelf101** [comment]
It isn't technically impossible. I will test an example again.
