### ISSUE TITLE
[BUG] When attempting to trade 3000 AUSD to USDT, user gets insufficient amount

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2091]
[BUG] When attempting to trade 3000 AUSD to USDT, user gets insufficient amount and is unable to execute the TWAP on the front-end. 

It appears that we do not have the correct routes from?

![Image](https://github.com/user-attachments/assets/17d5565c-adf7-4012-a117-b41057170cb6)

Also from the user:
> when we put 30k (which is worth 1 USD per AUSD) it does a wrong multiplication

![Image](https://github.com/user-attachments/assets/57a6c9c4-b7ca-4c45-b29b-ec862a186518)

**Comment by jamie088** [comment]
@webelf101 This is the API issue. AUSD token decimals is 6 but I got 18 from api.

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/paloma-nest-service/pull/93
