### ISSUE TITLE
[Chore] Upgrade to `cosmos-sdk 0.50.10` to support `cosmwasm-2.0.0`

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#2092]
I've been playing around with this a bit, but I've ran into a weird issue ultimately:

`Could not lock exclusive.lock. Is a different VM running in the same directory already?`

This comes from [here](https://github.com/CosmWasm/wasmvm/blob/4728aa17c84bd666850b94749a287595977bb146/internal/api/lib.go#L62), and looking at our implementation, there should only be one VM active.

I also upgraded `libwasmvm` to `2.1.2`, but to no avail. Clearing the file manually yields no results, neither does clearing the entire cache directory.

There's two branches on Pigeon and Paloma's VolumeFi repositories called `clohr/cosmos` with the changes, but I will table this for now to focus on more pressing matters.

**Comment by taariq** [comment]
@byte-bandit as confirmed, let's upgrade to https://github.com/cosmos/cosmos-sdk/releases/tag/v0.50.10

**Comment by taariq** [comment]
@byte-bandit Alessio would like us to merge in his change https://github.com/cosmos/cosmos-sdk/pull/21653 so that he is able to run his paloma Lightnode with better security. Will you also confirm the effort to merge this in for the upgrade?

**Comment by byte-bandit** [comment]
I think maybe another day on top of the rest for the fresh changes.

**Comment by taariq** [comment]
> I think maybe another day on top of the rest for the fresh changes.

Then let's leave it out. We can upgrade to it when it's in the next release. We're not under deadline for this feature. Thanks for the estimate.

**Comment by taariq** [comment]
Closing as shipped and deployed!
