### ISSUE TITLE
[BUG] insufficient funds to cover gas estimate error on gnosis chain

### ISSUE THREAD

**Issue by webelf101** [VolumeFi/paloma#2094]
https://gnosisscan.io/tx/0x96ff51fce676e37bbf2a24fa9085aeec42b687291b2d59981143051d55cb3fe2
gas limit is 298410 but relayer gas estimate parameter equals 362703
That leads to "Insufficient funds to cover gas estimate" error.
No valset update comes on gnosis chain.

**Comment by byte-bandit** [comment]
@webelf101 At the moment, you'll need to simply slap that estimate value on the message as gas. There is no quick solution for this other than reducing the estimate, which will take time.

**Comment by byte-bandit** [comment]
@webelf101 I thought this was about a stuck SLC, but I see now. I'll take a look, thank you.

**Comment by webelf101** [comment]
It happend on gnosis chain in reverted tx. But originally, they shouldn't be run if the tx would fail, and I should have not been able to see. It's weird. That means even though there is the same issue on the other chains, we may not be able to see until the pigeon force to run the failed tx. @byte-bandit
