### ISSUE TITLE
[BUG] Pigeons attest transactions that got rolled back

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#2095]
For example this: https://gnosisscan.io/tx/0xb282d6d6f7c3fc31dbbf556e512f0558be74c16e0959eccb7e127279073dabf2

The TX was reverted, but the valset ID got marked as deployed on Paloma.

**Comment by maharifu** [comment]
Closed with https://github.com/palomachain/paloma/pull/1284 and https://github.com/palomachain/pigeon/pull/433
