### ISSUE TITLE
[LIGHTNODE] Implement Transak to Purchase LightNode with Fiat

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2096]
As a user, I want to use the Transak API to purchase my LIghtNode with Fiat if I do not have any tokens so that I am able to purchase the software with my credit card.

**Acceptance Criteria**
1.  Users can select the purchase method on the Front-end when pressing **"Select Chain/Credit Cards"**
Design: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=2602-655&t=DKBe2ZvjvleexI90-4
3. Specify the amount to purchase as the amount from the LightNode Sale
4. Select target chain for purchase as Arbitrum for fiat purchase
5. Specify the Nodesale purchase wallet address for deposit
6. All purchases must be for crypto with **USDC (Arbitrum)** so that users are still paying in dollars for their purchase.NOTE: Additional Transak information here: https://docs.transak.com/docs/pass-information-on-behalf-of-the-user-and-skip-screens
7. If user select transak option for purchase, then we will create the FiatBot contract address to receive money from Transak.
8. Once receiving USDC token from Transak service, then we can call the pay_for_token, activate_wallet function in PalomaNodeSaleContract directly by using paloma.
9. Develop Factory, FiatBot Vyper contract, FiatBot Cosmwasm contract, and API for pruchase and activatewallet.
10. Transak users will have their own fiatbot per users and that bot address will be used as receipient address and we can manage all the steps by using Paloma(Compass-EVM) 
11. Front-End call api only and implement transak to receive USDC into fiatbot on frontend side

**Comment by joycehermosilla** [comment]
I added a Design Link.

**Comment by fullstack412** [comment]
@joycehermosilla can you let me know the design link please?

**Comment by taariq** [comment]
Closing as shipped. We're debugging now.
