### ISSUE TITLE
[BUG] Unable to use BNB to purchase node on BNB chain

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2098]
Attempted to spend BNB to purchase node. 

Purchase address: 0x83334ef0C6f6396413C508A7762741e9FD8B20E9

Error Log: 
anonymous) @ framework-fee8a7e75612eda8.js:9
purchase/:1 Access to fetch at 'https://volume.liquify.com/api=0440032/bsc' from origin 'https://www.palomachain.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
_app-25f6b9ac24f82efa.js:1 

Solution: Please only use quicknode for API. Please check Quicknode for the endpoint.

**Comment by jamie088** [comment]
@taariq Please share the quiknode url for BNB chain.

**Comment by taariq** [comment]
@jamie088 you are already a member of our Quicknode account. Please login and check.

**Comment by taariq** [comment]
@jamie088 https://dashboard.quicknode.com/endpoints
