### ISSUE TITLE
New Palomaswap UI

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#21]
**_WELCOME_**

- [ ]  As a user that arrives at Paloma Swap we should show a Welcome Message with a 2 call of action.

<img width="486" alt="1" src="https://user-images.githubusercontent.com/19958639/222997102-0a3ed1b3-682d-4413-b4bb-4049a35140ef.png">

https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=5659%3A12944&t=4ghRTHvYM7sd36Su-4

- [ ] The user can either “Earn Tokenback now” and be redirected to the Swap View (app) or
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=5892%3A10795&t=4ghRTHvYM7sd36Su-4

- [ ] If the user presses on the second call of action “Join the Community” we should redirect the user to the Discord community: https://discord.gg/tNqkNHvVNc

**SELECT DEX AND CHAIN**
- [ ] When the user lands on the Paloma Swap app they will need to select a Chain and a DEX where they want to SWAP.

https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=5860%3A10791&t=4ghRTHvYM7sd36Su-4

- [ ] On this view the user will see the Connect Wallet button disabled until they select a DEX and Chain.

<img width="523" alt="2" src="https://user-images.githubusercontent.com/19958639/222997110-1f69eb1c-26d2-4631-a888-26778417f35d.png">

- [ ] After selection both DEX and Chain the button will enable to the user be able to Connect their EVM wallet on the selected chain.

<img width="540" alt="3" src="https://user-images.githubusercontent.com/19958639/222997132-f3f162aa-e52a-45dd-a182-c565e8b3d84d.png">

**CONNECT WALLET**

When user presses Connect Wallet, will be redirected to the Connect Wallet flow that has 2 simple steps:

- [ ] First the user will connect a Wallet using Metamask or Wallet Connect on the chain they already select.

- [ ] Second, if the user has installed Paloma Nest Wallet will open the Chrome Extension to connect to Paloma Swap via Nest.

- [ ] If the user doesn’t have Nest installed, the button will say Download Paloma Nest Wallet and will be redirected to Chrome Store to download it.

**SWAP**

- [ ] After connects wallet the user will be redirected to the Swap view. Where they will be able to see the DEX where are they swapping, the chain and select the tokens.

**Comment by taariq** [comment]
Closing as we will not be focused on this to focus on the bots.
