### ISSUE TITLE
Vote Distribution Bot Vyper Contracts 

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#210]
# Background

_Vote distribution bot is a vote automation service. The use case of this ticket is the StakeDAO vote APR chaser bot. It is aimed to automatically vote the highest APR gauge for users._
_We need vyper contracts with functions to vote, claim, deposit and withdraw on StakeDAO._

# Done when
As a user, I want vyper contracts with the following function to help me finish the entire voting process on StakeDAO 
- [ ] swap(): swap user input token for SDT 
- [ ] lock(): lock SDT to get veSDT on StakeDAO
- [ ] vote(): vote for a gauge on StakeDAO
- [ ] claim(): claim rewards from a gauge
- [ ] withdraw(): convert veSDT to SDT, swap to ETH and send back to the user

**Comment by taariq** [comment]
Add for Convex as well

**Comment by verabehr** [comment]
Review comments: https://github.com/VolumeFi/vote-distribution-bot-vyper/pull/1

**Comment by verabehr** [comment]
Closing for now. We're moving on to fee collection first
