### ISSUE TITLE
[BUG] Lightnode doesn't allow me to activate a new node with same EVM Wallet

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#2102]
As I already bought a node, I cannot activate a new node with the same EVM Wallet. 

1. Node: paloma1y7fktjm0f2wdvjw2fgcjs78gs6f3xu988seepq
2. Node: paloma19ahtjv5weu024kkn5cdhcrtffxxfcw48pa7q4s

![Image](https://github.com/user-attachments/assets/3ecb09c5-7d0b-4cc0-b9de-e45aa47048b7)

**Comment by jamie088** [comment]
Fixed with https://github.com/palomachain/website/pull/126
