### ISSUE TITLE
[LIGHTNODE SALE] Used Paloma Address check on Validator Form

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2103]
As a user who enters an already existing Paloma address into the activation form, I want the front-end to verify that my Paloma address is a new address with zero balance so that I will not be able to attempt to activate already used Paloma address.

**Acceptance Criteria**
1. When user attempts to activate, very address on Paloma has zero balance
2. If address has previous balance, return error to the user "The Paloma Wallet is already used. Please use your LightNode to activate your wallet"
3. Use RPC endpoint from NodeGuru

**Comment by jamie088** [comment]
@joycehermosilla Please new design for this ticket.

**Comment by joycehermosilla** [comment]
@jamie088 @taariq Design: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=2444-328&t=FA4Z6VwPBQctt1AQ-4
<img width="246" alt="Captura de pantalla 2024-09-02 a las 18 12 39" src="https://github.com/user-attachments/assets/b39de1f5-c897-4bb0-b286-e0deda3baed3">

**Comment by taariq** [comment]
Fixed.
