### ISSUE TITLE
[BUG] Lightnode syncing status (storing used paloma address in all evm chains) after nodesold event doesn't work sometimes.

### ISSUE THREAD

**Issue by fullstack412** [VolumeFi/paloma#2106]
Just reviewed the log. paloma tx was successful. but it's I need to re-run the sync cosmwasm contract function until it's fully synced.

**Comment by taariq** [comment]
@fullstack412 why did the sync fail?

**Comment by fullstack412** [comment]
not sure. sync failed in matic chain 2 times, and 1 times in bnb, op chains. 
anyway, in this case, i need to rerun the tx until it works.

**Comment by fullstack412** [comment]
@taariq

**Comment by fullstack412** [comment]
I can't see submit_logic_call function in matic compass.

**Comment by taariq** [comment]
FYI @byte-bandit @maharifu @webelf101

**Comment by fullstack412** [comment]
https://github.com/VolumeFi/paloma_nodesale/pull/13
@taariq

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/paloma_nodesale/pull/13
