### ISSUE TITLE
[PALOMABOT] Re-enable Uniswap V3 TWAP bot on Palomabot.ai with new contracts.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2110]
CHORE: Re-enable Uniswap V3 TWAP bot on Palomabot.ai with new contracts for the following chains.
1.0x7d0FB75FCE1820Fd7D1ecC228512608Be80839C9 ARB
2. 0xa2d6bd947CDFA804D1a52987d3A50E6CF8F3550b BSC
3. 0x58506B2D11C33237f47d56e3117E557E71AEA55E ETH
4. 0x4495467f9cD04faF5fa65ed34AF335d4e2e7e129 OP
5. 0x1cD913ED4A88E14891eB4cd229197bb1a42b603E MATIC

**Comment by jamie088** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/491
