### ISSUE TITLE
[LIGHTNODE] Activated users want their correct GRAINs after #2105 fix

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2111]
Activated wallet https://paloma.explorers.guru/account/paloma1e7d3u4232hqxrh45wwyxzw0q5u7yf2uhqkg58r wants to know how to get his 50K GRAINs after resolution of #2105 issue.

Question: Will the amount be automatically adjusted in Poloma?

**Comment by maharifu** [comment]
@taariq The amount will not be adjusted by Paloma. The vesting accounts are immutable, we can't change the vesting amounts after creating them. The only way will be to activate a new license.
