### ISSUE TITLE
[LIGHTNODE]  Windows install. decryption failed: No secret key

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#2112]
Delegating 9000ugrain to palomavaloper1qxl8xy0rjl99zhaxgu4ffuegup9mh6qxdmcwkg
code: 0
codespace: ""
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: ""
timestamp: ""
tx: null
txhash: BFAE0FC7224486AC63EB0072638B1D23013E0B48B27568A9AD1976EDC100A89C

All done. Waiting for next cycle.
gpg: decryption failed: No secret key
migrate err for key mainkey.info: "exit status 2"

All done. Waiting for next cycle.
gpg: decryption failed: No secret key
migrate err for key mainkey.info: "exit status 2"

All done. Waiting for next cycle.

**Comment by maharifu** [comment]
@Cieloc Did this happen immediately after delegating? Or only on the next cycle, after an hour?

**Comment by Cieloc** [comment]
@maharifu This is still happening. Current logs:

PS C:\Users\mikea\password-store> docker run --pull=always -ti `
>>   -v $env:USERPROFILE\paloma-lightnode\.gnupg:/root/.gnupg `
>>   -v $env:USERPROFILE\paloma-lightnode\.password-store:/root/.password-store `
>>   palomachain/lightnode-client:v1 `
>>   automate
v1: Pulling from palomachain/lightnode-client
Digest: sha256:48fb3cc53fded40fc1ea46b590bb459fd56b35efda2295fb9dbd70a2d56d5d89
Status: Image is up to date for palomachain/lightnode-client:v1
Claiming all outstanding rewards
code: 18
codespace: sdk
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: 'must contain at least one message: invalid request'
timestamp: ""
tx: null
txhash: F459B28C94571DB676C0E9771B4CC82470E14A2462C949E95BC24E227ADE738A
Delegating 45000 over 5 validators

Delegating 9000ugrain to palomavaloper1wm4y8yhppxud6j5wvwr7fyynhh09tmv5fy845g
code: 0
codespace: ""
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: ""
timestamp: ""
tx: null
txhash: 08629FF7D02CB37FEBB54FDEBFAC0E63A76EDBFAA447342AD4C18368997F4F03

Delegating 9000ugrain to palomavaloper1j2zvqhxqycxlxj3stnmun8060wfhfw57n3znmt
code: 0
codespace: ""
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: ""
timestamp: ""
tx: null
txhash: 5B2B9E14CA3C3ACAFB3ABDB2B8F5FCE344EE48C44B49E8C59E5A775FD20E727C

Delegating 9000ugrain to palomavaloper1hsmnzawmnauy9qxkxzjqm2mpd20pmfaf5uj30x
code: 0
codespace: ""
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: ""
timestamp: ""
tx: null
txhash: 0FAC0864A65B7EBF779092957DC0EAA7D302E1C01E751977B96F31378F63A919

Delegating 9000ugrain to palomavaloper1swa5kcf9cl5dx2ypx0c5r9e5qdfnzp9w0yj7uv
code: 0
codespace: ""
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: ""
timestamp: ""
tx: null
txhash: 91D58B857284C8803B7A477AD175C62559A792C132D0CA274D8425EB755F9E9B

Delegating 9000ugrain to palomavaloper1qxl8xy0rjl99zhaxgu4ffuegup9mh6qxdmcwkg
code: 0
codespace: ""
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: ""
timestamp: ""
tx: null
txhash: BFAE0FC7224486AC63EB0072638B1D23013E0B48B27568A9AD1976EDC100A89C

All done. Waiting for next cycle.
gpg: decryption failed: No secret key
migrate err for key mainkey.info: "exit status 2"

All done. Waiting for next cycle.
gpg: decryption failed: No secret key
migrate err for key mainkey.info: "exit status 2"

All done. Waiting for next cycle.
gpg: decryption failed: No secret key
migrate err for key mainkey.info: "exit status 2"

All done. Waiting for next cycle.
gpg: decryption failed: No secret key
migrate err for key mainkey.info: "exit status 2"

All done. Waiting for next cycle.
gpg: decryption failed: No secret key
migrate err for key mainkey.info: "exit status 2"

All done. Waiting for next cycle.
gpg: decryption failed: No secret key
migrate err for key mainkey.info: "exit status 2"

All done. Waiting for next cycle.
gpg: decryption failed: No secret key
migrate err for key mainkey.info: "exit status 2"

All done. Waiting for next cycle.
gpg: decryption failed: No secret key
migrate err for key mainkey.info: "exit status 2"

All done. Waiting for next cycle.
gpg: decryption failed: No secret key
migrate err for key mainkey.info: "exit status 2"

All done. Waiting for next cycle.
gpg: decryption failed: No secret key
migrate err for key mainkey.info: "exit status 2"

All done. Waiting for next cycle.
gpg: decryption failed: No secret key
migrate err for key mainkey.info: "exit status 2"

All done. Waiting for next cycle.

**Comment by Cieloc** [comment]
Killing and restarting. Waiting for next cycle.

**Comment by maharifu** [comment]
@Cieloc please also check if the image was updated (it should print something at the beginning), because from your previous logs:
```
Digest: sha256:48fb3cc53fded40fc1ea46b590bb459fd56b35efda2295fb9dbd70a2d56d5d89
```
I believe this is not the latest version.

**Comment by Cieloc** [comment]
@maharifu Cool. Seems to be working now:

All done. Waiting for next cycle.
Claiming all outstanding rewards
code: 0
codespace: ""
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: ""
timestamp: ""
tx: null
txhash: D8701012B2146C9F39CDAB9EF3B297ECDAE08D321D9A49F59F0B9A114B330418
Delegating 800000004213 over 5 validators

Delegating 160000000845ugrain to palomavaloper1wm4y8yhppxud6j5wvwr7fyynhh09tmv5fy845g
code: 0
