### ISSUE TITLE
[BUG] Unable to purchase LightNode from BNB Chain. Transaction did go through, but sale does not progress

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2118]
BNB Purchase transaction: https://bscscan.com/tx/0xa1f6cf196ade461c8bfedcb0f4149d46d4fc84b2e93015ef7d46929f1f1c68a4

Errors received in the log:
[20240904_bsc_node_fail.log](https://github.com/user-attachments/files/16872203/20240904_bsc_node_fail.log)

Image 

![Image](https://github.com/user-attachments/assets/733e5c34-e0ba-4537-9250-dc174fa07d33)

**Comment by jamie088** [comment]
@fullstack412 Could you please check if this purchase tx worked correctly?

**Comment by fullstack412** [comment]
Yes. tx was successful
{"nodesale_id":"12","buyer":"0x83334ef0C6f6396413C508A7762741e9FD8B20E9","token_in":"0x0000000000000000000000000000000000000000","fund_usd_amount":"50000000","fee_usd_amount":"5000000","subscription_usd_amount":"0","slippage_usd_amount":"250000","estimated_node_count":1,"node_count":null,"promo_code":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"12","paloma_address":null,"grain_amount":null,"status":0,"network_name":"bnbnodesale14","tx_hash":"0xa1f6cf196ade461c8bfedcb0f4149d46d4fc84b2e93015ef7d46929f1f1c68a4","eth_sync":false,"arb_sync":false,"base_sync":false,"op_sync":false,"matic_sync":false,"bnb_sync":false,"created_at":"2024-09-04T14:23:30.710Z","updated_at":"2024-09-04T14:23:30.710Z"}]
@taariq @jamie088

**Comment by taariq** [comment]
Is this issue resolved?

**Comment by fullstack412** [comment]
@jamie088 
??? status?

**Comment by jamie088** [comment]
@taariq No issue, your transaction was executed successfully.

**Comment by taariq** [comment]
> @taariq No issue, your transaction was executed successfully.

So @jamie088 why couldn't I finish the purchase and how do I avoid the error log in the future?
