### ISSUE TITLE
[LIGHTNODE] As a user, I want to be able to use an 8 digit aphanumeric PROMO code or PROMO CODE URL

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2119]
As a user, I want to be able to use an 8 digit aphanumeric PROMO code when purchasing my Lightnode so that my PROMO code can be an interesting mix of numbers and letters.

**Acceptance Criteria**
1. Allow 8 Digit Alpha numeric Promo Code in the Front-end.
2. Allow 8 Digit Alpha numeric Promo Code to be used in back-end, but not maximum. We might make it bigger. 
3. Promo code persist in URL as https://palomachain.com/?code=ALPHAGROWTH so that the user does not need to type in the code.

**Comment by joycehermosilla** [comment]
Design: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=260-2322&t=GlhJ3d4L5gzJhl0D-4 @jamie088 @taariq

**Comment by joycehermosilla** [comment]
@jamie088 @taariq I deleted the Design. I was confused. One thing is the 4-digit Code to access the purchase flow. and the other is the promo code. My mistake sorry.

**Comment by jamie088** [comment]
@taariq Could you please write more details about `3. Promo code persist in URL as https://palomachain.com/?code=ALPHAGROWTH so that the user does not need to type in the code.`?

**Comment by joycehermosilla** [comment]
Means after user generate Promo code the front-end should generate a customised URL for each code. And user will be able to copy and paste it. @jamie

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jamie088** [comment]
@taariq @joycehermosilla When a user applies a promo code, do I change the URL to one that includes the promo code?
like this: https://www.palomachain.com/purchase/?code=ALPHAGROWTH
![image](https://github.com/user-attachments/assets/fcfb7e40-7e7a-4ac3-a4bd-878ae83805b8)

**Comment by joycehermosilla** [comment]
This is good. But more important is by Promo Code creation. See designs here: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=2879-634&t=dmDT3wb8dgEizMl9-4
 @jamie088

**Comment by taariq** [comment]
This is done.
