### ISSUE TITLE
[LIGHTNODE SALE] Ubuntu Linux instructions.

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#2123]
Add the Instructions for Linux OS.

Designs: 
https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=1965-910&t=zVIO8QNknMngeOT3-4

**Comment by taariq** [comment]
closed with https://github.com/palomachain/website/pull/142
