### ISSUE TITLE
[LIGHTNODE SALE] API: estimated price api

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#2124]
- [x] GET api for estimated node price api

**Comment by fullstack412** [comment]
@jamie088 
e.g. https://nodesale.palomachain.com/api/v1/estimateprice?estimate=654&promo_code=[hex-value]
estimateprice api

if user don't input promo code, you can call the api with estimate params only
e.g. https://nodesale.palomachain.com/api/v1/estimateprice?estimate=654

**Comment by jamie088** [comment]
Fixed with https://github.com/palomachain/website/pull/135
