### ISSUE TITLE
[LIGHTNODE SALE] Lightnode MAC OS Installation instructions

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#2129]
- [ ] Remove this step. Download Setup and run setup should be the last step.
![Image](https://github.com/user-attachments/assets/13812704-f5c0-41c4-8d1c-e137a02e664b)

Designs: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=1-4378&t=025zTtSoX262KaC3-4

- [ ] Update MAC OS and Windows Instructions based on current Figma versions.

**Comment by taariq** [comment]
Closing as incorrect.

**Comment by taariq** [comment]
@jamie088 this ticket is correct. I was incorrect. apologies @joycehermosilla

**Comment by taariq** [comment]
@joycehermosilla let's discuss. It's unclear from Figma what the right instructions are to be.

**Comment by taariq** [comment]
This is fixed.
