### ISSUE TITLE
[BUG] Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2133]
Purchasing Wallet: 0x6796760159bcE5d58C6Cb26822ad187892703F4A
Paloma Node Wallet: https://paloma.explorers.guru/account/paloma1hhugcymucypjdyu5gh03qs2vmau4e9ehlcz824

Error: Invalid paloma address. Please confirm your paloma address again.

![Image](https://github.com/user-attachments/assets/2f82335d-a794-4aca-8c4e-88ffdea213c7)

**Comment by fullstack412** [comment]
@taariq ?

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/paloma_nodesale/pull/15
