### ISSUE TITLE
Resolve `v2` resolution issue in Pigeon `go.mod`

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#2136]
We can no longer reference Paloma versions directly from Pigeon since we upgraded to a version higher than 1 due to the go mod versioning system. We will need to add a `/v2` suffix to our Paloma `go.mod`, but I forgot to do this for `2.2.0`.

**Comment by taariq** [comment]
@byte-bandit this going into the next release?

**Comment by taariq** [comment]
@maharifu you okay to take over this one?
