### ISSUE TITLE
[BUG] Whoops! An error occurred: {'transaction underpriced: gas tip cap 245466, minimum needed 1000000000'}

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2142]
when attempting `python promocode_ledger.py create_promo_code ALPHAGROWTH 0x6e57181D6b4b7c138a6F956AD16DAF4f27FC5E04 BSC`

  warnings.warn(
Creating promocode...
Promo code:  ALPHAGROWTH
Promo code HEX:  0x000000000000000000000000000000000000000000414c50484147524f575448
Recipient:  0x6e57181D6b4b7c138a6F956AD16DAF4f27FC5E04
Chain name:  BSC
RPC URL:  https://bsc-dataseed1.binance.org/
Derived Path:  44'/60'/71'/0/0
Nodesale contract address:  0x496C48d24a33B1Fd45782537eBd42157Bf265703
ENV variables MAX_ACCOUNTS_FETCH:  100
Whoops! An error occurred: {'code': -32000, 'message': 'transaction underpriced: gas tip cap 245466, minimum needed 1000000000'}

**Comment by fullstack412** [comment]
https://github.com/VolumeFi/w3tools/pull/15

@taariq 
It looks BSC gas estimation error.
I added the manual gas fee for BSC chain.
