### ISSUE TITLE
[DEVOPS] Sentry Alert on LCD server needs to be addresssed is consuming credits

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2144]
https://volume-x3.sentry.io/issues/5027929070/?project=6380489&referrer=project-issue-stream&statsPeriod=30d

**Comment by maharifu** [comment]
@taariq Where is this event coming from? The event says it's coming from `mainnet-validator`, but I don't see this service running there.
It also says it's coming from a VM with 64GB of RAM running Ubuntu 18.04, in the `Europe/Amsterdam` timezone. However, as far as I know, we have no VMs with that amount of memory, or running that OS. Do we have any other VM outside linode?

**Comment by maharifu** [comment]
The private key to Sentry was removed from the node_reset repo and the LCD project removed from Sentry.
