### ISSUE TITLE
[LIGHTNODE SALE] Activate instructions for MAC, Windows and Linux

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#2146]
After the Activation flow, we need to show instructions on how to activate using the terminal. The instructions are different for Windows, Mac, and Linux.

Designs: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=2605-907&t=GhEmAAFTKzaG3NEx-4

**Comment by jamie088** [comment]
Fixed with https://github.com/palomachain/website/pull/143
