### ISSUE TITLE
[LIGHTNODE SALE] PROMO CODE UI

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#2147]
A valid promo code should be added to the purchase total when a user adds a valid promo code.

- [ ] Input code UI. 
![Image](https://github.com/user-attachments/assets/a4036e1d-0f2a-4a8c-8193-366090510ce4)

- [ ] Valid Promo code add to the total
![Image](https://github.com/user-attachments/assets/0f24768d-705b-418c-8be7-5719180c3fba)

Designs: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=2658-419&t=0WmDcW7lLKI3sUDJ-4

**Comment by taariq** [comment]
Closing as shipped.
