### ISSUE TITLE
[LIGHTNODE] As a Paloma LIghtnode user, I want to use my Ledger hardware wallet with my Paloma LightNode

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2148]
As a Paloma LIghtnode user, I want to use my Ledger hardware wallet with my Paloma LightNode so that I am able to add my Ledger Grains to my Lightnode for staking.

**Acceptance Criteria**
1. Enable LIghtnode to add Ledger keys
2. add the `add-leger` option for Ledger keys.

**Comment by maharifu** [comment]
Closed with https://github.com/VolumeFi/lightnode-client/pull/17
