### ISSUE TITLE
[BUG] Unable to activate Lightnode on MacOS no keys found

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2154]
MacOS: 12.7.6 (21H1320)
2.7 GHz Dual-Core Intel Core i5
 
**Problem:** Mac fails to initials keystore. 
**No pasword created in password store**
 
h $HOME/Downloads/setup.sh activate
v1: Pulling from palomachain/lightnode-client
Digest: sha256:58f0e9024163c859eba661f413e888afe975596d1c05f39a69e0f1f4c5b15ed6
Status: Image is up to date for palomachain/lightnode-client:v1
No keys found. Please finish your node setup first.
node@Nodes-MacBook-Pro ~ % sh $HOME/Downloads/setup.sh automate
v1: Pulling from palomachain/lightnode-client
Digest: sha256:58f0e9024163c859eba661f413e888afe975596d1c05f39a69e0f1f4c5b15ed6
Status: Image is up to date for palomachain/lightnode-client:v1
Failed to unlock keys.
node@Nodes-MacBook-Pro ~ % sh $HOME/Downloads/setup.sh automate
v1: Pulling from palomachain/lightnode-client
Digest: sha256:58f0e9024163c859eba661f413e888afe975596d1c05f39a69e0f1f4c5b15ed6
Status: Image is up to date for palomachain/lightnode-client:v1
 
Available actions:
 
setup-node	Create a key, store it safely, and activate your node.
add-node	Create a key, store it safely, and activate additional nodes.
show-keys	Display all available paloma keys.
import-key	Import your existing key using the mnemonic.
activate	Activate your account and start vesting.
claim-rewards	Claim all outstanding rewards.
redelegate	Delegate your available tokens to all available validators.
automate	Automatically claim rewards and redelegate stake for all keys, every 24 hours.
node@Nodes-MacBook-Pro ~ % sh $HOME/Downloads/setup.sh show-keys 
v1: Pulling from palomachain/lightnode-client
Digest: sha256:58f0e9024163c859eba661f413e888afe975596d1c05f39a69e0f1f4c5b15ed6
Status: Image is up to date for palomachain/lightnode-client:v1
No records were found in keyring
node@Nodes-MacBook-Pro ~ % sh $HOME/Downloads/setup.sh import-key
v1: Pulling from palomachain/lightnode-client
Digest: sha256:58f0e9024163c859eba661f413e888afe975596d1c05f39a69e0f1f4c5b15ed6
Status: Image is up to date for palomachain/lightnode-client:v1
Initializing the password store. Please wait.
 
 
/Users/node/.config/paloma-lightnode
 
node@Nodes-MacBook-Pro Downloads % cd ~/.config/paloma-lightnode 
node@Nodes-MacBook-Pro paloma-lightnode % ls
node@Nodes-MacBook-Pro paloma-lightnode % pwd
/Users/node/.config/paloma-lightnode
node@Nodes-MacBook-Pro paloma-lightnode % ls 
node@Nodes-MacBook-Pro paloma-lightnode % ls -al
total 0
drwxr-xr-x  4 node  staff  128 Sep 10 11:46 .
drwxr-xr-x  3 node  staff   96 Sep 10 11:46 ..
drwx------@ 5 node  staff  160 Sep 10 11:57 .gnupg
drwxr-xr-x  2 node  staff   64 Sep 10 11:46 .password-store
node@Nodes-MacBook-Pro paloma-lightnode % cd .password-store 
node@Nodes-MacBook-Pro .password-store % ls
node@Nodes-MacBook-Pro .password-store % ls -al
total 0
drwxr-xr-x  2 node  staff   64 Sep 10 11:46 .
drwxr-xr-x  4 node  staff  128 Sep 10 11:46 ..
node@Nodes-MacBook-Pro .password-store % pwd
/Users/node/.config/paloma-lightnode/.password-store

    node@Nodes-MacBook-Pro .password-store %

**Comment by maharifu** [comment]
@taariq Seems you ddin't have any keys in `~/.config/paloma-lightnode` and tried to activate directly, without adding the keys first. Did you setup the node on this computer before? Where did you execute the setup script from at that time?

We try to find the old `./password-store` (relative) path first, and if not found, we fallback to `~/.config/paloma-lightnode`. Can you check if `./password-store` is there?

**Comment by taariq** [comment]
@maharifu we attempted to import-keys on the mac 

![Image](https://github.com/user-attachments/assets/a8125884-a096-4dd8-8af9-37ee1f5f36b6)

![Image](https://github.com/user-attachments/assets/046ae3d8-5bd8-471e-8732-3ac6b611467d)

**Comment by taariq** [comment]
@maharifu

**Comment by taariq** [comment]
@maharifu we have the logs

```
drwxr-xr-x  2 node  staff   64 Sep 10 11:46 .
drwxr-xr-x  4 node  staff  128 Sep 10 11:46 ..
node@Nodes-MacBook-Pro downloads % sh setup.sh import-key                            
v1-pinentrytty: Pulling from palomachain/lightnode-client
a2318d6c47ec: Already exists 
2a4db989566b: Pull complete 
b94dc33d49f9: Pull complete 
0f17fcb1deab: Pull complete 
b6fa33ac569f: Pull complete 
dbbd0f64fda5: Pull complete 
Digest: sha256:dc9c8c71af0ab33ef29e8f035ca32de53faa041f29ae98bca3b5adecdf69e855
Status:
Status: Downloaded newer image for palomachain/lightnode-client:v1-pinentrytty
Initializing the password store. Please wait.
+ gpg --batch --gen-key /etc/gpg.conf
gpg: error running '/usr/bin/gpg-agent': exit status 2
gpg: failed to start agent '/usr/bin/gpg-agent': General error
gpg: can't connect to the agent: General error
gpg: agent_genkey failed: No agent running
gpg: key generation failed: No agent running
node@Nodes-MacBook-Pro downloads %
```

**Comment by maharifu** [comment]
@taariq There are some reports around issues with shared volumes on docker for mac and VirtioFS. I'm not sure if this is the issue, but I pushed some changes to this container try to go around that. I also added some more debugging info. Can we try it one more time on this computer?

It would also be useful to gather some information about the docker setup on this PC. Specifically, the docker desktop version and the `file sharing implementation` setting. If this last one is set to VirtioFS (should be the default if recently installed), it's worthwhile to try to change to gRPC FUSE and see if that works.

**Comment by taariq** [comment]
@maharifu Same result and here's the output
```
Status: Downloaded newer image for palomachain/lightnode-client:v1-pinentrytty
HOME: /root
ID: uid=0(root) gid=0(root) groups=0(root)
gnupg:
total 12
-rw-r--r-- 1 root root 33 Sep 13 17:48 S.gpg-agent
-rw-r--r-- 1 root root 73 Sep 13 17:48 gpg-agent.conf
drwx------ 2 root root 64 Sep 10 18:52 private-keys-v1.d
-rw------- 1 root root 32 Sep 10 18:52 pubring.kbx
password-store:
total 0
Initializing the password store. Please wait.
+ gpg --batch --gen-key /etc/gpg.conf
gpg: error running '/usr/bin/
Initializing the password store. Please wait.
+ gpg --batch --gen-key /etc/gpg.conf
gpg: error running '/usr/bin/gpg-agent': exit status 2
gpg: failed to start agent '/usr/bin/gpg-agent': General error
gpg: can't connect to the agent: General error
gpg: agent_genkey failed: No agent running
gpg: key generation failed: No agent running
node@Nodes-MacBook-Pro downloads %
```

**Comment by maharifu** [comment]
This was identified as an issue with VirtioFS and Virtualization being active in docker for mac. Switching over to gRPC FUSE got it working fine.
