### ISSUE TITLE
[LIGHTNODE] As a user who has completed the Transak transaction and has to wait, I want a UI to tell me to check my email when my transaction is complete

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2157]
As a user who has completed the Transak transaction and has to wait for settlement, I want a UI to tell me to check my email when my transaction is complete so that I don't have to wait hours with my web browser for the transaction to complete.

**Acceptance Criteria**
1. Once the transak transaction is processing, show me a page with instructions to check my email when settlement is complete.
2. Send me an email link when the transaction is settled by transak to continue the purchase to the next step. NOTE Transak will send a success email as well.
3. Email Text:
Hi [Name],

Paloma received your purchase of XX.XX USD for YY Paloma LightNodes.  

You may now complete your LightNode purchase by clicking this link https://palomachain.com/continuepurchase link.

Thank you,
The Paloma Foundation

**Comment by joycehermosilla** [comment]
@taariq @jamie088 @fullstack412 Design: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=2639-1968&t=PTp0zynEAjPMCJGs-4

**Comment by taariq** [comment]
Closing as won't ship
