### ISSUE TITLE
[Skyway] Raise the last individual observed event nonce for all validators once a nonce becomes observed

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#2159]
Once an event becomes observed, we can safely raise the last observed nonce for all validators. This could prevent validators from being stuck trying to get old events after being offline for awhile. Also, since the event is already observed, having more validators attesting to it is just wasteful.

**Comment by taariq** [comment]
Shipped with https://github.com/palomachain/paloma/pull/1288
