### ISSUE TITLE
[Skyway] Paloma keeps a tap on outstanding pigeon evidences for events, pigeons can query those, and look directly at that block for the event in order to keep up

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#2160]
Instead of having pigeons go back a huge amount of blocks to get skyway events, we have pigeons query paloma for outstanding claims. Pigeons will then query these blocks directly for events and move on from there.

This should be used only when pigeons fall behind on events, so pigeons can keep their own events ordered.

**Comment by taariq** [comment]
Shipped.
