### ISSUE TITLE
[LIGHTNODE] [BUG] activate_wallet should be run on the purchased chain

### ISSUE THREAD

**Issue by fullstack412** [VolumeFi/paloma#2174]

**Comment by jamie088** [comment]
@taariq Can we change the activate flow so that activation can only be done on the Buymore board page? Current logic can't stop this problem.

**Comment by taariq** [comment]
@jamie088 Let's do it. We already have activate in the BuyMore Page as a CTA,.

**Comment by taariq** [comment]
Ths is fixed.
