### ISSUE TITLE
[LIGHTNODE] GRAINs are not automatically delegated with add-node

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#2176]
Today I bought a LightNode and the GRAINs were Delegated and collecting rewards. After some hours I added 2 nodes using the ``add-node`` command.

After checking Nodes Guru, I realized the 100,000 GRAINs were on "Delegatable Vesting," and I was not able to collect Rewards with the "automate" command. 

To be able to Delegate I needed to run ``redelegate``.

Why didn't I need to run this command with the first Node?

**Comment by maharifu** [comment]
Fixed with https://github.com/VolumeFi/lightnode-client/pull/18
