### ISSUE TITLE
[BUG] Add-ledger issues while testing on Linux

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2177]
Adding the ledger:
1. The text instructions say `add-ledger [account]` but it's not clear that the user needs to type in the command and an account name. If the setup prompts the user for an account, why dont' we simply have the command `add-ledger`?

2. Error 1: 
Delegating -10000ugrain to palomavaloper1am3k7czusdcewv55nhaugu2drn38af9464n65p
Error: unknown shorthand flag: '1' in -10000ugrain
Usage:
  palomad tx staking delegate [validator-addr] [amount] [flags]
  
3. Error 2: 
Error: decoding bech32 failed: invalid bech32 string length 5
Usage:
  palomad tx authz exec [tx-json-file] --from [grantee] [flags]

4. Wrong Index
My GRAINs on my ledger are on index 1 not index 0. How do we have the user specify the index number? This is a new feature as we agreed to default to index 0, but I am not able to use this as the ledger I have uses index 1.

**Comment by maharifu** [comment]
@taariq The errors are all related to a bad setup. Can you post the full logs of what you were running? Also, can you post the result of `cat $HOME/.config/paloma-lightnode/.paloma/keys`?

The `[account]` argument is supposed to be the HD account index and defaults to 0. So in that case you should use `add-ledger 1`. I will update the help text to make it less confusing.

**Comment by taariq** [comment]
@maharifu output: 
```
cat $HOME/.config/paloma-lightnode/.paloma/keys
[DancingBanana] paloma182ettr33r6cjh5sly58rl75wzcw8dn65pmey6x
[Scroll] paloma1lsw2g9cpsmh28rd3rnlek8tuev9lkx60f8wwat
```

**Comment by taariq** [comment]
@maharifu for the instructions

`add-ledger [0]`

**Comment by maharifu** [comment]
@taariq Can we close this?
