### ISSUE TITLE
[BUG] Linux setup.sh and setup-v2.sh exit even though Docker is installed

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2178]
**Command:**
  `./setup-v2.sh`

**Error:** 
```
docker could not be found. Please install docker first.
/usr/bin/docker
```

`which docker`  returns docker on the system `/usr/bin/docker`

**Problem:** It seems the setup scripts checks for Docker, but my docker runs under sudo on Ubuntu. When I edit the setup script and remove the check and then add `sudo` to the docker command, the script works fine. I guess we need to check for sudo setups.

**Comment by maharifu** [comment]
@taariq Can you post the result of `command -v docker`?

**Comment by taariq** [comment]
> @taariq Can you post the result of `command -v docker`?

output `/usr/bin/docker`

**Comment by maharifu** [comment]
Fixed with https://github.com/VolumeFi/lightnode-client/pull/19
