### ISSUE TITLE
[BUG] Attempting to Purchase a node with a Credit Card using Transak, nothign happens

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2179]
user attempt to purchase node on mobile with Transak sees the image prompting for wallet, but nothing happens

![Image](https://github.com/user-attachments/assets/a9ba9ee9-e449-45dc-af31-29377621e8a1)

**Comment by jamie088** [comment]
@taariq It looks like a Buymore board page, but it's not a purchase page. e tried using a credit card, but why is he on the Buymore board page? User don't need to connect wallet when purchase with credit card on purchase page.

**Comment by taariq** [comment]
Closing as won't fix.
