### ISSUE TITLE
[PROMOCODE] As a Promo code creator, I want all PROMO codes creating from my code to give me 1% of their sales

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2188]
As a Promo code creator, I want all PROMO codes creating from my code to give me 1% of their sales up to 5 levels so that I am able to generate more revenue from my promo code and from encouraging all my buyers to buy and get a promo code.

**Acceptance Criteria**1
1. Create a unique attribute in the PROMO code: PALOMA01, PALOMA02, PALOMA03, PALOMA04, PALOMA05
2. The person who creates a PROMO code on the last level can create PROMO codes and all levels above will collect fees.

**Comment by Cieloc** [comment]
https://www.notion.so/volumefi/EPIC-09-20-24-Promo-Code-MLM-107e002bb621800a86e2ed1c5e7c460b

**Comment by fullstack412** [comment]
If we really need this, we need to upgrade nodesale vyper contract.

**Comment by Cieloc** [comment]
@fullstack412 yup @taariq is already aware. Since we are touching the contracts, it might make sense to make the promo code generation process easier while we are at it, but I believe this MLM feature is urgent.

**Comment by taariq** [comment]
@fullstack412 absolutely aligned and agreed. We will need to upgrade nodesale vyper contract which means we'll need t update the Promo code generation as this manaul process with the ledger won't work. Well need a ticket for that.

**Comment by Cieloc** [comment]
https://www.notion.so/volumefi/EPIC-09-26-24-Promocode-Upgrade-10ce002bb62180fb89a2f105e378f802?pvs=4#10ce002bb621801e9e8acd4cbfdf4bd9
