### ISSUE TITLE
[PROMOCODE] As a Promocode owner, I want an email alert when someone uses my Promo code to purchase

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2190]
As a Promocode owner, I want an email alert when someone uses my Promo code to purchase so that I feel good and I know how much money I made with that purchase and how much commission I can claim.

**Acceptance Criteria**
1. Generate email for the user congratulating them on receiving the commission
2. Show the commission for the sale and total commissions generated to date
3. Provide a link for the promoter to login to Paloma and claim their commission
4. Email text:
     "COO! COO! Coongratulations LIghtNode Pigeon! Your Promocode [CODEID] was just used to purchase $X,XXX.00 of Paloma LIghtNodes. 

     Your Commission reward earned is $X,XXX.00 !!
     Your Total Commission rewards earned is $X,XXX.00!!

     Login to the Paloma BuyMore Board to claim your commission and buy more Paloma LightNodes here: 
https://www.palomachain.com/purchase/login/?type=board&redirect=/buy-more-board

REMINDER: Your purchases cannot be claimed until users ACTIVATE their Paloma LightNodes. Please remind all your buyers to activate their LightNodes immediately.

COO! COO!
Paloma

**Comment by Cieloc** [comment]
We should keep in mind that once the MLM Sell more board functionality goes live, we may need to send alerts to as many as 5 reward recipients.

**Comment by taariq** [comment]
@fullstack412 Is this done?
