### ISSUE TITLE
[PROMOCODE] As an admin, I want promo code requests to be automatically provisioned from the server

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2194]
As an admin, I want promo code requests to be automatically provisioned from the server so that I don't have to use a ledger and the private key for gas can be placed on a server.

**Acceptance Criteria**
1. Create a Promocode admin key to hold gas for promocode provisioning
2. Update nodesale contracts so the promocode key only used for promo gas
3. Update promocode provisioning so that the key is on the server when customer requests promo code and no manual intervention will be needed.

**Comment by Cieloc** [comment]
This Promocode admin key should be able control the create, edit, and delete of promocodes and nothing else.

**Comment by taariq** [comment]
Closing as not needed.
