### ISSUE TITLE
[BUG] User unable to claim Bonus See attached video

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2195]
See attached video https://github.com/user-attachments/assets/f69e4887-d44f-45f4-abae-8d33903e9ff4

![Image](https://github.com/user-attachments/assets/6304093f-f192-4fb4-95ff-0a4aef1f36a3)

**Comment by cosmoscats** [comment]
My ETH address is 0xf932AB73EAB43AA248A2932368B6f008ea607Fb0

This is what i see in brave browser console

Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: No claimable", method="estimateGas", transaction={"from":"0xf932AB73EAB43AA248A2932368B6f008ea607Fb0","to":"0x8050371F14Bb6E2395E936611615BE41237faF02","data":"0x4e71d92d","accessList":null}, error={"code":-32603,"message":"execution reverted: No claimable","data":{"originalError":{"message":"execution reverted: No claimable","code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000c4e6f20636c61696d61626c650000000000000000000000000000000000000000"}}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)

If you need additional info, let me know

**Comment by fullstack412** [comment]
@cosmoscats You have to use `0x38F9D425BC788Ce281E79B177594A212dDe4Aa04` this address to claim your reward.

**Comment by taariq** [comment]
closing as fixed.
