### ISSUE TITLE
[BUG] Snapshot is not compressed and downloads appear to halt

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2197]
![Image](https://github.com/user-attachments/assets/e6db9288-3c23-4970-9d44-267ab6ec7112)

![Image](https://github.com/user-attachments/assets/09f09bb9-62bf-4989-98a6-273afaf4b6e9)

1. it appears the snapshot is not compressed
2. It appears the snapshot does not complete properly so downloads appear to stop

**Comment by maharifu** [comment]
@taariq 

1. They are already compressed with bzip2, despite being named `.gz`. I renamed the files to reflect this.
2. I don't understand what this means?

**Comment by taariq** [comment]
It appears to be working. closing.
