### ISSUE TITLE
[BUG] rpc error: code does not allow to pay fees fee-grant not found

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2198]
Delegating 175264265ugrain to palomavaloper1z9fgzh7mzqgu33pdkxw0dqmqgm9l8exj6rl5wj
Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = l�P��u��kr��S��N� does not allow to pay fees for E���*���Y�k�Ჽ��: fee-grant not found: not found [/home/aptostake/go/pkg/mod/[cosmossdk.io/errors@v1.0.1/errors.go:151](http://cosmossdk.io/errors@v1.0.1/errors.go:151)] with gas used: '8847': unknown request
Usage:
  palomad tx authz exec [tx-json-file] --from [grantee] [flags]

**Comment by maharifu** [comment]
@taariq Do you have the address of the node that was trying to run this tx?

**Comment by taariq** [comment]
@maharifu 
1. paloma1qek2sp2srne2zav3694h9l7s2wuwcn5psv48pg 
2. paloma182ettr33r6cjh5sly58rl75wzcw8dn65pmey6x

These two addresses.

**Comment by maharifu** [comment]
> @maharifu
> 
>     1. paloma1qek2sp2srne2zav3694h9l7s2wuwcn5psv48pg
> 
>     2. paloma182ettr33r6cjh5sly58rl75wzcw8dn65pmey6x
> 
> 
> These two addresses.

Did you have the error on both?

paloma1qek2sp2srne2zav3694h9l7s2wuwcn5psv48pg does not have any grant, but paloma182ettr33r6cjh5sly58rl75wzcw8dn65pmey6x seems to have all correct grants to paloma1gh3c0mqrrc40057vtydxhy8pk27a5yhffpsh23.

On paloma1qek2sp2srne2zav3694h9l7s2wuwcn5psv48pg, can you run `node-recover` and try again?
And if you still have error on paloma182ettr33r6cjh5sly58rl75wzcw8dn65pmey6x run `node-recover` on it as well.

**Comment by taariq** [comment]
Closing as instructed.
