### ISSUE TITLE
Create an API to get the best Curve swap route for AAVE stable yield chaser vault

### ISSUE THREAD

**Issue by webelf101** [VolumeFi/paloma#2202]
# Background

We are building some backend scripts in Python and we need to get the best swap route on Curve swap.

But Curve SDK provides JavaScript SDK only.

And the SDK doesn't support `require` statement that we can use in our bot-info-api because our bot-info-api uses too old coding type.

# Done when

- [x] Create an API endpoint for the API to get the best curve swap route.
- [x] Create a service for the API.

**Comment by taariq** [comment]
Thank you! Closing as fixed!
