### ISSUE TITLE
[LIGHTNODE] As a user, I want the Purchase Processing Fee to be 10% of the Lightnode Purchase Price rounded up to the nearest Dollar

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2203]
As a user, I want the **Purchase Processing Fee** to be 10% of the Lightnode Purchase Price rounded up to the nearest Dollar so that I pay the Purchase Processing Fee per Lightnode as a reasonable cost of my LightNode setup.

**Acceptance Criteria**
1. Update the Purchase Processing Fee to 10% of 1 node price, rounded up to the nearest dollar.

**Comment by fullstack412** [comment]
@taariq Please follow this directions

https://etherscan.io/address/0x8050371F14Bb6E2395E936611615BE41237faF02#writeContract
https://bscscan.com/address/0x2f78AfAdD7E58052c4a8789dc01A1eD49848cc0C#writeContract
https://arbiscan.io/address/0x249cE7e8c5A0f7300f9c45Af70c644b39dABa4dB#writeContract
https://basescan.org/address/0x2f78AfAdD7E58052c4a8789dc01A1eD49848cc0C#writeContract
https://optimistic.etherscan.io/address/0x496C48d24a33B1Fd45782537eBd42157Bf265703#writeContract
https://polygonscan.com/address/0x496C48d24a33B1Fd45782537eBd42157Bf265703#writeContract
In these page, please `run set_processing_fee` function
`_new_processing_fee` : 6000000 (in case of $6)
`_new_subscription_fee` : 50000000

**Comment by taariq** [comment]
Fixed and run. Thank you!
