### ISSUE TITLE
[LIGHTNODE] As a Coinbase user, I want to see a Coinbase Wallet option to pay to purchase a LightNode

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2204]
As a Coinbase user, I want to see a Coinbase purchase selection to pay to purchase a LightNode with either my Coinbase account or my credit card.

**Acceptance Criteria**
1. In the payment drop-down, Add Coinbase Wallet payment option
2. Use the Coinbase Onramp API to start the purcahse flow https://docs.cdp.coinbase.com/onramp/docs/api-overview
3. Use the Coinbase wallet to settle the LightNode purchase via Coinbase Wallet
4. @joycehermosilla Please provide UI for payment option.

From: 
**Add funds to a linked self-custody wallet without leaving the DeFi protocol**
DeFi protocols can integrate Coinbase Onramp to let their users seamlessly fund and top-up their linked self-custody wallets. For example, users can link their self-custody wallet to a DeFi protocol; and if they don't have enough funds, they can use Onramp to add funds to their linked self-custody wallet without leaving the protocol.

**Comment by joycehermosilla** [comment]
Design and Flow here https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=3334-12703&t=BuHYgF5oRDQRWx8R-4

**Comment by taariq** [comment]
@jamie088 we don't require Coinbase wallet to use the on ramp API. If they don't have funds, then OnRamp API does the same as Transak

**Comment by jamie088** [comment]
@taariq Can you please create a Coinbase project ID for me? You can get the project ID from the Coinbase Developer Platform.

**Comment by taariq** [comment]
https://github.com/palomachain/website/pull/161 fixed.
