### ISSUE TITLE
[DEVOPS] Provison a private Docker Repo for the Paloma LightNode v2

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2209]
Let's create private docker repo on current servers so that we are able to auth v2 purchases and downloads of the light client.

**Comment by maharifu** [comment]
Deployed the registry in the bots-server. Left some instruction/information on Notion: https://www.notion.so/volumefi/Docker-Registry-10de002bb62180daa589ea40552ed270

**Comment by taariq** [comment]
Done.
