### ISSUE TITLE
[PALOMABOT] AAVE stable yield chaser bot UI

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#2214]
Designs for new Bot AAVE stable yield chaser bot.
Figma: https://www.figma.com/design/6DYR6QFkucGd1bsOILr7V0/Paloma-Bot?node-id=3590-662813&t=vSjyX5bWAL41ShhO-4
Epic: https://www.notion.so/volumefi/EPIC-08-16-24-AAVE-stable-yield-chaser-vault-d18d0f4c6d334ef6a9d99bd5628d79f8?pvs=4

- [ ] Current Stablecoin with the highest APY + token image
- [ ] User select Chain. Available only in Ethereum and Optimism
- [ ] User selects up to 5 deposit tokens.
- [ ] My Bots: The user sees the following data: Current Stablecoin, Current APY, Deposit Amount, Deposit Token, Bot Earnings, and Status.
My Bots Designs: https://www.figma.com/design/6DYR6QFkucGd1bsOILr7V0/Paloma-Bot?node-id=3588-662628&t=vSjyX5bWAL41ShhO-4

- [ ] Add Bot to Curve Bots as well. Designs: https://www.figma.com/design/vLd6scwseZilfUZJXI6oRQ/Curve-Bots?node-id=1058-15356&t=9OYwNa18WFFGmeWo-4

**Comment by taariq** [comment]
@webelf101 we'd like to use this on Optimism. Will you confirm that we can usse the back-end to choose OP chain for this?

**Comment by taariq** [comment]
Close as shipped.
