### ISSUE TITLE
[LIGHTNODE] BUYMOREBOARD is showing wrong amount of rewards.

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#2216]
![Image](https://github.com/user-attachments/assets/0e399c0d-59e9-4d7f-9a8e-3a9da9a456ea)
![Image](https://github.com/user-attachments/assets/b95e258b-5d2a-44fa-833e-d8a19b05e085)

Right Now BuyMoreboard is showing that my rewards are only $7.
Rewards should be **UNLOCKED + EMISSIONS**

**Comment by taariq** [comment]
Superseded by https://github.com/VolumeFi/paloma/issues/2244
