### ISSUE TITLE
[PROMOCODE] As an admin, I want an authenticated link to be able to pre-register promocodes and emails.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2218]
As an admin, I want an authenticated link to be able to pre-register promocodes and emails so that BD team can register promocode and email address and user will have to register/login and connect wallet to complete.

**Acceptance Criteria**
1. Create an admin-only page using nodesale admin wallet-connect to authenticate.
2. Create form with email and with Promocode entry to submit to create promo code in db
3. We will require user to login/register to connect their wallet and then trigger promo code request email.

**Comment by fullstack412** [comment]
@taariq you need to assign @jamie088 here too for UI task

**Comment by jamie088** [comment]
@taariq @joycehermosilla Do we have a design link for this page?

**Comment by taariq** [comment]
closing as won't ship. No longer needed.
