### ISSUE TITLE
[BUG] LIGHTNODE COINBASE Purchase "Unsupported Asset"

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#2222]
When trying to buy a light node using a Coinbase wallet, the pop-up diablog shows "Unsupported asset"

[Unsupported Asset pay.coinbase.com-1727464307466.log](https://github.com/user-attachments/files/17168750/Unsupported.Asset.pay.coinbase.com-1727464307466.log)

![Screenshot 2024-09-28 030211](https://github.com/user-attachments/assets/9f56432f-405d-4f45-bc4f-9a736058e82f)

**Comment by jamie088** [comment]
![image](https://github.com/user-attachments/assets/a2b4c03e-dd87-4469-98a1-bfcd457a7dfd)
