### ISSUE TITLE
[LIGHTNODE] As a user, I want VPS installation instructions for my LightNode

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2226]
As a user, I want VPS installation instructions for my LightNode so that I have VPS instructions separately.

**Acceptance Criteria**
1. Install and test VPS install
2. Add any special requirements for VPS.

Instructions shared by community member:

Update and get Certificates
```
sudo apt-get update
sudo apt-get install ca-certificates curl
```

Install docker key rings
```
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc
```

Install Ubuntu docker key rings
```
echo \
"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
$(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
```

Update packages and install docker
```
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```

Verify Docker runs
```
sudo docker run hello-world
```

Prepare your download directory
```
mkdir -p ~/Downloads
```

Get Paloma LightNode v1 setup (we already have this)
```
wget https://download.palomachain.com/lightnode/setup.sh -O ~/Downloads/setup.sh
```

Run Paloma LightNode v1 setup **(We have to add `bash` to our instructions)**
```
bash $HOME/Downloads/setup.sh
```

Activate Paloma LightNode v1 setup **(We have to add `bash` to our instructions)**
```
bash $HOME/Downloads/setup.sh activate
```

Automate Paloma LightNode v1 setup **(This is new step we need to add to ALL instructions)**
```
bash $HOME/Downloads/setup.sh automate
```

**Comment by taariq** [comment]
@maharifu we just need a confirm on these insturctions and @joycehermosilla can do UI.

**Comment by maharifu** [comment]
@taariq The instructions look OK to me. Should be the same as our current Linux instructions.
I'm not sure why we need `bash` instead of `sh`, but if it works, it works! I'll try to look into it.

**Comment by joycehermosilla** [comment]
**"(We have to add bash to our instructions)"** This is for ALL instructions windows, mac and linux? @maharifu @taariq

**Comment by taariq** [comment]
@joycehermosilla bash is just for VPS.

**Comment by taariq** [comment]
Removing @maharifu from this ticket.

**Comment by joycehermosilla** [comment]
Designs are ready. Adding @jamie088 (CC: @taariq)

**Comment by jamie088** [comment]
Fixed with https://github.com/palomachain/website/pull/165
