### ISSUE TITLE
[LIGHTNODE] Authz and IAVL issues https://github.com/palomachain/paloma/issues/1304

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2228]
Reference ticket: https://github.com/palomachain/paloma/issues/1304

**Comment by maharifu** [comment]
@taariq Are we OK to close this one? Maybe we should open a new ticket to try to replicate the IAVL issues, but for now, this one is done.

**Comment by taariq** [comment]
Closing as fixed. We'll open a new ticket to replicate the IAVL issue.
