### ISSUE TITLE
"status":"original error: Reverted Wrong count[BUG] EurE Bot fails: Fail with error 'Insufficient funds to cover gas estimate'

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2231]
New Bot! - Bot Name: eure, Token Input: dai, Amount Input: 3157.84, Token Output: dai, Amount Output: 3157.84, Chain Name: eth

Transaction failed due to the following:
https://gnosisscan.io/tx/0x866556f20d0987ff97b3252eba0ad07ce5c63013017fdbac467071f63ec95027

**Comment by webelf101** [comment]
I think we need to increase gas limit amount of the transaction. @maharifu @byte-bandit

**Comment by taariq** [comment]
> I think we need to increase gas limit amount of the transaction. @maharifu @byte-bandit

By how much? And what needs to change?
