### ISSUE TITLE
[LIGHTNODE] As a user, I want my LightNode to select validators that have a minimum of 50,000 Grains staked.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2237]
As a user, I want my LightNode to select validators that have a minimum of 50,000 Grains staked o that I don't delegate stake to validators that are starting validators to turn them off immediately.

**Acceptance Criteria**
1. Only delegate to validators that have a balance of 50,000 GRAINs.

**Comment by maharifu** [comment]
Instead of time base, we're going to use a minimum GRAIN amount: 1000 GRAIN
Filter out all validators that have less than that.

**Comment by taariq** [comment]
Let's make 50,000 GRAINs.
