### ISSUE TITLE
[LIGHTNODE] BUG - user is unable to activate his node on the client.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2239]
Not sure of the root cause. Do we tell them to try again?

arb network 0x1e6b5EBdd97aD37644B0D8E11AD55c48e6C38B43

paloma1wqu3g4r4x4m3t30x6pxfdltrpz5e7j3pj0lnda

Shikkiy
Hello! For some reason, installing the script didn't work via SH and I ran it via Bash (I had already added docker to the environment before and was under root entry)
Everything was ok, but in the last step(> sudo bash $HOME/setup.sh activate)
I got this error(Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account paloma.... not found: key not found)
I did the node activation by binding the paloma address, but there was an error in the RPC

**Comment by maharifu** [comment]
@taariq The license is ready to be activated on paloma. Can the user try the `activate` command again?

**Comment by taariq** [comment]
This user is all setup now Thank you.
