### ISSUE TITLE
[BUG] User unable to complete purchase with Coinbase wallet using Safari: Error: WebSocket connection closed abnormally with code: 3000 (Unauthorized: origin not allowed)

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2240]
User unable to complete purchase with Coinbase wallet using Safari

Error: Error: WebSocket connection closed abnormally with code: 3000 (Unauthorized: origin not allowed)

See attached logs[paloma_safari_debug_log.txt](https://github.com/user-attachments/files/17235933/paloma_safari_debug_log.txt)

**Comment by Nagiyay** [comment]
> User unable to complete purchase with Coinbase wallet using Safari
> 
> Error: Error: WebSocket connection closed abnormally with code: 3000 (Unauthorized: origin not allowed)
> 
> See attached logs[paloma_safari_debug_log.txt](https://github.com/user-attachments/files/17235933/paloma_safari_debug_log.txt)


Has your issue been escalated by a support member already?

**Comment by taariq** [comment]
Won't fix. Will tell users to use Chrome.
