### ISSUE TITLE
[BUG] Unable to activate Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account paloma16url84wrn47p0r3z2xwxsmzxz32l9v462fda3r not found: key not found

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2242]
Steps that user already did. User also waited and kept trying in case it was chain delay.

1. launched Docker
2. Performed the command
> sh $HOME/Downloads/setup.sh
saved seed phrase and my public address 
> paloma16url84wrn47p0r3z2xwxsmzxz32l9v462fda3r
3. at the dashboard I clicked ACTIVATE, entered my paloma address and signed the tx with my metamask wallet

4. now I am trying to perform the command
> sh $HOME/Downloads/setup.sh activate
in the terminal, but after entering my passphrase I am getting an error:
Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account paloma16url84wrn47p0r3z2xwxsmzxz32l9v462fda3r not found: key not found

![Image](https://github.com/user-attachments/assets/9f19f71e-88e9-4451-b64d-1c79bb7456ea)

Discord: https://discord.com/channels/987730379182051408/1291164617606692886/1291165994643095603

**Comment by maharifu** [comment]
@taariq The node sale event was delayed, but the license is now available to be activated on the lightnode client. The user should try the `activate` command again.

**Comment by taariq** [comment]
Closing this to review Compass Arbitrum SLCs. This is happening now a few times.
