### ISSUE TITLE
[BUG] Ligtnode V2 is asking for authentication when we are not doing any authentication

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2254]
jason@Jasons-MBP ~ % sh $HOME/Downloads/setup.sh
docker: Error response from daemon: failed to resolve reference "docker.palomachain.com/lightnode-client:v2": pull access denied, repository does not exist or may require authorization: authorization failed: no basic auth credentials.
See 'docker run --help'.

Another user:
![Image](https://github.com/user-attachments/assets/adecfa6a-b049-488a-95b1-03cfb63a7e0f)

**Comment by maharifu** [comment]
@taariq I merged the wrong branch and we had the wrong script in downloads.palomachain.com. I just replaced it with the right version.

**Comment by taariq** [comment]
This is fixed.
