### ISSUE TITLE
Allow to go back using the browser back button

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#226]
### Story
As a user who is going through the momentum bot flow, I want to go back to the previous step or I want to go directly to the view where I can start the bot 

### Done when

- [ ] I can go back to the previous step using the browser back button    
    - [x] from search results to search input parameters
    - [ ] from swap/start bot view to search results

**Comment by jamie088** [comment]
What is tokenID? We don't have any tokenID.

**Comment by verabehr** [comment]
I mean token address. Updating the description

**Comment by jamie088** [comment]
And for the second factor, currently, we can't go directly to the swap/start bot view page by entering parameters.
In this case, I can send the token address and volume value, etc as parameters, but I can't get the information of this token needed to show and start the bot. It means that we can't get the 6, 12, 24H volume, token name, symbol, and image that the current API is returning. to make this possible, a separate API is required for me.
like Get bot info of selected token @verabehr

**Comment by verabehr** [comment]
ok, let's discuss next week what's possible. I'll add this to the list of items in notion

**Comment by verabehr** [comment]
removing that part of the ticket. This is reallly the stop loss bot and will be done separately
