### ISSUE TITLE
[LIGHTNODE] Purchase Page Fixes

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#2262]
Please: 
Correct the Header text by removing the "and"

Add a line break between the sentences.

Bold the "Personal Discount Code:" and "50,000 GRAIN Rewards:" text

==================
Get Your Paloma Light Node Today Before Prices Increase!

Secure your Light Node, become a Paloma network active participant, and be rewarded. 

**Paloma is a new blockchain for pigeons, enabling fast blockchain interoperability and fast Web2.0 API integration into the Web3 ecosystems of chains.**

**The Paloma LightNode v2 includes:**

- **Personal Discount Code**: Receive a 10% commission in USDC and a 5% discount for every sale made with your discount code.
- **50,000 GRAIN Rewards**: Mine GRAIN tokens and stake mining rewards.

![Image](https://github.com/user-attachments/assets/96f80d38-afcf-4d98-b633-a880e596a754)

**Comment by taariq** [comment]
Closing as shipped.
