### ISSUE TITLE
[LIGHTNODE] Add AI Bot Tailored for Twitter on the Paloma LIghtNode Purchase Page

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2267]
As a user landing on the Paloma LightNode Purchase Page, I want to see on the Left Panel, below the V2 Listing, Tailored Custom AI for Twitter v1 with a bullet list of includes:

* Authenticate to use Paloma Custom AI for your Tweets
* Receive Tailored Points for using your AI for Twitter
* Create Tweets that sound like people you admire but are from you

Design: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=3334-14842&t=ucAaCe0NlVt3kJIx-4

And also add under **You Pay** the item 1x Tailored for Twitter AI so that I know I am getting a Twitter AI

![Image](https://github.com/user-attachments/assets/603a9430-da8f-4562-aea2-f302955139a7)

**Comment by joycehermosilla** [comment]
I added the Figma designs and @jamie088 to the ticket. (cc: @taariq )

**Comment by taariq** [comment]
Closing as wont' ship.
