### ISSUE TITLE
[LIGHTNODE] As a user, I want to see migration instructions to upgrade from v1 to v2 in the download instructions

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2270]
As a user, I want to see migration instructions to upgrade from v1 to v2 in the download instructions so that I am able to migrate my v1 Paloma LightNode to v2.

**Acceptance Criteria**
1. Add a link at the bottom of each download tab for Instructions to upgrade from v1 to v2.
2. Use the instructions from here for the Migration of v1 to v2 panels: https://www.notion.so/volumefi/EPIC-10-11-2024-Paloma-Lightnode-v1-to-v2-upgrade-Instructions-11ce002bb62180a8b83ce52a444277b3

Designs: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=3445-6207&t=Rw9c35JR8hWbVM7R-4

**Comment by joycehermosilla** [comment]
Why add it to the Download instructions?? I suggest adding it to the Buymore Board as a banner and when click then you get the instructions. Will new users download directly the V2? or need to go through the same instructions to upgrade. (@taariq)

**Comment by taariq** [comment]
> Why add it to the Download instructions?? I suggest adding it to the Buymore Board as a banner and when click then you get the instructions. Will new users download directly the V2? or need to go through the same instructions to upgrade. ([@taariq](https://github.com/taariq))

Because in the purchase flow, if users don't go to the upgrade instructions, their LightNode will stop working once they download and run setup. Therefore, we want to give upgrade instructions as part of download to everyone ahead of that and via regular link. No login needed.

**Comment by taariq** [comment]
@joycehermosilla Upgrades will be forever. The banner won't be forever and the buymore board is for buying more.

**Comment by taariq** [comment]
@maharifu will you confirm windows migration instructions on this ticket?

**Comment by joycehermosilla** [comment]
@maharifu THank you!

**Comment by joycehermosilla** [comment]
I updated the Designs: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=3445-6207&t=OgNZ65BTgjfEShcG-4 @jamie088 @taariq

**Comment by jamie088** [comment]
@joycehermosilla `1. Add a link at the bottom of each download tab for Instructions to upgrade from v1 to v2.`
Where is the link button in design? I didn't find it.

**Comment by joycehermosilla** [comment]
If I understand well, we will create the migration instruction in his URL. palomachain.com/purchase/migration. CC: @taariq  
So no link to the instructions is needed.

**Comment by jamie088** [comment]
@joycehermosilla But where can users find this URL?

**Comment by joycehermosilla** [comment]
Paloma LightNode Newsletter and Social Media.  @taariq right?

**Comment by taariq** [comment]
@jamie088 We'll give this link to users individually for now.

**Comment by taariq** [comment]
Closing as shipped.
