### ISSUE TITLE
[TAILORED] Add Generate Button and an indicator of how many daily generations are left

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#2274]
In the main Tailored Application, 

- There isn't a "Generate" button to create a new set of generations. 
- There isn't an indicator of how many Daily Generations are available. 
- I also cannot select different target profiles.

![Image](https://github.com/user-attachments/assets/0a7a1e41-22f3-4839-a724-d25f41d19294)

**Comment by taariq** [comment]
Shipped with https://github.com/VolumeFi/tailored-ui/pull/17
