### ISSUE TITLE
[LIGHTNODE] As a user on the Buy More Page, I want my Paloma Address to be clickable to copy the entire address

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2282]
As a user on the Buy More Page, I want my Paloma Address to be clickable to copy the entire address so that I can copy and paste my address as needed.

**Acceptance Criteria**
1. Add Click to Copy action on the Paloma Address on the lightnode page. 
2. Give a test alert `Paloma address copied`
3. ![Image](https://github.com/user-attachments/assets/807f588d-f693-4925-96fd-ca43d03af915)

**Comment by jamie088** [comment]
Fixed with https://github.com/palomachain/website/pull/179
