### ISSUE TITLE
[BUG] Eror /usr/local/bin/entrypoint.sh: line 356: [: -lt: unary operator expected

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2285]
It appears that NodeGuru was failing. Do we need a fallback?

**$ ./setup.sh node-recover**
v2: Pulling from palomachain/lightnode-client
Digest: sha256:8fbf9d43a98880f4db1a50bf44a7fc1af88729b8eccb382d086bb04a454e4aba
Status: Image is up to date for palomachain/lightnode-client:v2
docker.io/palomachain/lightnode-client:v2
**/usr/local/bin/entrypoint.sh: line 356: [: -lt: unary operator expected**

Setting staking grants for porkchop
**Error: post failed: Post "https://rpc-1.paloma.nodes.guru": dial tcp: lookup rpc-1.paloma.nodes.guru on 192.168.2.1:53: read udp 172.17.0.2:45286->192.168.2.1:53: i/o timeout**
Signing
Enter keyring passphrase (attempt 1/3):
**Error: post failed: Post "https://rpc-1.paloma.nodes.guru": dial tcp: lookup rpc-1.paloma.nodes.guru on 192.168.2.1:53: read udp 172.17.0.2:51169->192.168.2.1:53: i/o timeout**
Usage:
  palomad tx sign [file] [flags]

Flags:
  -a, --account-number uint      The account number of the signing account (offline mode only)
      --aux                      Generate aux signer data instead of sending a tx
  -b, --broadcast-mode string    Transaction broadcasting mode (sync|async) (default "sync")
      --chain-id string          The network chain ID
      --dry-run                  ignore the --gas flag and perform a simulation of a transaction, but don't broadcast it (when enabled, the local Keybase is not accessible)
      --fee-granter string       Fee granter grants fees for the transaction
      --fee-payer string         Fee payer pays fees for the transaction instead of deducting from the signer
      --fees string              Fees to pay along with transaction; eg: 10uatom
      --from string              Name or address of private key with which to sign
      --gas string               gas limit to set per-transaction; set to "auto" to calculate sufficient gas automatically. Note: "auto" option doesn't always report accurate results. Set a valid coin value to adjust the result. Can be used instead of "fees". (default 200000)
      --gas-adjustment float     adjustment factor to be multiplied against the estimate returned by the tx simulation; if the gas limit is set manually this flag is ignored  (default 1)
      --gas-prices string        Gas prices in decimal format to determine the transaction fee (e.g. 0.1uatom)
      --generate-only            Build an unsigned transaction and write it to STDOUT (when enabled, the local Keybase only accessed when providing a key name)
  -h, --help                     help for sign
      --keyring-backend string   Select keyring's backend (os|file|kwallet|pass|test|memory) (default "os")
      --keyring-dir string       The client Keyring directory; if omitted, the default 'home' directory will be used
      --ledger                   Use a connected Ledger device
      --multisig string          Address or key name of the multisig account on behalf of which the transaction shall be signed
      --node string              <host>:<port> to CometBFT rpc interface for this chain (default "tcp://localhost:26657")
      --note string              Note to add a description to the transaction (previously --memo)
      --offline                  Offline mode (does not allow any online functionality)
  -o, --output string            Output format (text|json) (default "json")
      --output-document string   The document will be written to the given file instead of STDOUT
      --overwrite                Overwrite existing signatures with a new one. If disabled, new signature will be appended
  -s, --sequence uint            The sequence number of the signing account (offline mode only)
      --sign-mode string         Choose sign mode (direct|amino-json|direct-aux|textual), this is an advanced feature
      --signature-only           Print only the signatures
      --timeout-height uint      Set a block timeout height to prevent the tx from being committed past a certain height

**Comment by maharifu** [comment]
@taariq the error `read udp 172.17.0.2:45286->192.168.2.1:53: i/o timeout` points to a docker issue, not a nodes.guru issue. This will be a problem in docker. Let's leave the issue open and try to find a workaround.
