### ISSUE TITLE
Palomabot FE queries are running very slow

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#229]
The FE queries sometimes take 30 seconds.
I think the issue is that the BE is querying CG upon a FE request every time. If so, that needs to be changed. For most FE queries, the response should come from the DB directly which will be much faster. Also we do not need to update the DB that often.

Here is my proposal:

Rewrite the API so FE requests all come from the DB
Create a new function solely for updating the DB with the newest data. We can run a cron to update every a few hours

**Comment by verabehr** [comment]
Taariq's loom: https://www.loom.com/share/1f2e2466f93446f5b901b250e9412973

**Comment by measure-fi** [comment]
Fixed in https://github.com/VolumeFi/trading-bots/commit/c867939c8d886b4446c4b25fed0dd362968d7fcf
