### ISSUE TITLE
[VOICE AI] Set Up Telephony Backend Service

### ISSUE THREAD

**Issue by Cieloc** [VolumeFi/paloma#2290]
To manage telephony programmatically it probably makes sense to use Twilio's infra/API.

I think this might get us 70% of the way there:

https://www.twilio.com/en-us/blog/build-ai-buddy-go-openai-retellai-twilio-programmable-voice

Will need to swap OpenAI for Deepinfra

Will need to swap Retell AI for OpenVoice

**Comment by taariq** [comment]
Closed as shipped.
