### ISSUE TITLE
[COMPASS] Executions are very slow on Compass and Arbitrum See transaction history

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2295]
> anyway, compass takes too long
i run the cw tx around 10 mins ago

07840D30B5046344FCA0DF33A89A62A70A82E3C4C87B5EC7D40603146DDC3B70
119D2A237E4DC9111C221F51A3873BC2C298A38E96FAF0DFA640D80E1664F92F
832DE9B6F3405C9ABC17AD11810D10477F938535D9184E7DDF4F12F7110EAFBD
https://arbiscan.io/address/0x82Ed642F4067D55cE884e2823951baDfEdC89e73#events
i can see the delay always happens when compass has Update_valset tx

**Comment by byte-bandit** [comment]
Looks like there was a period of degraded RPC performance from some Pigeons across the board. I don't really see any other errors in the logs though.

Tried some basic SLC executions earlier today, they went through immediately without delay, so looks like this might have been just a temporary slow down.

**Comment by taariq** [comment]
closing as RPC issue.
