### ISSUE TITLE
[BUG]  `node-recover` ERROR:  You do not have enough spendable balance in you account.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2298]
$ ./setup.sh node-recover
v2: Pulling from palomachain/lightnode-client
Digest: sha256:8032383dffdf6ec852aa0325ef3dd072fdb8a23138b528dae7b7e60931eebbff
Status: Image is up to date for palomachain/lightnode-client:v2
docker.io/palomachain/lightnode-client:v2
You do not have enough spendable balance in you account.

**Comment by maharifu** [comment]
@taariq What's the paloma address being recovered?

**Comment by taariq** [comment]
> [@taariq](https://github.com/taariq) What's the paloma address being recovered?

`paloma1aqxzj6a8x7uuh4lwg4xgt0fklsycdsjvtvmm4y`

**Comment by maharifu** [comment]
@taariq This account has no balance.

![Image](https://github.com/user-attachments/assets/2b31119f-ab89-4f06-9341-5eec02cf657c)

It also has no feegrant, and doesn't seem to be a node. What are we trying to do by recovering it?
