### ISSUE TITLE
Add fixed amount to gas limit.

### ISSUE THREAD

**Issue by webelf101** [VolumeFi/paloma#2299]
# Background

related to [this issue](https://github.com/VolumeFi/paloma/issues/2286).

I suggest increasing a fixed amount to gas limit(about 100K now) (NOT gas_estimate param in SLC).

Because, we spend such amount of gas to get params in SLC function in Solidity.

# Done when

- [ ] add 100K in gas limit of txes to Compass-evm

**Comment by taariq** [comment]
@webelf101 we need to close on this today.

**Comment by webelf101** [comment]
Of course, it is reflected in gas estimation. But the main issue is the point I check the gas in the smart contract. At the checkpoint, some gas was already spent so reduced gas amount will be compared with the gas estimate parameter. The gas spending happens when I get the parameters at the very beginning of the tx. It is about 100K right now. So I am comparing the remaining gas amount (reduced about 100K) and the gas estimate parameter value. That's why we sometimes fail the gas estimate validation check. And so I am asking to increase the gas limit for the tx. Does this make sense? @byte-bandit @taariq

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/pigeon/pull/449
