### ISSUE TITLE
[DEVOPS] Remove Pub Key from SSH on Volume Servers

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2302]
Remove the following Pubkeys from Volume SSH configs and bastion
1. AAAAB3NzaC1yc2EAAAADAQABAAABgQDg82YNYBYWglQTRM3qNXwqigm2wOpDFqhawUYnf/XPp1H9/aQQgVwKaEWjQ4lns7Vbj8eMNG296HnGPwl2do/ZsEbbFoTmQvQZqAiTpqIwwDVn8O8ZaRaecx2bXBrk4YWG5iNHjvYFRFmQavCCVA+m3is3QYCWLZcubD3X9Igr/0jj7dWdmMemIxBSpxOR3MMk4vqIPlu6NNcxh9aPUjRZDj7NvWFTvM5PJpuY+bUZp3ageIkRTJ28H5SIa6vKzW6gpy08TZHxWrAncumfvFdk/atmLe85NZe+ZxcaYBG/iykBrVyHWIPKOkTWqvlI1qO3GfrD0wKgVJA6XK+TV6Tp6dVNW3Q8nS5U5QXM19Gfrgr3HgW257ldoDz9Qqh3FJWRvUpLCO3FWzNY+nG9in44uTHlkw6AnQ2hKOnzC5ysr0vhqmdvD5TG7CsGUpe8UUA2A0UQ8gQNcXEPLplAdlei91nUsXJhMnUZg7int4tY//IvWeUu2XVJGoqPFUNmcI0= ashleyli@bogon

3. AAAAB3NzaC1yc2EAAAADAQABAAACAQCha4onb4Nk5ad4KyArXPTv+Jx2KjL5IYzKl6yGuCwHzcl/Biuaus64TfZC96uhgDX4OWngZX3L3veSQFYEViF5UQjBnSBj4hv25WnxQ0UjtZhKIaXrmDveqQjE7etyqk8fayDcdGW5M8tVWufcaLLG0QRgxUuZTgvFObubeee6I3MHK2TVBUfTRQFOXlYDHFLLURl8Hl6VmmvEtRG003aGJALukaIfZWRvuJq8gtTRrW936f3HbygTZ04pVyh+7/4KKs3DOIX36QOHBE6WwlpIU0Izq1m6hqWwSk0iuEZpUjUYPQ5VJIZVDD2UXzldOvISan7SWU2TYukWd3vWNa+qHx6cPBzjF+SDqbVs8cu1JCFfMk2jz9QPGRLaqb7AxgO5KUw6yqAwTVyDXy/DegNia7P3rlh2M7ECHuxgKPkLSHmW8IyPE88Mei4jRi41tudeNDK+Q4Rn50wlImQirbkbGLxBObh/zbjSfUpOggndeEhWdJGCrEVVA6hXPMy8PbyGDkFkaAX1uM4RaJgPx9E9XrSuJKhlfCCFa3wzvjES+Tl7ew2gPdA0O8MttMPe0OmfMyfxCvGWeDXWi5S9wx6XVGKe5T83HbgPpKhpYQ/IY0EpktkIpuCM27w4OxUMkW3+MI/lpA1XlIHULhyPNYtlsL+eSFwshKaUVfROkIiTuw== linux220129@DESKTOP-C2EETAR

4. AAAAB3NzaC1yc2EAAAADAQABAAABgQDM/yF+UQFDPHMGHgAc9qaMTua/3D7SCWDQMZwGJjYeRk62nExx/vpONy6/0VaSAAdA+ReiA3dhqLBrePFkt1bGjBHMSSjERmS+iCM8EcBYCFghQTFdakwDSMiWacfcyQrJDgjJvG5IMRz2K1/4yzn0aNT/6m55iBhNMxUsRU3GTxkZ0OVjVCeJgR4cEleYz74wUExXsDNrIsJ7XFw2JNH5RoYZGHMHGTl3mJ956T4oF+9B+E0p+72wWl0km5U4hsDLC2mgf90MPPPNfafec7Jj0c5d1IkTX1hO8MWdHK8qmTS3UDRJoLtn4iX6P3pd8XzykvN2eLtj8E6k665cq+E/sTP6pUK1r03QC2Cy0k8Ecl8uXOXO72ALuVYT4mcxve7pCzQqKINO7MDcjVstEmhiUTiSYP2Z8zdEq9PZzJzLHv/fk4QTgixgbaJddoN3i4O+05Nz5ZsAm0K0V+n+kh0RLPVzz9v5p4NQr2eG8kUQRjJNSHjJYK6zo6CYDkIt0vk= biyaq@DESKTOP-C2EETAR

**Comment by maharifu** [comment]
This is done.
