### ISSUE TITLE
[BOTS] Upgrade EurE Bot to fee of 0.5% ETH per Palomabot Transaction

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2303]
As a user, I want to pay a flast fee of 0.5% per EurE bot run so that I am paying a fee for the bot to run.

**Acceptance Criteria**
1. Add fee of 0.5% per bot tstart

**Comment by webelf101** [comment]
Is this replacement of 0.2% service fee or additional fee? @taariq

**Comment by taariq** [comment]
Updated to new 0.5% fee.

**Comment by taariq** [comment]
Closed as shipped.
