### ISSUE TITLE
[LIGHTNODE] Upgrade the Purchase Landing Page UI to address conversion failures

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2305]
As a user, when I land on the https://www.palomachain.com/purchase/ I want to see compelling reasons for me to purchase.

NOTE: We want to focus on the middle panel which has most purchase consideration activity.

1. Sale ending time is not highlighted and appears small and non-distinct. Fix this so that the Sale End is pronounced.
2. The remaining nodes number 144/884 is confusing. Users say they don't know how much remains. Separate the numbers and show the number of nodes left at the slot. users do not need to know how many total nodes in the slot
3. Implied FDV has been a big win. Most usres want to buy LOWER FDV before it rises. Show the IMPLIED FDV as linkd to the days left. For example: SALE ENDS WITH IMPLIED FDV of $16.98MM in 28 days 10 hrs 13 min
4. There is no Information for the Number of GRAINs in the middle panel. 50,000 Per NODE.
5. Create a design version with the left panel removed.

**Comment by joycehermosilla** [comment]
@taariq Version with Left Panel removed: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=3513-610&t=xjpPc2snhwxExvcT-4

Version with updated data: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=3513-610&t=xjpPc2snhwxExvcT-4

**Comment by taariq** [comment]
Thanks @joycehermosilla. .let's discuss. We are seeking  a radical redesign, not a continuation of what is not working.

1. No customer seems to care about the software features in the purchase consideration
2. Customers seem to care about FDV and Amounts left on the slot.
