### ISSUE TITLE
Compass-EVM Polygon fails to process SLCs

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2307]
https://paloma.explorers.guru/transaction/DA75E1987545A80C44DB8CE2BFD448F4AB79371E9CA860260B6FB2EA528590BD

fails to hit SLCs on Compass-EVM for Polygon
https://polygonscan.com/address/0x26f5da70095d69103ba8b2ee264a20cd4b590eab

**Comment by byte-bandit** [comment]
Temporary degraded performance, has recovered again.
