### ISSUE TITLE
[LIGHTNODE] New Purchase Page

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#2308]
We aim to implement changes to increase conversions on the LightNode Sale Purchase Page.

- [x] Remove Left side of the Puchase flow with information
- [x] Remove Customer Support Options 
- [x] Change remaining nodes in slot designs: 
![Image](https://github.com/user-attachments/assets/7a83d625-bae5-4516-b9db-f23e4256929e)

Designs here: https://www.figma.com/design/yC7zuL9bFx9yvPd2aBalX6/Paloma-Light-Sale-Node?node-id=3510-4559&t=xjpPc2snhwxExvcT-4

**Comment by jamie088** [comment]
Fixed with https://github.com/palomachain/website/pull/188

**Comment by taariq** [comment]
Closing as shipped.
