### ISSUE TITLE
[CHORE] Update Paloma LightNode Sale for new contracts after vote ends

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2322]
CHORE: Update LightNode Sale for new contracts after vote ends.

**Comment by fullstack412** [comment]
@jamie088 
pay_for_eth, pay_for_token, activate_wallet function params has been updated now.

New Nodesale Contract 
https://etherscan.io/address/0x92aB2012738039AB10E684B010053168f9c1A7E5
https://arbiscan.io/address/0xbD2c6F718Ee724884E536be3Fa6Ca5b3E0D1Be36
https://bscscan.com/address/0x25BF3E67ccF137BCacEAf529e5b68052Cca38915
https://polygonscan.com/address/0x25BF3E67ccF137BCacEAf529e5b68052Cca38915
https://basescan.org/address/0x25BF3E67ccF137BCacEAf529e5b68052Cca38915
https://optimistic.etherscan.io/address/0x2f78AfAdD7E58052c4a8789dc01A1eD49848cc0C
Fiatbot Factory Contract
https://arbiscan.io/address/0x4E968ffD9DB70593235be82D1B2a181d7090f640

**Comment by taariq** [comment]
Closing as shipped.
