### ISSUE TITLE
[BUG] Your Balance and Total Rewards dollar value is using Price Per Node as $40 which is incorrect.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2331]
**Your Balance** and **Total Rewards** dollar value is using Price Per Node as $40 which is incorrect.

![Image](https://github.com/user-attachments/assets/69bef5b2-5ea4-4c7a-911b-dbf9e9563fd2)

**Comment by fullstack412** [comment]
@taariq 
Is $400 correct for the balance dollar value then?

**Comment by taariq** [comment]
> @taariq Is $400 correct for the balance dollar value then?

Yes!

**Comment by taariq** [comment]
Finished. WOrking.
