### ISSUE TITLE
[LIGHTNODE] Update the Coingecko Mobile Banner to Join Paloma Discord for Airdrop Role

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2338]
Create new Coingecko Mobile Banner:
1. Call to Action: Join Paloma Discord to get the AirDrop Role and a free Twitter AI
2. Link to Discord: https://discord.gg/YbjCJvXBuu

**Comment by joycehermosilla** [comment]
Should be a GIF or static?

**Comment by taariq** [comment]
Animated GIF please!
