### ISSUE TITLE
[PALOMABOT] As a user, I want to see the Palomabot for Aave Yield so that I am able to deposit a token to start the bot

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2359]
As a user, I want to see the Palomabot for Aave Yield so that I am able to deposit a token to start the bot.

**Acceptance Criteria**
1. Implement UI for the Aave Yield Chaser Bot.
2. Change the name of the bot to Paloma Aave High Yield Bot.
3. Add to Palomabot UI page of bots.
4. Add Deposit transaction Fee as the currrent Price of a Paloma LightNode
5. Add / Complete Payment of LIghtNode with successful deposit and payment of transaction fee.

**Comment by taariq** [comment]
@joycehermosilla will you add the Figma link for the Ui here?

**Comment by jamie088** [comment]
https://discord.com/channels/987730379182051408/1065140873811218532/1303072725375516766
(There's no epic. It's very simply. Just add the Lightnode purchase fees as the bot transactionf ee.
When you star the bot, you are also buying  a Paloma LightNode
Folks prefer getting it as a bonus vs. paying for it first.
So we just make it the transaction cost to start the bot)

**Comment by taariq** [comment]
Shipped.
