### ISSUE TITLE
[API]: mybots api issue. Unable to see bots on the Mybots Page for Aave Yield Chaser Bot.

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#2368]
Missed `image` values in api result.
the image value was present in the `coin_info0` and `coin_info1` objects of each bot data. But we can't see this value now.

**Comment by taariq** [comment]
@webelf101 I also tested bot creation. I am unable to see my bots on the Mybots page. 
1. My address: `0x83334ef0C6f6396413C508A7762741e9FD8B20E9`

**Comment by taariq** [comment]
This worked. I am able to see the bot.
