### ISSUE TITLE
[GRAIN] As an admin, I need a script to send GRAINs across the bridge on all EVM chains and across to Solana

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2372]
As the Paloma Foundation admin, I need a script to send GRAINs across the bridge to any EVM supported chain so that GRAINs are ready on all EVM chains as well as Solana.

**Acceptance Criteria**
1. Create a Script for Sending GRAINs to EVM chains
2. Register Paloma GRAINs on Wormhole: https://portalbridge.com/advanced-tools/#/register
3. Create a Script using Wormhole to send GRAINs to Solana https://wormhole.com/docs/tutorials/messaging/cross-chain-token-contracts/#

**Comment by fullstack412** [comment]
@taariq 
- Grain token address on Solana
https://solscan.io/token/7QN7Bq8Hh9cU5UZdQ4n2AWvuxFeeXr7aGgvQNG9ERZJC
 
- Script for send grain from paloma to evm
https://github.com/VolumeFi/w3tools/tree/master/send-grain-paloma-to-evm

- tool for send grain from base to solana
https://portalbridge.com/advanced-tools/#/transfer

**Comment by taariq** [comment]
Shipped as completed and tested.
