### ISSUE TITLE
[API] /aave-apy api endpoint doesn't work with base, Polygon, and OP chains

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#2380]
https://dex.palomachain.com/aave-apy?chainid=8453&asset=0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913
https://dex.palomachain.com/aave-apy?chainid=10&asset=0x94b008aA00579c1307B0EF2c499aD98a8ce58e58
https://dex.palomachain.com/aave-apy?chainid=137&asset=0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174
result: `Unsupported chain`

**Comment by taariq** [comment]
Closing as fixed.
