### ISSUE TITLE
[BUG]  500 (Internal Server Error)

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2382]
anonymous) @ _app-10d27a400e15f378.js:1281
(anonymous) @ _app-10d27a400e15f378.js:1281
(anonymous) @ _app-10d27a400e15f378.js:1281
(anonymous) @ _app-10d27a400e15f378.js:1281
__async @ _app-10d27a400e15f378.js:1281
executeEndpoint @ _app-10d27a400e15f378.js:1281
(anonymous) @ _app-10d27a400e15f378.js:1
(anonymous) @ _app-10d27a400e15f378.js:1
(anonymous) @ _app-10d27a400e15f378.js:1
(anonymous) @ _app-10d27a400e15f378.js:1
(anonymous) @ _app-10d27a400e15f378.js:1
(anonymous) @ _app-10d27a400e15f378.js:1
(anonymous) @ _app-10d27a400e15f378.js:1
dispatch @ _app-10d27a400e15f378.js:1286
(anonymous) @ _app-10d27a400e15f378.js:1281
(anonymous) @ _app-10d27a400e15f378.js:1
(anonymous) @ _app-10d27a400e15f378.js:1281
Qk @ framework-fee8a7e75612eda8.js:9
(anonymous) @ _app-10d27a400e15f378.js:1281
fetchToken @ aave-high-yield-d01931dba8f6fe47.js:1
await in fetchToken
(anonymous) @ aave-high-yield-d01931dba8f6fe47.js:1
Qj @ framework-fee8a7e75612eda8.js:9
Hk @ framework-fee8a7e75612eda8.js:9
w @ framework-fee8a7e75612eda8.js:9
J @ framework-fee8a7e75612eda8.js:33
R @ framework-fee8a7e75612eda8.js:33
_app-10d27a400e15f378.js:1281 Fetch failed loading: GET "https://dex.palomachain.com/aave-apy?chainid=137&asset=0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174".
defaultFetchFn @ _app-10d27a400e15f378.js:1281
(anonymous) @ _app-10d27a400e15f378.js:1281
(anonymous) @ _app-10d27a400e15f378.js:1281
(anonymous) @ _app-10d27a400e15f378.js:1281
fulfilled @ _app-10d27a400e15f378.js:1281
Promise.then
step @ _app-10d27a400e15f378.js:1281
(anonymous) @ _app-10d27a400e15f378.js:1281
__async @ _app-10d27a400e15f378.js:1281
(anonymous) @ _app-10d27a400e15f378.js:1281
(anonymous) @ _app-10d27a400e15f378.js:1281
(anonymous) @ _app-10d27a400e15f378.js:1281
(anonymous) @ _app-10d27a400e15f378.js:1281
(anonymous) @ _app-10d27a400e15f378.js:1281
__async @ _app-10d27a400e15f378.js:1281
executeEndpoint @ _app-10d27a400e15f378.js:1281
(anonymous) @ _app-10d27a400e15f378.js:1
(anonymous) @ _app-10d27a400e15f378.js:1
(anonymous) @ _app-10d27a400e15f378.js:1
(anonymous) @ _app-10d27a400e15f378.js:1
(anonymous) @ _app-10d27a400e15f378.js:1
(anonymous) @ _app-10d27a400e15f378.js:1
(anonymous) @ _app-10d27a400e15f378.js:1
dispatch @ _app-10d27a400e15f378.js:1286
(anonymous) @ _app-10d27a400e15f378.js:1281
(anonymous) @ _app-10d27a400e15f378.js:1
(anonymous) @ _app-10d27a400e15f378.js:1281
Qk @ framework-fee8a7e75612eda8.js:9
(anonymous) @ _app-10d27a400e15f378.js:1281
fetchToken @ aave-high-yield-d01931dba8f6fe47.js:1

**Comment by jamie088** [comment]
This issue will be fixed once this ticket is closed: https://github.com/VolumeFi/paloma/issues/2380

**Comment by taariq** [comment]
Fixed. Closing.
