### ISSUE TITLE
[PALOMABOT] Support Yield Chaser Bot Back-end fixes for performance

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2388]
As a user, I want the Yield Chaser bot to provide the highest yield and the most up-to-date rates so that I am always chasing the best aave yield, per chain.

**Acceptance Criteria**
1. Optimize Yield Chaser bot perormance

**Comment by webelf101** [comment]
We need to add a logic to check the difference between APY/APR based on change asset period. We should assume that we will lose about 0.1% asset on asset change. That means, until we get profit from difference between APY of old asset and new asset with time more than the change asset loss, we shouldn't change asset. So we need to add a logic to check difference of APY/APR and prevent change asset until we have more profit.

**Comment by webelf101** [comment]
Also, we need to check if change asset make less than threshold. We don't want lose more than some percentage(i.e. 0.1%).

**Comment by taariq** [comment]
Closing as shipped.
