### ISSUE TITLE
[AAVE-VAULT] Add a new feature to check if change asset makes loss more than profit from APY and prevent it.

### ISSUE THREAD

**Issue by webelf101** [VolumeFi/paloma#2392]
We need to add a logic to check the difference between APY/APR based on change asset period. We should assume that we will lose about 0.1% asset on asset change. That means, until we get profit from difference between APY of old asset and new asset with time more than the change asset loss, we shouldn't change asset. So we need to add a logic to check difference of APY/APR and prevent change asset until we have more profit.

**Comment by taariq** [comment]
Closed as shipped.
