### ISSUE TITLE
reduce response time for palomabot search results

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#242]
- https://github.com/VolumeFi/trading-bots/commit/7d63a170f11a5f5798dbdf78d87ffb25631de109
- https://github.com/VolumeFi/trading-bots/commit/807f7efbb2876872dacad3ab51f88e476fce1013

**Comment by taariq** [comment]
@measure-fi As per our discussion yesterday, we do not want to put any further work into this ticket. We need the Cosmwasm Vote Distribution Bot as the leading priority for your efforts.
