### ISSUE TITLE
[PALOMABOT] As a user who is on ETH, I want to be able to start a Base bot without having to first transfer my tokens manually to Base

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2420]
As a user who has ETH on the Ethereum network, but wants to start an Aave Yield Chaser Bot, I want Paloma to deposit my ETH from Ethereum onto the target chain that I select so that I am able to catch yield on the target chain and it will rebalance wherever there is highest aave yield on stables on a different target chain

**Acceptance Criteria**
1. Create UI for a Cross-Chain Yield Chaser Bot. This will be a new and separate bot
  * The bot will show highest stable yield on one chain.    
4. Use the Aave Yield Chaser bot backend
5. Show only the top yield and the target chain
6. Start Bot will deposit to the target chain
7. Rebalance will move the vault balance from the current chain to the target chain, if the profit is within the limits
8. Limit Rebalances to ETH L1 and L2s ONLY. No Polygon. No BNB. No Gnosis
9. Users first swap into ETH
10. Use the default bridge contract for ETH deposits
11. Swap with Curve into the stable?

**Comment by taariq** [comment]
@webelf101 closing this to rug pull to something else.

**Comment by Misthh** [comment]
Hello @taariq  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
