### ISSUE TITLE
[WEBSITE] Upgrade Palomachain.com HomePage with Updated Designs

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2428]
design: https://www.figma.com/design/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=133-2&node-type=canvas&m=dev

Links:

Join the Community: https://discord.gg/tbzNsehE4u
Get Started: (coming soon - should link to the Form)
Learn more: (coming soon - should like to Got Talent Landing Page)
Purchase a LightNode: https://www.palomachain.com/purchase
Create your Talent Token: (coming soon - form)
Launch App 1 (Tailored): https://www.tailoredai.me/
Launch App (Paloma Bot): https://www.palomabot.ai/
View Docs: (Mint an Egg): https://docs.palomachain.com/guide/develop/quick-start/quick-start.html
View Docs: https://docs.palomachain.com/guide/develop/quick-start/quick-start.html

**Comment by joycehermosilla** [comment]
Maybe we should create for the meantime a Notion Page for the Talent Show? @taariq

**Comment by taariq** [comment]
Closing as shipped.
