### ISSUE TITLE
Question: Will you confirm whether we have x/scheduler functional for Cosmwasm Jobs on Paloma?

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2449]
Question: Will you confirm whether we have x/scheduler functional for Cosmwasm Jobs on Paloma? @byte-bandit I have this feeling that our jobs are not JUST EVM, but x/scheduler didn't give any hints to confirm that feeling.

**Comment by byte-bandit** [comment]
@taariq @webelf101 

The scheduler module at this time really is just a glorified job runner. It can run ANY job on Paloma (not just EVM, also execute CW contracts), but there is no actual scheduling logic. Every execution has to be triggered manually at the moment.
