### ISSUE TITLE
Volume New Website - QA 05/25

### ISSUE THREAD

**Issue by yc74** [VolumeFi/paloma#245]
### **Home page**  

a. Remove 'about' and possibly have our landing page as just https://volume.finance (I agree with this one @joycehermosilla any objections?)

![image](https://github.com/VolumeFi/paloma/assets/115569295/09860f8a-c558-44b2-927e-aa15eeb6ce71)

- [ ] Fix text kerning, kindly move 'private' to the next line @wdev733 

![image](https://github.com/VolumeFi/paloma/assets/115569295/c95f8ddc-a975-4d99-92b8-c3b0099b973a)

c. Blocking seems repetitive, maybe explore having our testimonial before "Decentralized management..." (@joycehermosilla what do you think?)

![image](https://github.com/VolumeFi/paloma/assets/115569295/06cfcbb6-6ecd-4990-ba67-dcca846ee9d9)

- [ ] Change "What Clients Say" to "Feedback from Volume Clients" @wdev733 

- [ ] Kindly reword from " Start building now using Volume SDK" to "Be the first to build on Volume SDK" @wdev733 

![image](https://github.com/VolumeFi/paloma/assets/115569295/e94dec11-f763-4c8c-8f90-5e293bb0813b)

- [ ] Button should read "Join the waitlist!" versus "Build now" // also, the button currently does not point to anything @wdev733 

### **End section**

![image](https://github.com/VolumeFi/paloma/assets/115569295/ae08f3bd-6d50-433c-b7b1-ce00ee2be0fb)

- [ ] Kindly add a short write up below Volume logo @wdev733 

_"For web3 users that want decentralized computation & storage to manage private keys, Volume delivers a new approach that promises 100% uptime at the lowest cost."_

- [ ] Add Volume Custody to the list of 'Products'  in the footer @wdev733 

- [ ] Rename 'Company Assets' to 'Company' and add the following below: @wdev733 
> Team
> Events
> Blog
> Careers

- [ ]  Under Social Media, kindly include: @wdev733 
> Volume Discord
> Paloma Discord (https://discord.gg/tNqkNHvVNc)
> Twitter
> LinkedIn

### **Volume Products**

a. Do we already have images for PalomaSwap & Volume SDK @joycehermosilla I'm struggling with the code snipped for the SDK, but will come up with some options we can review tomorow

- [ ] Under Volume Custody, please change text to: @wdev733 

_With Volume Custody, Clients delegate their assets & private keys to the Paloma Blockchain and its secure validator set._

![image](https://github.com/VolumeFi/paloma/assets/115569295/1f5fbb9c-3914-466f-8b79-6d3a871ec5e8)

### **Volume Pricing**

![image](https://github.com/VolumeFi/paloma/assets/115569295/a7035c3e-6edd-4347-8ccf-f77b176cc64a)

- [ ] Please adjust text kerning to @wdev733 

"Volume Private
Key Management"

- [ ] Change text from: @wdev733 
Start managing your Private Key Workflows on any target chain, today. The Volume team is here to help.
to:
Start managing your Private Key Workflows on any target chain.
Get in touch with the Volume team today.

![image](https://github.com/VolumeFi/paloma/assets/115569295/0f1f1af6-ebd8-4b7f-a51a-c24a09999d10)

c. In the table, is there a way to highlight Pro? Maybe green font for "Pro" @joycehermosilla 
d. Please darken (X) on MEV Front-Run protection & MEV Back-Run Revenue to emphasize that these aren't included in Starter @joycehermosilla 

- [ ] Under Pro, 5 Bots (instead of 5 Bot) @wdev733 

- [ ] Under Pro, 10 Keys (instead of 10 Key) @wdev733 

Thank you! Feel free to ping me for any questions or clarifications.

**Comment by taariq** [comment]
Geat suggestions.
