### ISSUE TITLE
Add parameters to trade service api

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#249]
Add the following parameters to the trade service api that lists all active bots

- [x] Chain ID (depending on the chain that the vyper smart contract is deployed on - we will launch with ethereum and bnb) `chain: "1", "56"` (Please return chain ID)
- [x] type (currently only `momentum`, we will add another bot hopefully next week) `bot: "Momentum Bot", "DCA Bot", "Limit Order Bot", "Stop Loss Bot"`
- [x] deposit id 
- [x] token name and token image for `token1` (from coingecko api) 
- [x] DEX name (this can be inferred from the vyper smart contract since we have one contract per DEX) `dex: "Uniswap V2", "PancakeSwap", "ApeSwap"`

**Comment by verabehr** [comment]
https://service.robots.palomachain.com/robots?depositor=0x83334ef0C6f6396413C508A7762741e9FD8B20E9

**Comment by rootedbox** [comment]
the front end should be able to break down the information.. do we need this ticket?

**Comment by verabehr** [comment]
@rootedbox I'm not sure what you mean by that. @jamie088 do you have everything that you need from this API or do we need more changes?

**Comment by jamie088** [comment]
@rootedbox No, we can't get the chainId and bot type with current information (deposit ID, token address) on frontend. I think the backend uses the contract address and chain when receiving the deposit event from the smart contract, so it knows the chainId and the bot type. Right? cc: @verabehr

**Comment by verabehr** [comment]
@rootedbox added one additional item to this ticket per https://discord.com/channels/987730379182051408/1014207212954066975/1113906188954898432

**Comment by verabehr** [comment]
@rootedbox moving this back into your todo. LMK if you have any questions

**Comment by verabehr** [comment]
bot: "Momentum Bot", "DCA Bot", "Limit Order Bot", "Stop Loss Bot"
chain: "1", "56" (Please return chain ID)
dex: "Uniswap V2", "PancakeSwap", "ApeSwap"

**Comment by verabehr** [comment]
@rootedbox why was this closed? I still see 2 out of the 3 tasks open. Also I don't see the latest code PR 50 reflected in the api yet
