### ISSUE TITLE
Paloma Bot Approve/Sign Flow

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#259]
- [x] After the user press "Start Bot" should be redirected to the Approve/Sing Transaction Flow.

- [x] Step 1: Approve Token A
Design:
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=7952-23633&t=2a5v9pjE92Ulrb2p-4

Loading Icon:
![Image](https://github.com/VolumeFi/paloma/assets/22323189/a697f4c4-1ae1-488e-8b55-4b135d4252cb)

![Image](https://github.com/VolumeFi/paloma/assets/22323189/2c6d6bf3-a43b-4a23-bbbc-41f8112c1f70)

- [x] Step 2: Deposit 
Desing: 
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=7956-25480&t=2a5v9pjE92Ulrb2p-4

Loading Icon: 
![Image](https://github.com/VolumeFi/paloma/assets/22323189/f415067b-3c9d-4a42-9b7e-8bd2d014bea6)

![Image](https://github.com/VolumeFi/paloma/assets/22323189/9ac952e7-0e49-4bd4-bc10-80b73ad64be3)

- [x] Step 3: Processing Transaction.

Design: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=7956-25633&t=2a5v9pjE92Ulrb2p-4

Loading Icon: 
![Image](https://github.com/VolumeFi/paloma/assets/22323189/1b4b4539-099f-491c-a139-6031beba44b2)

- [x] Step 4: Bot Successfuly created 
Design: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=7957-25773&t=2a5v9pjE92Ulrb2p-4

Icon: 

![Image](https://github.com/VolumeFi/paloma/assets/22323189/c821a1f0-9878-44bb-a93e-dd35828a89ac)

![Image](https://github.com/VolumeFi/paloma/assets/22323189/51e8d235-7088-45e6-adf8-2fe59da305b8)

**Comment by verabehr** [comment]
@jamie088 I'm not seeing the modal for step 1 when I'm asked to approve the token. It works, but I don't see our modal 


![Image](https://github.com/VolumeFi/paloma/assets/19958639/8c7841d2-f9ca-408c-960a-2d403d40a72d)
