### ISSUE TITLE
Palomabot: Improve Switch network and connect wallet flow

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#260]
### Background

As a Palomabot user, who wants to start a bot, I want to have the least steps possible before I can start when my wallet is not coneected or I'm on the wrong network.

### Done when
**switch network**
- [x] If an EVM wallet is connected and the user is on the wrong network, the CTA button on the search result page always shows `Start Bot`
- [x] If I'm not connected to the right network and click `Start Bot`, 
    - [x] open metamask and ask the user to switch their network in metamask
    - [x] redirect to the "start bot" page
    - [x] show a modal over start bot page to let the user know that they need to approve in metamask (big text: Waiting for Nework Switch, small text: Confirm switch to {{Network}} in your EVM wallet
- [x] [fallback behavior] If I'm on the "Start Bot" page and don't have the right network, 
    - [x] the CTA button on the bottom of the view should say "Switch Network" and when clicked open metamask to switch the network.
    - [x] clicking on the buy with token should open metamask to switch the network.

**connect wallet**
- [x] If no wallet is connected, always show the CTA button on the search result page always shows `Start Bot`
- [x] If I'm not connected to a wallet and click `Start Bot`, 
    - [x] open metamask and ask the user to connect
    - [x] redirect to the "start bot" page
    - [x] show a modal over start bot page to let the user know that they need to approve in metamask (big text: Waiting for Nework Switch, small text: Confirm switch to {{Network}} in your EVM wallet
- [x] [fallback behavior] If I'm on the "Start Bot" page and don't have a wallet connected 
    - [x] the CTA button on the bottom of the view should say "Connect Wallet" and when clicked open metamask to switch the network.
    - [x] clicking on the buy with token should open the connect wallet modal

06/01:

- [x] As a user that initiates a bot and has no tokens available we should show a message "No tokens found" CTA: Connect another wallet". When the user presses the CTA Metamask should open for the user to switch wallet. Design:   https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=8250-22258&t=sD2lRwWZM1ItntWj-4
![Image](https://github.com/VolumeFi/paloma/assets/22323189/5a38ca1c-3662-46cb-b1f7-3b89af6bc190)

**Comment by verabehr** [comment]
thanks @jamie088. This looks mostly good, but when I click on the "Connect another Wallet" CTA from the last point, nothing happens

**Comment by jamie088** [comment]
Oh, I missed it. I will do it soon.

**Comment by jamie088** [comment]
@verabehr I tried to implement the switch feature to another wallet, but Web3 does not support it. It is impossible now.
Can we add text instead of a button?

**Comment by verabehr** [comment]
I see, yes that's fine. We can keep it as text. @jamie088
