### ISSUE TITLE
Customize telegram confirmation message

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#262]
Currently, there is no message when a user signs up for Telegram alerts for Palomabot. 

See video https://drive.google.com/file/d/1MqLS-t4bEe9td0wI-t2T19fGvAkRk5Qs/view?pli=1 (starting ~ minute 9:50) and screenshot below. 

![Image](https://github.com/VolumeFi/paloma/assets/19958639/8febc553-24ab-49c0-ac49-aa43ddde7d12)

After user hits "start" we want to show this message: 
"Congrats! You will now receive alerts when any of your positions is exited."

**Comment by verabehr** [comment]
There is  a confirmation message now, but the user doesn't get any messages it seems. 

![Image](https://github.com/VolumeFi/paloma/assets/19958639/4589d3a3-fce4-4a16-83cd-09587938e725)

**Comment by rootedbox** [comment]
still need to qa on prod
