### ISSUE TITLE
Paloma: Optimize Endlbock marshaling to remove yaml marshaling

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#265]
Comment from @tac0turtle: "you guys are doing some crazy marhsaling in your endblock. it would be good to remove that or change it to something efficient. Not sure how these to things interact but if just not use yaml marshaling here." 

Requirements:
* Refactor Endlbock to remove yaml marshaling

![Image](https://github.com/VolumeFi/paloma/assets/701864/2b60c06b-f94e-48b3-a7c6-0d7212d35a50)
![Image](https://github.com/VolumeFi/paloma/assets/701864/a62fab65-c1e9-4fc6-98e4-34863fc65a31)

**Comment by klausklapper** [comment]
@taariq @ToasterTheBrave I have a fix for this one ready, but it does come with the disadvantage of diluting the logging. There are lots of pointer fields on this message, and with the yaml marshalling, I assume the information was preserved. There's no way that I'm aware of to automatically dereference pointers using a regular `fmt.Sprintf()` call.

What is the amount of information we actually want to log here? Is there a subset of information that we can log instead?

**Comment by ToasterTheBrave** [comment]
@klausklapper Do you have a quick example of what the logs look like before and after?

**Comment by byte-bandit** [comment]
@ToasterTheBrave Most of the the log message consists of byte array slices and or pointer addresses, both with and without YAML marshalling, it's just formatted differently.

I'd argue that logging the entire message is superfluous, as we're able to retrieve the contents directly from Paloma anyway using the message ID, which we already log. Unless there is some benefit of pumping all message contents into the log, I will go ahead and remove the log field from all calls in Paloma & Pigeon.

**Comment by taariq** [comment]
Fixed with #265

**Comment by taariq** [comment]
Fixed by https://github.com/palomachain/paloma/pull/897
