### ISSUE TITLE
Updates to valset updates (Compass-evm)

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#27]
# Background

_Describe the problem that we are trying to solve with this feature._
_If a path to a solution is known, feel free to write it down, but have an open mind_

we need to update findLastValsetMessageID() function and compass-evm smart contract. The transaction delays a few minutes as too many API request to fetch event logs from BNB.

As a validator, I want the pigeon relayer to read the last valset message id from the deployed chain CompassEVM conract instead of fetching event log. 

Related to https://github.com/VolumeFi/paloma/issues/15

# Done when

- [ ] Compass-EVM provides valset-message ID for read

**Comment by taariq** [comment]
@webelf101 are we able to get this done by 03/10?

**Comment by taariq** [comment]
Delivered with https://github.com/palomachain/compass-evm/pull/17
