### ISSUE TITLE
BUG: withdrawal from LOB bot fails after multiple updates

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#270]
Some withdrawals (so far all except the first) from LOB fail and we're seeing this error in pigeon 

```
Jun 01 00:13:30 m1 pigeon[3695463]: {"level":"debug","msg":"Sending Msg: creator:\"paloma1jejkd87srrggj20jdtkchtkcjscfv7jvuctluv\" proof:\u003ctype_url:\"/palomachain.paloma.evm.SmartContractExecutionErrorProof\" value:\"\\n8execution reverted: TransferHelper: TRANSFER_FROM_FAILED\" \u003e messageID:62 queueTypeName:\"evm/bnb-main/evm-turnstone-message\" ","time":"2023-06-01T00:13:30Z"}
```

**Comment by taariq** [comment]
@webelf101 This bug still persists for another day:
1. We currently are unable to get the correct price on the front-end for the entry points. Prices are now denominated in the native token and need to be denominated in dollars.
2. @rootedbox attempted a number of fixes, but lack of clarity of how this works prevents others from working on this codebase. This needs to change with an EPIC documenting the Web3.js flow. Please create one after a fix is complete. 
3. Withdrawals appear to be working. However, it's not clear how they are performing.
