### ISSUE TITLE
APY number for Palomabot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#272]
As a user, I want to see two APYs on the Palomabot site so that I know that there is an opportunity to collet yield performance.

**Performance Requirements**
1. Estimate APY from all Palomabot activities based on users bots
2. Individual APY on the MyBots page that is an APY taken from the Profit/Loss column and estimated for the year
3. Add info note to a pop-up explaining how the APY is calculated and a warning that they are subject to change.

**Comment by fieldtheory123** [comment]
The current version of the script: https://github.com/VolumeFi/trading-bots/blob/main/apy.py

Waiting for confirmation: https://www.notion.so/volumefi/EPIC-04-14-23-PalomaBot-ai-Momentum-Chaser-Bot-79c25a79c6ce48afafbb4d0db1cbbfc4#115fc00e06614f3dba6d7a96a686f77a

**Comment by taariq** [comment]
@rootedbox & @webelf101 will you please review the comments ☝ and provide responses TODAY

**Comment by fieldtheory123** [comment]
My understanding is that the answer to my question is currently blocked by the work of moving order and trade data to CW.

**Comment by fieldtheory123** [comment]
> All the data exist in the DB. But it stores block number instead of timestamp. However, we can calculate the timestamp from the block number.

Thanks. This is helpful. I will update this ticket shortly.

**Comment by fieldtheory123** [comment]
@webelf101 I have updated the code. Could you help with remaining tasks?  
1. write the get_trades_per_user() function to read trade data from the DB
2. convert block time to timestamps

**Comment by verabehr** [comment]
@fieldtheory123 @webelf101 what is the latest status on this? I know you mentioned this in standup, but I lost track of what the latest is

**Comment by fieldtheory123** [comment]
Need @webelf101's help on the asks above
