### ISSUE TITLE
AI Dev Summit Landing Page

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#276]
Implement the AI Dev Summit Landing Page

Design: https://www.figma.com/file/5SxDu8o2gA3KWd2GZEHnZr/Volume-Website?type=design&node-id=8535-3757&t=uTBcD6wFmm6Eu9Y0-4

Images: https://drive.google.com/drive/u/0/folders/1S4WuOvT2U0pJJHG7pZTU0QGS2T41m1MS

- [ ] Contact menu and Apply to Sponsor/Speaker should redirect to: https://www.figma.com/file/5SxDu8o2gA3KWd2GZEHnZr/Volume-Website?type=design&node-id=8604-23977&t=uTBcD6wFmm6Eu9Y0-4

- [ ] For now we will hide Speakers and Presented by sections.

**Comment by wdev733** [comment]
fixes in https://github.com/VolumeFi/ai-developer-summit/pull/3
