### ISSUE TITLE
Add Profit/Loss Total

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#277]
As a user I want to see in My Bots view my Profit/Loss Total, which is the sum of all the Profit/Loss values of Active Bots. 

![Image](https://github.com/VolumeFi/paloma/assets/22323189/f564b153-6646-4b67-b668-b48f1857fa4f)

Design: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=6776-22904&t=NmRyZbLaVHKL41D7-4

**Comment by jamie088** [comment]
Done. https://github.com/VolumeFi/palomabot/pull/42
