### ISSUE TITLE
BUG: Nest Wallet showing only transaction history from March. Balances are Rewards are also incorrect/old.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#285]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

{WRITE YOUR ANSWER HERE}
Paloma Nest Wallet browser extension shows only transactions since March and the balance is wrong.
Example wallet: https://paloma.explorers.guru/account/paloma1wm4y8yhppxud6j5wvwr7fyynhh09tmv5x5sfzm
Shows Spendable: 14 GRAINs, but Nest shows 0.8. See attached picture.

![image](https://github.com/VolumeFi/paloma/assets/701864/d63a133f-6285-4246-976b-7ab567096eb0)

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

1. Balances need to be correct
2. Claimable GRAINs balances need to be correct.

**Comment by taariq** [comment]
Fixed with storage issue on LCD server detected and removed by @rootedbox

**Comment by rootedbox** [comment]
FCD is updating and we now have an easy way over bad blocks.. will update later in the day how much more is left. @verabehr

**Comment by rootedbox** [comment]
Still updating looking good should be ready by the morning.
