### ISSUE TITLE
Volume pages should unfurl

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#297]
Volume.finance links should unfurl when posted in discord or other social media. 

**Non-blog links**
title: Volume
description: Affordable Private Key Management Software for the Rest of Us
image: use favicon

**Blog links**
title: Blog title
description: Blog Intro 
image: use blog image

**Comment by taariq** [comment]
@wdev733 is this done?

**Comment by wdev733** [comment]
Not yet. Still in progress

**Comment by verabehr** [comment]
@wdev733 what is the blocker for this one?

**Comment by taariq** [comment]
@wdev733 if this is not done today, we will close the ticket. it's now 24hours.

**Comment by verabehr** [comment]
This is the branch? https://github.com/VolumeFi/volumefi-website/tree/fix/seo-unfurl

**Comment by wdev733** [comment]
@verabehr yes. but please do not merge it.

**Comment by verabehr** [comment]
@wdev733 will ask @rootedbox to look at it when he's

**Comment by taariq** [comment]
Closing as won't ship.
