### ISSUE TITLE
Security: Add validation that EVM arbitrary logic call can't exceed 20kb

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#30]
# Background

There needs to be a limit and we are setting it to 20kb.

# Done when

- [ ] there is a check in ValidateBasic to fail if the size is greater than 20kb

**Comment by klausklapper** [comment]
@verabehr What exactly are we limiting here? The entire abi json content, or only the hex payload?

**Comment by taariq** [comment]
Background notes: https://www.notion.so/volumefi/EPIC-03-18-22-FedEx-Message-Signing-ec3cdfb857b44f508212198c3de3bee4?pvs=4#4087586bd6fb42fa966b0f870243e1e0

**Comment by verabehr** [comment]
Also this https://www.notion.so/volumefi/Short-document-describing-the-initial-idea-of-sending-messages-to-Terra-where-20kb-could-become-an-i-a7bf41e609124c56bb25af64e7e39daf?pvs=4

**Comment by taariq** [comment]
@klausklapper We are seeing that this limit was constrained to Terra blockchain, when we first discussed. Terra blockchain is no longer a focus of our cross-chain execution. As such, we're going to close this ticket as unneeded.

**Comment by taariq** [comment]
Closed as stale story.
