### ISSUE TITLE
Prepare  DCA, limit order and stop loss bots for production

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#306]
### Background
We want to get the DCA bot, limit order bot and stop loss bot ready for production. All bots will be deployed on Uniswap v2 Ethereum only and each bot should have it's own contract code (repo) and deployed contract address

### Done when
**DCA bot**
- [ ] DCA bot is deployed on uniswap v2 ethereum with compass mainnet `0x7Eec3e2f4d567794B927B6d904Fbf973bC8D15e6`
- [ ] Outstanding tasks to get DCA bot script set up on server are confirmed

**Limit order bot**
- [ ] Limit order bot vyper contract is forked out into it's own repo (separate from momentum bot)
- [ ] Limit order bot is deployed on uniswap v2 ethereum with compass mainnet `0x7Eec3e2f4d567794B927B6d904Fbf973bC8D15e6`
- [ ] Outstanding tasks to get limit order bot script set up on server are confirmed

**Stop loss bot**
- [ ] Stop loss bot vyper contract is forked out into it's own repo (separate from momentum bot)
- [ ] Stop loss bot is deployed on uniswap v2 ethereum with compass mainnet `0x7Eec3e2f4d567794B927B6d904Fbf973bC8D15e6`
- [ ] Outstanding tasks to get stop loss bot script set up on server are confirmed

**Comment by taariq** [comment]
as  per @webelf101 _I was going to do that after msg.sender feature. I think we need to update all the Vyper contracts with msg.sender check._
