### ISSUE TITLE
Gas estimation error in create job on Paloma testnet 15

### ISSUE THREAD

**Issue by webelf101** [VolumeFi/paloma#310]
```
palomad tx scheduler create-job \
  --job-id msg_sender_test0 \
  --chain-type evm \
  --chain-ref-id bnb-main \
  --definition definition.json \
  --payload payload.json \
  --payload-modifiable=true \
  --from paloma1arwskydtxc8w6jw0pa227yslmzrwllspxrlaga \
  --gas auto --fees 5000ugrain \
  --node tcp://testnet.palomaswap.com:26656 \
  --chain-id paloma-testnet-15 \
  -y
```
I tried to create a job and I set gas auto as above. And the transaction failed as out of gas.
```
raw_log: 'out of gas in location: WritePerByte; gasWanted: 108860, gasUsed: 109791:
  out of gas'
```
The transaction hash is `0BE5360877B754AD807BDDB3D74E38BB2A4659E87246808311C3FA8E4DA7FBE1`
So I had to run a transaction with fixed gas as follows.
```
palomad tx scheduler create-job \
  --job-id msg_sender_test0 \
  --chain-type evm \
  --chain-ref-id bnb-main \
  --definition definition.json \
  --payload payload.json \
  --payload-modifiable=true \
  --from paloma1arwskydtxc8w6jw0pa227yslmzrwllspxrlaga \
  --gas 120000 --fees 5000ugrain \
  --node tcp://testnet.palomaswap.com:26656 \
  --chain-id paloma-testnet-15 \
  -y
```
And it was successful.
The transaction hash is `741CEAEB5565490129EB2AD315573268BBF73610836BC407D913AC4D10EE3FF3`
Why does the auto gas estimate fail?

**Comment by taariq** [comment]
The gasWanted is still LESS than the gasUsed. This is the first I am seeing of this type of error. It may be possible that the create-job command is not properly adjusting for gas?

**Comment by taariq** [comment]
_You have to find a validator that accepts a transaction with the gas that you set using flags above, unfortunately the use of “gas=auto” flag isn’t always said to give a positive outcome.

There is currently no tool to know all node’s min_gas_price, but if you try to do a transaction without gas_price, you will get to know the node’s min_gas_price by failed log._ from https://medium.com/@Pat_who/gas-fees-gas-price-on-cosmos-network-how-do-you-manage-them-bdf304b15a52

**Comment by taariq** [comment]
https://github.com/VolumeFi/paloma/issues/214#issuecomment-1553597700 provides a good solution. --gas-adjustment
