### ISSUE TITLE
ERC-20 blueprint token should check message sender

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#316]
### Background
https://www.notion.so/volumefi/EPIC-06-16-23-Palomabot-Fees-into-Paloma-Grain-Pool-0d40c46f180c4cb89e6ae6f715584b11?pvs=4

We want to upgrade the ERC-20 blueprint contract to only accept messages from a paloma address owned by the Paloma foundation

### Done when

- [ ] ERC-20 blueprint is updated to check the message sender and only accept messages from a specific Paloma address 
- [ ] Compass-EVM is updated (if needed)
- [ ] the new functionality is tested on the private testnet

**Comment by taariq** [comment]
> I was going to set the paloma address after deployment.

How will you set the address after deployment if the ERC-20 is owned by Compass-EVM?

**Comment by wc117** [comment]
I am going to set the address using a new job.

**Comment by taariq** [comment]
@wc117 is this ticket finished?
