### ISSUE TITLE
BUG: Paloma Nest Wallet does not claim GRAINs.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#337]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Nest wallet claim function for GRAIN rewards does not work and shows no error after entering password. Claim button sits as grey. 

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Try to claim GRAINs rewards. Does not work.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

GRAINS claim without issue.

**Comment by verabehr** [comment]
no longer reproducible
