### ISSUE TITLE
Palomaswap User Etherscan API to acquire and cache divisor decimal data for all tokens 

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#34]
# Background

Remove hard coded calculations and use https://api.etherscan.io/api?module=token&action=tokeninfo&contractaddress=0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0&apikey=3GTHDR8H336VTVGH1Q2D6V9X6VRTS9WT92 to identify the correct decimals for each token and store this in cache.

# Done when

- [x] Palomaswap usese API and cache divisor for correct decimals on all swaps
- [ ] Should available on different networks including Ethereum, BSC, Polygon, and etc...

**Comment by verabehr** [comment]
https://github.com/palomachain/paloma-nest-service/pull/24
