### ISSUE TITLE
Implement gas wallet usage for compass

### ISSUE THREAD

**Issue by ToasterTheBrave** [VolumeFi/paloma#340]
Compass needs a wallet per evm to hold gas from users in escrow before Pigeons execute jobs.  We then need to set up usage of this wallet
* Create a wallet when deploying a new compass evm
* Pigeons must attest that users added funds to the wallet
* Pigeons need the ability to claim their owed funds
  * We must ensure there can be no double-claiming of funds

More info in epic: https://www.notion.so/volumefi/EPIC-09-26-22-Paloma-Gas-Management-78319280833e4c7c8ffad368eddb1d91

**Comment by verabehr** [comment]
This is mostly encapsulated in the compass changes https://github.com/palomachain/compass-evm/pull/35

**Comment by byte-bandit** [comment]
This is done with https://github.com/VolumeFi/paloma/issues/1718
