### ISSUE TITLE
Rework Paloma scheduling logic for basic support of fee market

### ISSUE THREAD

**Issue by ToasterTheBrave** [VolumeFi/paloma#342]
This was rewritten to scope it down to the necessary features.  As written, it was too large for one ticket.  New tickets have been created for later delivery after the basics of this are working.

With the upcomming Pigeon fee market, we need smarter scheduling by Paloma.  Instead of round-robin pigeons picking up jobs, we want Paloma to assign jobs to a pigeon.

This first ticket is to lay the minimum required groundwork.  There are other tickets for the additional features of this.
* Paloma job execution should pick a pigeon and assign it the job.  This removes any scheduling logic from Pigeon.  Pigeons no longer pick work, they are assigned work.

More info can be found in the epic: More info can be found in the Epic: https://www.notion.so/volumefi/EPIC-09-26-22-Paloma-Gas-Management-78319280833e4c7c8ffad368eddb1d91

**Comment by taariq** [comment]
Closing as done.
