### ISSUE TITLE
Implement Pigeon fee market

### ISSUE THREAD

**Issue by ToasterTheBrave** [VolumeFi/paloma#343]
Implement pigeons setting their own fees and paloma exposing the lowest price to users

* Allow Pigeons to set their fee as a percentage over current gas fee
* Paloma needs to track the pigeon's fees
* Paloma needs to expose the total fee (gas fee + pigeon fee + security fee + community fund fee + ?) to users when they want to schedule a job

More info in epic: https://www.notion.so/volumefi/EPIC-09-26-22-Paloma-Gas-Management-78319280833e4c7c8ffad368eddb1d91

**Comment by taariq** [comment]
Closed and fixed with #1220
