### ISSUE TITLE
Track gas usage of pigeons for reimbursement

### ISSUE THREAD

**Issue by ToasterTheBrave** [VolumeFi/paloma#344]
Paloma needs to track the gas promised to a Pigeon that runs a job
* Calculate the expected gas for the job
* Track balance of security fees and community fund fees
* Track what pigeons are owed for successful job executions

More info in epic: https://www.notion.so/volumefi/EPIC-09-26-22-Paloma-Gas-Management-78319280833e4c7c8ffad368eddb1d91

**Comment by taariq** [comment]
Closing as old.

**Comment by byte-bandit** [comment]
This is done with https://github.com/VolumeFi/paloma/issues/1718
