### ISSUE TITLE
Add RSI technical indicator to momentumbot DB as we have MACD already

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#346]
### Background
https://www.notion.so/volumefi/EPIC-06-23-Technical-Indicator-bots-69a30e994bf94e7fafbf5e7b27234f42?pvs=4#a671345bcba34d9c8fbf5aa5d91f2540

### Done when

- [ ] momentum.palomabot.ai api has the MACD and RSI indicator attached to each result

**Comment by taariq** [comment]
@measure-fi will you share where the MACD data is already in the DB?

**Comment by measure-fi** [comment]
@taariq There is existing unused code to compute macd, it's only in the DB insofar as all coingecko responses are cached.

**Comment by fieldtheory123** [comment]
I will look into this ticket

**Comment by fieldtheory123** [comment]
@verabehr https://github.com/VolumeFi/trading-bots/pull/34
This PR should take care of ingesting technical indicators to the DB
