### ISSUE TITLE
BUG: mixpanel page_load events have no custom properties

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#348]
We're missing the volume events in mixpanel. There are no events for PAGE_LOAD_VOLUME and the PAGE_LOAD events (I think these are the Volume ones) don't have any properties 

https://mixpanel.com/project/2744781/view/3280621/app/events#wCUm45giDiMz

**Comment by rootedbox** [comment]
we are now saving page data in the page_load event Page:
https://volumefi-website-k590yy1av-volume.vercel.app/
