### ISSUE TITLE
Add bloxroute's frontrun protection to all txes

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#35]
# Background

We need to send users' swap tx to BloxRoute’s private validators, instead of the mempool.

EPIC: https://www.notion.so/volumefi/EPIC-03-03-Add-BloxRoute-to-PalomaSwap-0c08a4aacebe4054b36c37b33a941b25
@verabehr 

# Done when

- [ ] All txes, regardless via the DEX’s router or Wallchain’s proxy router, should be sent to BloxRoute’s endpoint.

**Comment by verabehr** [comment]
https://github.com/palomachain/paloma-swap-ui/pull/63
