### ISSUE TITLE
Private Credit API and functionality

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#350]

**Comment by verabehr** [comment]
@wdev733 when will this be complete?

**Comment by taariq** [comment]
@wdev733 we need you to share the status of this ticket here please.

**Comment by taariq** [comment]
@wdev733 If the API is working, let's close as completed and continue to bring the apps into Volume.

**Comment by wdev733** [comment]
@taariq Need some updates. I'll close it when I am done
