### ISSUE TITLE
Modify Momentum and Stop-loss scripts

### ISSUE THREAD

**Issue by webelf101** [VolumeFi/paloma#352]
https://github.com/VolumeFi/limit-order-bot-script/blob/04bf65fc70e43744391164ec02c765bc3a605cc0/limit-orders.js#L348-L352
This is the code part to check profit-taking and stop-loss condition. Please use either of them on momentum and stop-loss bot.

**Comment by taariq** [comment]
@rootedbox please review and request additional context as needed.

**Comment by verabehr** [comment]
@webelf101 @rootedbox  @taariq I think this is the logic: 

momentum bot: stop loss and profit taking
stop loss bot: stop  loss only
limit order bot: profit taking only
