### ISSUE TITLE
My bots api issue

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#353]
I created 2 new bots in Momentum Bot (one is in Uniswap V2 and another is in Pancakeswap). But I can see the one bot created using Uniswap V2 but can't see another bot created using Pancakeswap in my bots api results. What is the problem? Please check the contract address are same with Frontend. frontend is using this contract address: `0x017DE2968e78a6e4B637206f7c2437F122c4ec03` BSC_Pancakeswap.

And also I still can't see the bot type in my bots api results.
cc: @verabehr

**Comment by verabehr** [comment]
@rootedbox does the DB need to be cleared again?

**Comment by jamie088** [comment]
One question @rootedbox
What value returns as a 'deposit_id' in my bot api results? You can get the deposit_id from the deposit event when creating a new bot. Are you correctly returning this value as deposit_id? I tested Stop bot using this deposit_id but failed. This value is incorrect and I guess it looks like the backend is using a value that automatically increments by 1, not get from deposit event. Could you please check this again?
