### ISSUE TITLE
Momentumbot Indicator integration

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#358]
### BAckground
https://www.notion.so/volumefi/EPIC-06-23-Technical-Indicator-bots-69a30e994bf94e7fafbf5e7b27234f42?pvs=4#9a751d51d1864fad95cac3998bbf24ed

### Done when 

- [ ] momentum search is using the newly added MACD and RSI indicators
- [ ] UI is integrated with vyper smart contract
- [ ] my bots page reads from service api

**Comment by taariq** [comment]
Won't ship
