### ISSUE TITLE
Upgrades to contract for registering/claiming from ethereum transactions

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#36]
# Background

_Describe the problem that we are trying to solve with this feature._
_If a path to a solution is known, feel free to write it down, but have an open mind_

We want to make updates to the Wallchain CW contract based on our initial testing. Details https://www.notion.so/volumefi/EPIC-01-27-Paloma-Wallet-Claim-Grains-Drop-for-Paloma-Swaps-with-Wallchain-enhancement-f992a1b800814909b520d242e82b66c7?pvs=4#8ba6b11b67ea471a92a2b1f82d7c12cf

# Done when
- [ ] events are emitted whenever a successful register or claim transaction happens
- [ ] registration stop gap is implemented so that registrations throw errors when balance is less than registration amount.

**Comment by taariq** [comment]
Closed and fixed with https://github.com/palomachain/paloma-rs/pull/61
