### ISSUE TITLE
BUG: Refreshing the palomabot website n times disconnects teh EVM wallet

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#367]
Steps to reproduce: 
1. connect EVM wallet to Palomabot
2. refresh 2-3 times

Expected: EVM wallet should still be connected

Actual: EVM wallet is no longer connected and user has to connect again

**Comment by jamie088** [comment]
Could you please check this problem on your side? This problem did not happen on my side. @verabehr

**Comment by verabehr** [comment]
yes, I could reproduce see my loom here https://www.loom.com/share/c647ebb2d0d74e90af6b45a0576d9673

**Comment by verabehr** [comment]
happens on other pages as well, not just this one

**Comment by jamie088** [comment]
Sorry, could you please check again after cleaning the cache? @verabehr

**Comment by verabehr** [comment]
Just this? or more?

![Image](https://github.com/VolumeFi/paloma/assets/19958639/d4bee72a-139a-4f64-ac59-d721681580c3)

**Comment by jamie088** [comment]
Please select Browsing history. and also please clear local storage too

![Image](https://github.com/VolumeFi/paloma/assets/83244763/f35a8d3d-127d-4420-84a0-bbb9384644e4)

**Comment by verabehr** [comment]
I cleared all three (it didn't show in the loom unfortunately), but now the connected wallet doesn't even show in the beginning. I also still see the issue 

https://www.loom.com/share/44d7691d7eaa4dcf8f62cda7140e5ac1
