### ISSUE TITLE
UI Feedback Palomabot 06/26

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#368]
- [x] on momentumbot: Fetching prices is hard to read - it's grey on grey.
We need to change color of the CTA to #F9DDFB 
<img width="439" alt="Captura de pantalla 2023-06-26 a las 21 11 06" src="https://github.com/VolumeFi/paloma/assets/22323189/486d7b96-12b1-42f6-bbad-3cb671e49e80">
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=7922-22390&mode=design&t=XrAGD3T8n0R3zNrP-4

Loading icon: 
![Spinner-Round_Spinner-Round-05_2 (1)](https://github.com/VolumeFi/paloma/assets/22323189/194c00bb-d624-40b8-a3e3-08e14fb2ba5b)

- [x] While the transaction is processing we will show a progress bar and the "bird" will be static. 

<img width="350" alt="Captura de pantalla 2023-06-26 a las 21 54 25" src="https://github.com/VolumeFi/paloma/assets/22323189/e50e927b-7778-4ffc-bb35-fb084bfd21db">

Design: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=7956-25633&mode=design&t=XrAGD3T8n0R3zNrP-4

Progress Bar:
![Loading Bar](https://github.com/VolumeFi/paloma/assets/22323189/d63751e5-c27c-4850-bad6-79b9906eeb75)

- [x] on the momentum listing page, the token name and icon should be clickable as well to get to the "start bot" swap screen

**Comment by joycehermosilla** [comment]
I updated the designs and icons @jamie088 @verabehr

**Comment by fieldtheory123** [comment]
@verabehr @joycehermosilla @jamie088 Adding two things from my testing of the limit order bot:
1. I can't set limit price (green circle). The idea is that the FE would allow users to set the "swap amount", which should be higher than the market rate. But the FE seems to fetch price and set it directly.
2. I have sufficient BNB for the trade but got a "insufficient fund" msg (red circle).
3. "Swap" and "Swap with" look very confusing and hard to know which is which. Also, usually the top bar is for tokens users have and the bottom bar is for tokens users want to swap for. (blue circle)
<img width="556" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/8ed252cc-5fb6-4bc8-9fe5-c1fe8829fbcc">

**Comment by fieldtheory123** [comment]
Suggestion regarding point 3 above: 
`You sell; 
You buy`
1inch, DYFN both do it that way
<img width="358" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/0e8e1538-0f91-481f-a64e-e70d7878a028">
