### ISSUE TITLE
service for uniswap v3 twap bot is set up

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#371]

**Comment by verabehr** [comment]
blocked by completion of smart contracts for v3 variants

**Comment by webelf101** [comment]
Backend script for Uniswap V3 will be same as Uniswap V2 TWAP bot script. So please create a duplicated service as Uniswap v2 TWAP bot but not started one. I will set the parameters so that it can work as a Uniswap V3 TWAP bot. @rootedbox

**Comment by rootedbox** [comment]
@webelf101 /home/rootedbox/app/curve-twap-3-dca-bot-script location of new setup.. it is not turned on as requested
