### ISSUE TITLE
Limit Order Bot: tokens still in the smart contract after swap

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#376]
After deposit, my swap (bnb->busd) was executed https://bscscan.com/tx/0x5803b61132290c9ede2ae7cd04dc4aa4ea1a94578dc390b4fd31793caa706971

But the busd is in the contract instead of being sent back to me. And I don't have any LOB under "my bot" so there's no FE option for me to get the tokens back.

**Comment by verabehr** [comment]
This is not a bug. The funds are only returned to the user after the bot executes. I see 2 positions for this wallet in the API, so if there is a but it is not in the smart contract
