### ISSUE TITLE
BUG: FCD doesn't recover if a block is not found

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#380]
When the FCD can't find a block it just gives up and doesn't try the next block [06-26 17:52 [ERROR]: http://validator.palomachain.com:1317/cosmos/base/tendermint/v1beta1/blocks/2000715 height 2000715 is not available] 

Proposed solution: 
Skip the block and continue

**Comment by taariq** [comment]
Closed with upgrade on #523
