### ISSUE TITLE
BUG: deleting bot creates a duplicate listing - but nothing is on the my bot api

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#382]
see my video here https://drive.google.com/file/d/1Ssb1k7UGEmWFqFW9bBPvtQgqYOH3oHwb/view?usp=sharing - the mybot api does not show a duplicate

This went away on refresh though

**Comment by verabehr** [comment]
were you able to reproduce this @jamie088 didn't happen to me last time I canceled, so wondering if this is actually a persistent issue

**Comment by jamie088** [comment]
@verabehr Fixed. https://github.com/VolumeFi/palomabot/pull/70
