### ISSUE TITLE
BUG: Web socket connection to walletconnect.org rejected and ongoing using Chrome

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#389]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

WebSocket connection to 'wss://q.bridge.walletconnect.org/?env=browser&host=www.palomabot.ai&protocol=wc&version=1' failed: 
_socketCreate @ 619.aec64c9951871019.js:1
open @ 619.aec64c9951871019.js:1
_initTransport @ 619.aec64c9951871019.js:1
m @ 619.aec64c9951871019.js:1
N @ 619.aec64c9951871019.js:1
register @ 619.aec64c9951871019.js:1
U @ 619.aec64c9951871019.js:1
D @ 619.aec64c9951871019.js:1
getProvider @ _app-295e9386a0c1d6ba.js:22

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

No walletconnect errors.

**Comment by jamie088** [comment]
@taariq  **WalletConnection. Inc** shut down **walletconnect v1.0** on **June 28th**. So should migrate to **v2.0**.
I implemented walletconnect with v2 in palomabot from the beginning but still using v1 in the Pancakeswap SDK so I need to upgrade this. I tried it before sometimes, but it was difficult to match with other package versions. I will fix it asap.
(I think this problem is in palomaswap too.)

**Comment by taariq** [comment]
FYI @wdev733 FYI

**Comment by taariq** [comment]
@jamie088 how much more effort required here?

**Comment by jamie088** [comment]
I think I need to fix it at least 5 hours. @taariq 
I couldn't work yesterday because of another ticket. And I can't work today as my plan is to work on the Curve Limit order bot. If there are no other priority tickets tomorrow, I will fix it.

**Comment by taariq** [comment]
@jamie088 let's leave this alone for now. We need working bots. We can fix later.
