### ISSUE TITLE
CHORE: Finish setting up private credit api

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#390]
The private credit api code was updated here https://github.com/VolumeFi/private-credit-db and needs to be fully deployed. Some tasks were already done and currently calling private-credit-api.volume.finance gives a 404 ngnix error

Done so far, but please qa the work:
1. Repo cloned on rootedbox@nest-service.palomachain.com in the ~/app folder --> `~/app/private-credit-db`
2. Added a `start.sh` script to the directory
3. Added `.env` file
4. created a service file `/etc/systemd/system/private-credit-api.service`
5. Set up an A record private-credit-api.volume.finance https://ap.www.namecheap.com/Domains/DomainControlPanel/volume.finance/advancedns
6. Started service

**Comment by rootedbox** [comment]
server is setup and running with certs https://private-credit-api.volume.finance
