### ISSUE TITLE
Add bots from old contract to API

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#391]
### Background
We have old contracts from prior testing that still have funds in them from team members as well as investors. We need a UI to allow folks to withdraw

### Done when

- [ ] Active bots from contracts listed here https://www.notion.so/volumefi/Palomabot-repo-inventory-73691914623c4e91a0972ef6f13aad98?pvs=4#08fa6899e47a420baea7c6f47c95b573 are included in the service API
- [x] #457
    - [ ] token ID and token image for token1
    - [ ] deposit_id
    - [ ] network_name
    - [ ] bot: 'old'
    - [ ] bot contract address

**Comment by jamie088** [comment]
@verabehr No, that's enough. I only need 4 values: token name, image, chain, and contract address. You can remove DEX value.

**Comment by taariq** [comment]
@rootedbox please update us with progress on this before you leave, tonight. @jamie088 We need this urgently

**Comment by rootedbox** [comment]
as long as we only add contracts to the network file and never remove them then we are good.

**Comment by rootedbox** [comment]
add "old tag" to old contracts

**Comment by taariq** [comment]
> add "old tag" to old contracts

Anything blocking us from getting this done on Monday @rootedbox?

**Comment by jamie088** [comment]
@rootedbox I updated my requirements, so please check it.
