### ISSUE TITLE
My bot page: Withdraw from old contracts

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#392]
### Background
We have old contracts from prior testing that still have funds in them from team members as well as investors. We need a UI to allow folks to withdraw

### Done when

- [x] My bot page has a new tab (Old Bots)
- [x] User can see token name and image
- [x] User can withdraw tokens from contract

**Comment by verabehr** [comment]
blocked by https://github.com/VolumeFi/paloma/issues/391

**Comment by taariq** [comment]
@rootedbox and @jamie088 what's the status here?

**Comment by taariq** [comment]
@rootedbox please verify this is working.
