### ISSUE TITLE
Smart Contract & Backend for Paloma private credit

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#394]
### Background
https://www.notion.so/volumefi/EPIC-06-23-MVP-Paloma-Private-Credit-a21fb924e5054bb4b75e0e11ceb2a85e?pvs=4#92525d1814a14a909abdf6a165cf19b6

### Done when
We can perform automated swaps on chain for any Volume swap address

**Comment by taariq** [comment]
Closing as not needed.
