### ISSUE TITLE
Update fees on for bots

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#398]
Gas Refund of 0.015ETH / 0.0015BNB/ 0.15Matic
Transaction fee of 0.5% (original token amount)

Requirements:
1. Gas Refund fees go into the gas-refund wallet
2. Transaction fees go into a separate Paloma EVM wallet. Please confirm whether this add more costs?

**Comment by taariq** [comment]
Requires that all bots are stopped and the Vyper contract replaced.

**Comment by taariq** [comment]
@webelf101 is this complete?

**Comment by taariq** [comment]
Please use this address for fees: `0x7a16fF8270133F063aAb6C9977183D9e72835428`

**Comment by taariq** [comment]
Closing as fixed.
