### ISSUE TITLE
Volume apps UI

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#404]
As a user, I want to see a menu item called "APPS" where the user can select the following products:

- Volume Private Credit
- All bots that are listed on palomabot.ai

We want the same functionality for the bots listed on volume that we have on palomabot. 
_Note that we will have new contracts for each bot deployed since we won't charge a fee via the contract for the bots listed on volume_

Design: https://www.figma.com/file/5SxDu8o2gA3KWd2GZEHnZr/Volume-Website?type=design&node-id=9140-3934&mode=design&t=qVNJLOkmrQZkZ4la-4

**Comment by taariq** [comment]
Will pause and re-assign to new Front-end Dev.
