### ISSUE TITLE
BUG: DCA But Submit button does not work

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#406]
The DCA Bot button does not function. See the Loom: https://www.loom.com/share/f9867f994ea34718a0b356b70baec2e9?sid=53360a33-1c85-4d15-b458-92e24b44d315

**Comment by jamie088** [comment]
I disabled Start DCA bot button because start DCA bot is working now but can't get the DCA bot from robots BE api.
And after I get the DCA bot, I need to fix the my bots page with api returns result.
value key matching between FE and BE
