### ISSUE TITLE
Question: Are we able to deploy ERC20 as Paloma Account for user or do we need something else?

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#407]
Question: Are we able to deploy ERC20 as Paloma Account for user or do we need something else?

Volume custody wants to create addresses in its Addressbook that are Paloma controlled, but authorized by users Paloma address. Is our ERC20 able to be used for this case? Users will send funds to Paloma's ERC-20 on EVM, but authorization to control funds will be from users Paloma key.

Also, this will require gas to create these contracts so is there a cheaper approach?

**Comment by taariq** [comment]
@wc117 will you respond to this question please?

**Comment by verabehr** [comment]
@wc117 @wdev733 @taariq is this question still open/relevant?
