### ISSUE TITLE
BUG: Duplicated my bot

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#417]
`The Virtua Kolect` bot was duplicated on my bot api result. 
![image](https://github.com/VolumeFi/paloma/assets/83244763/883dd2d2-ca58-4ebf-bf1a-6b1ac88b2af0)
![image](https://github.com/VolumeFi/paloma/assets/83244763/e2d818f3-dd50-4144-8134-97b2910162a9)
As you can see in the screenshot, my bot API has duplicated the tvk bot with the same deposit_id 17.

**Comment by taariq** [comment]
I have seen this problem as well.

**Comment by rootedbox** [comment]
I can't reproduce this right now and I'm not seeing it in the current data. please set to in progress when we see this again. @jamie088 @taariq
