### ISSUE TITLE
URGENT: Add Bot Metrics to Mixpanel for Tracking

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#419]
As a Marketing Team member, I want to add Paloambot tracking to mixpanel:
1. Active Bots (Bar chart)
  a. Name of the Bot
  b. Number of Bots for that Name

2. Total Bot TVL (Line chart in USD live bots)

3. Total Bot Volume (Line Chart of Total Deposits)

**Comment by rootedbox** [comment]
I've added mix tracking to all bots.. and pushed code to server tomorrow I will add the reports. @taariq
