### ISSUE TITLE
Schedule jobs to new pigeons on failure to run by an assigned pigeon

### ISSUE THREAD

**Issue by ToasterTheBrave** [VolumeFi/paloma#420]
If a pigeon fails to run a job, or has a failure from the job, a new pigeon should be selected up to X retries

More info can be found in the epic: More info can be found in the Epic: https://www.notion.so/volumefi/EPIC-09-26-22-Paloma-Gas-Management-78319280833e4c7c8ffad368eddb1d91

**Comment by taariq** [comment]
Closing this as now a duplicate of #1036
