### ISSUE TITLE
[PF 01] Track metrics

### ISSUE THREAD

**Issue by ToasterTheBrave** [VolumeFi/paloma#421]
Track pigeon performance for use in scheduling weights

We want to assign jobs to pigeons based on several weighted features.  The groundwork for this should already be done, but we need to track the features so we can use them.

- The pigeon's message uptake rate
- The pigeon's message delivery success rate
- The pigeon's message delivery speed
- Active MEV Endpoint * (Mev endpoint setting)
- Active tx type: 2 set* (eip 1559 for lower gas)

More info can be found in the epic: More info can be found in the Epic: https://www.notion.so/volumefi/EPIC-09-26-22-Paloma-Gas-Management-78319280833e4c7c8ffad368eddb1d91

---

## ⏰ Estimate

`8 days`

## ❓ Open questions

- What's the best place to store the metrics? Directly in scheduler or new module? I need to take a fresh look at the code that's already there.

**Comment by taariq** [comment]
Added TWO new weights:
- Active MEV Endpoint * (Mev endpoint setting)
- Active tx type: 2 set* (eip 1559 for lower gas)
