### ISSUE TITLE
[PF 03] Adjust job assigning to include pigeon performance information

### ISSUE THREAD

**Issue by ToasterTheBrave** [VolumeFi/paloma#422]
We want to assign jobs to pigeons based on several weighted features.  The groundwork for this should already be done, and the data should be tracked.  Now, it's time to add it into the weighting system

- The pigeon's message uptake rate
- The pigeon's message delivery success rate
- The pigeon's message delivery speed
- Active MEV Endpoint * (Mev endpoint setting)
- Active tx type: 2 set* (eip 1559 for lower gas)

More info can be found in the epic: More info can be found in the Epic: https://www.notion.so/volumefi/EPIC-09-26-22-Paloma-Gas-Management-78319280833e4c7c8ffad368eddb1d91

---

## ⏰ Estimate
`1 - 2 days`

**Comment by taariq** [comment]
@byte-bandit and to confirm, we include Pigeon Relay Fee as one of the factors to adjust the assignment. Yes?

**Comment by byte-bandit** [comment]
@taariq Correct. We still have to push out PF02 for this to take effect, but that should be a straight forward change. After that, the only large piece of engineering left is tracking the fees and collecting them, which still has some question marks on it.
