### ISSUE TITLE
Deploy VolumeApp and VolumeBots

### ISSUE THREAD

**Issue by wdev733** [VolumeFi/paloma#425]
Deploy 2 websites on Vercel

- Volume App
repo: https://github.com/VolumeFi/volume-app
domain: app.volume.finance

- Volume Bot
repo: https://github.com/VolumeFi/volumebot
domain: bots.volume.finance
[Important] Deploy `dev` branch.

**Comment by rootedbox** [comment]
https://app.volume.finance and https://bots.volume.finance are up
