### ISSUE TITLE
EPIC: New Stop Loss Bot for LP Positions

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#426]
As a user, who is a Liquidity Provider on an AMM, I want my liquidity pools balance to be rebalanced if I have 80%

**Comment by taariq** [comment]
@fieldtheory123 as per our chat, will you complete and we can build the EPIC off the story.

My view: 1) Paloma holds the LP position and exits when price declines and value is lost.

**Comment by fieldtheory123** [comment]
EPIC started https://www.notion.so/volumefi/EPIC-07-21-23-Stop-Loss-Bot-for-LP-Positions-0f49fb1c5b16480c9022ff4e22bcde2c

**Comment by fieldtheory123** [comment]
Done.
