### ISSUE TITLE
BUG: DCA bot 

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#429]
Taariq created a DCA bot successfully but My bots api are returning empty result.
https://etherscan.io/tx/0x111462b4cb271adfc47862a824a96b5deaff050a74a078b24d99c95964d56cbd
https://service.palomabot.ai/robots?depositor=0x83334ef0C6f6396413C508A7762741e9FD8B20E9
Could you please check this? @rootedbox

**Comment by taariq** [comment]
Okay. SO I see the bot, but where is the token?

**Comment by jamie088** [comment]
@taariq I think the backend API is failing to execute the contract on every set trade time.
So I created this ticket: https://github.com/VolumeFi/paloma/issues/416

**Comment by taariq** [comment]
Fixed.
