### ISSUE TITLE
Implement the Paloma Gravity Bridge on the Cosmos Side

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#431]
//We want to finally implement the Gravity Bridge features on the Paloma Go side that are missing from Paloma.

Our work on https://github.com/cosmos/gravity-bridge is the basis for Paloma's Compass-EVM. We want the Goside features for being able to lock assets on Paloma and target chains with Gravity.

Other bridges in Go include:
https://github.com/axelarnetwork?q=&type=all&language=go&sort=
https://github.com/cosmos/gravity-bridge
https://github.com/PeggyJV/gravity-bridge/issues/360
https://www.notion.so/volumefi/EPIC-02-xx-Mutli-EVM-Gravity-Upgrade-09aa9a2f15f84e0596dbbaafa48d00a6#0dbca3f9d5f64da2b36508c911b4198a

**Comment by taariq** [comment]
I have DRAFTED the initial Gravity EPIC here https://www.notion.so/volumefi/EPIC-07-14-23-Paloma-Bridge-Completion-4fc345966c4f48c3b4aca2e84bc5d5b9

**Comment by verabehr** [comment]
@ToasterTheBrave how much time will you need after this is unblocked?

**Comment by ToasterTheBrave** [comment]
@verabehr That's really hard to say.  Not having the token contract is preventing me from seeing if things work (then no time) or if there's a fundamental flaw (then potentially several days of time).

**Comment by verabehr** [comment]
Got it, thanks @ToasterTheBrave.
