### ISSUE TITLE
Aave Leverage Borrower Epic

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#432]

**Comment by fieldtheory123** [comment]
EPIC initiated.

**Comment by fieldtheory123** [comment]
All but user stories are done. Stories are on pause until we decide to start building the product. 

https://www.notion.so/volumefi/EPIC-07-07-23-AAVE-leveraged-borrow-bot-3fd2a9ef6ae4402180982d4f0b19f2c2
