### ISSUE TITLE
BUG: My bot API isn't getting the selected user's bot correctly.

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#434]
https://service.palomabot.ai/robots?depositor=0x8F5eBDdcf2bae86D3A4E3C4De427E705d2eBF432
![image](https://github.com/VolumeFi/paloma/assets/83244763/a1ec62e9-8f5a-4a83-95ee-e7cec78ae70e)
LUKSO bot is not my bot. (depositor is 0x83334ef0C6f6396413C508A7762741e9FD8B20E9)
Not filtering depositor now.

**Comment by taariq** [comment]
Fxed.
