### ISSUE TITLE
CHORE: run staking script for Volume validator via cron

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#45]
# Background

_Describe the problem that we are trying to solve with this feature._
_If a path to a solution is known, feel free to write it down, but have an open mind_

With inflation turned on, we are getting rewards that need to be claimed and restaked regularly 

# Done when

- [ ] we have a daily cron job that runs this script for the mainnet validator https://github.com/VolumeFi/staking-tools/blob/main/paloma.sh

**Comment by rootedbox** [comment]
Second part of script not working... 

Get reward from Delegation
{"height":"0","txhash":"498E26474F0E6C50EECAC08296A3EB971F2C1AD9A3F16442EBA3879FECEC9FE1","codespace":"","code":0,"data":"","raw_log":"[]","logs":[],"info":"","gas_wanted":"0","gas_used":"0","tx":null,"timestamp":"","events":[]}
BALANCE: 71115983 ugrain

Claim rewards

incorrect passphrase
EOF
EOF

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/staking-tools/pull/1/files fixes for spaces in script..
