### ISSUE TITLE
Create Epic and Stories for Profit Taking & Stop Loss Bot

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#452]
CHORE: To create the Epic for the Profit Taking & Stop Loss Bot for Curve, Uniswapv2 and Pancakeswap

**Comment by fieldtheory123** [comment]
Done. https://www.notion.so/volumefi/EPIC-07-14-23-Stop-loss-and-profit-taking-bot-for-Curve-Uniswapv2-and-Pancakeswap-925417f7334c48ddb3dbe40b05c68099
