### ISSUE TITLE
Confirm Prior Art on Arbitrum and Optimism via Axelar

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#467]
Check with Axelar on their prior art for support of Arbitrum and Optimsim and confirm design opportunities for Paloma.

**Comment by byte-bandit** [comment]
Axelar core is written in `Go`, but looking at both Axelar satellite as well as their relayer (the components that actually relay and sign to other chains) are both written in TypeScript on top of `NestJS`. This is why they don't face the whole `geth` issue.

**Comment by taariq** [comment]
Got it. Yeah. We are writing our commands in Go. Okay. We're a different beast. Closing as resolved!
