### ISSUE TITLE
BUG: Nest Wallet unable to send transactions as of 07/17

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#469]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

The Nest Wallet is unable to complete send or claim transactions. This may be an issue with the FCD Server.

**Comment by verabehr** [comment]
I'm not able to reproduce this issue as of 9:49am PT
