### ISSUE TITLE
Curve liquidation bot epic

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#470]

**Comment by fieldtheory123** [comment]
Reviewing Curve's liquidation scripts

**Comment by fieldtheory123** [comment]
https://www.notion.so/volumefi/EPIC-07-21-23-Curve-liquidation-bot-53dfb2e553ea4cb5b5c7f84942143e56

**Comment by taariq** [comment]
Closing as agreed Lending Bot as priority for dev/rev/Curve.
