### ISSUE TITLE
Set up vote distribution script on server

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#471]
https://github.com/VolumeFi/vote-distribution-bot-script

https://www.notion.so/volumefi/Palomabot-repo-and-contract-address-inventory-73691914623c4e91a0972ef6f13aad98?pvs=4

**Comment by rootedbox** [comment]
@wc117 we still need an example in the README on how to configure  these scripts

https://github.com/VolumeFi/vote-distribution-bot-script/blob/master/README.md

cc: @verabehr

**Comment by verabehr** [comment]
@rootedbox will you please share instructions that worked for you before? This is not the first bot, but the first bot for @wc117, so we can move forward faster. We've gone back and forth a few times now

**Comment by rootedbox** [comment]
@wc117 we are missing environment variables and what the variables should be configured too.

**Comment by wc117** [comment]
Okay. I will set it but we need to update VoteDistributionBot contracts and script. So let me do that after the update.

**Comment by wc117** [comment]
@rootedbox

**Comment by rootedbox** [comment]
They are now setup and running as cronjobs
