### ISSUE TITLE
Update Python SDK with Skyway commands

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#477]
CHORE: Update Python SDK with all Skyway commands.

query commands: https://docs.palomachain.com/guide/develop/palomad/subcommands-q.html#skyway-attestations
tx commands: https://docs.palomachain.com/guide/develop/palomad/subcommands-tx.html#gov-submit-legacy-proposal

**Comment by verabehr** [comment]
This is blocked until the commands are available as rpc endpoints

**Comment by taariq** [comment]
@webelf101 will you please test again?

**Comment by taariq** [comment]
@webelf101 after the votes have passed. That will be in 4 hours.

**Comment by taariq** [comment]
Closing as shipped.
