### ISSUE TITLE
Mixpanel: track wallet connect/disconnect

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#48]
# Background

_Describe the problem that we are trying to solve with this feature._
_If a path to a solution is known, feel free to write it down, but have an open mind_

As Volume team, I want to track the wallet connect and disconnect events from Palomaswap in Mixpanel 

# Done when

- [ ] Wallet connect and disconnect to EVM wallet or Nest is tracked including
            1. wallet type (Paloma or EVM)
            2. wallet balance
            3. wallet address

**Comment by rootedbox** [comment]
@verabehr think this is a front end issue

**Comment by verabehr** [comment]
this is not needed
