### ISSUE TITLE
BUG: Mixpanel still adding duplicates in Bot Performance Tracking

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#482]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

https://mixpanel.com/project/2744781/view/3280621/app/events#bftGCwucNqvs looks very strange. 

These three transactions are duplicates of one transaction. According to @rootedbox looks like a big om curvestoploss allowing multiples to be added of the same bot.

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/limit-order-bot-script/pull/67
https://github.com/VolumeFi/momentum-order-bot-script/pull/8
https://github.com/VolumeFi/curve-limit-order-bot-script/pull/8
https://github.com/VolumeFi/curve-stop-loss-bot-script/pull/6

@taariq @verabehr these are required before I add the following index to fix the problem `CREATE UNIQUE INDEX idx_deposits_on_multiple_columns ON deposits (deposit_id, network_name, bot, contract);
`

**Comment by taariq** [comment]
@rootedbox these are all merge. Please add the index and test.
