### ISSUE TITLE
BUG: Sentry alerts for Curvebot that must be fixed before 07/19

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#483]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

**PALOMABOT-1T - TypeError: Cannot read properties of undefined (reading 'networkVersion')**
https://volume-x3.sentry.io/issues/4323939359/?alert_rule_id=14480958&alert_timestamp=1689699216471&alert_type=email&environment=vercel-production&project=4505354828185600&referrer=alert_email

**PALOMABOT-1S - TypeError: Cannot read properties of undefined (reading 'networkVersion')**
https://volume-x3.sentry.io/issues/4323939175/?alert_rule_id=14480958&alert_timestamp=1689698874990&alert_type=email&environment=vercel-production&project=4505354828185600&referrer=alert_email

**Comment by taariq** [comment]
Ticket updated and key error https://github.com/VolumeFi/paloma/issues/484 assigned to @rootedbox

**Comment by verabehr** [comment]
Closing, this appears to be all testing related
