### ISSUE TITLE
Palomabot: Add money back guarantee disclaimer and contract addresses

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#486]
### Background
https://www.notion.so/volumefi/EPIC-07-19-23-UI-UX-Enhancements-for-Palomabot-VolumeApps-and-Curvebots-2c5d5b9b079b43dfb8ef28b648b29c85

### Done when 

- [x] we have the money back disclaimer on all palomabot pages (like we have for curvebot) `Money Back Guarantee: If you are unsatisfied with the performance of the bot, Volume will refund your gas and bot execution fees, upon proof of ownership of the signing key, no questions asked.`
- [x] The disclaimer titles are bolded `DISCLAIMER` `CURVE DISCLAIMER` `Fees` `Money Back Guarantee` (see curvebots.fi)
- [ ] The contract addresses are shown on the bot pages (see curvebots.fi) - cc @joycehermosilla we need a UI for this I think

**Comment by taariq** [comment]
Delivered.

**Comment by verabehr** [comment]
@taariq this was not yet delived on palomabot.ai. Confirming that we also want it there?
