### ISSUE TITLE
UI for vote distribution bot on palomabot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#498]
### Background
https://www.notion.so/volumefi/EPIC-05-05-23-Vote-Distribution-Bot-on-StakeDAO-and-Convex-6e60b5b9668c4a38887737a544ea4668?pvs=4

Figma: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=8636%3A23048&mode=design&t=9efqFVSTe4WgDbDE-1

### Done when 

- [x] voting bot is added to the list of bots on palomabot
- [ ] user can select strategy when starting a bot
- [ ] contract is integrated
- [ ] user can start a bot
- [ ] user can see bots on my bot page
- [ ] Update Create a Bot view for APR Chase: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=8636-23048&mode=design&t=5wA6uchsRFl8PAt8-4
- [ ] Update Create a Bot view for Proportional Weighting: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=8654-39337&mode=design&t=5wA6uchsRFl8PAt8-4

**Comment by verabehr** [comment]
this is done

**Comment by joycehermosilla** [comment]
@wdev733 @verabehr Here is the updated version of Create a Bot.

**Comment by verabehr** [comment]
moving contract integration into separate ticket as contracts are not yet ready
