### ISSUE TITLE
Palomabot: UI tweaks Curve Stop loss and Curve Limit order bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#502]
Details here: 

https://www.notion.so/volumefi/EPIC-07-31-Stop-loss-and-Limit-order-bot-Price-ratio-d5fcfa6443214ad4a0c0a7c026be3077?pvs=4#5dafe79848d94c23ae8fb7df5a8430e4

**Comment by taariq** [comment]
@jamie088 we need this ticket completed today. Will that be possible?

**Comment by jamie088** [comment]
@taariq Yes, no problem.

**Comment by verabehr** [comment]
I'm marking this as blocked until we clear this up. If that is the case, then the market price label doesn't make any sense in my opinion. @fieldtheory123 help please? - this also affects https://github.com/VolumeFi/paloma/issues/495 that @wdev733 is working on.

**Comment by jamie088** [comment]
@verabehr Sorry, I don't know well what should I do with this ticket. There are many changed requirements so I am confused. Could you please more clearly this ticket?

**Comment by verabehr** [comment]
@jamie088 did you look at the notion doc in the ticket description?

**Comment by verabehr** [comment]
@jamie088 let us know when this is live on curvebot
