### ISSUE TITLE
EPIC: Palomabot Telegram Bot Commands Feature set

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#508]
Create EPIC with Feature set for Telegram Bot Commans for Palomabot. For example, some basic admin commands:

1. Link Wallet
2. Palomabot status
3. Start a Bot
4. Stop a Bot
5. List Bots

Anything else?

**Comment by fieldtheory123** [comment]
Done. https://www.notion.so/volumefi/EPIC-07-28-23-Palomabot-Telegram-Bot-Commands-Features-7609ce4331664b16828006272cb3c98d
