### ISSUE TITLE
Search token api for palomabot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#510]
### Background
https://www.notion.so/volumefi/EPIC-06-23-23-Palomabot-UI-improvements-8903b0a5977045e7908cbc21829fd2e3?pvs=4#186ad04c4b2a4bcca7e866da331b7c83

### Done when

- [x] all available coins on coingecko that are traded on Uniswap v2 Ethereum, Pancakeswap BNB, Apeswap BNB, or Curve, are retrieved from coingecko downloaded and stored in a volume DB
- [x] DB is refreshed every hour
- [x] all tokens are returned in an api for the FE to use (get all)
- [x] a specific is returned in the api when searched by token name, token ID, or token address
- [x] the parameters returned in the api are for tokens are https://www.notion.so/volumefi/EPIC-06-23-23-Palomabot-UI-improvements-8903b0a5977045e7908cbc21829fd2e3?pvs=4#7d02245a1ffc41dfbaff72c812e6085a

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/token_api

**Comment by rootedbox** [comment]
Completed but I still need to put on server.. setup dns / nginx

**Comment by rootedbox** [comment]
https://tokens.palomachain.com/ for status
https://tokens.palomachain.com/coins for all coins
https://tokens.palomachain.com/coint{coin_id or coin_hash}

server is down right now because coin data is begin filled in.. should be on later tonight.. 11/27
