### ISSUE TITLE
CHORE: document how to deploy a vyper contract for testing

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#513]
### Background:
With more chains coming online the rest of the engineering wants to know how to deploy Vyper contracts for integration testing. They currently do so by following the steps here https://www.notion.so/volumefi/Create-and-Execute-Cross-Chain-Job-50e42451cb324de19dd2357900043f15. 

### Done when

- [ ] Steps to deploy a vyper contract needed for the test steps above are documented in notion in the runbook section https://www.notion.so/volumefi/3210d731122748a89673af9e427d3d96?v=104c0fe64abf469bb2f74c437a0729cc&pvs=4

**Comment by taariq** [comment]
@wc117 and @ToasterTheBrave this is closed. Please re-open if still an issue.

**Comment by taariq** [comment]
Re-opening.
