### ISSUE TITLE
CHORE: Move Palomabot robots to its own linode instance.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#519]
CHORE: 
1. The lcd server will be deleted. 
2. Move robots api server to own instance and migrate DB to new server. 
3. No ssh password root logins
4. Add team keys to server.
5. Add server to better uptime

**NOTE**
**Please verify all active bots are migrated to this instance.**

**Comment by verabehr** [comment]
closing as won't fix. This server is currently not shared with the lcd

**Comment by taariq** [comment]
Closing as not needed.
