### ISSUE TITLE
Wallchain tx issues: claim tx fee too high; backrun profit not shown in rewards; low default gas limit 

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#52]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

1. couldn't run claim, as claim fees exceed GRAIN airdrop for claiming
<img width="264" alt="image" src="https://user-images.githubusercontent.com/18745242/223442319-d8139649-e70c-40cd-b8d6-8ef462e1c950.png">

2. for a tx that SHOULD contain backrun (confirmed using ApeSwap's frontend), the backrun profit is not shown in the reward amount

3. the backrun swap was partially reverted, due to low gas amount by default. We should raise default gas when there's backrun https://bscscan.com/tx/0xc03f4b1dc473c73adfe99811110dd187ead105199cd7d71c17e4c2d0a37ac11e

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

1. I was trying to claim GRAIN that I received from swapping but it failed as the claim fee was too high
2. I swapped BNB for BAT and saw that Wallchain's endpoint saying there's backrun profit. The profit was not shown in the GRAIN reward amount
3. I swapped BNB for BAT and the [first one](https://bscscan.com/tx/0xc03f4b1dc473c73adfe99811110dd187ead105199cd7d71c17e4c2d0a37ac11e) was partially reverted due to low gas by default. The [second time](https://bscscan.com/tx/0xbb4ca6d44d990a6a5800c9a372be58620ec7e9ca5fda202ca6b685d226771dd3) it worked once I raised gas to 1,000,000 

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

1. I should be able to claim with the GRAIN airdropped to me
2. PalomaSwap's FE should show GRAIN reward amount with backrun profit included
3. The FE should automatically raise gas limit when there's backrun

**Comment by verabehr** [comment]
We are currently always giving the 10% of the Swap amount in USD and are not taking the Wallchain tokenback amount into account. This is not yet part of the spec. 

The first part is already ticketed here and needs to be fixed https://github.com/VolumeFi/paloma/issues/10

**Comment by taariq** [comment]
@fieldtheory123 to clarify #2, you mean the backrun profit in GRAINs only. Correct?
