### ISSUE TITLE
Re-provision the lcd server on a new linode instance

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#520]
We need to 

- [x] 1. reprovision the lcd server on a new linode instance
- [x] 2. disable password login - only ssh login should be allowed
- [x] 3. when 1 and 2 are complete, delete old linode lcd instance
- [x] 4. alert linode team here https://cloud.linode.com/support/tickets/20831765 when OLD instance deleted.

**Comment by taariq** [comment]
Closing as complete.
