### ISSUE TITLE
Curve Limit order and Curve stop loss bot - use price ratio

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#522]
### Background: 
The current "limit ratio" and "stop Loss" is technically incorrect if the output token is not stable coin. We want to implement an interim solution to switch to using the coingecko price ratio instead of just the input token price. This would not be fully correct, but at least the limit order ratio would be correct

**Curve Limit order bot script AND Curve Stop loss bot script**

- [x] create tracking_price0, tracking_price1, deposit_price0, deposit_price1 in the db
- [x] copy tracking_price to tracking_price0 and deposit_price to deposit_price0
- [x] replace in all the tracking_price to tracking_price0 and deposit_price to deposit_price0 in all of the code
- [x] fetch the price data for token1 from coingecko  (like we do for token0 already)
- [x] store it in the db as `deposit_price1`
- [x] continue to update token1 as tracking_price1
- [x] get the coingecko price ratio of `(price token1)/(price token 0)`[ here https://github.com/VolumeFi/curve-limit-order-bot-script/blob/master/limit-orders.js#L408](https://github.com/VolumeFi/curve-limit-order-bot-script/blob/master/limit-orders.js#L420) AND  here https://github.com/VolumeFi/curve-stop-loss-bot-script/blob/master/limit-orders.js#L372
- [x] update this line https://github.com/VolumeFi/curve-limit-order-bot-script/blob/bf9e5af42386ec8f41bb80bb322f87001acad09a/limit-orders.js#L412 to compare the price ratio from the point above to the stored price ratio. I
    - [x] **Limit order**: if the price ratio is higher than the deposit_price1/deposit_price, withdraw with profit taking
    - [x] **Stop Loss**: if the price ratio is lower than the deposit_price1/deposit_price, withdraw with stop loss

**Comment by webelf101** [comment]
Currently, we store price data of token 0 in the DB. So we need to store the token 1 price, too. And we need to update the price check part so that we check changes in price ratio between now and deposit time instead of checking the token 0 price change.

**Comment by verabehr** [comment]
@webelf101 updated with required steps, will you double check if I'm missing anything here?

**Comment by taariq** [comment]
@fieldtheory123 this ticket will need your QA support please.

**Comment by fieldtheory123** [comment]
@rootedbox what's the status of this ticket?

**Comment by verabehr** [comment]
@rootedbox I updated the ticket, I thought we were using tracking price, but we only need deposit_price

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/curve-stop-loss-bot-script/pull/8
https://github.com/VolumeFi/curve-limit-order-bot-script/pull/14
@fieldtheory123 @verabehr

**Comment by verabehr** [comment]
both were approved, but we should time merging of these to not affect current bots

**Comment by rootedbox** [comment]
@verabehr or @taariq this needs to be merged https://github.com/VolumeFi/curve-limit-order-bot-script/pull/14 that being said I've updated the server with the code and both services have been restarted.
