### ISSUE TITLE
BUG: Mometum Bot is not processing at the Stop Loss Price

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#528]
Stop loss not working. See image below.

![Image](https://github.com/VolumeFi/paloma/assets/701864/f4c9fe5e-85b5-4d1b-8bb9-8435ec0b802d)

**Comment by verabehr** [comment]
This looks like the SAME bug that we had on the limit order bot https://github.com/VolumeFi/stop-loss-bot-script/blob/master/stop-loss.js#L363. The denominator should only be in the denominator

**Comment by verabehr** [comment]
It is correct here https://github.com/VolumeFi/momentum-order-bot-script/blob/fd14ac062d7551d02f4578ad0ad0a9ff51827051/momentum.js#L427

**Comment by webelf101** [comment]
They are the same calculation.
y = x * (1000 - a) / 1000
y = x - x * a / 1000
Both are the same result.

**Comment by verabehr** [comment]
we need to 
figure out what's happening on momentum bot
confirm if any of the other bots are affected

**Comment by verabehr** [comment]
I'm not sure this actually did anythign @rootedbox https://github.com/VolumeFi/paloma/issues/512

**Comment by verabehr** [comment]
On the momentum bot we are getting getMinAmount exception: Error: Returned error: execution reverted: Unauthorized from the contract also "failed to execute message; message index: 0: Unauthorized: execute wasm contract failed [!cosm!wasm/wa>
