### ISSUE TITLE
bug:  FCD is sending logs to newrelic

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#53]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

We're still seeing logs from the FCD in Newrelic. About 3.5k per 30 minutes

https://onenr.io/0Bj3NZdpxRX

Initially removed here https://github.com/VolumeFi/paloma/issues/18

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

No logs whatsoever from this machine

**Comment by rootedbox** [comment]
disabled logging on lcd

**Comment by verabehr** [comment]
closing, as we're moving to data dog
