### ISSUE TITLE
Feedback from Volume testing

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#531]
https://www.notion.so/volumefi/Curve-fi-bot-feedback-07-21-b90b665c93a441238402514b50022fc4?pvs=4

**Comment by fieldtheory123** [comment]
@joycehermosilla 

<img width="899" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/cca70455-fb94-4098-a49a-6b7668e47600">
Change "Profit Taking" to "Limit Price"

<img width="872" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/71628542-b892-436d-b01e-601ab76f79af">
Change "Stop Loss" to "Stop-loss Price"

**Comment by fieldtheory123** [comment]
<img width="886" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/191eba32-a685-49f4-ab55-e5a5b06233e0">
"limit" -> "limit price"

**Comment by verabehr** [comment]
Zhibai's points were moved into https://github.com/VolumeFi/paloma/issues/538
