### ISSUE TITLE
Question: Why is birdlady is still running on Cosmovisor?

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#532]
During the upgrade to 1.6.0 @byte-bandit noticed that birdlady is currently running on Cosmovisor? Is that expected and if so what is the reason?

**Comment by ToasterTheBrave** [comment]
I don't have an answer for this.  I noticed it week before last, but didn't pay much attention.  It's possible when we recreated birdlady to get past the appHash issue, it was left using cosmovisor.

We should get rid of cosmovisor completely.

**Comment by ToasterTheBrave** [comment]
Birdlady is no longer using cosmovisor

**Comment by verabehr** [comment]
Thanks @ToasterTheBrave
