### ISSUE TITLE
CHORE: add old contract back to the networks.json

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#534]
### Background
some old contracts were removed from the momentum bot networks.json. For most contracts deposits were already withdrawn through the UI, but for one, there is still one open deposit that we need to show on the UI again https://bscscan.com/address/0xb0317d3f9639e384e90bb996a8874342d2b4545e

We will not run any jobs on this contract, the only thing that will happen with this contract is 
1. show the deposit to the user in the `old bots` tab in the UI
2. allow the user to withdraw with the `cancel` function

### Done when

- [ ] The contract is added back to the correct network.json and shows in the API

**Comment by taariq** [comment]
Is this even needed?

**Comment by verabehr** [comment]
Closing since I have not heard otherwise and we have more important bird to feed
