### ISSUE TITLE
Curve Limit order and stop loss bot: `coin_info` for `0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE` is `null`

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#535]
This happens on Curve Limit order and Curve Stop Loss bot and doesn't happen for all tokens. It happens for 
ETH (0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE), but there may be others. 

```
{
	"deposit_id": "10",
	"token0": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
	"token1": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
	"amount0": "2000000",
	"depositor": "0x9FC09a1d181F45Aa424E1ca7267c15e87e691BDD",
	"deposit_price": "0.99961",
	"tracking_price": "0.999755",
	"profit_taking": "5",
	"stop_loss": "494",
	"expire": "1690386399",
	"network_name": "ETH",
	"dex_name": "curve",
	"bot": "curveStopLoss",
	"contract": "0xF8a8341c14C606f42Fc6945cF26417Ba947bc5aA",
	"old": "0",
	"coin_info": null
}
```

```
	"deposit_id": "1",
	"token0": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
	"token1": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
	"amount0": "100000000000000000",
	"depositor": "0xD0e08D653C3ead747865c3674FFa93ecDefDd045",
	"deposit_price": "1894.45",
	"tracking_price": "1859.13",
	"profit_taking": "9",
	"stop_loss": "0",
	"expire": "1689822042",
	"network_name": "ETH",
	"dex_name": "curve",
	"bot": "curveLimitOrder",
	"contract": "0x2090E42354ff8Ddc143EDE813D7e727BCAb6d398",
	"old": "true",
	"coin_info": null
```

```
	"deposit_id": "22",
	"token0": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
	"token1": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
	"amount0": "2000000",
	"depositor": "0x9FC09a1d181F45Aa424E1ca7267c15e87e691BDD",
	"deposit_price": "0.999761",
	"tracking_price": "0.999488",
	"profit_taking": "6",
	"stop_loss": "0",
	"expire": "1690385850",
	"network_name": "ETH",
	"dex_name": "curve",
	"bot": "curveLimitOrder",
	"contract": "0x0F1b995AAd8572c084A3B8174f25b17D97B7CB1C",
	"old": "0",
	"coin_info": null
```

Curve bots FE doesn't have icon when target token is ETH (0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE). 

<img width="905" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/6f5b96da-6af2-418b-a3f8-57fc244e9a53">

We need the middleware to return proper `coin_info` when the target token is `0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE`

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/bot-info-api/pull/5

**Comment by verabehr** [comment]
@rootedbox something was wrong in the logic, now all  20 deposits have the same image https://assets.coingecko.com/coins/images/279/small/ethereum.png?1595348880 in this API https://service.palomabot.ai/robots. But not all had ETH as deposit

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/bot-info-api/pull/6/files

**Comment by verabehr** [comment]
@fieldtheory123 this was fixed on the server and confirmed in the API. Will you please also confirm this in the UI? My bot already expired.. Thanks
