### ISSUE TITLE
bug: Frontend is not displaying error when tokenback registration fails

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#54]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

When there is an error on tokenback registration the API throws an error, but the error is not shown to the user on the Frontend, so the end user has no idea as happend to Taariq here https://discord.com/channels/987730379182051408/1031224593966448661/1082800454947328061

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

We should retry to register once and if that fails show an error to the user on the UI. 

"Tokenback reward registration failed. Please open a ticket on Discord. "

**Comment by taariq** [comment]
Closing
