### ISSUE TITLE
EPIC: leveraged ST-ETH and Convex staking bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#540]

**Comment by taariq** [comment]
Based on Gearbox ST-ETH strategy.

**Comment by fieldtheory123** [comment]
EPIC: https://www.notion.so/volumefi/EPIC-07-28-23-Curve-Convex-Staking-Bot-5483b9146bf7443eb95cce4cc144c38a

**Comment by fieldtheory123** [comment]
Done.
