### ISSUE TITLE
BUG: Curve Limit Order Bot fails at Cosmwasm for withdraw_type: 8

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#544]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Curve Limit Order Bot fails with the error in logs for The  withdraw_type: 8
{ deposit_id: 13, withdraw_type: 8, expected: '49750000000000000' }

```
data: {
Jul 26 02:31:16 snapshot start.sh[3207542]:       code: 2,
Jul 26 02:31:16 snapshot start.sh[3207542]:       message: "failed to execute message; message index: 0: AllPending: execute wasm contract failed [!cosm!wasm/wasmd@v0.40.0-rc.0/x/wasm/keeper/keeper.go:394] With gas wanted: '18446744073709551615' and gas used: '105611' ",
Jul 26 02:31:16 snapshot start.sh[3207542]:       details: []
Jul 26 02:31:16 snapshot start.sh[3207542]:     }
```
It appears that we may need to update the Cosmwasm contract for Curve withdraw types of 8?

**Comment by rootedbox** [comment]
looked at all cancels on contract https://etherscan.io/address/0x0F1b995AAd8572c084A3B8174f25b17D97B7CB1C none with type 8

const EXPIRE = 8;

**Comment by verabehr** [comment]
potentially the same as #542
