### ISSUE TITLE
Mixpanel: Add Fees Collected as Cumulative Line on Bots and convert Bots to Cumulative Lines

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#548]
1. Update all the Bot metrics to Cumulative Line vs. Cumulative metric
2. Add New chart for Cumulative Fees Collected as Line as well. Please note that fees are collected on DEPOSIT. 
    i. refund wallet ethereum: 0x7a16fF8270133F063aAb6C9977183D9e72835428 . 
    ii. refund wallet bnb: 0x6dc0a87638cd75cc700ccdb226c7ab6c054bc70b 
    iii. Since there are a lot of transactions on this wallet, it's probably best to query all contracts for transactions that go into the refund wallets e.g. here https://etherscan.io/address/0x0F1b995AAd8572c084A3B8174f25b17D97B7CB1C#internaltx or here https://bscscan.com/address/0x2bb70661949f32c2a9d1f7b7d9c094d9e1856ff4#internaltx
    iv. The list of all current contracts can be found here: https://www.notion.so/volumefi/Palomabot-repo-and-contract-address-inventory-73691914623c4e91a0972ef6f13aad98?pvs=4

**Comment by taariq** [comment]
Reminder @rootedbox we are not querying distinct depositors. We are querying for all bots running.

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/fees-collected-mix-panel will be installed tomorrow onto server

**Comment by rootedbox** [comment]
I'm not getting any connection between our contracts and these wallets.. even when I'm manually checking. I think I'm missing something.

**Comment by taariq** [comment]
https://etherscan.io/tx/0xd3db098b2ff55732db813e3b5378f84a3c5f6b341fb9d75f323c1b9e3d60e642/advanced#internal Check the internal call. You'll see the 0.015 ETH that was collected for gas on this tx.

**Comment by taariq** [comment]
Where are the cumulative lines?
WHere are fees collected?

**Comment by verabehr** [comment]
module.exports = {
    eth_contracts: [
        '0x4594E59AcE780D137c23Da87cFFdaf8acb72020A',
        '0x5A827A278751900bb35511d3cD370c41DE1A1bf5',
        '0x22A0adCe2f10b51CB5b0818f004d2596ceFeF6F1',
        '0x2090E42354ff8Ddc143EDE813D7e727BCAb6d398',
        '0x0F1b995AAd8572c084A3B8174f25b17D97B7CB1C',
        '0xF8a8341c14C606f42Fc6945cF26417Ba947bc5aA',
        '0xaA79eD113b5f14565fB5A200Cfa28E1FbDb94EF5',
        '0x2049e8Dcba698f2D6127E1f3e423D2278A1538d2',
    ],
    bnb_contracts: [
        '0x2bb70661949f32c2a9D1F7B7D9C094D9E1856ff4',
        '0x9d0C0029D143CD7D1Ca9E2Df13a4A3b7A46ECdBB',
        '0x8517C96Bc7eE6a94CFc9ab3c26Dd4f1afC0Af572',
        '0xdB14A009bD4bfEB19fd03Ba75BaE51FcA690913c',
        '0x6f92B6aA3258C9e6389Bf7CF4914dDc27B2eb206',
        '0x7d0FB75FCE1820Fd7D1ecC228512608Be80839C9',
        '0x017DE2968e78a6e4B637206f7c2437F122c4ec03',
        '0xD44f43957f52f1aDc848796b29edb328134A1782',
        '0x1253285073b6fb536e421F5DD27414019D79Fbf7',
    ]
};

**Comment by verabehr** [comment]
@rootedbox  Please add the following contracts:
ETH:
0xda721Ab46632864cDeDBDc0574417DE9fe8528fC
0x3B620038A3E78f133f84936c82f2779A1CAD3574
0x8C629A57eE1610581EB375529d07b097673d3470
0x18399AfcE07A30F2DF69946b6110C45A1B4E6111
0x6eA64066ef9Fa9Efaf2E98bE2db5Ef9f3F8355C5
0xd02d8b2c72cd13fb73cdfe28aa37aeba04ed19e6
0x4495467f9cd04faf5fa65ed34af335d4e2e7e129
0xF6f6895CfF43172818c43310a3C22d43c453344a
0xBcc9B67f8116c76d16F26f59f994aeF377866ADD
0xeF09aeF92C066917534Ba094cD0120A2561D7Bc9


BNB
0xEE6aB4E4917A31F9085f7E7E5912e43B5E22D172
0xb0869515a630c8c362Dc81ca3400D461Df6Eb0aD
0xb0317d3f9639e384e90bb996a8874342d2b4545e
0x6096F14ED42C4602264532Cdf79beA7DEa0A4a7E
0xF398C9e0fBaD8Bbad10cb2C9f8B7823259D43175



Please also add this wallet for tracking for eth in addition to the one you're already tracking: 0x6dc0a87638cd75cc700ccdb226c7ab6c054bc70b 

My notes are here for reference https://docs.google.com/spreadsheets/d/1FIh2lT80__wnvs03nemGQPtLi0wvmGwCbhqUlRfa-fI/edit#gid=208402853

**Comment by rootedbox** [comment]
BEGIN
https://etherscan.io/tx/0x8afeabb4363646cecb4ace1c6b13094bf508a708b3114ad5c4432cb5b3b8a1ba 0.01
https://etherscan.io/tx/0xc187fa17cdcf5eeec369cccfe3035bccf96d17a532716f5ad889fad7bc9fbffa 0.01
https://etherscan.io/tx/0xaf2c05bd6a3fdc12a5de07749333485162b6c068d2ed0e20146601d6a16d29fe 0.01
https://etherscan.io/tx/0x10fa7068d9bf18c33c46a54a1229c1a52da2d4671b86867427e03b6a0328d0d5 0.01
https://etherscan.io/tx/0x6db2533936bc5290120934cbad2b943d74a149ee03deeae51526a1ab58a3ab63 0.01
https://etherscan.io/tx/0x6a1d5985f7e4aca43f1d2e4744941b7ddc5619cfd009bda9606035bb3195632b 0.01
https://etherscan.io/tx/0x0ed6e1b31031802d737d598c80412454068e48e7e39cb69bf39ea5791b43cec5 0.01
https://etherscan.io/tx/0x922c2c9ad9bd9a0b72908912b42fd2f1a6fac9ff19c6b311c87086e6642f6200 0.01
https://etherscan.io/tx/0x343b8cf49793af8b3b9094b5059a11dcd7eaf544b8eca1ba2f0cb34bf26387bf 0.01
https://etherscan.io/tx/0x7a1e0fb802182a822c8cb0000acec70ba1de38f295e7fbffb1cc5be597a8d3a7 0.01
https://etherscan.io/tx/0x2021b83216daa2ffc17bb1d8428238ac70f4b6b5d3a4ef7971c16fc87c2f98c3 0.01
https://etherscan.io/tx/0xc6479ef3feacf2147df13b19f05afead55eea9462f899bcbc251b0f69905cc00 0.01
https://etherscan.io/tx/0xbe0827f217443b8a05069d942928dbf550d9da2bd0cd49be94dec01bf12af412 0.01
https://etherscan.io/tx/0xd00f044b4142ace86e2282c259c41e3a66271e6b084f166bc97a12a315e8112e 0.01
https://etherscan.io/tx/0xd9393f3f3eaaf05a5ee8dc7db6ca449a868e8728b68b745e3889f40a596ead58 0.01
https://etherscan.io/tx/0x97fcbee60ebddf15ddfa0789ca2d51c14c38156f137cda0ba2a93494324a5d1b 0.01
https://etherscan.io/tx/0xb261f1804ab8263fb456b3ea35ed23510b5b00fd56b417c9356ae17a4e302dc6 0.01
https://etherscan.io/tx/0xdd7fbd185e9335c0c7017362ba086e4c42a6c21738e3cd4140daf1d963b526d9 0.01
https://etherscan.io/tx/0x46fdb370b1e86acb96252aee54d1c4106f9dc041d077e8dedbdb6eec1622bb47 0.01
https://etherscan.io/tx/0x6a5a14609db432b439c2159ed2447992b3349bc3858d66a9ab4885171f4a4221 0.015
https://etherscan.io/tx/0xe437e3d87203d53d17c85f1a9b602379d91ba7b503c208b5ac96b986b2faca4e 0.015
https://etherscan.io/tx/0x72a8e36d28d4e233178ced8489a9e56d8f7442a82884f7581004c1c5fc253195 0.015
https://etherscan.io/tx/0xe26b5e8f3a47a3c07721bce0f154b0e717457ae9335bc06c5d2057cb7ee0e135 0.015
https://etherscan.io/tx/0x3caa75c310fa81016be13c9457b8ab64e83ac1a84296fd2d5fa65b4c3be85d17 0.015
https://etherscan.io/tx/0x654e81a6d406423b44d6fabf30759cd7fe5bbeb4bdc130397e462194d71daf94 0.015
https://etherscan.io/tx/0xfb8aea4d8860b42a469fc7fba775c970aecf89f1e37abd3aa7520d90e89b25b1 0.015
https://etherscan.io/tx/0x64f200e330e24c4cdade8b127574bfdca40625b814ae28dc03f2b309b32cb94c 0.015
https://etherscan.io/tx/0xe4dd9a7367014789f28dab23e3431921700f463be371e335424184590edac93a 0.015
https://etherscan.io/tx/0x3b30ebb5e5cbe350865b074aeffeba62de2727ed876555a56d05afdc15a8c54e 0.015
https://etherscan.io/tx/0xd2d5c846de6759bc0f6f33615a390514a63c4c17c2b9e72e0ae5ee25319deb98 0.015
https://etherscan.io/tx/0xd32f15da68d10f5bf96048a10f72c6eb03dc2c6be965e74a0263cdbb61bf1c53 0.015
https://etherscan.io/tx/0x89e2dcfdb04df9bb62945c0f4246b7b14333d9b1cfbe67d39bc037d81fa7e921 0.015
https://etherscan.io/tx/0xdb9a37cd8fc1186746aff70872c72297e9607e133a45ec873b0ba61be1f367f6 0.015
https://etherscan.io/tx/0x655a418fcadc139c835999f164bc97fff8bec17a6ade8d8cb6f7bd84818e53c5 0.015
https://etherscan.io/tx/0xc0610fb3f18c30f6f135f962ec69c88f67711f3579c13d2e159ce3e090dd6114 0.015
https://etherscan.io/tx/0xe1ae811fc94011c8dc1b5e69831bbaf6d2d4e09e93637aad4714a07369a5b7d5 0.015
https://etherscan.io/tx/0x24a1ada83a0b64cf52ad81261ffcef447ca489f15741780e9011969d834d26e8 0.015
https://etherscan.io/tx/0x013c1565c5bb1caff85ac0c98a974e22fb1431c343e8aef44c01f5cd4cbfef46 0.015
https://etherscan.io/tx/0xd3db098b2ff55732db813e3b5378f84a3c5f6b341fb9d75f323c1b9e3d60e642 0.015
https://etherscan.io/tx/0x5ace9207688638f543a170aeb05063583d8e8909664d4eac26a9e2c9cedb6183 0.015
https://etherscan.io/tx/0x4705b08afc4eabbf8f37d3e03c8d4bc0f1367b29688d9f7e20ae71c3d0a1b382 0.015
https://etherscan.io/tx/0xe5570bca2c9ecb5a22be461a5166cc4ca7b6658d010d7a117da9534e09b1d150 0.015
https://etherscan.io/tx/0xa67e416eee2eada5c09c0a9717604363f0cf65271b79b100716304a818ee5143 0.00005
https://etherscan.io/tx/0xf5848f02efa5a023b1e4e454b5ee5579bf6d11501b0e425103dca13d55f824aa 0.015
https://etherscan.io/tx/0x44ac67128defb1847e94915d4c005f50fc642d9eeec25285b10899d32e99e868 0.015
https://etherscan.io/tx/0x797097fad0dd81527650745dfef15bec4eb46f378db3c4dc4df3d46fa17e8244 0.0005
https://etherscan.io/tx/0x8e94a61f64bcbab11813ecca442d3675650552b728571503b52246183271ee20 0.015
https://etherscan.io/tx/0x00322187c9ac9cb6d9423adf6e3633fda60bd545532853d5cfb30eb78f1aa60c 0.045
https://etherscan.io/tx/0x27624c8374cc8368ca5b00219969f176fc03451f3a2b265947ca14c522180e72 0.03
https://etherscan.io/tx/0xbf778872928ff648b65ac956b7bade20df67a1b090df7fd3621c9ad17bfd72b3 0.015
https://etherscan.io/tx/0x6b27c11d1b747bd03241f3603a701fce7ba8df0ba093d48406337f36ab02a8c7 0.015
https://etherscan.io/tx/0x706698eff1877c579292a4988c6f233487654f6eb54d8d643846132b2ac42736 0.0005
https://etherscan.io/tx/0x9d043b56e17f7bb0197506258fc96f9b76c2e6f16ebdb04245dc5f8456d9bf4f 0.0005
https://etherscan.io/tx/0x256f89e14be701f672138f2fc144f340051227b83e40f64f4f9c319aece515bb 0.00005
https://etherscan.io/tx/0x47da2fb8bd26b722c4069ec941e8e70e53f96ea168a360a1fc6c30244cdcf316 0.0005
https://etherscan.io/tx/0x1cb34d987a32c2045d526254f27781fae9a745c384a652b511c20aa601122c3f 0.000075
https://etherscan.io/tx/0x245a4987d96a75da534a9877e047c1f35af804fde37646d0b8d7715bcb70332b 0.00005
https://etherscan.io/tx/0x5c1917f07bbf9a903c26411c2ff6d094f7ead58add6e62f2406434450aad657c 0.00005
https://etherscan.io/tx/0x436dafdd76ae609e7fc0b628adef62deebd2bd75217352bb125ed65687a22469 0.0001
https://etherscan.io/tx/0x436dafdd76ae609e7fc0b628adef62deebd2bd75217352bb125ed65687a22469 0.000005
https://etherscan.io/tx/0x436dafdd76ae609e7fc0b628adef62deebd2bd75217352bb125ed65687a22469 5e-7
https://etherscan.io/tx/0x436dafdd76ae609e7fc0b628adef62deebd2bd75217352bb125ed65687a22469 0.000005
https://etherscan.io/tx/0x436dafdd76ae609e7fc0b628adef62deebd2bd75217352bb125ed65687a22469 0.00025
https://etherscan.io/tx/0xb4ece687f27e180f5990abdf0cb6830a2872209a1d7427e1a6f3cf3d98e8b084 0.00005
https://etherscan.io/tx/0xb905893aaedcb24b9d77debfd36a235fa9431bb176adff0b3c60a186ba996979 0.00005
https://etherscan.io/tx/0x6179d69f41788b7b5348814972f5ee33977ca8e883c0dae58e15ffe5b5918588 0.015
https://etherscan.io/tx/0x41af91e0d7ab4f63f7f7016629e358a067abb1ec99ce4faebca52284ed82744b 0.015
https://etherscan.io/tx/0x6f4fd00c6d4db39f27e6b5bc2af7ed137038b7847a052d9efda6589b7835f456 0.015
https://etherscan.io/tx/0xe3a8ddbee34b46b764ee126f02ebebfceb4bfbd113441f11e2e9301d8ac65f13 0.015
https://etherscan.io/tx/0x7cae8963e5df909123246a3bfd5bf6656c3861907f64e3cfc970243fbb0a6470 0.015
https://etherscan.io/tx/0x36a3d230cb5eaa5b99cd9c3cd79b160be62aa934fbb1ffceb915203f8677fff5 0.015
https://etherscan.io/tx/0xec4e25a55ea2230dceffe472120b20ce9d6bc4f01c830ee138765aff3001e4cc 0.015
https://etherscan.io/tx/0x47e610fc6a2d034a17f5e432aa7f92a2755786ddb266ed95f453f0bbfbd5eb0d 0.015
https://etherscan.io/tx/0x5ae3d5bb951574739620a1a640250f345f171afb00b8077af7a0aa1c4df02c01 0.015
https://etherscan.io/tx/0x39e951cbd9fbe17a7dd27a274fa5b4e39ba1a7fa07170a865ba912dc8dca7abb 0.015
https://etherscan.io/tx/0x069e4dcea37d336b23e0c68055e9b833c7827dd1c2d13a6c3d80f64c7b317870 0.015
https://etherscan.io/tx/0x20369af51df65fcc67dd171d23d655c0db96ec23a1b262b402b7b9a0977edc5b 0.015
https://etherscan.io/tx/0x1da6dcbd11b34ae0ae742040c342c77ee25a90215794ef9f40dfea31dcd45523 0.015
https://etherscan.io/tx/0xf17bcb806900fb29b7c90de7a53f1e63b91a40504368b0e774b2f0181dd66746 0.015
https://etherscan.io/tx/0xea70fe8483ff9d750a6c0eb904c236e7118a2aa7b92a0fb317bad9f4f395e87c 0.015
https://etherscan.io/tx/0xf842dacdf3f20f1932d7770f41c284719695370c99cfa07ade6b3f0e365f3699 0.015
https://etherscan.io/tx/0x15b6c84fd929cb80250c633cc911f43fc0f25e193619d64b84c65240646010b0 0.015
https://etherscan.io/tx/0xcb43ea51e8e523caf4da426b1e3bafc4750f6c3ae22001824b491ec4fdfa9d0a 0.015
https://etherscan.io/tx/0x032e2f932bf0f2f6936cb0c102fd2f020e2aff7cd4e42519c284e650f81407d3 0.015
https://etherscan.io/tx/0x7e9c3e73fff4cac9a8e4e426e7945b299155d6bf91e70dc7f555502488674d86 0.015
https://etherscan.io/tx/0x5fd9a675b8fbf151db10c26a58630bd2d72c432668a59cd4ba9c9ef9325041db 0.015
https://etherscan.io/tx/0x4bce54abefdad327e2882364b76110c1c2120193bbf91d7ed0cbbef41d07a33f 0.015
https://etherscan.io/tx/0xb669999a322d2e7b36f0abac0e2834986e0bf4697a64b4ffa23bd31171c6647b 0.015
https://etherscan.io/tx/0xfd89203236d40810b565fc562892f975c982bbbd1f7322c8f1226c69fe1a92c9 0.015
https://etherscan.io/tx/0x42d3c7ffdae0b276943371f7ecfe74b3eac6cbbe07a25bdc469b05b9ca1c5019 0.015
https://etherscan.io/tx/0x682e4baf6eb2cd5c6d01f101fc63743ee727710c1fcf24bb9af554e5a61f9133 0.0005
https://etherscan.io/tx/0xc081b92226800988626e0d9aa4cc6ccaa15d0d35ba896ea5d6bf8b18cfa06df5 0.0001
https://etherscan.io/tx/0x1f37e3952510988e3c75b0fc3ce6971a6a53a75b3f7cf6c1f35436f9fdb00bac 0.000025
https://etherscan.io/tx/0x5e5078ec7f7be96f4af7685aca8aaf5153ae1b4b25405f72d8843f87255f7e5d 0.00005
https://etherscan.io/tx/0x39da6c22f90235b416e15cfc8f92ba1d0f49b44c013258f0c2b9c376afe7adec 0.00005
https://etherscan.io/tx/0x1be20802ce705ce315b6267ada2ca6eb023a7a01a78c4d4a38f3d299becc1d2a 0.015
https://etherscan.io/tx/0x6473727911c03833ea2ede65f525f89e34c9d4a89474ab4f7e992fc9eaf2c2ae 0.015
https://etherscan.io/tx/0xffb0e37dece795674ad5dbdff79c12a1da8cf8b36e70ca958eee84e5376c636c 0.015
https://etherscan.io/tx/0xa20fb99a6a33a5bbd17e9bb663dd768d979d83e61191e5256d1edb373fbb7e75 0.015
https://etherscan.io/tx/0x41ef9e3be7cbff61983ca58eb17985f281cd38b239bb5cf577a2cf4a7014a775 0.015
https://etherscan.io/tx/0x93db5ffbc020fdb66e2fe340bd6a3beb385215229c9a75776f1f6e7b6316d7c0 0.015
https://etherscan.io/tx/0x6f32c6301bc8c16c2a039e6307413d5bb2ea740e2dcc2be76908c24192638ed6 0.015
https://etherscan.io/tx/0xb4568668123356c386e5dbe217b60416311013a4acb43138d594d1307dce18e4 0.015
https://etherscan.io/tx/0x9370beb492bdfaf27c5e2a8e76c9995b6439d2e252a98cb81be64f1c7ef41686 0.015
https://etherscan.io/tx/0x64d842cda236113325b3efa315fe1fb8328c3221d046a1c3311d3915acb6c402 0.015
https://etherscan.io/tx/0x46d799b251e603972a2c50554f426cea9ddf0a9ba466817a310f30be26e2be99 0.015
https://etherscan.io/tx/0x1ca8b9b3325914c2083f764e5433a4d650984865de28b74ec1a299f1ea370e4b 0.015
https://etherscan.io/tx/0xb9e03ceaa546272b97b8d9183965bb280136d5eb7ffd20d1cecc501f0d487365 0.015
https://etherscan.io/tx/0x544d3c462390df7e7d3c673ba5eca3ec9d070613f375e0a83d72b67b72c02bbb 0.015
https://etherscan.io/tx/0x3fbb44b5422fbf7d7ccee25fba33a908109f46143e2d54611af876beb25210b4 0.015
https://etherscan.io/tx/0x111462b4cb271adfc47862a824a96b5deaff050a74a078b24d99c95964d56cbd 0.05
https://etherscan.io/tx/0x9499f2db7ab39c5828afceef2c4abebf3688bee03532bf1532b5cdfcd07d7643 0.01
https://etherscan.io/tx/0x4c374cf946028558dee7ccdb3a6febf75700981d70b53967779681c85973beaa 0.01
https://etherscan.io/tx/0x8112ea7eaca9f7f43c4fae2cd15696e0653f9b31eb25af708f84852382147f58 0.01
https://etherscan.io/tx/0xadb3c8c6fb6ace7173ea94d2d38cf205473090dfc1870e0f97310ce3cd0713f1 0.01
https://etherscan.io/tx/0x79932b26a2cc639dc58f24ad2a4ed9ea1d609bf71f14986e83c2e803b2be15e3 0.015
https://etherscan.io/tx/0x6d065d9425f202a120fb64f74f198b93ad7337f6b9e1b628c81e61476cf24aec 0.000223502538039566
https://etherscan.io/tx/0x7b38606a7cff3397e15a7ff6993a9f0212da94e6afaa36c84bac6632ca04fee4 0.015
https://etherscan.io/tx/0x0fe6942b8844aafd3f3db196fb044cdb21097195e273c60a3f8c982a7c449cee 0.015
https://etherscan.io/tx/0xcaaae7d57ab10a6006eb7bd46084dba40ae8f5870b25b882e51189878af545e4 0.015
https://etherscan.io/tx/0xff5546b9aa9297c58163b5cd838efccbc07126bf42a15f60576b4d0e78b2c270 0.000266737406646843
https://etherscan.io/tx/0x6adeefc0cedee8e845c7e3af0d60dcd640c6cf55ada837da840bb19002e91a84 0.000442515670765105
https://etherscan.io/tx/0x6adeefc0cedee8e845c7e3af0d60dcd640c6cf55ada837da840bb19002e91a84 0.000382784312933814
https://etherscan.io/tx/0xf399ecd155c67983d815450627a3ed44bdb91ca40a1a9a2787287b83921952a2 0.015
https://etherscan.io/tx/0x98890d8a24b2c0b1e157e744651fae98278c1cad97868d1d9f9ce04621cd813c 0.015
https://etherscan.io/tx/0xaa841c7935d2b4e15e00a7f6e7825d1dfe8ac1622ec73a0165fa2935a7941254 0.015
https://etherscan.io/tx/0xccaeb8cd054b1988e71964feb87d4ad088f2c2bb2ab907e6816d5afb804201a5 0.01
https://etherscan.io/tx/0x4667a3592ecaa19ad7ea545ed7bec07f704bc7d67ad60101186d6c17adcc2294 0.000171184224437116
https://etherscan.io/tx/0xaabd09eb8cb523761c749a6340238884803c39b643369f73923c5b3e297117f9 0.000171184224437116
https://etherscan.io/tx/0x5a96b9f674dbfc570e37676d17e7760bc83f298ccbf605a1df64c275d5204f95 0.000171226166527008
https://etherscan.io/tx/0xbb15664657a94f21c89b6d1c7012a5bb3612f4bcd1f3b026c0a622a0aa746b63 0.000171116280870249
https://etherscan.io/tx/0xdbe364a6e0da830f894d976e886fd236e8d48992ab1e0d269f223e62378744ef 0.000171116280870249
https://etherscan.io/tx/0xd755fd002b728fb0b8c0689e383a798842d337475d3a7edbfbafb318f7784b6b 0.000083005035894456
https://etherscan.io/tx/0x3aee9cb86c3efed5029d7951c6b9ffeb1d8e5f0ea5d9a62da814a52bb1b14a2e 0.000083004866885387
https://etherscan.io/tx/0x608af26b7386085ec59149c37a457634638b1b263a73f42cb93d80ca51424ef6 0.000083003709002645
https://etherscan.io/tx/0x95e20c313ceffef2e995f3a5d977483aa213a498dea415354717fd56079c7883 0.00002494112782841
https://etherscan.io/tx/0x8d0ac4258bec81746a5d7036dc12120ee7fa09a2cad10d758634567f9f0c362d 0.000024941125623223
https://etherscan.io/tx/0xd6ce0e972be6bcf91adce12fa69e517689fe31e0ce966cb12e3b72ed8e17d092 0.000024909694501308
https://etherscan.io/tx/0x16c150c9cf5a77a1929569121f02c416c90166b8c8458c4083270ad175286e1a 0.000025170617858425
https://etherscan.io/tx/0x8023523abb3f26385a0b79360eebb6400f8db1d0adf20a56b4f8ed6bb2133bf4 0.000033259434281412
https://etherscan.io/tx/0x327e9369304025970c14cafa19464a59872ca89121be9ed9b933659350e81645 0.000033259380016644
https://etherscan.io/tx/0x4588212c3a9157be8326d1203dd8a550113a6301b0f0ca04235ac5791bc8ceb8 0.000033259323007224
https://etherscan.io/tx/0x9dcffe8d138c4cd43c1f98d7b38399763cfd06ddbabcf4435b130a0a53bd8b55 0.045
https://etherscan.io/tx/0x00c4b661abfdf840378fbd035247881e22e11989b1d472755bed5cd3467efb2c 0.045
https://etherscan.io/tx/0xa3ecdbe6c83e0ee95cb8164fd9d066c08d07fa5be269324fd2959d275739a843 0.045
https://etherscan.io/tx/0xb14e3e8dfc4b9c636636d1747a1687eb18e4e512e7f99966566d9d3fe3af1532 0.03
https://etherscan.io/tx/0x843a58f0d1c5c9fcb1a8d9e50e7abe57939002be3150d265363ed294265cdb52 0.03
https://etherscan.io/tx/0xb58a0b6547c4df9159d9f2c51da4802627e3df274c33dc1ecc908385d239cc22 0.03
https://etherscan.io/tx/0x2550b6a8cad1c5fbd587420941bb32b0d45dd97d5ef21289e8405150d946446e 0.03
https://etherscan.io/tx/0x421b9e12955efd145db9d57c5dbbe2b3e240b339f1d912413a4abf21368fb236 0.045
https://etherscan.io/tx/0xb8ade6f59d4ab2633d1b2da2997955ee0981cd2c8e3a387e277b7b893be2435b 0.015
https://etherscan.io/tx/0xc326696213579e2c33f2a16f688d14aab9a0a152e21d55c0d66661b772e642f1 0.015
https://etherscan.io/tx/0x85ef386b5659bbcdec13d5f3f923952ace44360569cb2a9ad9661be349e6b6e9 0.015
https://etherscan.io/tx/0x47b60e00ab303ff1c745fc638e11b6f67ca5564bbd2dc60f981866679a0983ea 0.015
https://etherscan.io/tx/0x7e401133f9370245d3ba23ef890c2d6cc2ed29d4212140eb09b6239302159883 0.015
https://etherscan.io/tx/0xf5b24a0559db3cc104825bb160bc8efa20a50b6b342f154bd9482a9e31e00324 0.05
https://etherscan.io/tx/0x7fab7b8a3d7c4b565dffe3768f88a62cac09bb5c63501fc0762d472ab922827c 0.05
https://etherscan.io/tx/0x5af3f64dc12e5ef03da33300b264ae6cccaf33f68c23d82cc5f4424168c3ba83 0.05
https://etherscan.io/tx/0xbe09b6115d782574ef62cf4c256b82cff3ee8a8a9ec40d7d345232d96882fe9e 0.05
https://etherscan.io/tx/0x4627ef292fae6dda478dad7eb5867fe778ee62e4b174ff6563b3dda51899d312 0.045
https://etherscan.io/tx/0xdb6648817b4168befec9c6d6d4d8cb273f389822dd2949c1e29f226dd4867ac7 0.015
https://etherscan.io/tx/0x6379ca686411218e22035ff39663d3827f3c6e365b1d6a5ab63adf4600b1d2b4 0.06
https://etherscan.io/tx/0x8664a9f75550378c3ab1d9516fb9a577624248031f6c466a423ad68919daf979 0.06
https://etherscan.io/tx/0x0ff4afd40eff272ee37ae505b513acc232cbf7422a79cc9019907857d7b81df0 0.06
https://etherscan.io/tx/0x58b736402fec1fa053db450c72910af225a348a51aed24c58331fb2b8b2d2899 0.015
https://etherscan.io/tx/0xe118130541346a799e88ece9506214e2432912a43a8b7a0194a9450267533a50 0.015
https://etherscan.io/tx/0x2144df51cab3cbcca4fc6139a0d2562fd5d93f24c6eaab35d4938dc888827251 0.015
https://etherscan.io/tx/0xae752b272384b5b6e58e0e835fe58589e6778d45d86f039e2fa41de2cc6e924d 0.015
https://etherscan.io/tx/0xaa8d8a51605814d4249f183bd30a49aadc1b100af4feba305ea713bc8caa4b63 0.015
https://etherscan.io/tx/0x37d76fd73efea1b715fa83bff2d97c32e8ceb3fc87347f3e129715531fe08b9f 0.015
https://etherscan.io/tx/0x579b76dda71c331c434811fe25ef7200f8a82eb0023e42fc3d25b64c42e7d141 0.015
https://etherscan.io/tx/0x7e6af19d0b544a948b8e97e6b4c26615bc68c83ce6f5059d2a29c16e1e17c2bc 0.05
https://etherscan.io/tx/0x7434b6c7bc1cf25f10fe557471dc07c593b57a5d038d5fc5b877edb931f33272 0.05
https://etherscan.io/tx/0x491bd40065964b1c50a4635e7bdbf9151a25e5d9fa848974dc9bbc56d6c8fe8c 0.05
https://etherscan.io/tx/0x127bcfd01fc7ca42679a9127895a84587813f94ea7e4780d1388e5ff67d7d296 0.05
https://etherscan.io/tx/0x5803b61132290c9ede2ae7cd04dc4aa4ea1a94578dc390b4fd31793caa706971 0.05
https://etherscan.io/tx/0x701278a42653f92c2e60d13081e8b815b25c0d02501be03f0ae6ca4067c5a406 0.05
https://etherscan.io/tx/0xc882d31e1aee1846d8908d04cd4efb915e4b8de054b1fe76edb3b785b577251a 0.05
https://etherscan.io/tx/0xbca4f0f030351cb56c5e2e6e753734bf108248b55fac5079451278c69d568a9d 0.05
https://etherscan.io/tx/0x14cdb0508f897701ca9638943fab48979bb1ee36b327f7bc286ab117b8be5a71 0.06
https://etherscan.io/tx/0x060d5af22cdb9464046a57dead3bd8ab6135986477678da059e9b7cbf2ef60b9 0.06
https://etherscan.io/tx/0x5adc75f4a1cee962c44257af536f6a59cf25f231c5254a09d7feae266e807599 0.000058062457338995
https://etherscan.io/tx/0x423dbddfca2fbf80303e64c870986778fcd930e2a1120b319538f0649cc72f35 0.0015
https://etherscan.io/tx/0xf492f144d54d40e3449dc8fa79d90612ce2694c37800ec92a4a12b1c247bceb7 0.06
https://etherscan.io/tx/0x9633d0b863d1dfba681bd9d90998f0d7963e5002148c777d8930cd8b485470e9 0.06
https://etherscan.io/tx/0x892893398b93adf27b6ef7a85a040f30d4c697487133bc16a477f2de7f0252fb 0.06
https://etherscan.io/tx/0x8be454a48a140efe7c3b910a74b2fd0a7ba55c6f8175334d8a226397b1cd8b01 0.06
https://etherscan.io/tx/0x8f4dce24ad0f9b5cb4e33ae35b80b5943cc6dc4b07ec95abc6581bc20f9605d4 0.05
https://etherscan.io/tx/0x8cf1208cddb2af8a1c60d152ea5882523c4f62f1c09e5e82d55abd7e52c5d1ea 0.05
END


@verabehr all the transactions it found and the value for that transaction
