### ISSUE TITLE
Add Volume & Number of users to "Choose a Bot view"

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#550]
As a user who is on the Curvebot.fi page and the palomabot.ai page, I want to see the following vanity metrics for each bot label:
1. Number of users
2. Bot Volume (number of deposits + withdrawals)
3. Highest Bot Return (%) (highest return from the momentum token)

So that I know the bots are busy and have users and volume and are not dead.

**Comment by verabehr** [comment]
@taariq do we want the number of unique wallets for "users"
