### ISSUE TITLE
Telegram alert when bot update and add alerts

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#555]
### Background
https://www.notion.so/volumefi/EPIC-07-28-23-Telegram-alert-additions-ab6f799b1fc840a39b23d2409d455b51?pvs=4

We want to give more details in the bot messages to include the 

- `bot type` (e.g. `Momentum` or `Gecko` or `Curve Limit Order` or...
- `token name` (from coin info)
- `remaining_counts` for DCA bot

### Done when
**Expiration**
- [x] alert is sent when a bot is withdrawn with withdraw type “Expire” (Curve limit, Curve stop loss, limit order, stop loss): “Your `bot type` Palomabot for `token name` expired. Your deposit was sent back to your wallet. Check your bots on https://palomabot.ai/ and open new positions.”

**DCA (Curve and Uni variants) Bot not the last swap**

- [x] alert with the following message when a swap happened, but the bot is still active (swaps are remaining): “Palomabot swapped `token name` for you. Your `bot type` bot is still active with `remaining_counts` swaps remaining. You will get an alert on the next swap. Check your bots on [https://palomabot.ai/”](https://palomabot.ai/)

**Last swap on DCA, Limit order, Stop Loss, Momentum, Gecko (Curve and Uni variants)**
- [x] alert with the following message when a swap happened and the bot is closed out: “Congratulations! Palomabot closed your `bot type` for your `token name` position! Check your bots on https://palomabot.ai/ and open new positions.”

**Comment by verabehr** [comment]
@jamie088 confirming that this ticket is not done yet?

**Comment by jamie088** [comment]
@verabehr  Yes, not yet. Right now I am focusing on the Momentum bot daily telegram alert ticket. I guess I can finish these 2 tickets by today.

**Comment by verabehr** [comment]
Perfect, thanks. Just wanted to confirm @jamie088.

**Comment by jamie088** [comment]
@verabehr in DCA, alert with the following message when a swap happened, but the bot is still active (swaps are remaining): “Palomabot swapped `token name` for you. Your `bot type` bot is still active with `remaining_counts `swaps remaining. You will get an alert on the next swap. Check your bots on [https://palomabot.ai/”](https://palomabot.ai/)"

In here, What is the `bot type`?
I think this case is only for the DCA bot, so we don't need to bot type. or you mean "Your DCA bot is still active with `remaining_counts `swaps remaining."?

**Comment by verabehr** [comment]
@jamie088 bot type is Momentum, DCA, Curve Limit Order... We also want it for the expiration (and also for the final message, I'l update). The variables are explained at the top, they should all be in the API and DB already

**Comment by verabehr** [comment]
@jamie088 I think we're just missing the Gecko bot now

**Comment by verabehr** [comment]
@jamie088 is this done? Including for Geckobot?

**Comment by jamie088** [comment]
@verabehr Yes. Done.
