### ISSUE TITLE
Modify Telegram alerts for DCA bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#556]
### Background
https://www.notion.so/volumefi/EPIC-07-28-23-Telegram-alert-additions-ab6f799b1fc840a39b23d2409d455b51?pvs=4

### Done when

- [ ] receives an alert with the following message when a swap happened, but the bot is still active (swaps are remaining): “Palomabot made a swap for you. Your bot is still active an you will get an alert on the next swap. Check your bots on [https://palomabot.ai/”](https://palomabot.ai/)
- [ ] receives the existing alert with the following message when a swap happened and the bot is closed out: “Congratulations! Palomabot closed your position! Check your bots on https://palomabot.ai/ and open new positions.”

**Comment by verabehr** [comment]
@jamie088 is this ticket done including the different message?

**Comment by jamie088** [comment]
@verabehr No, I just saw the first subtask. If it's not a priority over other tickets, I'll work on it tomorrow.

**Comment by verabehr** [comment]
It's not a priority. I just wasn't sure. Thanks for confirming

**Comment by verabehr** [comment]
closing this, moved into #555
