### ISSUE TITLE
Add endpoint for querying bot performance

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#562]
### Background
https://github.com/VolumeFi/paloma/issues/550

### Done when
we have a new API endpoint that has the following information: 

- [x] total number of depositors across all bots as "users" 
- [x] total number of deposits + withdrawals across all bots as "volume"

**Comment by rootedbox** [comment]
@verabehr https://github.com/VolumeFi/bot-info-api/pull/7

**Comment by verabehr** [comment]
follow up requests:

- [ ] rename `volume` to `bots`
- [ ] add one more endpoint called `volume` - this should have the sum of deposits and withdrawals in USD

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/bot-info-api/pull/8
