### ISSUE TITLE
Integrate contracts for vote distribution bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#572]

**Comment by wdev733** [comment]
Vote Distribution Bot contracts:
APR Chaser factory contract.
https://etherscan.io/address/0x7c0e10b07c685d2362d384f377322226521719b4

Proportional Weighting factory contract.
https://etherscan.io/address/0xc83e716aa7e9ae17d78bab37aab702777abaf75d

**Comment by taariq** [comment]
What's the status on this? @wdev733

**Comment by taariq** [comment]
@wdev733 closing as completed. We wait on StakeDAO
