### ISSUE TITLE
New API: Get the token info of the specified token.

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#574]
https://www.notion.so/volumefi/EPIC-07-28-23-Telegram-alert-additions-ab6f799b1fc840a39b23d2409d455b51?pvs=4#222c2bb418c343c080c5d76754f7dd67
Currently, we don't have an API for getting the token info of the specified token.
So I need a new API that gets the token info of specified token using these params: dex name, token name(or symbol - you can choose).
(Same result as one token in this API: **https://momentumbots.palomachain.com/?dex=uniswap_v2&lag_return=6&daily_volume=0&vol_30=1&market_cap=1**)

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/momentum_trades_api/pull/3

**Comment by rootedbox** [comment]
https://momentumbots.palomachain.com/?dex=uniswap_v2&lag_return=6&daily_volume=0&vol_30=1&market_cap=1&token=cellframe

@jamie088
