### ISSUE TITLE
BUG: Bot not found on Back-end or Front-end

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#579]
From @ToasterTheBrave:

I tested a couple weeks ago when the call first came out to test.  Looking again now, I don't see the bot I created on that day.

What happened to the 0.035 ETH that was transferred to the bot contract when I created a bot 10 days ago? ( https://etherscan.io/tx/0x47e610fc6a2d034a17f5e432aa7f92a2755786ddb266ed95f453f0bbfbd5eb0d )?  Is it just that I can't see it because of a bug in the UI?

**Comment by ToasterTheBrave** [comment]
It was mentioned that maybe the bot was withdrawn, because we only show active bots.  I did not execute a withdraw, nor does it show in the eth address I'm using for testing: https://etherscan.io/address/0x9647c2f39fd6ade44d43d96346d3987f019c102e

**Comment by verabehr** [comment]
This is the deposit transaction:
https://etherscan.io/tx/0x47e610fc6a2d034a17f5e432aa7f92a2755786ddb266ed95f453f0bbfbd5eb0d

This is the withdraw transaction - looks like it expired: https://etherscan.io/tx/0x436dafdd76ae609e7fc0b628adef62deebd2bd75217352bb125ed65687a22469

@webelf101 will you please double check that this looks right?

**Comment by ToasterTheBrave** [comment]
Maybe I'm not understanding then... It was withdrawn and I can't see it, and I don't have the ETH back to the address I sent it from.  To me, it seems the ETH has evaporated.

If everything's working as expected, this isn't good UX for the bot.  It's never good to not know where your money went.

**Comment by taariq** [comment]
@ToasterTheBrave you actually received funds here: https://etherscan.io/address/0x9647c2f39fd6ade44d43d96346d3987f019c102e#internaltx

You received **0.0199 ETH** or **$36.92**  

You paid about **0.015** in fees vi a Transfer on deposit:
0.015 ETH From
[0x0F1b99...97B7CB1C](https://etherscan.io/address/0x0f1b995aad8572c084a3b8174f25b17d97b7cb1c)
To
[0x6dc0A8...054bc70b](https://etherscan.io/address/0x6dc0a87638cd75cc700ccdb226c7ab6c054bc70b)

Your limit order expired. Yeah, we need better UX to show your PAST/OLD bots. That's still to be done in EPIC: ...wait... @fieldtheory123 where's our EPIC for historical bot performance?

**Comment by ToasterTheBrave** [comment]
Ahh... Internal transaction.  I was just looking at regular transactions.  Thanks for pointing it out.
