### ISSUE TITLE
Set up new Geckobot as a service

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#585]
We're setting up a new bot. It will be a clone of momentum-bot  - https://github.com/VolumeFi/paloma/issues/584

### Done when
Geckobot is running as a service on the server and is included in the API

**Comment by rootedbox** [comment]
https://gecko.momentumbots.palomachain.com/?dex=uniswap_v2&lag_return=6&daily_volume=0&vol_30=1&market_cap=1
