### ISSUE TITLE
Gecko momentum api

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#588]
- [x] update code on the `lorentz` server to include this PR https://github.com/VolumeFi/trading-bots/pull/40/files
- [x] fork the repo, so that the service can be separate and the DB doesn't write to the same place
- [x] call `get_top_gainers` function (same way that `get_high_returns` is called) - this should be in the app.py 
- [x] results from this function should be funneled into a new api called gecko-gainers.palomabot.ai which should return the data teh same way as the momentum.palomabot.ai api returns the data

**Comment by rootedbox** [comment]
https://gecko.momentumbots.palomachain.com/?dex=uniswap_v2&lag_return=6&daily_volume=0&vol_30=1&market_cap=1
