### ISSUE TITLE
Add Final ETH Uniswap V2 Dexes Fraxswap and ShibaSwap to Palomaswap

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#59]
# Background

We want all the ETH Uniswap v2 variant DEXes added to PalomaSwap

# Done when

- [ ] Add FraxSwap on ETH
- [x] Add Shibaswap on ETH
- [x] List them below Uniswap v2
- [x] Add Wallchain wallet integration
- [x] Ensure Bloxroute transactions

**Comment by verabehr** [comment]
Fraxswap has been moved down in priority - closing
