### ISSUE TITLE
replace number for bots with individual count per bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#590]
https://service.palomabot.ai/stats - the `bots` number should be per bot as well, like the `volume` number

@wdev733 FYI

- [x] rename exisitng `bots` number to `bots_total` 
- [x] add new calculation `bots` that shows the number of bots (active an withdrawn) per bot type

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/bot-info-api/pull/14
