### ISSUE TITLE
Missing chain switch prompt on momentum start bot page

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#596]
Steps to reproduce

1. Go to Palomabot and connect to Ethereum
2. go to telegram palomabot and click on a link for a token on pancakeswap
3. You should be redirected to the start bot page for that token you selected
4. click on select token for "Sell" field

Expected: I should be prompted to switch to ethereum in metamask

Actual: I'm not prompted to switch my chain and am stuck with no tokens to select

**Comment by jamie088** [comment]
Fixed. https://github.com/VolumeFi/palomabot/pull/134
