### ISSUE TITLE
redesign website for palomachain

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#600]
As a user, I want to see the new palomachain front-page with the updated positioning for decentralized bots.

**Acceptance Criteria**
1. Update the home page design
2. Update home page text
3. Deploy updated design and content

- [x] CTA to "Launch App" 
![Image](https://github.com/VolumeFi/paloma/assets/22323189/6655e7f2-3d5a-430f-84ef-4ef42275db41)

- [x] Change Banner: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=10694-139151&mode=design&t=TPHVOo6uZDuHIOH8-4
![Image](https://github.com/VolumeFi/paloma/assets/22323189/e702672d-f872-4d76-a5e7-64c96f0d29db)

Image: 
![Image](https://github.com/VolumeFi/paloma/assets/22323189/d26fff1d-a051-4bee-8710-5398cbdcf445)

Clouds: 
![Image](https://github.com/VolumeFi/paloma/assets/22323189/823a3de6-15d9-4159-b26d-c1d12848cf46)

- [x] Change counting of messages to "Total Bot Messages" and "Total Bots" AND change the "total bots" number to use the `bots_total` from the https://service.palomabot.ai/stats api
![Image](https://github.com/VolumeFi/paloma/assets/22323189/c221aec4-6727-4d34-9100-08abe081feb3)

- [ ] Change text to Permissionless Bots: 
![Image](https://github.com/VolumeFi/paloma/assets/22323189/bbc6ea36-1eac-415b-85b5-c6a6cebc8f1d)

- [x] Change image to: 

![Image](https://github.com/VolumeFi/paloma/assets/22323189/7995a164-5ae6-4163-baa6-1a3513457a97)

- [x] Use Cases: Remove "Mint an Egg"
![Image](https://github.com/VolumeFi/paloma/assets/22323189/16728568-e3c4-4c70-91fe-9211501d6e3f)

- [x] How to build on Paloma?: 
![Image](https://github.com/VolumeFi/paloma/assets/22323189/d1c2d086-260e-4044-b865-e2844402763a)

- [x] Remove Mint an Egg from Footer: 

![Image](https://github.com/VolumeFi/paloma/assets/22323189/636afc54-0942-4e2e-9bb2-bfce6e4b079a)

- [ ] Menu "Developers" add "Security" 
![Image](https://github.com/VolumeFi/paloma/assets/22323189/d0e9b017-6ed4-4af9-8098-a259bed10451)

**Comment by verabehr** [comment]
@wdev733 here is the figma https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=10694%3A139151&mode=design&t=ZWCSt4gKJZCZc4bf-1
