### ISSUE TITLE
PalomaBot Text Update: Increase Text size to 18px for metrics and place on each line

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#602]
The current metrics text is too small and too much for one line.

1. Increase the Bot Title Text size to 20px
2. Increase the Bot Metrics Text size to 18px
3. Update the metrics Text as follows:
  a. **Highest Return** (NO DECIMAL PLACES)
  b. **Total Volume**
  c. **Total Bots**
4. No dividers and place each metric on its own line. 

5. Use the image below as example 
 
<img width="751" alt="Screenshot 2023-08-04 at 12 33 37 AM" src="https://github.com/VolumeFi/paloma/assets/701864/fe1adadb-be2b-4931-8a63-3c8b3ddafa68">

**Comment by rootedbox** [comment]
@taariq https://github.com/VolumeFi/palomabot/pull/138

**Comment by taariq** [comment]
Finished.
