### ISSUE TITLE
Closed Bots page

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#603]
As a user I want to be able to see my Closed Bots.

API endpoint: https://service.palomabot.ai/robots?completed=true

On "_My Bots"_ page I want to see a new button called Closed Bots.
![Image](https://github.com/VolumeFi/paloma/assets/22323189/d02bb176-d4b4-4594-960b-690a95fe2c74)

When Closed Bots is selected I want to see a Table with the following data:
* Bot Type: Momentum / Gecko AI
* Date
* Token name
* Profit/Loss amount
* Tx Hash 
* Withdraw Type: Expired, Profit Taking, Stop Loss, Canceled.

Design: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=10830-139783&mode=design&t=FtCxqU9VQl8Pwm9T-4

**Comment by verabehr** [comment]
@jamie088 - cc @joycehermosilla - since not all bots actually set the withdraw type, we can't use that column at the moment. Let's move on without it for now

**Comment by jamie088** [comment]
Done with https://github.com/VolumeFi/palomabot/pull/351
