### ISSUE TITLE
Telegram Bot CTA on Palomabot.ai

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#604]
As a user I want to be able to see the CTA for Create Telegram Alerts more clearly and often.

- [x] Change Telegram button to: 
![Image](https://github.com/VolumeFi/paloma/assets/22323189/4124aeb5-e92c-478d-89b6-6249cf7fd5f6)
Design: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=10830-139783&mode=design&t=FtCxqU9VQl8Pwm9T-4

Icon: 

![Image](https://github.com/VolumeFi/paloma/assets/22323189/c325fd30-0658-4438-835b-1059986ddfcb)

- [x] On My Bots Page I want to see a button with "Activate Alerts"

![Image](https://github.com/VolumeFi/paloma/assets/22323189/e605796b-6954-4bd8-848f-f10891a80e27)

Design: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=9788-116104&mode=design&t=FtCxqU9VQl8Pwm9T-4

**Comment by verabehr** [comment]
@jamie088 will you be able to close on this today?

**Comment by jamie088** [comment]
@verabehr Yes. I will do it by today.

**Comment by jamie088** [comment]
@verabehr Done. https://github.com/VolumeFi/palomabot/pull/144

**Comment by verabehr** [comment]
@jamie088 mobile UI is here - thanks @joycehermosilla https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=11164%3A22533&mode=design&t=PmcQMOtTcqrH00GJ-1
