### ISSUE TITLE
Telegram Bot

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#614]
Implementation of our Telegram Bot "UI"
Epic and Flow: https://www.notion.so/volumefi/EPIC-07-28-23-Telegram-alert-additions-ab6f799b1fc840a39b23d2409d455b51?pvs=4#9c299c2c454f4c1c8dacedd3f3e3f44a

**Comment by taariq** [comment]
Closed and moved to @rootedbox
