### ISSUE TITLE
Endpoint for return numbers  | speed up FE numbers

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#615]
We need to add  new numbers to the https://service.palomabot.ai/stats endpoint. 

### done when
- [ ] `max_return_momentum_uni`: the highest `7D Return` number of the momentum bots api for uniswap v2 https://momentumbots.palomachain.com/?lag_return=6&dex=uniswap_v2&daily_volume=0&vol_30=100000&market_cap=1000000 has been added to the stats api 
- [ ] `max_return_momentum_pancake`: the highest `7D Return` number of the momentum bots api for pancakeswap https://momentumbots.palomachain.com/?lag_return=6&dex=pancakeswap_new&daily_volume=0&vol_30=100000&market_cap=1000000 has been added to the stats api
- [ ] `max_return_momentum_uni_panckake`: the highest `7D Return` number of the momentum bots api across pancakeswap and uniswap https://momentumbots.palomachain.com/?lag_return=6&dex=uniswap_v2&daily_volume=0&vol_30=100000&market_cap=1000000 and https://momentumbots.palomachain.com/?lag_return=6&dex=pancakeswap_new&daily_volume=0&vol_30=100000&market_cap=1000000
- [ ] `max_return_gecko_uni`: the highest `7D Return` number of the gecko bots api for uniswap v2 https://gecko.momentumbots.palomachain.com/?lag_return=6&dex=uniswap_v2&daily_volume=0&vol_30=1&market_cap=1
- [ ] `max_return_gecko_pancake`: the highest `7D Return` number of the gecko bots api for pancakeswp v2 https://gecko.momentumbots.palomachain.com/?lag_return=6&dex=pancakeswap_new&daily_volume=0&vol_30=1&market_cap=1
- [ ] `max_return_gecko_uni_pancake`: the highest `7D Return` number of the gecko bots api across https://gecko.momentumbots.palomachain.com/?lag_return=6&dex=uniswap_v2&daily_volume=0&vol_30=1&market_cap=1 and https://gecko.momentumbots.palomachain.com/?lag_return=6&dex=pancakeswap_new&daily_volume=0&vol_30=1&market_cap=1
- [ ] `max_return_curve`: the highest `7D Return` number of the momentum bots api for curve https://momentumbots.palomachain.com/?lag_return=6&dex=curve_ethereum&daily_volume=0&vol_30=100000&market_cap=1000000

**Comment by rootedbox** [comment]
https://service.palomabot.ai/stats
