### ISSUE TITLE
UI feedback - new palomachain website

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#617]
![Image](https://github.com/VolumeFi/paloma/assets/19958639/50a9151e-0f2a-4bc6-84ae-9d3be5c1358b)
- [x] 1 - change `Execute an EVM contract` to `Set up a limit order bot`  -->Link to  https://www.palomabot.ai/
- [x] 2 the link for `Readme` under Security should go to https://docs.palomachain.com/guide/security/security.html

--
![Image](https://github.com/VolumeFi/paloma/assets/19958639/b63637ff-9fd0-4513-96ff-4e49f2337f3a)
- [x] 1 - remove `Pyth Price feed`
- [x] 2 replace `Palomaswap` with `Palomabot` and link to https://www.palomabot.ai/

--
![Image](https://github.com/VolumeFi/paloma/assets/19958639/301e7d0d-5a43-4cff-8927-dcf2831445d3)
![Image](https://github.com/VolumeFi/paloma/assets/19958639/09c20546-16c9-4515-9293-9e7f82b418b4)
- [x] What is this number? It should be the same number as before just a different label 

--
![Image](https://github.com/VolumeFi/paloma/assets/19958639/e98f785d-fed3-48fa-ae88-9c3d03f76b63)

- [x] Security should link to https://docs.palomachain.com/guide/security/security.html

- [x] Please shrink the spacing between the header and banner image to start. 
![Image](https://github.com/VolumeFi/paloma/assets/22323189/a627895b-db90-4d50-8d7d-fdfced9e7aa2)

- [x] Clouds should be the same color as the background.

![Image](https://github.com/VolumeFi/paloma/assets/22323189/0e2cf2b7-3d67-4887-94c6-576deab3f47b)

**Comment by joycehermosilla** [comment]
@wdev733 @verabehr I added 2 new items to correct.
