### ISSUE TITLE
Create scheduled refund job for Optimism

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#622]
Tasks:

1. Fork the ETH/BNB refund package and create a new one for Polygon, scheduled for daily refunds.  
2. Restart the refund schedule job for ETH/BNB.

Specs: https://www.notion.so/volumefi/Gas-refund-specs-1ffc5242fd234f21b50561f9095d54eb

**Comment by rootedbox** [comment]
@fieldtheory123 @verabehr  the version on the server already does polygon and eth refunds. Am I missing something?

**Comment by verabehr** [comment]
Note that this morning's refund didn't run because of a bscan issue. It successfully ran when manually triggered by @rootedbox. 

@webelf101 @fieldtheory123 let us know what else is needed at this moment

**Comment by verabehr** [comment]
@rootedbox I think @fieldtheory123 meant to ask for setting it up for `Optimism`  not `Polygon`. The config details are in the linked Notion

**Comment by rootedbox** [comment]
ok I'll check that out @verabehr

**Comment by fieldtheory123** [comment]
@webelf101 Didn't you tell me that Polygon's refund contract was just created on Monday?

**Comment by fieldtheory123** [comment]
@rootedbox the ETH/BNB refund stopped and is still not up https://etherscan.io/address/0x6dc0A87638CD75Cc700cCdB226c7ab6C054bc70b

**Comment by webelf101** [comment]
We don't have any transactions on ETH and BNB to compass-evm from then. That's why we don't have refunds. @fieldtheory123

**Comment by verabehr** [comment]
Optimism compass evm : 0x05d7b3A021DAFA1A52Aef09B8057493847cb6800

**Comment by verabehr** [comment]
https://github.com/palomachain/gas-refund/pull/10
