### ISSUE TITLE
Launch Coingecko New Tokens Bot

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#623]
As a user, I want to see a new bot called Coingecko New which will list all the latest listed tokens by Coingecko that I can ape into to start a bot.

**Acceptance Criteria**
1. Use Coingecko API endpoint to create a new bot: details here: https://apiguide.coingecko.co, https://apiguide.coingecko.com/exclusive-endpoints/for-paid-plan-subscribers#coins-list-new
2. Show List of new Coins like the Momentum Table. Use similar UI. Uniswap/Pancake only
3. Allow users to start Bot based on this list.

**Comment by fieldtheory123** [comment]
The change for the backend script is complete.

Next steps: 

1. @rootedbox clone a new repo from https://github.com/VolumeFi/trading-bots/tree/main, just like the CG top gainer bot. Then start an API service using momentum_scanner_intraday.get_new_listing() funtion.

2. Once the API is ready, @wdev733 can access the data, which is in this format:
                           price  30_day_mean_volume  30_day_mean_marketcap
we-all-got-mantle-illness    1.0        61870.708688                    0.0
abachi-2                     1.0         4975.283136                    0.0
just-clone-it                1.0       126708.731046                    0.0
all-in-coin                  1.0        39326.946891                    0.0
league-bot                   1.0       171667.403685                    0.0
...                          ...                 ...                    ...
cpiggy-bank-token            1.0        25834.808166                    0.0
shredn                       1.0       288306.376675                    0.0
quasar-2                     1.0         6206.553772                    0.0
echoes                       1.0       227531.288350                    0.0
truthgpt-eth                 1.0        20045.454103                    0.0

**Comment by verabehr** [comment]
The api base domain should gecko.new.palomabot.ai

**Comment by rootedbox** [comment]
@fieldtheory123 @verabehr it's all setup but not code is coming out https://gecko.new.palomabot.ai/

**Comment by fieldtheory123** [comment]
Two possible sources as discussed in Discord:
1. https://github.com/VolumeFi/coingecko-new-backend-bots/blob/main/cache_db.py#L35 we need a new db table
2. could it be a timeout thing? the new function momentum_scanner_intraday.get_new_listing() takes a bout 30 seconds to run

**Comment by verabehr** [comment]
https://github.com/VolumeFi/paloma/issues/588

**Comment by verabehr** [comment]
@fieldtheory123 once you update the code in github, you'll need to do the following to get the code onto the server: 

`ssh lorentz` (if you haven't logged in since the latest security updates, follow the instructions here https://www.notion.so/volumefi/SSHing-into-Volume-Paloma-Servers-ff97b346f75d45d3a170549ee023238f?pvs=4) 

```
cd app/coingecko-new-backend-bots
git pull
service gecko_new_backend restart
```
