### ISSUE TITLE
CHORE: Add All bots to Better Uptime for real-time tracking

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#625]
CHORE: Add All Robot endpoints to Better Uptime so that if anything does down, we'll know.

**Comment by rootedbox** [comment]
Limit Order Bot
http://check.bots.palomachain.com/limit-order-bot-script/
Momentum Order Bot
http://check.bots.palomachain.com/momentum-order-bot-script/
Stop Loss Bot
http://check.bots.palomachain.com/stop-loss-bot-script/
Gecko Bot
http://check.bots.palomachain.com/gecko-bot-script/
Curve Stop Loss Bot
http://check.bots.palomachain.com/curve-stop-loss-script/
