### ISSUE TITLE
CHORE: Deploy contracts and set up scripts for Gecko New token bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#627]
- [x]  Clone the momentum bots repos as `gecko-newtoken-bot-...`  - functionality will be the same a momentum bot 
     - [x] https://github.com/VolumeFi/momentum-bot-vyper-uniswap-v2
     - [x] https://github.com/VolumeFi/momentum-bot-uni-v2-cosmwasm
     - [x] https://github.com/VolumeFi/momentum-order-bot-script
- [x] Deploy the vyper and CW contracts, so they can be set up on the server
- [ ] set up and start services

**Comment by verabehr** [comment]
https://github.com/VolumeFi/gecko-newtoken-bot-vyper-uniswap-v2
https://github.com/VolumeFi/gecko-newtoken-bot-uni-v2-cosmwasm
https://github.com/VolumeFi/gecko-newtoken-bot-script

**Comment by webelf101** [comment]
Please create a service with https://github.com/VolumeFi/gecko-newtoken-bot-script and let me know.
@rootedbox

**Comment by rootedbox** [comment]
@webelf101 done
