### ISSUE TITLE
Curvebot: Add wallet connect functionality

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#637]
We have several issues with wallet connect on palomabot and curvebot. We have more people connecting on mobile, so we want this to work properly. 

### done when

- [ ] **palomabot** wallet connect button is more visible ([Figma](https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=11176-91895&mode=design&t=xF3e0sXO2ZzTN4CO-4))

<img width="345" alt="Captura de pantalla 2023-08-15 a las 16 12 55" src="https://github.com/VolumeFi/paloma/assets/22323189/a8dfaa91-3cc8-4f41-903b-805838c6d894">

- [ ] **palomabot** When the user presses Wallet Connect the modal view for Connecting the Wallet should disappear.
<img width="895" alt="Captura de pantalla 2023-08-15 a las 16 13 35" src="https://github.com/VolumeFi/paloma/assets/22323189/a41a3b4c-e2c0-41de-8fe5-3bd0a5b01488"> 

- [ ] **palomabot** users can link their wallet through wallet connect. At the moment if you try to link metamask, you're stuck on this screen 

![Image](https://github.com/VolumeFi/paloma/assets/19958639/fe2713f2-07b3-4ba7-8120-f2fa2c67e882)

- [ ] **curvebot** the wallet connect option shows when user clicks on connect wallet button from a mobile device and it works the same as for Palomabot

**Comment by taariq** [comment]
@jamie088 moving this back to @wdev733 for delivery at 9AM PT. @jamie088 I will ask you to QA.

**Comment by taariq** [comment]
Completd.
