### ISSUE TITLE
BUG: DCA Bot has so many problems. They are documented in this ticket with two Looms.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#642]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

1. Loom Number 1 of DCA Bott: 
https://www.loom.com/share/f00a579374c54139b695c9a2a74d4e3e?sid=f7e556ee-076d-48e6-a01c-c0bdb23eb1b7

2. Loom Number 2 of DCA Bot:
https://www.loom.com/share/d2e09a7ed88542399760ee3e86265588?sid=8a3a2ecc-c70f-414e-b11d-aed4663f4762

**Transactions:**

- [x] 1. DCA Bot Transactions Happened with 1 minute of each other: https://etherscan.io/address/0x83334ef0C6f6396413C508A7762741e9FD8B20E9#internaltx Which was incorrect when they were scheduled for 1 hour apart.

**Front-end:** 

- [x]  The DCA Bot was scheduled to start at 1AM, but on the website it said it would start in 1, but they started at the time I scheduled so the front-end was incorrect. Check Loom. @wdev733 this is still an issue. The "time to next trade" field is not showing the right time left.   - moved to https://github.com/VolumeFi/paloma/issues/656
- [x] No TVL shows on the bot page  - we don't have the tracking price, so the FE can't calculate this.
- [x] Bot is not visible on CurveBot My bots if started on Palomabot.

**Telegram Alerts**

- [ ] 1. Wrong information, but also showin gthat the bots did not respect the schedule. See the attached picture  <img width="298" alt="Screenshot 2023-08-13 at 1 16 45 AM" src="https://github.com/VolumeFi/paloma/assets/701864/eb0c6ef8-fd17-440a-8f9d-506065f14388"> - moved to https://github.com/VolumeFi/paloma/issues/657

**Comment by fieldtheory123** [comment]
@wdev733 more issues:

I started a DCA bot with the following input:
<img width="916" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/829cabd0-1b36-44f2-9378-82867baae88e">

I started the bot at 3:12pm my local time. It is 4:21pm so all three trades should have done. But so far only the deposit tx at the beginning is there https://etherscan.io/tx/0x4627ef292fae6dda478dad7eb5867fe778ee62e4b174ff6563b3dda51899d312

Also, there's no DCA bot under mybots page:
<img width="913" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/2d414588-ce39-4b15-964a-ee5e01d24a96">
