### ISSUE TITLE
Short-Squeeze Bots EPIC

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#651]
short-squeeze bot: bots that monitor futures' short positions on CEX and DEX with a dashboard like the one for momentum bo

**Comment by fieldtheory123** [comment]
Done (renamed to Futures Positioning Bot)

https://www.notion.so/volumefi/EPIC-08-18-23-Futures-Positioning-Bot-aa6dd1727104459a9f6758ae566d1a2f
