### ISSUE TITLE
DyDx Starkware Position Manager Bot

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#653]
Create a Starkware position Manager Bot for DYDX that we will use for a Grant application with DyDx.

**Comment by fieldtheory123** [comment]
I have done some initial exploration. These ideas are what I find feasible:

1. A bot similar to Curve lending bot that manages position risk to avoid liquidation 
2. Short squeeze bot - but based on other data sources

**Comment by fieldtheory123** [comment]
Draft applications are in review 
https://www.notion.so/volumefi/Paloma-dYdX-Trading-Bot-Grant-Application-by-the-Volume-team-2f24fa1d8bdf4fb9b0aff58dc840e316
https://www.notion.so/volumefi/Paloma-Starkware-Cairo-contracts-for-bots-grant-d8f245a2f37f4933951fbffaa5c78528
