### ISSUE TITLE
Metaverse Bots: What are the largest metaverse communities for Paloma

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#654]
Metaverse Bots: What are the largest metaverse communities for Paloma?

1. Identify the largest and most vibrant metaverse communities and valuation
2. Identify a palomabot opportunity for a possible grant and bot design

**Comment by fieldtheory123** [comment]
Exploring friend.tech's API and contract transactions.

**Comment by taariq** [comment]
@fieldtheory123 closing as not your area of happiness.
