### ISSUE TITLE
BUG: time left until next trade field is incorrect

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#656]
- [ ]  The DCA Bot was scheduled to start at 1AM, but on the website it said it would start in 1, but they started at the time I scheduled so the front-end was incorrect. Check Loom. @wdev733 this is still an issue. The "time to next trade" field is not showing the right time left.

Here is an example from my last bot
```
{"deposit_id":"4","token0":"0x6B175474E89094C44Da98b954EedeAC495271d0F","token1":"0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE","amount0":"18345292926018252191","depositor":"0x9FC09a1d181F45Aa424E1ca7267c15e87e691BDD","network_name":"ETH","dex_name":"curve","bot":"curveDCA","number_trades":"2","remaining_counts":"2","interval":"1800","starting_time":"1692126000","contract":"0x6eA64066ef9Fa9Efaf2E98bE2db5Ef9f3F8355C5","coin_info":
```

![Image](https://github.com/VolumeFi/paloma/assets/19958639/a9b05900-61dc-4011-8c8f-0499e71908f1)

![Image](https://github.com/VolumeFi/paloma/assets/19958639/330ad1c8-d824-4415-b50a-8954442f36b8)

**Comment by wdev733** [comment]
@verabehr could you add more details please?

**Comment by verabehr** [comment]
![Image](https://github.com/VolumeFi/paloma/assets/19958639/726de88e-c9a0-4e49-9f1d-9f64bdeff48a)

One more screenshot. >50 minutes to next trade when 1/2 trades are complete is impossible if the trade interval is only 30 minutes
