### ISSUE TITLE
bug: Gecko new listing bot shows insufficient amount

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#662]
Got this on this page: https://www.palomabot.ai/coingecko-new-tokens/bot/?dex=uniswap_v2&token=pond-coin

<img width="756" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/5f462f1c-ed1f-492e-addf-69980731f855">

As shown, I have 0.2 ETH but it says "insufficient amount" even though I'm selling 0.001 ETH. As a result, I can't trade.

**Comment by verabehr** [comment]
happens to me as well

**Comment by verabehr** [comment]
fixed via api
