### ISSUE TITLE
CHORE: add OP and Gnoiss Compass EVM contracts to stats count

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#666]
We want the OP compass EVM to be counted in this API  https://count.palomachain.com/ and sent to mixpanel

OP mainnet: https://optimistic.etherscan.io/address/0xe3e2E3ebd228485FCbC812D1DBA0B2F90233E56c
Gnosis mainnet: https://gnosisscan.io/address/0x2E00587b846ec97b293F86b1243Dd4280aA22CbF

**Comment by rootedbox** [comment]
https://github.com/palomachain/kits/pull/14
