### ISSUE TITLE
Pigeon Relay Issues: Reduce job execution time delay on Pigeon from 15 minutes to 5 seconds

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#67]
# Background

After execute job request~, there are too long delay to execute the job on bnb chain. It was 5~15 minutes in the test. Jobs must execute when they are made or at least at the same time as a Paloma Block, 5 seconds. See issue #1 here: https://www.notion.so/volumefi/EPIC-03-10-Issues-in-DCA-trading-bot-test-2dabb3506acc4a33a5714d8b7a252a16

# Done when

- [x] identify why Paloma chain scheduled jobs do not execute immediately
- [ ] Implement immediate job execution and test with DCA Bot

**Comment by taariq** [comment]
@webelf101 will you provide us example Python SDK code for sending the message so that we can test this in the private testnet?

**Comment by taariq** [comment]
@verabehr & @webelf101: We want to benchmark message queue and delivery so that we know what is causing time delays.

**Comment by verabehr** [comment]
we know that messages take a while to be sent because of the account sequence mismatch errors during pigeon signature and attestation
