### ISSUE TITLE
Bug - Pigeon using hard-coded number for consensus comparison

### ISSUE THREAD

**Issue by ToasterTheBrave** [VolumeFi/paloma#673]
Pigeon has a hard-coded number it's comparing power against to decide if it thinks consensus is reached.

That's flat out the wrong way to do it.  Looks like legacy code from Matija in June 2022 (https://github.com/palomachain/pigeon/commit/8d550bf902517fa9d5d36e9e718ee6e15cb6c77b#diff-989cee9cdd4280d3a0b50bd5c31d634dc1d6cdd2d31824c35c9ba75fe3b89bb5R318).

Comparison happening here: https://github.com/palomachain/pigeon/blob/master/chain/evm/compass.go#L634
Comparing against 2863311530 from here: https://github.com/palomachain/pigeon/blob/master/chain/evm/compass.go#L28

The fix: Check against the total power of the valset, not some hard-coded number

**Comment by taariq** [comment]
On Paloma Testnet. Completed.
