### ISSUE TITLE
Add Fund My token to the Sell Pop-up listing of tokens to use for a transaction

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#689]
As a user, who is selecting tokens to sell, I want to be able to fund my bot with tokens from Onramper directly from within the dialog box so that I don't have h find the dialog box on the main screen.

**Acceptance Criteria**
1. Update UI so that Funding the bot is part of the sell dialog. Desing: 
![image](https://github.com/VolumeFi/paloma/assets/22323189/dead8d3d-5d58-4500-8292-c0e8547324a8)
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=7122-21890&mode=design&t=XnmbzkhPtJaB3K29-4

**Comment by wdev733** [comment]
@taariq no details for #2 ?
![image](https://github.com/VolumeFi/paloma/assets/53801750/b214a4ff-c750-45d0-a630-638385d3470b)

**Comment by taariq** [comment]
@wdev733 I deleted the 2nd image. It was an original draft that @joycehermosilla improved on with the first. Let me know if you need further support or clarification.

**Comment by wdev733** [comment]
@taariq thanks for the quick answer. So user will move to `onramper` page when he clicks the `Add funds to your bot` ?

**Comment by taariq** [comment]
@wdev733 Yes. When we say "move" we mean they will have popup page/dialog window for onramper. They won't leave their position page.

**Comment by joycehermosilla** [comment]
Curve Bots design: https://www.figma.com/file/vLd6scwseZilfUZJXI6oRQ/Curve-Bots?type=design&node-id=202-36&mode=design&t=9o4XjPeSzr06EYOa-4 @wdev733
