### ISSUE TITLE
bug: Mybot api responses are not correct

### ISSUE THREAD

**Issue by wdev733** [VolumeFi/paloma#690]
# What is happening?
https://service.palomabot.ai/robots?depositor=0xD0e08D653C3ead747865c3674FFa93ecDefDd045
- `0xBcc9B67f8116c76d16F26f59f994aeF377866ADD` is the old contract and response should have `old: 1`
- The bot has already been canceled (2nd image). so it should not be returned.

# Screenshots
![image](https://github.com/VolumeFi/paloma/assets/53801750/b0653f9e-1395-403f-98ee-ed77b6c47395)
![image (1)](https://github.com/VolumeFi/paloma/assets/53801750/9e769b4e-ecd5-4eee-8ccc-202393975705)

**Comment by taariq** [comment]
@rootedbox are you addressing this?
