### ISSUE TITLE
Erro: No RPC Url available for chainId: 56 while using https://www.palomaswap.com/pancakeswap/

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#70]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Error: No RPC Url available for chainId: 56 while using https://www.palomaswap.com/pancakeswap/
```
Error: No RPC Url available for chainId: 56
  at Gt.updateRpcUrl (https://www.palomaswap.com/_next/static/chunks/pages/_app-70b3c6fffc0520ce.js:1:622285)
  at Gt.updateState (https://www.palomaswap.com/_next/static/chunks/pages/_app-70b3c6fffc0520ce.js:1:622098)
  at Object.callback (https://www.palomaswap.com/_next/static/chunks/pages/_app-70b3c6fffc0520ce.js:1:621251)
  at None (https://www.palomaswap.com/_next/static/chunks/pages/_app-70b3c6fffc0520ce.js:1:598422)
  at Array.forEach (<anonymous>)
...
(7 additional frame(s) were not displayed)
```
Sentry: https://volume-x3.sentry.io/issues/4005166213/?alert_rule_id=13986897&alert_timestamp=1678816163481&alert_type=email&environment=production&project=4504816371236864&referrer=alert_email

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

RPC must be available for BNB chain.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

{WRITE YOUR ANSWER HERE}

**Comment by wdev733** [comment]
@taariq Can you reproduce this error again? If yes, please attach a loom link

**Comment by taariq** [comment]
Closing. No repro. Works. now.
