### ISSUE TITLE
Pigeon Keep Alive Block Height Migration Cleanup

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#709]
There are some fragments of the time based keep alive approach left over to ensure a smooth migration which should be removed now.

- old time based constants in `keep_alive.go`
- any checks against the old `AliveUntil` field
- remove the `AliveUntil` field from the struct
- remove any code annotated with `deprecated` in this context

**Comment by taariq** [comment]
Much needed.

**Comment by taariq** [comment]
@byte-bandit where is this? When is this being delivered?

**Comment by byte-bandit** [comment]
> @byte-bandit where is this? When is this being delivered?

This is a follow up to switching Pigeons keep alive logic to away from "Time to live" and towards "Blocks to live" instead. We need to support both during the initial migration. Once it's been deployed to both public and private test net, this issue covers a bit of clean up that needs doing afterwards. Not much work though, should be done within an hour. 

I expect to pick this one up on the side next week or the week after, depending on when we push out a release to both nets.

**Comment by taariq** [comment]
Thanks for the clarification. Agreed and aligned.

**Comment by taariq** [comment]
Fixd.
