### ISSUE TITLE
Add Frame as Direct Connect Option on Palomabot and Curvebot under Metamask and above WalletConnect

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#712]
As a user, I want to see Frame as a default wallet selection below Metamask, but above WalletConnect so that I don't have to use WalletCOnnect to use Frame and I can go directly.

**Acceptance Criteria**
1. Add new option for Frame Wallet for direct connection instead of via Metamask or WalletConnect.

**Comment by verabehr** [comment]
tested on palomabot.ai and looks good

**Comment by taariq** [comment]
Closing as delivered.
