### ISSUE TITLE
API for APR and gauge for vote distribution bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#713]
For the vote distribution bot, the FE needs to show the APR and gauge that is retrieved via Python script

### Done when

- [ ] This python script https://github.com/VolumeFi/vote-distribution-bots/tree/main is set up to run as cron and runs daily on the `bots-server` ( @fieldtheory123 will you confirm how often this should be run?)
- [ ] There is an API endpoint implemented to return the **APR** (`$python get_vote pool`) and **gauge** (`python get_vote curve`)

**Comment by taariq** [comment]
Closing.
