### ISSUE TITLE
Increase CPU for LCD, so it doesn't fall behind and fix uptime check

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#721]
it looks like the CPU is pretty pegged.  FCD is using a lot of CPU.  We either need to move FCD to its own server, or stand up a more powerful server that can handle the load.

### Done when

- [x] LCD server is resized and caught up
- [x] uptime can check the lcd server 
- [ ] update the terraform code and open a PR with the changes made directly in Linode for the first bullet point

**Comment by verabehr** [comment]
@rootedbox this endpoint  https://lcdcheck.palomachain.com/ is still giving a 502 error. Will open this ticket until that's fixed

**Comment by rootedbox** [comment]
we are not using that url anymore

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/linode-iac/pull/9

**Comment by verabehr** [comment]
@rootedbox if we're not using https://lcdcheck.palomachain.com/  anymore, what are we using for uptime? I don't have a login, so can't see it.

**Comment by verabehr** [comment]
this no longer uses a separate domain, but a port on the lcd domain.

**Comment by rootedbox** [comment]
had questions https://github.com/VolumeFi/linode-iac/pull/9

**Comment by taariq** [comment]
@rootedbox upgraded this CPU again today.
