### ISSUE TITLE
bug: Auto refund not working

### ISSUE THREAD

**Issue by KyErgus** [VolumeFi/paloma#723]
# What is happening?

- Wallet balances that need automatic replenishment for the ETH network do not work for a few wallets. Etherscan information is available at the link below.
 https://etherscan.io/tx/0xbb15664657a94f21c89b6d1c7012a5bb3612f4bcd1f3b026c0a622a0aa746b63

**Comment by taariq** [comment]
Thanks. We know the issue. Closing as we will have a new fix for failed transactions.
