### ISSUE TITLE
Curve Base bridge-LP bot

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#730]
https://www.notion.so/volumefi/EPIC-09-08-Curve-Base-Bridge-LP-bot-fd053a281b914c5681a1914684e378f2?pvs=4

**Comment by taariq** [comment]
@wc117  is there work completed on this ticket? If so, will you push and link the repo?

**Comment by wc117** [comment]
https://github.com/VolumeFi/curve_base_bridge_lp_bot_vyper
I just pushed draft code.

**Comment by taariq** [comment]
Thank you @wc117. This is very helpful!

**Comment by verabehr** [comment]
the incentives ran out - closing
