### ISSUE TITLE
Create middleware for Curve lending bot

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#735]
Task:
Create middleware for Curve lending bot the same way as the stop-loss bot. Details: https://www.notion.so/volumefi/EPIC-07-27-23-Curve-lending-bots-e22990bbc1904f34b0d4eaf5dd77ade0?pvs=4#a6d16cd383da45b6a8ff0026938b9b3a -> BE and middleware

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/curve-lending-bot
