### ISSUE TITLE
BUG: daily announcements are no longer published to the forum

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#737]
The daily announcemnets are no longer published to the forum. It appears that the service had been set up on the hardware machine that was deprecated on Aug 29 in the afternoon and was never migrated afterwards. 

### Done when 
https://github.com/VolumeFi/paloma-storyblokupdates is set up on the bots-server and daily announcements get published to the forum again

**Comment by rootedbox** [comment]
updated code and config.. will not close until I see posting tomorrow
