### ISSUE TITLE
BUG: Sentry is overloaded on LCD failures by 15K and Unclosed Client Session by 24K

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#738]
Reduce LCD Capture Exception Alerts. 15K in last 24 hours.
https://volume-x3.sentry.io/issues/3930149722/?project=6380489&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0

and
https://volume-x3.sentry.io/issues/4443395347/?project=4505082653573120&query=&referrer=issue-stream&statsPeriod=14d&stream_index=0

**Comment by rootedbox** [comment]
disabled node reset on robot server because it's not needed as it's not running lcd.
disabled sentry for /home/rootedbox/app/curve-dca-bot-script

should fix both exception

@taariq

**Comment by taariq** [comment]
@webelf101 moving this ticket to you:

1. The Async.io script is overloading Sentry with errors for unclosed Client Session. Will you please update the python script to close all asyncio sessions to remove this error?  The bots creating this error are:
  a. sentry for /home/rootedbox/app/curve-dca-bot-script
  b. disabled sentry for /home/rootedbox/app/dca_bot_python_scrip

**Comment by verabehr** [comment]
FYI, also filtered out localhost alerts on palomabot

**Comment by taariq** [comment]
Fixed by fixed by https://github.com/VolumeFi/curve-twap-bot-script/pull/28
