### ISSUE TITLE
As a TWAP user, I want to see BOTH icons of the TWAP on the Mybot Page listing

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#748]
As a TWAP user, I want to see BOTH icons of the TWAP on the Mybot Page listing so that I know what token was sold and what token I sold and bought in the TWAP myBot view.

**Acceptance Criteria**
1. Update token listing for Mybot to show SoldToken BoughtToken in the token listings

**Comment by verabehr** [comment]
@jamie088 I believe this needs an API update since we don't have the token info for both tokens in there currently?

**Comment by verabehr** [comment]
ok, marking as blocked for now then

**Comment by verabehr** [comment]
api was update to contain `coin_info1` and `coin_info0`. `coin_info` is still available for backwards compatibility
