### ISSUE TITLE
BUG: Unable to connect wallet with Vivaldi and Frame after reloading

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#751]
Today, I was unable to use Vivaldi and Frame wallet with WalltConnect.
1. Wallet was Disconnected.
2. WalletConnect said wallet was connected
3. With our without Frame connected, unable to move past WalletConnect dialog box.

See the Loom: https://www.loom.com/share/39ad404e36ae4d788b681fa4bd50ce7f?sid=fbb2a529-d5c8-4b12-b4d6-ffc3e4efcb7a

Sentry alert: https://volume-x3.sentry.io/issues/4401471727/?project=4505354828185600&query=is%3Aunresolved&referrer=issue-stream&stream_index=0

**Acceptance Criteria**
1. Test Frame + WalletConnect + Vivaldi on all changes.

**Comment by taariq** [comment]
@jamie088 & @verabehr please test with Vivaldi BEFORE we close.

**Comment by verabehr** [comment]
@jamie088 it works well as long as I don't refresh. If I refresh the browser, I get stuck like @taariq did in the video

**Comment by verabehr** [comment]
looks good now
