### ISSUE TITLE
Upgrade Dune Analytics Dashboard for Palomabot Curve TWAP contracts

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#752]
As a user, I want to see a Dune Analytics Dashboard of Paloambot's Curve TWAP Bot contract so that I know that Volume's Curve TWAP bot is viewable.

**Acceptance Criteria**
1. Use the Dune Analytics query here: https://dune.com/queries/3001470/4981581?category=decoded_project&namespace=curve_twap_bot&contract=curve_twap_vyper&blockchains=ethereum

**Comment by taariq** [comment]
@fieldtheory123 do you have an update we are able to look at?

**Comment by taariq** [comment]
@fieldtheory123 this blocks token launch. Let's connect and see how we might get it into a presentable version.

**Comment by fieldtheory123** [comment]
Working on an update. Happy to connect

**Comment by fieldtheory123** [comment]
Ran into a technical blocker - for some reason I couldn't join the trade table with Dune's price table. This is needed to show correct dollar volume amount. Working on a alternative solution.

**Comment by fieldtheory123** [comment]
The previous blocker is lifted and queries are working. Now working on the analytics.

**Comment by fieldtheory123** [comment]
Done. https://dune.com/palomabot/curvetwapbotvolumetimeseries

**Comment by verabehr** [comment]
volume is still undercounted - marking as blocked until this is resolved https://github.com/VolumeFi/paloma/issues/799

**Comment by taariq** [comment]
Closing as complete. We will only track volume as deposits on the website and dune.
