### ISSUE TITLE
CHORE: Update refund scripts with the new compass

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#759]
All refund scripts need to be updated since new compass were deployed

**TESTNET**
bnb-main	0xb77B80f08E05beF080bfD2022d0Ef277EA815dC6
eth-main	        0x4911920E9F354DbCA895CA4eE5F8f6E02d560996
matic-main	0x16F8fA1BfE2c7eEdEB8C644CdE73b172B8529E11
op-main	        0x6FaF9429c05DA406F77292CcCc0F42D4eF7Cc6a8

**MAINNET**
base-main	0x3C89a1FD995d35a0E87952B0c3F3aC2a46cF83Ab
bnb-main	0xFca1FBA89e880666f0851B211CBDa98027E3AbB4
eth-main	        0x4473eA62D337140879719FACD6dbF2D1931C09C1
matic-main	0x950AA3028F1A3A09D4969C3504BEc30D7ac7d6b2
op-main	        0xEdB353a241d6efD19494635FF966acc12aEEAeec

**Comment by webelf101** [comment]
Base for testnet? @verabehr

**Comment by verabehr** [comment]
This is done except Base - closing
