### ISSUE TITLE
Deploy bots with new compass  [& update SQL inserts - completed]

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#761]
### New Compass addresses: 

bnb-main	0x79e9f573D908E012aC6E1F7978cb09e0065E6355
eth-main	       0xa00CF3504FfaCff301E4973e21B44C052d087157

### Done when
The following bots have been updated and are using the new compass

Bots currently live on website
- [x] TWAP Curve
---
- [x] Limit order bot Curve
- [x] Stop loss bot Curve
- [x] Momentum Curve
---
- [x] Momentum Uniswap
- [x] Momentum Pancakeswap
- [x] TWAP Uniswap
- [x] TWAP Pancakeswap
- [x] Gecko Bot Momentum Uniswap
- [x] Gecko Bot Momentum Pancakeswap
- [x] Gecko New Token Bot Uniswap
- [x] Gecko New Token Bot Pancakeswap

**Comment by wc117** [comment]
StakeDAO bot is blocked as unlock from smart contract issue and it isn't alive. @verabehr

**Comment by verabehr** [comment]
@webelf101 when you start on this ticket, please follow the priority order grouping. Most important is getting Curve TWAP (and Curve MultiWAP back online)

**Comment by verabehr** [comment]
added new compass addresses deployed on 9/15
