### ISSUE TITLE
Multiple TWAP Upgrade Requests - After Approvals, do deposit in 1 tx

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#768]
# Background
After approvals, deposit all multiwap coins in one transaction.

# Done when
- [x] Multiple TWAP deposit is completed in one transaction and not one transaction per token.

**Comment by taariq** [comment]
@webelf101 added you tot this ticket

**Comment by taariq** [comment]
As per @webelf101, this will require a change in the Vyper contract.

**Comment by verabehr** [comment]
no longer blocked as we have compass deployed now
