### ISSUE TITLE
Paloma DEX - Flow 1: All Pools view and Connect Wallet

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#77]
As a user, I want to be able to see PalomaChain Pools and Connect my Nest Wallet to Paloma DEX.

- [ ] Main view/Home:
Figma: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=6284%3A16054&t=YAmyFhoMRPspxoSR-4

- [ ] The user will be able to see Total value, 24 hr Volume and the Grain Price.
<img width="645" alt="Captura de pantalla 2023-03-17 a las 16 01 42" src="https://user-images.githubusercontent.com/22323189/225942284-d4ff79df-1f58-4c2f-8d4a-846b1bc8bfee.png">

- [ ] The user will see all the available pools scrolling down:
<img width="383" alt="Captura de pantalla 2023-03-17 a las 16 02 01" src="https://user-images.githubusercontent.com/22323189/225942386-f8b6c47b-922b-4f7d-b99e-c452a7f34648.png">

- [ ] User will be able to switch between Tesnet and Mainnet https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=6284%3A16974&t=YAmyFhoMRPspxoSR-4 
<img width="364" alt="Captura de pantalla 2023-03-17 a las 16 01 13" src="https://user-images.githubusercontent.com/22323189/225942167-9cc2b341-659d-43ad-a421-24dc12f4aeb3.png">

- [ ] The user will be able to Connect their Nest Wallet to Paloma DEX 
<img width="262" alt="Captura de pantalla 2023-03-17 a las 16 03 11" src="https://user-images.githubusercontent.com/22323189/225942689-8cc45e92-5f03-4bdd-93c5-51dce10e8420.png">

- [ ] If the user has the Google Chrome Extention already installed the call on the modal view will have the call to action will be: Connect Nest Wallet. https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=6284%3A16619&t=YAmyFhoMRPspxoSR-4
<img width="361" alt="Captura de pantalla 2023-03-17 a las 16 04 06" src="https://user-images.githubusercontent.com/22323189/225943085-ddcdb9a6-3275-4de6-8e48-240718b93c3d.png">

- [ ] If the user hasn't installed the Chrome Extention the call of action should be: Download Nest Wallet and redirect the user to https://chrome.google.com/webstore/detail/paloma-nestbeta/cjmmdephaciiailjnoikekdebkcbcfmi
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=6290%3A14715&t=YAmyFhoMRPspxoSR-4
<img width="351" alt="Captura de pantalla 2023-03-17 a las 16 06 38" src="https://user-images.githubusercontent.com/22323189/225943624-a7203421-6a1b-472e-8ded-a4f151111863.png">

- [ ] After the user presses Connect with Nest Wallet the modal view will show the "Connecting..." modal view and will pop up the Nest Wallet Extention with the connection confirmation. 
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=6284%3A16743&t=YAmyFhoMRPspxoSR-4
<img width="566" alt="Captura de pantalla 2023-03-17 a las 16 09 20" src="https://user-images.githubusercontent.com/22323189/225944325-ae9b5275-31da-4f20-9d4c-6a837937b68b.png">

- [ ] After successfully connecting the wallet, the user will be able to see the wallet address of the wallet connected. https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=6284%3A16162&t=YAmyFhoMRPspxoSR-4
<img width="563" alt="Captura de pantalla 2023-03-17 a las 16 09 57" src="https://user-images.githubusercontent.com/22323189/225944479-aad06b46-493b-4e9b-8fc9-ed6c5fe26f67.png">

- [ ] By pressing the Wallet address the user will be able to see a drop-down menu that allows him/her to 1. Copy Address, 2. Open Explorer 3. Disconnect the Wallet. https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=6284%3A16375&t=YAmyFhoMRPspxoSR-4

<img width="318" alt="Captura de pantalla 2023-03-17 a las 16 11 38" src="https://user-images.githubusercontent.com/22323189/225944898-9af01c66-4f3a-4d46-a403-9d2c22ae9982.png">

**Comment by taariq** [comment]
Closing in favor of Paloma NFP DEX.
