### ISSUE TITLE
BUG: Total fees collected on Mixpanel are wrong for last 7 days.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#770]
See the fees collected here https://mixpanel.com/project/2744781/view/3280621/app/boards#id=3475733&edited-bookmark=S7Qmr7v9BQZ1 do not represent volume fees for the same time period.

**Comment by verabehr** [comment]
I see that the fees in some db complete events are not set

**Comment by rootedbox** [comment]
I've fixed a bug causing things going to mix panel early.. will need to figure out a way to back input data..

**Comment by rootedbox** [comment]
fixed another issue with null's and nans causing fees_charged not to be set properly.. And I've ran a script to catch up data to proper
