### ISSUE TITLE
tracking ticket - pigeon jailing

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#774]
https://github.com/palomachain/paloma/issues/973

**Comment by taariq** [comment]
Next step: remove lock usage during the keep-alive send calls.

**Comment by byte-bandit** [comment]
Installed https://github.com/VolumeFi/pigeon/tree/clohr/mutex-log on main net validator. This removes the lock during keep alive calls.

The validator should no longer get jailed now (hear hear). We'll see if it creates other problems. If good on Monday, we'll cut a release.
