### ISSUE TITLE
BUG: Submit Logic calls for TWAP Bot fail to hit EVM. No errors

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#782]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

from @webelf101:
https://paloma.explorers.guru/account/paloma10dry4t7gr8rhd0khqcqyq95ytdh6vs8sjv84yj
We are sending messages but they don't go to Vyper contract.

From @verabehr 
There are also messages in the eth queue but no error data

Further reporting on Discord here:
https://discord.com/channels/987730379182051408/1065140873811218532/1152341714791579649

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

Paloma 1.80. Pigeon 1.8.1

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Send Logic calls on Paloma Mainnet.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Logic calls will work.

**Comment by byte-bandit** [comment]
Most likely a symptom of the ongoing issue we're observing, following up on here: https://www.notion.so/volumefi/8-22-2023-Main-Message-relay-to-eth-main-down-f5564ff053d54d018ef6e8d9bacc6c7b
