### ISSUE TITLE
Backend script for optimized TWAP bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#785]

**Comment by fieldtheory123** [comment]
First MVP is pushed https://github.com/VolumeFi/optimized-twap-bot-script

Working on a more advanced version to have more reliable gas estimate and trade interval optimization.

**Comment by taariq** [comment]
@fieldtheory123 is this done?

**Comment by fieldtheory123** [comment]
Closed. MVP will be implemented first. Once it is up and running, we will kick off backend upgrade for more data-driven optimization.
