### ISSUE TITLE
Automate Paloma deployments

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#792]
making an attempt to move to Github Actions for a more streamlined process that doesn't rely on engineering resources so much. I'm adding a new public key for the runner to testnet and mainnet servers (different keys each).

**Comment by taariq** [comment]
@byte-bandit this is done. Yes?

**Comment by byte-bandit** [comment]
@taariq The basics are done. It needs battle testing and fleshing out over the coming weeks. I'll do that during our deployment windows and extend as needed.
