### ISSUE TITLE
[Gravity] Support compass EVM update

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#795]
As a user of Paloma, I want Paloma to be able to migrate tokens and funds to new compass-EVM deployments when a vote for new compass passes.

---

## Process

- Update compass deployment code to keep a reference history of old compass addresses
- After successful update, Pigeons change ownership of GRAIN token to new compass
- Only THEN mark new compass contract as enabled

## Acceptance criteria

- [ ] Support transfer of ERC20 token ownership from old compass contract to new one

**Comment by byte-bandit** [comment]
Reopening, this still needs the Pigeon work done, otherwise we won't be able to upgrade compass anymore.

**Comment by byte-bandit** [comment]
TODO:

- pigeon needs to actually call the appropriate method on old compass
- paloma needs to verify TX has not yet been executed again

**Comment by taariq** [comment]
@byte-bandit so this will block #857 as well. Yes?

**Comment by taariq** [comment]
@byte-bandit so this will block https://github.com/VolumeFi/paloma/issues/857 as well. Yes?

**Comment by byte-bandit** [comment]
@taariq It doesn't block implementation of #857 , but I can only work on one thing at a time. So it becomes a question of priority.

**Comment by taariq** [comment]
@verabehr will you move the TODOs into a new ticket with the acceptance criteria and we'll close this as complete to this stage. We'll leave the new ticket in TODOs.
