### ISSUE TITLE
Optimized TWAP middleware

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#801]
EPIC: https://www.notion.so/volumefi/EPIC-09-15-23-Optimized-TWAP-Bot-MVP-9a27e99f9d274ac696b9f93c172854e7
Backend script: https://github.com/VolumeFi/optimized-twap-bot-script/blob/main/optimize.py

Optimized TWAP bot requires a new middleware for the FE to request optimized TWAP parameters. The request's format is
`{'input_amount': , 'prices':}`. These will be given to the backend script `optimize.py` and run the `optimize()` function. The function returns `input_amount` and `prices` back to the FE. 

To do:

- [x] Write middleware and run API service as described above 
- [x] secure endpoint with passcode as done for hte other bot apis

**Comment by rootedbox** [comment]
@fieldtheory123 we need optimize.py to be able to accept inputs from the command line.
