### ISSUE TITLE
UI feedback on multiwap

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#805]
On Palomabot and on Curvebot,

we want to add `max` buttons as well as the USD amount of the input amount of hte token selected. See feedback here https://discord.com/channels/987730379182051408/1065140873811218532/1155860685947949067 and comments here https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=11516%3A8952&mode=design&t=UDbLH82WCJOzXnOb-1

**Comment by taariq** [comment]
Closing as complete.
