### ISSUE TITLE
Remove Sentry tracking on palomaswap localhost

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#81]
# Background

_Describe the problem that we are trying to solve with this feature._
_If a path to a solution is known, feel free to write it down, but have an open mind_
We're sending errors from palomaswap localhost to Sentry which causes a lot of noise. For example this one https://volume-x3.sentry.io/issues/4020183998/?project=4504816371236864&query=is%3Aunresolved&referrer=issue-stream

# Done when

- [ ] we're no longer getting errors from locahost UI testing

**Comment by rootedbox** [comment]
told sentry server not to process.
