### ISSUE TITLE
Sweepstakes Landing Page

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#815]
Landing page: https://palomabot.ai/sweepstakes
Designs: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=12091-2560&mode=design&t=33luaeukTGaq1Rph-4

Rules Page: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=12094-3031&mode=design&t=33luaeukTGaq1Rph-4

Rules doc: https://docs.google.com/document/d/1ZUOFIPX00jqf5qVs1EOQzGUjT0xItsMyCkteXpXL__w/edit#heading=h.xf3imbrhl71v

**Comment by verabehr** [comment]
@joycehermosilla @taariq is this still relevant?

**Comment by taariq** [comment]
No longer relevant. Closing.
