### ISSUE TITLE
bug: robots API issue for the TWAP bot

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#816]
robots API is sending the bought token info for the `coin_info` and `coin_info1` on the TWAP bot.
I created a TWAP bot with ETH and USDT but API is returning only USDT info at the `coin_info` and `coin_info1`.
![image](https://github.com/VolumeFi/paloma/assets/83244763/eb134556-cf59-4d91-b39e-44ff7f69c759)

**Comment by verabehr** [comment]
this is actually coin_info0
