### ISSUE TITLE
Validator Error: failed to send paloma status update

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#823]
Error received by validator:

time="2023-10-01T00:22:34Z" level=error msg="failed to send paloma status update" chain-reference-id=eth-main error="unable to resolve type URL /palomachain.paloma.paloma.MsgAddStatusUpdate: tx parse error [cosmos/cosmos-sdk@v0.47.4/x/auth/tx/decoder.go:42]" message-id=113430 message-type="*types.Message_SubmitLogicCall" msg-id=113430 queue-name=evm/eth-main/evm-turnstone-message queue-type-name=evm/eth-main/evm-turnstone-message x-correlation-id=ckcbngjajpm0pric4j5g

1. **Unable to resolve type URL** pigeon error. Is this a regression?

**Comment by byte-bandit** [comment]
Is this coming from our node or another validator? Judging from the logs on our node, the pigeon status update mechanic works reliably.

There is a window of approximately 45 minutes on October 1st between `16:30 UTC` and `17:15 UTC` where this error is flooding the logs. It doesn't show up before or after that window, at least on our validator.

I believe this is probably connected to the SLC message retry changes we've made.

**Comment by taariq** [comment]
This is from another validator. Okay. closing for now.
