### ISSUE TITLE
Add Expiration for curve lending bot

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#833]
Like limit order bots and stop-loss bots, we would like to have an expiration for Curve lending bot. Namely, users will specify the duration of their bot on the FE like below. When a bot expires, monitoring will stop and users can cancel their bot to withdraw.  

<img width="778" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/ff4ed2c9-62f6-431a-8bbd-8d86e28e8abf">

Resource: https://github.com/VolumeFi/curve-limit-order-bot-vyper/blob/master/contracts/curve_limit_order_bot.vy#L46

Tasks:
1. Add expire in the vyper contract for Curve lending bot like the limit order bot

**Comment by verabehr** [comment]
https://github.com/VolumeFi/curve-lending-bot-vyper/commit/2acea219f319f738be72081608bd1cea2407696a
