### ISSUE TITLE
Curve Lending: Add additional events to backend script and bot-info api

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#834]
### Background
Add the risk reduction option  and expiration from the curve vyper event to the DB, the script and the bot-info API

**Risk reduction**
event UpdateRepayable:
    collateral: address
    bot: address
    repayable: bool

This event is for setting repay/add_collateral. If repayable is True, it means the user wants repay, if it is False, the user wants add_collateral.

-[ script area affected](https://github.com/VolumeFi/curve-lending-bot/blob/main/curve-lending.js#L262): call function `repay` if event is `TRUE` and `add_collateral` if event is `FALSE`

**Bot expiration**
event UpdateExpire:
    collateral: address
    bot: address
    expire: uint256

### Done when

- [ ] script calls the right function (repay vs collateral) depending on event value
- [ ] FE can get the risk reduction option and  bot expiration time from the bot-info API

**Comment by rootedbox** [comment]
We now ignore DepositCollateral? use UpdateRepayable and UpdateExpire.. what does repayable do? what does expire do?

**Comment by wc117** [comment]
The events have bot address and collateral address, and the repayable/expire. Repayable is the option that the user wants repay or add_collateral. And expire is the bot expire timestamp.

**Comment by wc117** [comment]
Those are what @fieldtheory123 asked me to add.

**Comment by rootedbox** [comment]
does does @fieldtheory123 need to add something to DepositCollateral?? @verabehr

**Comment by rootedbox** [comment]
@wc117 @fieldtheory123 https://github.com/VolumeFi/curve-lending-bot/pull/11
