### ISSUE TITLE
Curve limit order bot bug: order executed with price much lower than limit price

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#837]
Selling ETH for USDC, with limit price ratio at $17 while market price ratio was at $16.38. Execution took place right after deposit (3 blocks behind) with price close to market, indicating the scheduler didn't wait until the price reached limit price.

Order:
<img width="811" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/d04cfc00-e293-4fba-94d0-9ed1eb06c2fc">

Deposit: https://etherscan.io/tx/0xa8c9582cd61a1c79f8903b7599b4a921964bf0a811b4826699b2ff815979506a

Execution: https://etherscan.io/tx/0x2063cc9b61817e86b628d2559deb671c374a626e13ccc48b58d6e6a92d5105c3

Tasks:
1. Find out why this is happening and fix

**Comment by verabehr** [comment]
I think this is happening because we never fixed the UI to match the updated backend script. I'll move the UI ticket into @jamie088 queue and will mark this as blocked until the UI was updated
