### ISSUE TITLE
Curve lending bot: coin info is NULL in the bot-info API

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#838]
{"deposit_id":"0","token0":"0","token1":"0","amount0":"5000000000000000","amount1":"38287906260352484","depositor":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","withdrawer":"0x944cF2acB0DB10d0863fE45C4916B2fd7005C6a4","dex_name":"curve","bot":"lending_curve","contract":"0xe0b6D0c1b41eFE8d1E5B3DDf6b503Db1CeA9553C","sent_to_mixpanel":"0","create_to_mixpanel":"0","created_at":"2023-10-04 21:16:14","coin_info":null,"coin_info1":null,"coin_info0":null}]

**Comment by rootedbox** [comment]
server didn't have latest code
