### ISSUE TITLE
BUG: Just in time valsets are no longer being published before SLC

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#846]
On messenger, just in time valsets are no longer being published on the target chain even though there are logic calls. 

On ETH-main the last valset update was published on 9-25, but we have logic calls on 9-26 and after https://etherscan.io/txs?a=0xa00CF3504FfaCff301E4973e21B44C052d087157

BNB: https://bscscan.com/address/0x79e9f573D908E012aC6E1F7978cb09e0065E6355

Polygon & OP: unclear since we had no submit logic calls. 

This doesn't happen on private testnet. There was no code release in mainnet on 9/25 or 9/26

when writing this ticket a new valset was actually published on eth-main... 

--> I think the next best course of action is to confirm if we indeed should expect a valset update before every logic call the way the code is currently written

**Comment by byte-bandit** [comment]
As far as I can tell, we definitely send a valset update every time we execute a job on Paloma via the scheduler.

The thing is, we don't always go via the scheduling module. Jobs being executed by running the `palomad tx wasm execute` command completely circumvents the scheduling module. For all those, I do not believe we publish a JIT valset update, ever. 

That would also explain why I haven't been able to reproduce any of this using regular scheduler jobs. I usually only use those as they're much easier to setup and test with. It also explains why this behaviour frequently appears with transactions coming from our bots.

I have never touched this side of Paloma yet, and my knowledge my be faulty here, but I believe most/all bot functionality against Paloma is directly against WASM contracts and not using the scheduler module.

Paloma will publish a new valset to the target chain after 30 days, but we've never hit that threshold. 

## Open questions

- Why do the SLC calls still succeed, even though the valset is sometimes heavily out of date, all the while they run into "checkpoint error" if the valset is only outdated by minutes?
- How do we perform a JIT valset update for those jobs coming directly from the WASM module? It's not functionality native to Paloma. I believe we may be able to hook into an even or so, but will need to do more digging here.
