### ISSUE TITLE
Mixpanel: Create a list of unique addresses that have interacted with Palomabot

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#852]
For Palomabot sweepstakes, we need a count of how many unique addresses interacted with our bot contracts.

Requirements:
1. Create new Dashboard in Mixpanel for Unique Palomabot Users
* Unique EVM address
* Deposit transaction amount
* Deposit transaction date

**Comment by rootedbox** [comment]
https://mixpanel.com/project/2744781/view/3280621/app/insights#report/45222816/~(originDashboard~(id~3475733~title~'Paloma*2520Dashboard~template_type~null))
