### ISSUE TITLE
[BUG] Missing CLI-KEY on main net validator?

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#853]
We have two addresses for each of our nodes in both private and public test net, but only **one** address on our validator for main net. I'm not 100% sure what's the reason behind this, but it looks like there is only one key being used on main net.

**Comment by verabehr** [comment]
Yes, we never set it up that way. I think part of the reason was to have the same setup that most other validators have as well - cc @taariq

**Comment by taariq** [comment]
yup. most validators use one key. this is as designed. private testnet having two keys was an old habit from Chase. it's not needed.
