### ISSUE TITLE
Upgrade to Go-Ethereum abi-gen code-generated ABIs on the Go 

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#86]
# Background

Upgrade to Go-Ethereum abi-gen code-generated ABIs on the Go side so that we will also upgrade to use a direct connection to the Smart Contract. 

# Done when
- [ ] Update to use ABI-Gen code

**Comment by verabehr** [comment]
https://github.com/palomachain/paloma/pull/775
