### ISSUE TITLE
BUG: Issues with bot stats API

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#860]
- [x] 1. Geckobot top gainers shows Total Volume: $2,312,230,942,626,479,000

![Image](https://github.com/VolumeFi/paloma/assets/701864/05c1be54-4a6a-42df-ab58-4f19536b2d46)

- [ ] 2. lending_curve bot is missing from the API

**Comment by verabehr** [comment]
Point 2 is still open

**Comment by verabehr** [comment]
this is not fixed

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/bot-info-api/pull/44
