### ISSUE TITLE
BUG: Curve TWAP doesn't show the token listings

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#862]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

No twap today because my coins don't show up. Only shows ETH and Fund my Bot

![telegram-cloud-photo-size-1-4985698419628682280-y](https://github.com/VolumeFi/paloma/assets/701864/3610b428-41d5-4faf-9c4b-3a0249e69b69)

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Attempt Curve TWAP

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

All Coins show up without delay.

**Comment by verabehr** [comment]
this was tested ~10:49pm PT on oct 10

**Comment by verabehr** [comment]
@jamie088 0x7a16ff8270133f063aab6c9977183d9e72835428

**Comment by verabehr** [comment]
I also see all my tokens using my personal wallet btw

**Comment by verabehr** [comment]
closing for now as we can't reproduce reliably or see any errors in Sentry.

**Comment by taariq** [comment]
10/14/2023: $2MM TWAP attempt with address https://etherscan.io/address/0x7a16fF8270133F063aAb6C9977183D9e72835428

**ONLY ETH tokens shows. All other tokens don't show.**

Michael, [Oct 14, 2023 at 5:53:11 PM]:
list is still not fixed

So I can't

**keep in mind - I am in Australia at the moment

So all the http requests are long

Might be that your thing just considers them as failed b/c it took too long bu they are not

Anyhow

Not usable ye...

![telegram-cloud-photo-size-1-4999187735084378913-y](https://github.com/VolumeFi/paloma/assets/701864/e37e0b90-0290-4773-b756-a68b797ad982)

**Comment by taariq** [comment]
@verabehr & @jamie088 this is a Moralis issue. We are not returning the tokens list. No errors in the browser. Let's use another provider. @jamie088 please attempt to replace this with https://www.quicknode.com/token-api and see if we can get what we need.

**Comment by taariq** [comment]
Moralis shows that success was 100% , but no other logs 

![image](https://github.com/VolumeFi/paloma/assets/701864/af577204-b822-40c5-a7c1-97484845650a)

**Comment by taariq** [comment]
Okay. So maybe not moralis, but might be the Nest Wallet causing problems.

https://volume-x3.sentry.io/issues/4381900845/?alert_rule_id=13483462&alert_timestamp=1697331180177&alert_type=email&environment=production&notification_uuid=8fce0519-0368-45a7-8b1b-5f19b1aa1765&project=6380489&referrer=alert_email

This bug happened at the same time that user was attempting to TWAP.

This bug has a ticket: https://github.com/VolumeFi/paloma/issues/829

**Comment by taariq** [comment]
This also had a resolution: https://github.com/VolumeFi/paloma/issues/844 but it may not have been engouh.

**Comment by taariq** [comment]
Increased the frequency in #844 to see if this is the fix.
