### ISSUE TITLE
BUG: Lending Bots TVL is also wrong

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#863]
![Image](https://github.com/VolumeFi/paloma/assets/701864/3689170c-dded-4286-8106-8455b90b5ed1)

**Comment by jamie088** [comment]
@rootedbox Please match the `tracking_price` of the Curve Lending bot with USD price same as other bots.
![image](https://github.com/VolumeFi/paloma/assets/83244763/d5ba497c-722f-4cdc-ac36-96fe482d5983)
![image](https://github.com/VolumeFi/paloma/assets/83244763/88729ff3-7ab6-41b1-aabc-6515a301a1db)
