### ISSUE TITLE
Curve Lending bot fixes

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#864]
- [ ] #881
- [x] my bot page crvUSD and collateral token are swapped
- [x] we're not showing the risk ratio - it's always zero
- [x] every time the view is refreshed the list sorting changes. With 2 bots they flip which one is the first and the second
- [x] Change "Risk Ratio" to "Health Threshold" on the my bot page and on the start bot page
- [x] On the my bot page show: 
    - [x] borrowed amount
    - [x] Health (next to Health Ratio)

- [x] Update the expired bots - design to follow from @joycehermosilla 
    - [x] show status as "expired"
    - [x] show collateral token
    - [x] show risk ratio

**Comment by jamie088** [comment]
@joycehermosilla Could you please share the designs for this ticket?
