### ISSUE TITLE
Feedback Palomaswap 03/22 and 3/28

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#87]
- [x] remove `$` in front of token amount on confirmation screen  
<img width="256" alt="Screen Shot 2023-03-22 at 1 39 06 PM" src="https://user-images.githubusercontent.com/19958639/226991414-68ad19cf-56dd-4734-9713-1658e8750f37.png">

- [ ] Change `FREE GRAINS FOR EVERY SWAP` to `GET FREE GRAINS FOR EVERY SWAP`
- [ ] The button color for the "Confirm swap" screen should be the same button color as on the first swap screen instead of light pink 
<img width="352" alt="Screen_Shot_2023-03-28_at_10 12 35_AM" src="https://user-images.githubusercontent.com/19958639/228281198-685b41e0-bdf8-4807-9781-bfa9e9e25158.png">
<img width="424" alt="Screen_Shot_2023-03-28_at_10 14 42_AM" src="https://user-images.githubusercontent.com/19958639/228281200-d30fb39d-4bb8-4759-be06-cef54bbb09ad.png">

- [x] #187
<img width="379" alt="Screen Shot 2023-03-28 at 2 51 48 PM" src="https://user-images.githubusercontent.com/19958639/228339019-e21a67a6-59a8-45f1-9ad6-3ef45db97f4b.png">

**Comment by taariq** [comment]
Closing
