### ISSUE TITLE
Curve lending bot FE: add withdraw in the input

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#871]
When a user starts a Curve lending bot, we would like to have an option for them to determine how much crvUSD they would like to withdraw to their own wallet while keeping the rest in the contract for potential repay. It will be a percentage number. 

This is the function to call for withdraw https://github.com/VolumeFi/curve-lending-bot-vyper/blob/master/contracts/curve_lending_bot.vy#L244

Tasks:
1. Add a `withdraw` input parameter on the FE when a lending bot is started
2. call the `withdraw_crvusd` function in the contract when starting the bot
3. @joycehermosilla Add some text explaining withdraw means how much will the user get from borrowing and the rest will be sitting in the contract for protecting the loan
Design: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=12304-17715&mode=design&t=wC3FOkupyGMQi9aL-4

Tooltip:"This number determinated how much CRV is going to your wallet, the rest will stay in the contract to protect your loan"

**Comment by jamie088** [comment]
@fieldtheory123 We already have a withdraw_amount parameter in create_loan function. So I think we don't need to call withdraw_crvusd function when starting the bot
