### ISSUE TITLE
Curve lending: store health_threshold and only create one bot per BotStarted event

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#872]
Two issues as discussed

- [x] the `health_threshold` from the BotStarted event needs to be stored in the DB, so that the script can compare current `health` against that `health_threshold`
- [ ] there should only be one bot database record per `BotStarted` event. Currently there are multiple.

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/curve-lending-bot/pull/15 the changes needed too use health_threshhold and only 1 bot per bot started..

**Comment by rootedbox** [comment]
That being said.. @wc117 @verabehr @taariq 

when ever I call 

```
def health(collateral: address, bot: address) -> int256:
    return Bot(bot).health(collateral)
```

on the contract.. if i use the collateral and bot address given on  BotStarted I get an exception that the function is returning null

```
getHealth exception: Error: Returned error: execution reverted
    at Object.ErrorResponse (/Users/rootedbox/Source/VolumeFi/curve-lending-bot/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /Users/rootedbox/Source/VolumeFi/curve-lending-bot/node_modules/web3-core-requestmanager/lib/index.js:300:36
    at /Users/rootedbox/Source/VolumeFi/curve-lending-bot/node_modules/web3-providers-http/lib/index.js:127:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  data: null
}
tracking_price updated successfully.
getHealth exception: Error: Returned error: execution reverted
    at Object.ErrorResponse (/Users/rootedbox/Source/VolumeFi/curve-lending-bot/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /Users/rootedbox/Source/VolumeFi/curve-lending-bot/node_modules/web3-core-requestmanager/lib/index.js:300:36
    at /Users/rootedbox/Source/VolumeFi/curve-lending-bot/node_modules/web3-providers-http/lib/index.js:127:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  data: null
```

Now if I send the bot address first and then the collateral address I do get a value back but it's way to high to be used against the health_threshhold given in botstarted

**Comment by fieldtheory123** [comment]
@rootedbox could you post the number here? You need to divide it by 1e18

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/curve-lending-bot/pull/16
