### ISSUE TITLE
Paloma DEX - Flow 2: Add Liquidity

### ISSUE THREAD

**Issue by joycehermosilla** [VolumeFi/paloma#88]
As a user, I want to be able to Add Liquidity to the Paloma DEX Pools. 

- [ ] The user on the Landing Page/Home will be able to scroll though the pools and see the CTA "Add Liquidity"
<img width="161" alt="Captura de pantalla 2023-03-23 a las 9 28 32" src="https://user-images.githubusercontent.com/22323189/227145654-45b17b1a-9173-4e46-ba9a-9c3c4e952773.png">

- [ ] After selecting a Pool and pressing "Add Liquidity" the user will be redirected to the Add Liquidity flow. Starting with this view:
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=6310%3A14976&t=qckWRB06QjpbCqCz-4
<img width="425" alt="Captura de pantalla 2023-03-23 a las 9 30 16" src="https://user-images.githubusercontent.com/22323189/227146084-af18d9ad-73d8-4d08-a29c-2538f6c06f9d.png">

- [ ] The user will see the Pool name on the top of the view.
<img width="337" alt="Captura de pantalla 2023-03-23 a las 9 31 18" src="https://user-images.githubusercontent.com/22323189/227146300-cdea065e-3cd8-4f1e-ac6d-4f7493d5cceb.png">

- [ ] All Pools are double-sided, so the user will need to input an amount for both tokens. 
<img width="346" alt="Captura de pantalla 2023-03-23 a las 9 31 29" src="https://user-images.githubusercontent.com/22323189/227146352-2c225a43-1e2f-4d75-aeea-0e2d1856587f.png">

- [ ] User will be able to see the Available Balance of both tokens.
<img width="251" alt="Captura de pantalla 2023-03-23 a las 9 32 06" src="https://user-images.githubusercontent.com/22323189/227146542-2d9669f8-247d-4fdc-bbbe-d3145503390a.png">

- [ ] While the user hasn't input an amount, the CTA will look disabled with the copy "Enter an amount"
<img width="316" alt="Captura de pantalla 2023-03-23 a las 9 33 27" src="https://user-images.githubusercontent.com/22323189/227146817-763929bc-9a0d-48e1-9e3f-fe28d69e207b.png">

- [ ] If the user inputs an amount higher than the balance the CTA will show the copy "Insufficient amount"
<img width="375" alt="Captura de pantalla 2023-03-23 a las 9 33 42" src="https://user-images.githubusercontent.com/22323189/227146870-97dafe16-e49d-4bd6-ba60-ef5f9026b732.png">
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=6315%3A16380&t=qckWRB06QjpbCqCz-4

- [ ] If the user inputs an amount lower or equal to the balance the CTA will show the copy "Add Liquidity" and looks enabled.
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=6315%3A15712&t=qckWRB06QjpbCqCz-4
<img width="285" alt="Captura de pantalla 2023-03-23 a las 9 35 24" src="https://user-images.githubusercontent.com/22323189/227147244-1d2cd29f-6e54-4fd3-9ea5-094cf0c6722e.png">

- [ ] After pressing on Add Liquidity the user will see a Confirm Add Liquidity view. User will see token amounts that will be deposited and transaction details.
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=6315%3A16968&t=qckWRB06QjpbCqCz-4

- [ ] After Confirming the Add Liquidity transaction. The user will see a loading icon with the message "Confirm Transaction in your Wallet". Also here the user will see the action/transaction that they will accept in this case "Adding 45 PUSD and 30 GRAIN"
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=6372%3A15382&t=qckWRB06QjpbCqCz-4

- [ ] At the same time the Nest Wallet will pop up a Transaction Confirmation with the transaction details: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=6372%3A15382&t=qckWRB06QjpbCqCz-4

- [ ] After confirmation in the wallet the user will return to the Landing Page where they will see on the top of the view "1 Pending Transaction" with a loading spinner icon, while the transaction is being executed. https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=6372%3A16040&t=qckWRB06QjpbCqCz-4

- [ ] After the Transaction is successfully executed we will show a confirmation message underneath the wallet address.
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?node-id=6372%3A16388&t=qckWRB06QjpbCqCz-4 <img width="290" alt="Captura de pantalla 2023-03-23 a las 9 42 06" src="https://user-images.githubusercontent.com/22323189/227148838-70b95671-2195-46d8-8889-7355c7aa8a68.png">

**Comment by taariq** [comment]
Closing in favor of Paloma NFP DEX.
