### ISSUE TITLE
BUG: gravity tries to send a message that has already been relayed

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#880]
Details:  https://www.notion.so/volumefi/ERC-20-transfers-on-op-main-paloma-testnet-a1e235dd59b74106ad5b0651bfb087a2?pvs=4

Note that both birdlady and birdpoop2 were taken offline by stopping pigeon service to force lack of consensus to stop more messages to be sent.

**Comment by taariq** [comment]
We still have this persisting on testnet due to batches still in the system. Pigeons still see the bad batch.

**Comment by verabehr** [comment]
@taariq @byte-bandit, does this mean more work will be required to fully fix this issue?

**Comment by byte-bandit** [comment]
@verabehr The main problem is fixed, Validators will not keep burning ETH trying to relay the batch. So this lowers the priority here I assume. There is however still a bug in place, as Pigeons are supposed to remove a batch once its been executed, and this doesn't seem to work yet either. I assume we have to supply the same fix I did for this at another point in the code.

So this will need to be addressed before launching gravity on main net. Those batches won't cause Validators to burn ETH any longer, but they will clog the system and create noise and traffic (and also never ever disappear on their own).a

**Comment by verabehr** [comment]
Thanks @byte-bandit. Agreed on the lower priority here. I think it makes
sense to break this into a new ticket then
