### ISSUE TITLE
Validator unjailing backoff

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#888]
There's still a lot of noise coming from Validators being jailed due to their Pigeons simply being too low in balance or not supporting all target chains.

In this case, the very high TTL of approx. 1 hour doesn't come into effect, as the Pigeons never get to call in again (because they don't support all queues for example).

Instead, Validators unjail automaticaly, and Paloma will grant them approx. 5 minutes of grace period before jailing them again. This creates a lot of noise, as the problem isn't resolving itself.

We want to introduce a [backoff](https://en.wikipedia.org/wiki/Exponential_backoff) for unjailing Validators, which will become increasingly more punishing the more often a validator is jailed within a short period of time again.

This will prevent the majority of noise to valset updates due to the jail/unjail shift in validator power, as well as provide some incentives for Validators to make sure their Pigeon configuration matches the requirements.

---

## Implementation notes

This will slowly increase the duration in jail to up to 72h, where it caps. If a validator hasn't fixed the underlaying issue and unjails after 72h, they will become protected by the grace period for about 5 minutes before becoming jailed again for 72h.

If we uncap and let this spiral to higher durations, I think it might become very difficult to get out of this state, with long period of downtime for validators, possibly losing their interest in joining again.

- [x] Verify `GetJailedValidators` doesn't need adapting
- [x] Update `Jail` method to use slashing keeper instead of staking keeper, set `sk.Jail()` to set `jailed` flag as well as `sk.JailUntil()` to set the jailed duration
- [x] Apply backoff durations: 0m, 5m, 15m, 1h, 6h, 24h and cap at 24h
- [x] Keep track of last jail time & last jail duration. If validator hasn't become jailed since last duration + `x`, reset the backoff
- [x] Set `x` to `duration * 1.2`, giving it a 20% buffer from the last duration. The longer you were jailed, the longer you'll have to behave.

**Comment by taariq** [comment]
@byte-bandit what was also the issue and proposed solution for unjail scripts?

**Comment by byte-bandit** [comment]
> @byte-bandit what was also the issue and proposed solution for unjail scripts?

Yeah, this change is to tackle the noise we get from naughty pigeons who continuously unjail automatically instead of addressing the underlaying root cause. 

Essentially, cosmos SDK jailing includes logic for a jail duration. If we can leverage that somehow, we can continuously increase this duration, meaning validators would spend more time in jail before being able to unjail. I want to look more into this option as opposed to writing our own solution.

**Comment by verabehr** [comment]
@byte-bandit Marbar actually mentioned yesterday that other chains do this as well

**Comment by taariq** [comment]
@byte-bandit let's get this in for the next release, this week?
