### ISSUE TITLE
Error: decoding bech32 failed: invalid bech32 string length 6

### ISSUE THREAD

**Issue by rootedbox** [VolumeFi/paloma#891]
when running queries on our validator box we are getting bech32 failed

example
```
palomad query bank balances Volume -o json
Error: decoding bech32 failed: invalid bech32 string length 6
```

this use to work fine.

**Comment by taariq** [comment]
Closing as won't fix. @rootedbox please use the public address of the account and not the string `Volume` to query balances on the account.
