### ISSUE TITLE
Gnosis Bot UI

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#893]
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=12522%3A41227&mode=design&t=pBBHbCZicPDRQkzP-1

**Comment by jamie088** [comment]
https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=12970-574855&mode=design&t=dNVHrvMqLBoFYvmO-4
