### ISSUE TITLE
Curve lending: Update stop bot functionality

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#909]
https://www.notion.so/volumefi/EPIC-07-27-23-Curve-lending-bots-e22990bbc1904f34b0d4eaf5dd77ade0?pvs=4#b2aefa8a6ed1470781804c087350a24b

Blocked by https://github.com/VolumeFi/paloma/issues/908

**Comment by joycehermosilla** [comment]
Design are here: https://www.figma.com/file/ClniQyKFqN1hSpWizV5O4A/Paloma?type=design&node-id=12866-283304&mode=design&t=q8K9dUxC1SRdXwlf-4
