### ISSUE TITLE
BUG: Missing Uniswap v3 ZERO token. Are Uniswap token lists current?

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#91]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

unable to APE into ZERO token on uniswap v3. 
Token lists are not complete. https://www.geckoterminal.com/eth/pools/0xa80838d2bb3d6ebaed1978fa23b38f91775d8378

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Search Zero token on Uniswap.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

ZERO Token will be available for Uniswap v3 swap.

**Comment by wdev733** [comment]
@taariq All these tokens are not available on the uniswapv3? Even `aave` and `1inch` ?

**Comment by taariq** [comment]
Any of the tokens that are relatively new. The first FOUR are unavailable.

**Comment by verabehr** [comment]
https://github.com/palomachain/paloma-nest-service/pull/37
