### ISSUE TITLE
limit-order bot getMinAmount issue

### ISSUE THREAD

**Issue by rootedbox** [VolumeFi/paloma#921]
when trying to see why the server went down.. we are getting the following exception a lot.. needs to be fixed

getMinAmount exception: TypeError: contractInstance.methods.withdraw is not a function
Oct 26 10:22:30 bots-server start.sh[2673130]:     at getMinAmount (/home/rootedbox/app/limit-order-bot-script/limit-orders.js:500:49)
Oct 26 10:22:30 bots-server start.sh[2673130]:     at getNewBlocks (/home/rootedbox/app/limit-order-bot-script/limit-orders.js:480:53)

**Comment by verabehr** [comment]
I think this was already fixed with this https://github.com/VolumeFi/limit-order-bot-vyper-uniswap-v2/commit/b087c750aed80d4972d882844f02a39599c6ab18
