### ISSUE TITLE
CHORE: add missing bots services to uptime

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#926]
Add the following bot services to uptime

- [x] curve-momentum-bot | ~/app/curve-momentum-bot-script | https://github.com/VolumeFi/curve-momentum-bot-script
- [x] gecko-newtoken-bot | ~/app/gecko-newtoken-bot-script | https://github.com/VolumeFi/gecko-newtoken-bot-script
- [x] dca-bot-service | ~/app/dca_bot_python_script | https://github.com/VolumeFi/twap_bot_python_script
- [x] curve-limit-order | ~/app/curve-limit-order-bot-script | https://github.com/VolumeFi/curve-limit-order-bot-script
- [x] curve-lending-bot | ~/app/curve-lending-bot | https://github.com/VolumeFi/curve-lending-bot

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/twap_bot_python_script/pull/34
