### ISSUE TITLE
Mixpanel: Add new contracts deployed for all bots and check data

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#928]

**Comment by verabehr** [comment]
@rootedbox last DB complete and DB create events were 13 days ago. It looks like events are again not coming into Mixpanel

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/fees-collected-mix-panel/commit/e52a91196fdbe9c7c1d4693e7774569c31a78f34

**Comment by taariq** [comment]
This is showing wrong data. Re-opening.
