### ISSUE TITLE
BUG: Better Uptime Failures are happening every day

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#929]

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/nginx/commit/16aaabb980bc49323d49689b962c5a84cecb3b95

caching responses at 5 seconds.. so that the server responds instantly

**Comment by verabehr** [comment]
@rootedbox can this be closed then?

**Comment by rootedbox** [comment]
yes I only updated bots on http://check.bots.palomachain.com/ but I think that's what we care about most. @verabehr
