### ISSUE TITLE
EPIC: Cost Optimized TWAP Path Discovery for Curve

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#930]
As a user, I want Paloma to find lowest gas-cost path for my TWAP so that I am not using the most expensive paths for gas.

** Acceptance Criteria**
1. EPIC For Curve path-dependent TWAPs

**Comment by fieldtheory123** [comment]
Yes it is here https://www.notion.so/volumefi/EPIC-11-03-23-Optimizing-routes-for-multi-TWAP-bots-0185e8fdeec245b38bd95d350548d553

**Comment by taariq** [comment]
Epic delivered.
