### ISSUE TITLE
BUG: TWAP bot shows no tokens. Just keep spinning.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#941]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

BUG: TWAP bot shows no tokens. Just keep spinning.

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

https://www.curvebot.fi/curve-twap/ and connect wallet.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Tokens are listed.

**Comment by verabehr** [comment]
This might be related https://volume-x3.sentry.io/issues/3965070840/?alert_rule_id=13483462&alert_timestamp=1698914185818&alert_type=email&environment=production&notification_uuid=a79a7090-1bd6-446c-a119-002f0c88a8c4&project=6380489&referrer=alert_email

**Comment by rootedbox** [comment]
https://github.com/palomachain/paloma-nest-service/pull/70
