### ISSUE TITLE
BUG: Can't start momentum bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#949]
when clicking start bot button, user is NOT taken to start bot page. There is an error in the console 

![Image](https://github.com/VolumeFi/paloma/assets/19958639/0930c43c-2e44-446e-82f2-71eef2d2d544)

**Comment by taariq** [comment]
@jamie088 reopening this issue as its also replicated on Curvebot https://www.curvebot.fi/curve-momentum/lists/?lag_return=6&vol_30=100000&market_cap=1000000. Not able to start any bots.
