### ISSUE TITLE
Alert when bot paloma wallets have 5 grains or less

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#951]

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/wallet_check

**Comment by rootedbox** [comment]
Uptime Watching these Addresses

[paloma156nvzxcp59wa9j5zj3fuj56lw2r5kldesas0l9](https://wcheck.palomachain.com/paloma156nvzxcp59wa9j5zj3fuj56lw2r5kldesas0l9)
[paloma1zt8h0pduv0v2mqqj7ft9swcmku7nxw47wcdz9h](https://wcheck.palomachain.com/paloma1zt8h0pduv0v2mqqj7ft9swcmku7nxw47wcdz9h)
[paloma1veyp40yu0rep48hqvmwzu7eypg6xnf8ecde373](https://wcheck.palomachain.com/paloma1veyp40yu0rep48hqvmwzu7eypg6xnf8ecde373)
[paloma1lz3fvuv4sd2lzddyjhttwmp22glgyl25g6erkh](https://wcheck.palomachain.com/paloma1lz3fvuv4sd2lzddyjhttwmp22glgyl25g6erkh)
[paloma1drm33t0fj2cspkecmjehp776nr8tfcf0y5qn30](https://wcheck.palomachain.com/paloma1drm33t0fj2cspkecmjehp776nr8tfcf0y5qn30)
[paloma1ff7hlgz69qwkq38wrlyfjrlqc5qlyhxksx3al5](https://wcheck.palomachain.com/paloma1ff7hlgz69qwkq38wrlyfjrlqc5qlyhxksx3al5)
[paloma17s05s7kxcwz9z5f9fet2vehdy0ak7w29pnr3uw](https://wcheck.palomachain.com/paloma17s05s7kxcwz9z5f9fet2vehdy0ak7w29pnr3uw)
[paloma1fkdsluy0g5qv7xlpn3q2lg4xvx85axqlljej4p](https://wcheck.palomachain.com/paloma1fkdsluy0g5qv7xlpn3q2lg4xvx85axqlljej4p)
[paloma1l8xfxu06t8ls3zy4vcnfmhudlah7gf3f8r9e3m](https://wcheck.palomachain.com/paloma1l8xfxu06t8ls3zy4vcnfmhudlah7gf3f8r9e3m)
[paloma10dry4t7gr8rhd0khqcqyq95ytdh6vs8sjv84yj](https://wcheck.palomachain.com/paloma10dry4t7gr8rhd0khqcqyq95ytdh6vs8sjv84yj)
[paloma1hpwja8w0xzq23mmtrwkt7rdvj82stjalx9dryr](https://wcheck.palomachain.com/paloma1hpwja8w0xzq23mmtrwkt7rdvj82stjalx9dryr)
