### ISSUE TITLE
BUG: Curve lending testing feedback

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#954]
- [x] 1. `repayable` should be set to false by default when starting a bot
- [x] 2. the repay window is very confusing
    - [x] I shouldn't be able to repay more than the max loan amount. I can currently enter my max balance. The max button should populate the loan amount
    - [x] The numbers don't add up `loan amount` and `Total to repay` and the number the user needs to put in is different from as well
    - [x] when total to repay is 100%, the button still says insufficient amount. I need to repay 100.1 for the button to be active

https://drive.google.com/file/d/1UUTaYZg1gIcMZPg9tgfEuq4PtDyDkRLg/view?usp=sharing

![Image](https://github.com/VolumeFi/paloma/assets/19958639/d9bf70c7-14cf-420a-b908-e23412786c69)

![Image](https://github.com/VolumeFi/paloma/assets/19958639/067a22bd-3613-4f75-a53e-1ffd6088041a)

**Comment by jamie088** [comment]
@verabehr `The numbers don't add up loan amount and Total to repay and the number the user needs to put in is different from as well` I am not sure what you mean.

**Comment by verabehr** [comment]
did you look at the video? I have no idea what numbers to put into the input field to pay the loan back and actually activate the button. 

- If I copy the number called `Total loan amount` at the top, it doesn't work. 
- If I copy the number that is called `Total to Repay` it doesn't work. 
- I then increase the number slowly, so the number that I have in the input field (`11.557` is larger than `total loan amount` and also larger than `total to repay`) only then the button to repay activates
- however, now `total to repay` percentage is > 100%. If I chose a number where `total to repay` percentage is 100%, I'm not able to use the repay button. 

I don't know which number is correct here, but I would expect that. 

1. total to repay = total loan amount
2. the input number that activates the button = total to repay = total loan amoun
3. I don't need to pay back more than 100% in `total to repay` percentage
4. I'm not allowed to pay back more than 100% - pressing the max button should enter the full amount

@fieldtheory123 plz add anything that I'm missing here

**Comment by verabehr** [comment]
@jamie088 I think point 2 is still open from this one?
