### ISSUE TITLE
BUG: Mixpanel numbers are incorrect for Bot Volumes again

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#960]
@rootedbox Mixpanel Bugs show different numbers for bot volume on different panels.

Example: **Volume by Wallet does not equal Volume by Dex in totals.**

**Comment by verabehr** [comment]
Events are not coming in again. Last event was recorded in mixpanel 6 days ago which is when this broke last time

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/fees-collected-mix-panel/pull/13

**Comment by rootedbox** [comment]
II. service wasn't running.  I've fixed by creating a web server on the service for uptime to check https://mixpanel.collector.palomachain.com
