### ISSUE TITLE
BUG: FCD is stuck in late September

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#964]
compare 

https://fcd.palomachain.com/v1/txs?account=paloma1m7t67rgpjqz8pu0z8x5pa5996xv5kgc0u35dmd&limit=100

with 

https://paloma.explorers.guru/account/paloma1m7t67rgpjqz8pu0z8x5pa5996xv5kgc0u35dmd

stuck on block `5321023`

**Comment by verabehr** [comment]
Also confirm that the auto-skip is running, it should be per this https://github.com/VolumeFi/paloma/issues/523

**Comment by rootedbox** [comment]
had to update initial_height

cat /home/fcd/fcd/run_collector.sh
#!/bin/bash
export CHAIN_ID=messenger
export LCD_URI=https://lcd2.palomachain.com
export RPC_URI=http://lcd2.palomachain.com:26657
export FCD_URI=https://fcd.palomachain.com
export TOKEN_NETWORK=mainnet
export INITIAL_HEIGHT=5473208
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
nvm use 16
/home/fcd/.nvm/versions/node/v16.20.1/bin/npm run collector

**Comment by verabehr** [comment]
reopening as we don't have the auto-skip code for the FCD yet or anymore unlike previously thought
