### ISSUE TITLE
Curve leverage bot UI

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#967]
https://www.notion.so/volumefi/EPIC-10-27-23-Curve-leverage-lending-bot-d7358cbd9dd849acb6e68aa00b081a1b?pvs=4#f60b76ab08584564a5938a842aee8e11
https://www.figma.com/file/6DYR6QFkucGd1bsOILr7V0/Paloma-Bot?type=design&node-id=384-198286&mode=design&t=fq8yhhXAYDwNzEOW-4

**Comment by taariq** [comment]
@jamie088 Issues as of 12/9/2023
1. Curve Leveage Lending requires wallet connect on click instead of the bot page.
2. Stop Button is not working on Curvebot.fi lending bot page

**Comment by verabehr** [comment]
Also curvebot.fi css is broken
