### ISSUE TITLE
bug: robots api is broken

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#971]
The robots API hasn't been working since a few hours ago.
I think after Steven worked on the Gnosis Offramp eure bot script, API appears to have been broken. (Gnosis bot was not shown in the API)
![image](https://github.com/VolumeFi/paloma/assets/83244763/dcbf9fd6-4ac7-4757-ad83-c650773a02ce)

The FE code that was used to create the first new bot is here https://github.com/VolumeFi/palomabot/tree/feat/gnosis-bot

**Comment by rootedbox** [comment]
fixed https://service.palomabot.ai/robots
https://github.com/VolumeFi/bot-info-api/commit/6841a94a9c65627a76467b5ec599626cb96026a0

**Comment by verabehr** [comment]
https://discord.com/channels/987730379182051408/1065140873811218532/1172228583004057610
