### ISSUE TITLE
BUG Mixpanel: EURe Offramp transactions not showing up in Mixpanel

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#974]
No EURe transactions are showing up in Mixpanel.

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/fees-collected-mix-panel/commit/00b97871c56ce65a0328331da06a4d9c1b78bdaa

**Comment by taariq** [comment]
@rootedbox still not seeing any EURe transactions for today even after my $46.00 test: https://mixpanel.com/project/2744781/view/3280621/app/boards#id=3475733&edited-bookmark=T9uWCxc7iB7E

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/fees-collected-mix-panel/commit/20396667972a2dfd8c5f360ce0309f90a6e41705
https://github.com/VolumeFi/fees-collected-mix-panel/commit/990d48985b82bab3a63dc93d4325f21f380a5770
