### ISSUE TITLE
Sentry: Add all toast errors to Sentry

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#975]
@jamie088 & @rootedbox we want all `toast` errors to go to Sentry. 

most important are the "no swap route available", but really we want all

**Comment by rootedbox** [comment]
Pop-Up Errors Need to go to sentry.

**Comment by verabehr** [comment]
@rootedbox I found these in the code here, is it not possible to add Sentry to these specific errors?

https://github.com/VolumeFi/palomabot/blob/main/hooks/useCurveMultiTWAPBot.tsx#L81
https://github.com/VolumeFi/palomabot/blob/main/hooks/useCurveSwap.tsx#L54
