### ISSUE TITLE
BUG: Curvebot TWAP CORS Error when attempting Cure TWAP.JsonRpcProvider failed to detect network and cannot start up

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#982]
**NOTE: These CORS error do not occur on Palomabot.ai TWAP bot for Curve.**

_app-637794b937182ed5.js:1068 JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
curve-twap/:1 Access to fetch at 'https://virginia.rpc.blxrbdn.com/' from origin 'https://www.curvebot.fi' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
_app-637794b937182ed5.js:1068 

**And another CORS bug:**
bot/:1 Access to fetch at 'https://nest-service.palomachain.com/tokens/market-data?network=1&token=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2' from origin 'https://www.curvebot.fi' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
nest-service.palomachain.com/tokens/market-data?network=1&token=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2:1 
        
        
       Failed to load resource: net::ERR_FAILED
curve-twap-dd2b6faa00b2f1a2.js:1 Uncaught (in promise) Object
_app-637794b937182ed5.js:1068 
        
        
       POST https://www.curvebot.fi/monitoring/?p=4505354828185600&o=1200162 429 (Too Many Requests)

**Comment by verabehr** [comment]
Noting that this is isolated to Jason so far.

**Comment by taariq** [comment]
@verabehr this was my error on my console.

**Comment by taariq** [comment]
Closing as most likely WalletGuard behaving badly.

**Comment by fieldtheory123** [comment]
Still getting this error after selecting Dola -> DBR as input and output tokens:

`Access to fetch at 'https://virginia.rpc.blxrbdn.com/' from origin 'https://www.curvebot.fi' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by verabehr** [comment]
@jamie088 the https://virginia.rpc.blxrbdn.com/ url is outdated, please use the new endpoint listed here for ALL bots https://docs.bloxroute.com/introduction/protect-rpcs

**Comment by taariq** [comment]
Moved to new feature story: https://github.com/VolumeFi/paloma/issues/1073
