### ISSUE TITLE
EPIC addition: TWAP for Gnosis Offramp Bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#986]

**Comment by taariq** [comment]
@fieldtheory123 is this done?

**Comment by fieldtheory123** [comment]
Done 
https://www.notion.so/volumefi/EPIC-09-29-23-Stables-Offramp-to-Euros-Gnosis-Bot-b1dc5977ed6340d09d3f55855f96db58#1c565dd47deb4cc4808f104e389c6e6b
