### ISSUE TITLE
[BUG] Error validating balances too early

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#988]
Pigeons query for target chain blocks too early when validating balances. There needs to be at least one block in between the requested time and the latest. Given the target chain speed, this might not always be the case if Pigeons are too quick.

It would make sense to keep balance validation messages in a short lived buffer before actually sending them out to ensure the target chain has moved on enough to verify the data.

```
Nov 07 10:32:14 mainnet-validator pigeon[419548]: {"error":"there are 1 errors in the group:\nerror  1: couldn't find block: block has not yet been generated\n","level":"error","msg":"error returned in process loop","time":"2023-11-07T10:32:14Z","x-correlation-id":"cl514ad8c5kqak2r035g"}
```

**Comment by taariq** [comment]
@byte-bandit this fix for the next release this week?

**Comment by verabehr** [comment]
@taariq after discussing with @byte-bandit - removing from this week. It's not urgent at the moment, and we get more benefit from #888
