### ISSUE TITLE
REGRESSION BUG: Unable to get list of tokens using Vivaldi + Frame + Watcher Account 

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#994]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Unable to get full token list from account `0x7a16fF8270133F063aAb6C9977183D9e72835428` using Vivaldi + Frame + Watcher account. This is a possible regression of token lists not getting updated.

**Browser Logs:**
       Failed to load resource: net::ERR_FAILED
_app-c36b3619a1468034.js:1068 Moralis SDK Core Error: [C0006] Request failed: timeout of 20000ms exceeded
    at e.makeError (https://www.curvebot.fi/_next/static/chunks/pages/_app-c36b3619a1468034.js:1093:91498)
    at e.<anonymous> (https://www.curvebot.fi/_next/static/chunks/pages/_app-c36b3619a1468034.js:1093:90951)
    at https://www.curvebot.fi/_next/static/chunks/pages/_app-c36b3619a1468034.js:1093:77752
    at Object.throw (https://www.curvebot.fi/_next/static/chunks/pages/_app-c36b3619a1468034.js:1093:77857)
    at s (https://www.curvebot.fi/_next/static/chunks/pages/_app-c36b3619a1468034.js:1093:76634)
(anonymous) @ _app-c36b3619a1468034.js:1068

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Add `0x7a16fF8270133F063aAb6C9977183D9e72835428` to Frame as watcher and use Curvebot with Vivaldi.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Tokens are found and listed.

**Comment by rootedbox** [comment]
i'm getting a list of tokens using vivaldi.. and frame
also getting them. using chrome and rabby wallet

**Comment by taariq** [comment]
@jamie088 please open a ticket with Moralis. This appears to be something on their side. https://forum.moralis.io/t/solved-metamask-auth-moralis-sdk-core-error-c0006-request-failed-with-status-undefined-timeout-of-10000ms-exceeded/19110

**Comment by taariq** [comment]
@jamie088 @rootedbox from Moralis
> Hi there, Thank you for your patience. ​​We  will soon be releasing an update for this API endpoint in the coming  weeks. This > issue will be fixed with that update. For a temporary fix,  you can try adding a retry logic in your code. Since the issue 
> seems to  be happening randomly retrying might help to get the 200 response  status.Feel free to reply if you have any other > questions🙌
> --
>
