### ISSUE TITLE
URGENT: Update Compass to emit the event nonce for Testnet and Mainnet Proposal 11/14

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#996]
At the moment, gravity events emitted from the contract have the following signature:

- `SendToPalomaEvent(address,address,string,uint256)`
- `BatchSendEvent(address,uint256)`

It's necessary that all events observed by Pigeons contain an `event nonce`, that is continuously increased with every event emitted by the contract.

At the moment, the `uint256` field of the `BatchSendEvent()` only emits the `batch nonce` that was used when calling it, so it's signature would need to look like this: `BatchSendEvent(address,batchNonce,eventNonce)` instead.

I do not know what the `uint256` field of the `SendToPalomaEvent` emits at the moment.

But the event nonce should be included in all events emitted, and shared across every event.

**Comment by verabehr** [comment]
Here is an example of `SendToPaloma` event on bnb for reference as well https://bscscan.com/tx/0xedbdabffd33f56e550d2d6aa1787913d8810f6ef589696257afa360b278df016#eventlog

**Comment by byte-bandit** [comment]
@webelf101 

Because we already have validators with populated data for event nonces, we'd need to event to start emitting nonces from `100'000` instead of `0`.
