### ISSUE TITLE
Limit order and stop loss my bot page calculation change

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#997]
On the mybot page for 

- [ ] Curve limit order
- [ ] Curve stop loss
- [ ] Uniswap limit order
- [ ] Uniswap stop loss
- [ ] Pancakeswap limit order
- [ ] Pancakeswap stop loss 
- [ ] 

Update the `Profit Taking` column 

- [ ] Update Column name to `Deposit Ratio`
- [ ] Update calculation to deposit_ratio = deposit_token_price / output_token_price = `deposit_price` / `deposit_price1`
- [ ] Remove the `$` before the number

**Comment by verabehr** [comment]
got it, moved back into your todo then for after the curve api updates

**Comment by verabehr** [comment]
@jamie088 is this complete? If not, please work on this today, so we can get all the bots (curve, uniswap, pancake) live before Wednesday

**Comment by jamie088** [comment]
@verabehr It's not finished, but @taariq mentioned a few days ago that the Search by Tokens ticket is a higher priority than it, so I've moved to the Search by Tokens ticket now. Please let me know which ticket should I work on today, again. Thank you.

**Comment by jamie088** [comment]
I got it. I will move to this ticket.
