### ISSUE TITLE
Backend script for curve leverage lending

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#998]
### Background: 

- Repo that needs to be updated: https://github.com/volumefi/curve-leverage-lending-bot
- Vyper code: 
    -  Blueprint https://github.com/VolumeFi/curve-leverage-lending-bot-vyper/blob/master/contracts/curve_leverage_bot.vy
    - Factory https://github.com/VolumeFi/curve-leverage-lending-bot-vyper/blob/master/contracts/factory.vy

### Done when:  
- [x] remove https://github.com/VolumeFi/curve-leverage-lending-bot/blob/main/leverage_lending.py (no longer needed with new approach)
- [ ] curve-lending.js is updated to 
    - [x] to call `repay_extended` ([vyper](https://github.com/VolumeFi/curve-leverage-lending-bot-vyper/blob/master/contracts/curve_leverage_bot.vy#L46)) instead of `repay` (bot_info_repays)
    - [x] to the add collateral option is removed, we will always repay
    - [x] so that all `BotStarted` events per wallet are combined into one record. As we may deploy several bots for one wallet to increase their leverage
- [ ] The script is on the server and the service is set up 
- [ ] Paloma address is created for this new bot
- [ ] Paloma address as well as bot script is added to all alert channels and checks

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/curve-leverage-lending-bot/pull/2
